// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ActivityDomain undocumented
type ActivityDomain string

const (
	// ActivityDomainVUnknown undocumented
	ActivityDomainVUnknown ActivityDomain = "Unknown"
	// ActivityDomainVWork undocumented
	ActivityDomainVWork ActivityDomain = "Work"
	// ActivityDomainVPersonal undocumented
	ActivityDomainVPersonal ActivityDomain = "Personal"
	// ActivityDomainVUnrestricted undocumented
	ActivityDomainVUnrestricted ActivityDomain = "Unrestricted"
)

// ActivityDomainPUnknown returns a pointer to ActivityDomainVUnknown
func ActivityDomainPUnknown() *ActivityDomain {
	v := ActivityDomainVUnknown
	return &v
}

// ActivityDomainPWork returns a pointer to ActivityDomainVWork
func ActivityDomainPWork() *ActivityDomain {
	v := ActivityDomainVWork
	return &v
}

// ActivityDomainPPersonal returns a pointer to ActivityDomainVPersonal
func ActivityDomainPPersonal() *ActivityDomain {
	v := ActivityDomainVPersonal
	return &v
}

// ActivityDomainPUnrestricted returns a pointer to ActivityDomainVUnrestricted
func ActivityDomainPUnrestricted() *ActivityDomain {
	v := ActivityDomainVUnrestricted
	return &v
}
