// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AlertStatus undocumented
type AlertStatus string

const (
	// AlertStatusVUnknown undocumented
	AlertStatusVUnknown AlertStatus = "Unknown"
	// AlertStatusVNewAlert undocumented
	AlertStatusVNewAlert AlertStatus = "NewAlert"
	// AlertStatusVInProgress undocumented
	AlertStatusVInProgress AlertStatus = "InProgress"
	// AlertStatusVResolved undocumented
	AlertStatusVResolved AlertStatus = "Resolved"
	// AlertStatusVDismissed undocumented
	AlertStatusVDismissed AlertStatus = "Dismissed"
	// AlertStatusVUnknownFutureValue undocumented
	AlertStatusVUnknownFutureValue AlertStatus = "UnknownFutureValue"
)

// AlertStatusPUnknown returns a pointer to AlertStatusVUnknown
func AlertStatusPUnknown() *AlertStatus {
	v := AlertStatusVUnknown
	return &v
}

// AlertStatusPNewAlert returns a pointer to AlertStatusVNewAlert
func AlertStatusPNewAlert() *AlertStatus {
	v := AlertStatusVNewAlert
	return &v
}

// AlertStatusPInProgress returns a pointer to AlertStatusVInProgress
func AlertStatusPInProgress() *AlertStatus {
	v := AlertStatusVInProgress
	return &v
}

// AlertStatusPResolved returns a pointer to AlertStatusVResolved
func AlertStatusPResolved() *AlertStatus {
	v := AlertStatusVResolved
	return &v
}

// AlertStatusPDismissed returns a pointer to AlertStatusVDismissed
func AlertStatusPDismissed() *AlertStatus {
	v := AlertStatusVDismissed
	return &v
}

// AlertStatusPUnknownFutureValue returns a pointer to AlertStatusVUnknownFutureValue
func AlertStatusPUnknownFutureValue() *AlertStatus {
	v := AlertStatusVUnknownFutureValue
	return &v
}
