// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AndroidRequiredPasswordType undocumented
type AndroidRequiredPasswordType string

const (
	// AndroidRequiredPasswordTypeVDeviceDefault undocumented
	AndroidRequiredPasswordTypeVDeviceDefault AndroidRequiredPasswordType = "DeviceDefault"
	// AndroidRequiredPasswordTypeVAlphabetic undocumented
	AndroidRequiredPasswordTypeVAlphabetic AndroidRequiredPasswordType = "Alphabetic"
	// AndroidRequiredPasswordTypeVAlphanumeric undocumented
	AndroidRequiredPasswordTypeVAlphanumeric AndroidRequiredPasswordType = "Alphanumeric"
	// AndroidRequiredPasswordTypeVAlphanumericWithSymbols undocumented
	AndroidRequiredPasswordTypeVAlphanumericWithSymbols AndroidRequiredPasswordType = "AlphanumericWithSymbols"
	// AndroidRequiredPasswordTypeVLowSecurityBiometric undocumented
	AndroidRequiredPasswordTypeVLowSecurityBiometric AndroidRequiredPasswordType = "LowSecurityBiometric"
	// AndroidRequiredPasswordTypeVNumeric undocumented
	AndroidRequiredPasswordTypeVNumeric AndroidRequiredPasswordType = "Numeric"
	// AndroidRequiredPasswordTypeVNumericComplex undocumented
	AndroidRequiredPasswordTypeVNumericComplex AndroidRequiredPasswordType = "NumericComplex"
	// AndroidRequiredPasswordTypeVAny undocumented
	AndroidRequiredPasswordTypeVAny AndroidRequiredPasswordType = "Any"
)

// AndroidRequiredPasswordTypePDeviceDefault returns a pointer to AndroidRequiredPasswordTypeVDeviceDefault
func AndroidRequiredPasswordTypePDeviceDefault() *AndroidRequiredPasswordType {
	v := AndroidRequiredPasswordTypeVDeviceDefault
	return &v
}

// AndroidRequiredPasswordTypePAlphabetic returns a pointer to AndroidRequiredPasswordTypeVAlphabetic
func AndroidRequiredPasswordTypePAlphabetic() *AndroidRequiredPasswordType {
	v := AndroidRequiredPasswordTypeVAlphabetic
	return &v
}

// AndroidRequiredPasswordTypePAlphanumeric returns a pointer to AndroidRequiredPasswordTypeVAlphanumeric
func AndroidRequiredPasswordTypePAlphanumeric() *AndroidRequiredPasswordType {
	v := AndroidRequiredPasswordTypeVAlphanumeric
	return &v
}

// AndroidRequiredPasswordTypePAlphanumericWithSymbols returns a pointer to AndroidRequiredPasswordTypeVAlphanumericWithSymbols
func AndroidRequiredPasswordTypePAlphanumericWithSymbols() *AndroidRequiredPasswordType {
	v := AndroidRequiredPasswordTypeVAlphanumericWithSymbols
	return &v
}

// AndroidRequiredPasswordTypePLowSecurityBiometric returns a pointer to AndroidRequiredPasswordTypeVLowSecurityBiometric
func AndroidRequiredPasswordTypePLowSecurityBiometric() *AndroidRequiredPasswordType {
	v := AndroidRequiredPasswordTypeVLowSecurityBiometric
	return &v
}

// AndroidRequiredPasswordTypePNumeric returns a pointer to AndroidRequiredPasswordTypeVNumeric
func AndroidRequiredPasswordTypePNumeric() *AndroidRequiredPasswordType {
	v := AndroidRequiredPasswordTypeVNumeric
	return &v
}

// AndroidRequiredPasswordTypePNumericComplex returns a pointer to AndroidRequiredPasswordTypeVNumericComplex
func AndroidRequiredPasswordTypePNumericComplex() *AndroidRequiredPasswordType {
	v := AndroidRequiredPasswordTypeVNumericComplex
	return &v
}

// AndroidRequiredPasswordTypePAny returns a pointer to AndroidRequiredPasswordTypeVAny
func AndroidRequiredPasswordTypePAny() *AndroidRequiredPasswordType {
	v := AndroidRequiredPasswordTypeVAny
	return &v
}
