// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AttendeeType undocumented
type AttendeeType string

const (
	// AttendeeTypeVRequired undocumented
	AttendeeTypeVRequired AttendeeType = "Required"
	// AttendeeTypeVOptional undocumented
	AttendeeTypeVOptional AttendeeType = "Optional"
	// AttendeeTypeVResource undocumented
	AttendeeTypeVResource AttendeeType = "Resource"
)

// AttendeeTypePRequired returns a pointer to AttendeeTypeVRequired
func AttendeeTypePRequired() *AttendeeType {
	v := AttendeeTypeVRequired
	return &v
}

// AttendeeTypePOptional returns a pointer to AttendeeTypeVOptional
func AttendeeTypePOptional() *AttendeeType {
	v := AttendeeTypeVOptional
	return &v
}

// AttendeeTypePResource returns a pointer to AttendeeTypeVResource
func AttendeeTypePResource() *AttendeeType {
	v := AttendeeTypeVResource
	return &v
}
