// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// CallState undocumented
type CallState string

const (
	// CallStateVIncoming undocumented
	CallStateVIncoming CallState = "Incoming"
	// CallStateVEstablishing undocumented
	CallStateVEstablishing CallState = "Establishing"
	// CallStateVEstablished undocumented
	CallStateVEstablished CallState = "Established"
	// CallStateVHold undocumented
	CallStateVHold CallState = "Hold"
	// CallStateVTransferring undocumented
	CallStateVTransferring CallState = "Transferring"
	// CallStateVTransferAccepted undocumented
	CallStateVTransferAccepted CallState = "TransferAccepted"
	// CallStateVRedirecting undocumented
	CallStateVRedirecting CallState = "Redirecting"
	// CallStateVTerminating undocumented
	CallStateVTerminating CallState = "Terminating"
	// CallStateVTerminated undocumented
	CallStateVTerminated CallState = "Terminated"
	// CallStateVUnknownFutureValue undocumented
	CallStateVUnknownFutureValue CallState = "UnknownFutureValue"
)

// CallStatePIncoming returns a pointer to CallStateVIncoming
func CallStatePIncoming() *CallState {
	v := CallStateVIncoming
	return &v
}

// CallStatePEstablishing returns a pointer to CallStateVEstablishing
func CallStatePEstablishing() *CallState {
	v := CallStateVEstablishing
	return &v
}

// CallStatePEstablished returns a pointer to CallStateVEstablished
func CallStatePEstablished() *CallState {
	v := CallStateVEstablished
	return &v
}

// CallStatePHold returns a pointer to CallStateVHold
func CallStatePHold() *CallState {
	v := CallStateVHold
	return &v
}

// CallStatePTransferring returns a pointer to CallStateVTransferring
func CallStatePTransferring() *CallState {
	v := CallStateVTransferring
	return &v
}

// CallStatePTransferAccepted returns a pointer to CallStateVTransferAccepted
func CallStatePTransferAccepted() *CallState {
	v := CallStateVTransferAccepted
	return &v
}

// CallStatePRedirecting returns a pointer to CallStateVRedirecting
func CallStatePRedirecting() *CallState {
	v := CallStateVRedirecting
	return &v
}

// CallStatePTerminating returns a pointer to CallStateVTerminating
func CallStatePTerminating() *CallState {
	v := CallStateVTerminating
	return &v
}

// CallStatePTerminated returns a pointer to CallStateVTerminated
func CallStatePTerminated() *CallState {
	v := CallStateVTerminated
	return &v
}

// CallStatePUnknownFutureValue returns a pointer to CallStateVUnknownFutureValue
func CallStatePUnknownFutureValue() *CallState {
	v := CallStateVUnknownFutureValue
	return &v
}
