// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// CallDirection undocumented
type CallDirection string

const (
	// CallDirectionVIncoming undocumented
	CallDirectionVIncoming CallDirection = "Incoming"
	// CallDirectionVOutgoing undocumented
	CallDirectionVOutgoing CallDirection = "Outgoing"
)

// CallDirectionPIncoming returns a pointer to CallDirectionVIncoming
func CallDirectionPIncoming() *CallDirection {
	v := CallDirectionVIncoming
	return &v
}

// CallDirectionPOutgoing returns a pointer to CallDirectionVOutgoing
func CallDirectionPOutgoing() *CallDirection {
	v := CallDirectionVOutgoing
	return &v
}
