// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DefenderMonitorFileActivity undocumented
type DefenderMonitorFileActivity string

const (
	// DefenderMonitorFileActivityVUserDefined undocumented
	DefenderMonitorFileActivityVUserDefined DefenderMonitorFileActivity = "UserDefined"
	// DefenderMonitorFileActivityVDisable undocumented
	DefenderMonitorFileActivityVDisable DefenderMonitorFileActivity = "Disable"
	// DefenderMonitorFileActivityVMonitorAllFiles undocumented
	DefenderMonitorFileActivityVMonitorAllFiles DefenderMonitorFileActivity = "MonitorAllFiles"
	// DefenderMonitorFileActivityVMonitorIncomingFilesOnly undocumented
	DefenderMonitorFileActivityVMonitorIncomingFilesOnly DefenderMonitorFileActivity = "MonitorIncomingFilesOnly"
	// DefenderMonitorFileActivityVMonitorOutgoingFilesOnly undocumented
	DefenderMonitorFileActivityVMonitorOutgoingFilesOnly DefenderMonitorFileActivity = "MonitorOutgoingFilesOnly"
)

// DefenderMonitorFileActivityPUserDefined returns a pointer to DefenderMonitorFileActivityVUserDefined
func DefenderMonitorFileActivityPUserDefined() *DefenderMonitorFileActivity {
	v := DefenderMonitorFileActivityVUserDefined
	return &v
}

// DefenderMonitorFileActivityPDisable returns a pointer to DefenderMonitorFileActivityVDisable
func DefenderMonitorFileActivityPDisable() *DefenderMonitorFileActivity {
	v := DefenderMonitorFileActivityVDisable
	return &v
}

// DefenderMonitorFileActivityPMonitorAllFiles returns a pointer to DefenderMonitorFileActivityVMonitorAllFiles
func DefenderMonitorFileActivityPMonitorAllFiles() *DefenderMonitorFileActivity {
	v := DefenderMonitorFileActivityVMonitorAllFiles
	return &v
}

// DefenderMonitorFileActivityPMonitorIncomingFilesOnly returns a pointer to DefenderMonitorFileActivityVMonitorIncomingFilesOnly
func DefenderMonitorFileActivityPMonitorIncomingFilesOnly() *DefenderMonitorFileActivity {
	v := DefenderMonitorFileActivityVMonitorIncomingFilesOnly
	return &v
}

// DefenderMonitorFileActivityPMonitorOutgoingFilesOnly returns a pointer to DefenderMonitorFileActivityVMonitorOutgoingFilesOnly
func DefenderMonitorFileActivityPMonitorOutgoingFilesOnly() *DefenderMonitorFileActivity {
	v := DefenderMonitorFileActivityVMonitorOutgoingFilesOnly
	return &v
}
