// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DeviceManagementExchangeAccessState undocumented
type DeviceManagementExchangeAccessState string

const (
	// DeviceManagementExchangeAccessStateVNone undocumented
	DeviceManagementExchangeAccessStateVNone DeviceManagementExchangeAccessState = "None"
	// DeviceManagementExchangeAccessStateVUnknown undocumented
	DeviceManagementExchangeAccessStateVUnknown DeviceManagementExchangeAccessState = "Unknown"
	// DeviceManagementExchangeAccessStateVAllowed undocumented
	DeviceManagementExchangeAccessStateVAllowed DeviceManagementExchangeAccessState = "Allowed"
	// DeviceManagementExchangeAccessStateVBlocked undocumented
	DeviceManagementExchangeAccessStateVBlocked DeviceManagementExchangeAccessState = "Blocked"
	// DeviceManagementExchangeAccessStateVQuarantined undocumented
	DeviceManagementExchangeAccessStateVQuarantined DeviceManagementExchangeAccessState = "Quarantined"
)

// DeviceManagementExchangeAccessStatePNone returns a pointer to DeviceManagementExchangeAccessStateVNone
func DeviceManagementExchangeAccessStatePNone() *DeviceManagementExchangeAccessState {
	v := DeviceManagementExchangeAccessStateVNone
	return &v
}

// DeviceManagementExchangeAccessStatePUnknown returns a pointer to DeviceManagementExchangeAccessStateVUnknown
func DeviceManagementExchangeAccessStatePUnknown() *DeviceManagementExchangeAccessState {
	v := DeviceManagementExchangeAccessStateVUnknown
	return &v
}

// DeviceManagementExchangeAccessStatePAllowed returns a pointer to DeviceManagementExchangeAccessStateVAllowed
func DeviceManagementExchangeAccessStatePAllowed() *DeviceManagementExchangeAccessState {
	v := DeviceManagementExchangeAccessStateVAllowed
	return &v
}

// DeviceManagementExchangeAccessStatePBlocked returns a pointer to DeviceManagementExchangeAccessStateVBlocked
func DeviceManagementExchangeAccessStatePBlocked() *DeviceManagementExchangeAccessState {
	v := DeviceManagementExchangeAccessStateVBlocked
	return &v
}

// DeviceManagementExchangeAccessStatePQuarantined returns a pointer to DeviceManagementExchangeAccessStateVQuarantined
func DeviceManagementExchangeAccessStatePQuarantined() *DeviceManagementExchangeAccessState {
	v := DeviceManagementExchangeAccessStateVQuarantined
	return &v
}
