// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// EdgeCookiePolicy undocumented
type EdgeCookiePolicy string

const (
	// EdgeCookiePolicyVUserDefined undocumented
	EdgeCookiePolicyVUserDefined EdgeCookiePolicy = "UserDefined"
	// EdgeCookiePolicyVAllow undocumented
	EdgeCookiePolicyVAllow EdgeCookiePolicy = "Allow"
	// EdgeCookiePolicyVBlockThirdParty undocumented
	EdgeCookiePolicyVBlockThirdParty EdgeCookiePolicy = "BlockThirdParty"
	// EdgeCookiePolicyVBlockAll undocumented
	EdgeCookiePolicyVBlockAll EdgeCookiePolicy = "BlockAll"
)

// EdgeCookiePolicyPUserDefined returns a pointer to EdgeCookiePolicyVUserDefined
func EdgeCookiePolicyPUserDefined() *EdgeCookiePolicy {
	v := EdgeCookiePolicyVUserDefined
	return &v
}

// EdgeCookiePolicyPAllow returns a pointer to EdgeCookiePolicyVAllow
func EdgeCookiePolicyPAllow() *EdgeCookiePolicy {
	v := EdgeCookiePolicyVAllow
	return &v
}

// EdgeCookiePolicyPBlockThirdParty returns a pointer to EdgeCookiePolicyVBlockThirdParty
func EdgeCookiePolicyPBlockThirdParty() *EdgeCookiePolicy {
	v := EdgeCookiePolicyVBlockThirdParty
	return &v
}

// EdgeCookiePolicyPBlockAll returns a pointer to EdgeCookiePolicyVBlockAll
func EdgeCookiePolicyPBlockAll() *EdgeCookiePolicy {
	v := EdgeCookiePolicyVBlockAll
	return &v
}
