// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// Enablement undocumented
type Enablement string

const (
	// EnablementVNotConfigured undocumented
	EnablementVNotConfigured Enablement = "NotConfigured"
	// EnablementVEnabled undocumented
	EnablementVEnabled Enablement = "Enabled"
	// EnablementVDisabled undocumented
	EnablementVDisabled Enablement = "Disabled"
)

// EnablementPNotConfigured returns a pointer to EnablementVNotConfigured
func EnablementPNotConfigured() *Enablement {
	v := EnablementVNotConfigured
	return &v
}

// EnablementPEnabled returns a pointer to EnablementVEnabled
func EnablementPEnabled() *Enablement {
	v := EnablementVEnabled
	return &v
}

// EnablementPDisabled returns a pointer to EnablementVDisabled
func EnablementPDisabled() *Enablement {
	v := EnablementVDisabled
	return &v
}
