// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// EventType undocumented
type EventType string

const (
	// EventTypeVSingleInstance undocumented
	EventTypeVSingleInstance EventType = "SingleInstance"
	// EventTypeVOccurrence undocumented
	EventTypeVOccurrence EventType = "Occurrence"
	// EventTypeVException undocumented
	EventTypeVException EventType = "Exception"
	// EventTypeVSeriesMaster undocumented
	EventTypeVSeriesMaster EventType = "SeriesMaster"
)

// EventTypePSingleInstance returns a pointer to EventTypeVSingleInstance
func EventTypePSingleInstance() *EventType {
	v := EventTypeVSingleInstance
	return &v
}

// EventTypePOccurrence returns a pointer to EventTypeVOccurrence
func EventTypePOccurrence() *EventType {
	v := EventTypeVOccurrence
	return &v
}

// EventTypePException returns a pointer to EventTypeVException
func EventTypePException() *EventType {
	v := EventTypeVException
	return &v
}

// EventTypePSeriesMaster returns a pointer to EventTypeVSeriesMaster
func EventTypePSeriesMaster() *EventType {
	v := EventTypeVSeriesMaster
	return &v
}
