// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// FollowupFlagStatus undocumented
type FollowupFlagStatus string

const (
	// FollowupFlagStatusVNotFlagged undocumented
	FollowupFlagStatusVNotFlagged FollowupFlagStatus = "NotFlagged"
	// FollowupFlagStatusVComplete undocumented
	FollowupFlagStatusVComplete FollowupFlagStatus = "Complete"
	// FollowupFlagStatusVFlagged undocumented
	FollowupFlagStatusVFlagged FollowupFlagStatus = "Flagged"
)

// FollowupFlagStatusPNotFlagged returns a pointer to FollowupFlagStatusVNotFlagged
func FollowupFlagStatusPNotFlagged() *FollowupFlagStatus {
	v := FollowupFlagStatusVNotFlagged
	return &v
}

// FollowupFlagStatusPComplete returns a pointer to FollowupFlagStatusVComplete
func FollowupFlagStatusPComplete() *FollowupFlagStatus {
	v := FollowupFlagStatusVComplete
	return &v
}

// FollowupFlagStatusPFlagged returns a pointer to FollowupFlagStatusVFlagged
func FollowupFlagStatusPFlagged() *FollowupFlagStatus {
	v := FollowupFlagStatusVFlagged
	return &v
}
