// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// LogonType undocumented
type LogonType string

const (
	// LogonTypeVUnknown undocumented
	LogonTypeVUnknown LogonType = "Unknown"
	// LogonTypeVInteractive undocumented
	LogonTypeVInteractive LogonType = "Interactive"
	// LogonTypeVRemoteInteractive undocumented
	LogonTypeVRemoteInteractive LogonType = "RemoteInteractive"
	// LogonTypeVNetwork undocumented
	LogonTypeVNetwork LogonType = "Network"
	// LogonTypeVBatch undocumented
	LogonTypeVBatch LogonType = "Batch"
	// LogonTypeVService undocumented
	LogonTypeVService LogonType = "Service"
	// LogonTypeVUnknownFutureValue undocumented
	LogonTypeVUnknownFutureValue LogonType = "UnknownFutureValue"
)

// LogonTypePUnknown returns a pointer to LogonTypeVUnknown
func LogonTypePUnknown() *LogonType {
	v := LogonTypeVUnknown
	return &v
}

// LogonTypePInteractive returns a pointer to LogonTypeVInteractive
func LogonTypePInteractive() *LogonType {
	v := LogonTypeVInteractive
	return &v
}

// LogonTypePRemoteInteractive returns a pointer to LogonTypeVRemoteInteractive
func LogonTypePRemoteInteractive() *LogonType {
	v := LogonTypeVRemoteInteractive
	return &v
}

// LogonTypePNetwork returns a pointer to LogonTypeVNetwork
func LogonTypePNetwork() *LogonType {
	v := LogonTypeVNetwork
	return &v
}

// LogonTypePBatch returns a pointer to LogonTypeVBatch
func LogonTypePBatch() *LogonType {
	v := LogonTypeVBatch
	return &v
}

// LogonTypePService returns a pointer to LogonTypeVService
func LogonTypePService() *LogonType {
	v := LogonTypeVService
	return &v
}

// LogonTypePUnknownFutureValue returns a pointer to LogonTypeVUnknownFutureValue
func LogonTypePUnknownFutureValue() *LogonType {
	v := LogonTypeVUnknownFutureValue
	return &v
}
