// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ManagedAppClipboardSharingLevel undocumented
type ManagedAppClipboardSharingLevel string

const (
	// ManagedAppClipboardSharingLevelVAllApps undocumented
	ManagedAppClipboardSharingLevelVAllApps ManagedAppClipboardSharingLevel = "AllApps"
	// ManagedAppClipboardSharingLevelVManagedAppsWithPasteIn undocumented
	ManagedAppClipboardSharingLevelVManagedAppsWithPasteIn ManagedAppClipboardSharingLevel = "ManagedAppsWithPasteIn"
	// ManagedAppClipboardSharingLevelVManagedApps undocumented
	ManagedAppClipboardSharingLevelVManagedApps ManagedAppClipboardSharingLevel = "ManagedApps"
	// ManagedAppClipboardSharingLevelVBlocked undocumented
	ManagedAppClipboardSharingLevelVBlocked ManagedAppClipboardSharingLevel = "Blocked"
)

// ManagedAppClipboardSharingLevelPAllApps returns a pointer to ManagedAppClipboardSharingLevelVAllApps
func ManagedAppClipboardSharingLevelPAllApps() *ManagedAppClipboardSharingLevel {
	v := ManagedAppClipboardSharingLevelVAllApps
	return &v
}

// ManagedAppClipboardSharingLevelPManagedAppsWithPasteIn returns a pointer to ManagedAppClipboardSharingLevelVManagedAppsWithPasteIn
func ManagedAppClipboardSharingLevelPManagedAppsWithPasteIn() *ManagedAppClipboardSharingLevel {
	v := ManagedAppClipboardSharingLevelVManagedAppsWithPasteIn
	return &v
}

// ManagedAppClipboardSharingLevelPManagedApps returns a pointer to ManagedAppClipboardSharingLevelVManagedApps
func ManagedAppClipboardSharingLevelPManagedApps() *ManagedAppClipboardSharingLevel {
	v := ManagedAppClipboardSharingLevelVManagedApps
	return &v
}

// ManagedAppClipboardSharingLevelPBlocked returns a pointer to ManagedAppClipboardSharingLevelVBlocked
func ManagedAppClipboardSharingLevelPBlocked() *ManagedAppClipboardSharingLevel {
	v := ManagedAppClipboardSharingLevelVBlocked
	return &v
}
