// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ManagedAppDataStorageLocation undocumented
type ManagedAppDataStorageLocation string

const (
	// ManagedAppDataStorageLocationVOneDriveForBusiness undocumented
	ManagedAppDataStorageLocationVOneDriveForBusiness ManagedAppDataStorageLocation = "OneDriveForBusiness"
	// ManagedAppDataStorageLocationVSharePoint undocumented
	ManagedAppDataStorageLocationVSharePoint ManagedAppDataStorageLocation = "SharePoint"
	// ManagedAppDataStorageLocationVLocalStorage undocumented
	ManagedAppDataStorageLocationVLocalStorage ManagedAppDataStorageLocation = "LocalStorage"
)

// ManagedAppDataStorageLocationPOneDriveForBusiness returns a pointer to ManagedAppDataStorageLocationVOneDriveForBusiness
func ManagedAppDataStorageLocationPOneDriveForBusiness() *ManagedAppDataStorageLocation {
	v := ManagedAppDataStorageLocationVOneDriveForBusiness
	return &v
}

// ManagedAppDataStorageLocationPSharePoint returns a pointer to ManagedAppDataStorageLocationVSharePoint
func ManagedAppDataStorageLocationPSharePoint() *ManagedAppDataStorageLocation {
	v := ManagedAppDataStorageLocationVSharePoint
	return &v
}

// ManagedAppDataStorageLocationPLocalStorage returns a pointer to ManagedAppDataStorageLocationVLocalStorage
func ManagedAppDataStorageLocationPLocalStorage() *ManagedAppDataStorageLocation {
	v := ManagedAppDataStorageLocationVLocalStorage
	return &v
}
