// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ManagementAgentType undocumented
type ManagementAgentType string

const (
	// ManagementAgentTypeVEas undocumented
	ManagementAgentTypeVEas ManagementAgentType = "Eas"
	// ManagementAgentTypeVMdm undocumented
	ManagementAgentTypeVMdm ManagementAgentType = "Mdm"
	// ManagementAgentTypeVEasMdm undocumented
	ManagementAgentTypeVEasMdm ManagementAgentType = "EasMdm"
	// ManagementAgentTypeVIntuneClient undocumented
	ManagementAgentTypeVIntuneClient ManagementAgentType = "IntuneClient"
	// ManagementAgentTypeVEasIntuneClient undocumented
	ManagementAgentTypeVEasIntuneClient ManagementAgentType = "EasIntuneClient"
	// ManagementAgentTypeVConfigurationManagerClient undocumented
	ManagementAgentTypeVConfigurationManagerClient ManagementAgentType = "ConfigurationManagerClient"
	// ManagementAgentTypeVConfigurationManagerClientMdm undocumented
	ManagementAgentTypeVConfigurationManagerClientMdm ManagementAgentType = "ConfigurationManagerClientMdm"
	// ManagementAgentTypeVConfigurationManagerClientMdmEas undocumented
	ManagementAgentTypeVConfigurationManagerClientMdmEas ManagementAgentType = "ConfigurationManagerClientMdmEas"
	// ManagementAgentTypeVUnknown undocumented
	ManagementAgentTypeVUnknown ManagementAgentType = "Unknown"
	// ManagementAgentTypeVJamf undocumented
	ManagementAgentTypeVJamf ManagementAgentType = "Jamf"
	// ManagementAgentTypeVGoogleCloudDevicePolicyController undocumented
	ManagementAgentTypeVGoogleCloudDevicePolicyController ManagementAgentType = "GoogleCloudDevicePolicyController"
)

// ManagementAgentTypePEas returns a pointer to ManagementAgentTypeVEas
func ManagementAgentTypePEas() *ManagementAgentType {
	v := ManagementAgentTypeVEas
	return &v
}

// ManagementAgentTypePMdm returns a pointer to ManagementAgentTypeVMdm
func ManagementAgentTypePMdm() *ManagementAgentType {
	v := ManagementAgentTypeVMdm
	return &v
}

// ManagementAgentTypePEasMdm returns a pointer to ManagementAgentTypeVEasMdm
func ManagementAgentTypePEasMdm() *ManagementAgentType {
	v := ManagementAgentTypeVEasMdm
	return &v
}

// ManagementAgentTypePIntuneClient returns a pointer to ManagementAgentTypeVIntuneClient
func ManagementAgentTypePIntuneClient() *ManagementAgentType {
	v := ManagementAgentTypeVIntuneClient
	return &v
}

// ManagementAgentTypePEasIntuneClient returns a pointer to ManagementAgentTypeVEasIntuneClient
func ManagementAgentTypePEasIntuneClient() *ManagementAgentType {
	v := ManagementAgentTypeVEasIntuneClient
	return &v
}

// ManagementAgentTypePConfigurationManagerClient returns a pointer to ManagementAgentTypeVConfigurationManagerClient
func ManagementAgentTypePConfigurationManagerClient() *ManagementAgentType {
	v := ManagementAgentTypeVConfigurationManagerClient
	return &v
}

// ManagementAgentTypePConfigurationManagerClientMdm returns a pointer to ManagementAgentTypeVConfigurationManagerClientMdm
func ManagementAgentTypePConfigurationManagerClientMdm() *ManagementAgentType {
	v := ManagementAgentTypeVConfigurationManagerClientMdm
	return &v
}

// ManagementAgentTypePConfigurationManagerClientMdmEas returns a pointer to ManagementAgentTypeVConfigurationManagerClientMdmEas
func ManagementAgentTypePConfigurationManagerClientMdmEas() *ManagementAgentType {
	v := ManagementAgentTypeVConfigurationManagerClientMdmEas
	return &v
}

// ManagementAgentTypePUnknown returns a pointer to ManagementAgentTypeVUnknown
func ManagementAgentTypePUnknown() *ManagementAgentType {
	v := ManagementAgentTypeVUnknown
	return &v
}

// ManagementAgentTypePJamf returns a pointer to ManagementAgentTypeVJamf
func ManagementAgentTypePJamf() *ManagementAgentType {
	v := ManagementAgentTypeVJamf
	return &v
}

// ManagementAgentTypePGoogleCloudDevicePolicyController returns a pointer to ManagementAgentTypeVGoogleCloudDevicePolicyController
func ManagementAgentTypePGoogleCloudDevicePolicyController() *ManagementAgentType {
	v := ManagementAgentTypeVGoogleCloudDevicePolicyController
	return &v
}
