// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// MdmAuthority undocumented
type MdmAuthority string

const (
	// MdmAuthorityVUnknown undocumented
	MdmAuthorityVUnknown MdmAuthority = "Unknown"
	// MdmAuthorityVIntune undocumented
	MdmAuthorityVIntune MdmAuthority = "Intune"
	// MdmAuthorityVSccm undocumented
	MdmAuthorityVSccm MdmAuthority = "Sccm"
	// MdmAuthorityVOffice365 undocumented
	MdmAuthorityVOffice365 MdmAuthority = "Office365"
)

// MdmAuthorityPUnknown returns a pointer to MdmAuthorityVUnknown
func MdmAuthorityPUnknown() *MdmAuthority {
	v := MdmAuthorityVUnknown
	return &v
}

// MdmAuthorityPIntune returns a pointer to MdmAuthorityVIntune
func MdmAuthorityPIntune() *MdmAuthority {
	v := MdmAuthorityVIntune
	return &v
}

// MdmAuthorityPSccm returns a pointer to MdmAuthorityVSccm
func MdmAuthorityPSccm() *MdmAuthority {
	v := MdmAuthorityVSccm
	return &v
}

// MdmAuthorityPOffice365 returns a pointer to MdmAuthorityVOffice365
func MdmAuthorityPOffice365() *MdmAuthority {
	v := MdmAuthorityVOffice365
	return &v
}
