// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// MediaState undocumented
type MediaState string

const (
	// MediaStateVActive undocumented
	MediaStateVActive MediaState = "Active"
	// MediaStateVInactive undocumented
	MediaStateVInactive MediaState = "Inactive"
	// MediaStateVUnknownFutureValue undocumented
	MediaStateVUnknownFutureValue MediaState = "UnknownFutureValue"
)

// MediaStatePActive returns a pointer to MediaStateVActive
func MediaStatePActive() *MediaState {
	v := MediaStateVActive
	return &v
}

// MediaStatePInactive returns a pointer to MediaStateVInactive
func MediaStatePInactive() *MediaState {
	v := MediaStateVInactive
	return &v
}

// MediaStatePUnknownFutureValue returns a pointer to MediaStateVUnknownFutureValue
func MediaStatePUnknownFutureValue() *MediaState {
	v := MediaStateVUnknownFutureValue
	return &v
}
