// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// MessageActionFlag undocumented
type MessageActionFlag string

const (
	// MessageActionFlagVAny undocumented
	MessageActionFlagVAny MessageActionFlag = "Any"
	// MessageActionFlagVCall undocumented
	MessageActionFlagVCall MessageActionFlag = "Call"
	// MessageActionFlagVDoNotForward undocumented
	MessageActionFlagVDoNotForward MessageActionFlag = "DoNotForward"
	// MessageActionFlagVFollowUp undocumented
	MessageActionFlagVFollowUp MessageActionFlag = "FollowUp"
	// MessageActionFlagVFyi undocumented
	MessageActionFlagVFyi MessageActionFlag = "Fyi"
	// MessageActionFlagVForward undocumented
	MessageActionFlagVForward MessageActionFlag = "Forward"
	// MessageActionFlagVNoResponseNecessary undocumented
	MessageActionFlagVNoResponseNecessary MessageActionFlag = "NoResponseNecessary"
	// MessageActionFlagVRead undocumented
	MessageActionFlagVRead MessageActionFlag = "Read"
	// MessageActionFlagVReply undocumented
	MessageActionFlagVReply MessageActionFlag = "Reply"
	// MessageActionFlagVReplyToAll undocumented
	MessageActionFlagVReplyToAll MessageActionFlag = "ReplyToAll"
	// MessageActionFlagVReview undocumented
	MessageActionFlagVReview MessageActionFlag = "Review"
)

// MessageActionFlagPAny returns a pointer to MessageActionFlagVAny
func MessageActionFlagPAny() *MessageActionFlag {
	v := MessageActionFlagVAny
	return &v
}

// MessageActionFlagPCall returns a pointer to MessageActionFlagVCall
func MessageActionFlagPCall() *MessageActionFlag {
	v := MessageActionFlagVCall
	return &v
}

// MessageActionFlagPDoNotForward returns a pointer to MessageActionFlagVDoNotForward
func MessageActionFlagPDoNotForward() *MessageActionFlag {
	v := MessageActionFlagVDoNotForward
	return &v
}

// MessageActionFlagPFollowUp returns a pointer to MessageActionFlagVFollowUp
func MessageActionFlagPFollowUp() *MessageActionFlag {
	v := MessageActionFlagVFollowUp
	return &v
}

// MessageActionFlagPFyi returns a pointer to MessageActionFlagVFyi
func MessageActionFlagPFyi() *MessageActionFlag {
	v := MessageActionFlagVFyi
	return &v
}

// MessageActionFlagPForward returns a pointer to MessageActionFlagVForward
func MessageActionFlagPForward() *MessageActionFlag {
	v := MessageActionFlagVForward
	return &v
}

// MessageActionFlagPNoResponseNecessary returns a pointer to MessageActionFlagVNoResponseNecessary
func MessageActionFlagPNoResponseNecessary() *MessageActionFlag {
	v := MessageActionFlagVNoResponseNecessary
	return &v
}

// MessageActionFlagPRead returns a pointer to MessageActionFlagVRead
func MessageActionFlagPRead() *MessageActionFlag {
	v := MessageActionFlagVRead
	return &v
}

// MessageActionFlagPReply returns a pointer to MessageActionFlagVReply
func MessageActionFlagPReply() *MessageActionFlag {
	v := MessageActionFlagVReply
	return &v
}

// MessageActionFlagPReplyToAll returns a pointer to MessageActionFlagVReplyToAll
func MessageActionFlagPReplyToAll() *MessageActionFlag {
	v := MessageActionFlagVReplyToAll
	return &v
}

// MessageActionFlagPReview returns a pointer to MessageActionFlagVReview
func MessageActionFlagPReview() *MessageActionFlag {
	v := MessageActionFlagVReview
	return &v
}
