// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// OnenoteSourceService undocumented
type OnenoteSourceService string

const (
	// OnenoteSourceServiceVUnknown undocumented
	OnenoteSourceServiceVUnknown OnenoteSourceService = "Unknown"
	// OnenoteSourceServiceVOneDrive undocumented
	OnenoteSourceServiceVOneDrive OnenoteSourceService = "OneDrive"
	// OnenoteSourceServiceVOneDriveForBusiness undocumented
	OnenoteSourceServiceVOneDriveForBusiness OnenoteSourceService = "OneDriveForBusiness"
	// OnenoteSourceServiceVOnPremOneDriveForBusiness undocumented
	OnenoteSourceServiceVOnPremOneDriveForBusiness OnenoteSourceService = "OnPremOneDriveForBusiness"
)

// OnenoteSourceServicePUnknown returns a pointer to OnenoteSourceServiceVUnknown
func OnenoteSourceServicePUnknown() *OnenoteSourceService {
	v := OnenoteSourceServiceVUnknown
	return &v
}

// OnenoteSourceServicePOneDrive returns a pointer to OnenoteSourceServiceVOneDrive
func OnenoteSourceServicePOneDrive() *OnenoteSourceService {
	v := OnenoteSourceServiceVOneDrive
	return &v
}

// OnenoteSourceServicePOneDriveForBusiness returns a pointer to OnenoteSourceServiceVOneDriveForBusiness
func OnenoteSourceServicePOneDriveForBusiness() *OnenoteSourceService {
	v := OnenoteSourceServiceVOneDriveForBusiness
	return &v
}

// OnenoteSourceServicePOnPremOneDriveForBusiness returns a pointer to OnenoteSourceServiceVOnPremOneDriveForBusiness
func OnenoteSourceServicePOnPremOneDriveForBusiness() *OnenoteSourceService {
	v := OnenoteSourceServiceVOnPremOneDriveForBusiness
	return &v
}
