// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// OnenotePatchInsertPosition undocumented
type OnenotePatchInsertPosition string

const (
	// OnenotePatchInsertPositionVAfter undocumented
	OnenotePatchInsertPositionVAfter OnenotePatchInsertPosition = "After"
	// OnenotePatchInsertPositionVBefore undocumented
	OnenotePatchInsertPositionVBefore OnenotePatchInsertPosition = "Before"
)

// OnenotePatchInsertPositionPAfter returns a pointer to OnenotePatchInsertPositionVAfter
func OnenotePatchInsertPositionPAfter() *OnenotePatchInsertPosition {
	v := OnenotePatchInsertPositionVAfter
	return &v
}

// OnenotePatchInsertPositionPBefore returns a pointer to OnenotePatchInsertPositionVBefore
func OnenotePatchInsertPositionPBefore() *OnenotePatchInsertPosition {
	v := OnenotePatchInsertPositionVBefore
	return &v
}
