// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// PhysicalAddressType undocumented
type PhysicalAddressType string

const (
	// PhysicalAddressTypeVUnknown undocumented
	PhysicalAddressTypeVUnknown PhysicalAddressType = "Unknown"
	// PhysicalAddressTypeVHome undocumented
	PhysicalAddressTypeVHome PhysicalAddressType = "Home"
	// PhysicalAddressTypeVBusiness undocumented
	PhysicalAddressTypeVBusiness PhysicalAddressType = "Business"
	// PhysicalAddressTypeVOther undocumented
	PhysicalAddressTypeVOther PhysicalAddressType = "Other"
)

// PhysicalAddressTypePUnknown returns a pointer to PhysicalAddressTypeVUnknown
func PhysicalAddressTypePUnknown() *PhysicalAddressType {
	v := PhysicalAddressTypeVUnknown
	return &v
}

// PhysicalAddressTypePHome returns a pointer to PhysicalAddressTypeVHome
func PhysicalAddressTypePHome() *PhysicalAddressType {
	v := PhysicalAddressTypeVHome
	return &v
}

// PhysicalAddressTypePBusiness returns a pointer to PhysicalAddressTypeVBusiness
func PhysicalAddressTypePBusiness() *PhysicalAddressType {
	v := PhysicalAddressTypeVBusiness
	return &v
}

// PhysicalAddressTypePOther returns a pointer to PhysicalAddressTypeVOther
func PhysicalAddressTypePOther() *PhysicalAddressType {
	v := PhysicalAddressTypeVOther
	return &v
}
