// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// PrereleaseFeatures undocumented
type PrereleaseFeatures string

const (
	// PrereleaseFeaturesVUserDefined undocumented
	PrereleaseFeaturesVUserDefined PrereleaseFeatures = "UserDefined"
	// PrereleaseFeaturesVSettingsOnly undocumented
	PrereleaseFeaturesVSettingsOnly PrereleaseFeatures = "SettingsOnly"
	// PrereleaseFeaturesVSettingsAndExperimentations undocumented
	PrereleaseFeaturesVSettingsAndExperimentations PrereleaseFeatures = "SettingsAndExperimentations"
	// PrereleaseFeaturesVNotAllowed undocumented
	PrereleaseFeaturesVNotAllowed PrereleaseFeatures = "NotAllowed"
)

// PrereleaseFeaturesPUserDefined returns a pointer to PrereleaseFeaturesVUserDefined
func PrereleaseFeaturesPUserDefined() *PrereleaseFeatures {
	v := PrereleaseFeaturesVUserDefined
	return &v
}

// PrereleaseFeaturesPSettingsOnly returns a pointer to PrereleaseFeaturesVSettingsOnly
func PrereleaseFeaturesPSettingsOnly() *PrereleaseFeatures {
	v := PrereleaseFeaturesVSettingsOnly
	return &v
}

// PrereleaseFeaturesPSettingsAndExperimentations returns a pointer to PrereleaseFeaturesVSettingsAndExperimentations
func PrereleaseFeaturesPSettingsAndExperimentations() *PrereleaseFeatures {
	v := PrereleaseFeaturesVSettingsAndExperimentations
	return &v
}

// PrereleaseFeaturesPNotAllowed returns a pointer to PrereleaseFeaturesVNotAllowed
func PrereleaseFeaturesPNotAllowed() *PrereleaseFeatures {
	v := PrereleaseFeaturesVNotAllowed
	return &v
}
