// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RatingUnitedKingdomMoviesType undocumented
type RatingUnitedKingdomMoviesType string

const (
	// RatingUnitedKingdomMoviesTypeVAllAllowed undocumented
	RatingUnitedKingdomMoviesTypeVAllAllowed RatingUnitedKingdomMoviesType = "AllAllowed"
	// RatingUnitedKingdomMoviesTypeVAllBlocked undocumented
	RatingUnitedKingdomMoviesTypeVAllBlocked RatingUnitedKingdomMoviesType = "AllBlocked"
	// RatingUnitedKingdomMoviesTypeVGeneral undocumented
	RatingUnitedKingdomMoviesTypeVGeneral RatingUnitedKingdomMoviesType = "General"
	// RatingUnitedKingdomMoviesTypeVUniversalChildren undocumented
	RatingUnitedKingdomMoviesTypeVUniversalChildren RatingUnitedKingdomMoviesType = "UniversalChildren"
	// RatingUnitedKingdomMoviesTypeVParentalGuidance undocumented
	RatingUnitedKingdomMoviesTypeVParentalGuidance RatingUnitedKingdomMoviesType = "ParentalGuidance"
	// RatingUnitedKingdomMoviesTypeVAgesAbove12Video undocumented
	RatingUnitedKingdomMoviesTypeVAgesAbove12Video RatingUnitedKingdomMoviesType = "AgesAbove12Video"
	// RatingUnitedKingdomMoviesTypeVAgesAbove12Cinema undocumented
	RatingUnitedKingdomMoviesTypeVAgesAbove12Cinema RatingUnitedKingdomMoviesType = "AgesAbove12Cinema"
	// RatingUnitedKingdomMoviesTypeVAgesAbove15 undocumented
	RatingUnitedKingdomMoviesTypeVAgesAbove15 RatingUnitedKingdomMoviesType = "AgesAbove15"
	// RatingUnitedKingdomMoviesTypeVAdults undocumented
	RatingUnitedKingdomMoviesTypeVAdults RatingUnitedKingdomMoviesType = "Adults"
)

// RatingUnitedKingdomMoviesTypePAllAllowed returns a pointer to RatingUnitedKingdomMoviesTypeVAllAllowed
func RatingUnitedKingdomMoviesTypePAllAllowed() *RatingUnitedKingdomMoviesType {
	v := RatingUnitedKingdomMoviesTypeVAllAllowed
	return &v
}

// RatingUnitedKingdomMoviesTypePAllBlocked returns a pointer to RatingUnitedKingdomMoviesTypeVAllBlocked
func RatingUnitedKingdomMoviesTypePAllBlocked() *RatingUnitedKingdomMoviesType {
	v := RatingUnitedKingdomMoviesTypeVAllBlocked
	return &v
}

// RatingUnitedKingdomMoviesTypePGeneral returns a pointer to RatingUnitedKingdomMoviesTypeVGeneral
func RatingUnitedKingdomMoviesTypePGeneral() *RatingUnitedKingdomMoviesType {
	v := RatingUnitedKingdomMoviesTypeVGeneral
	return &v
}

// RatingUnitedKingdomMoviesTypePUniversalChildren returns a pointer to RatingUnitedKingdomMoviesTypeVUniversalChildren
func RatingUnitedKingdomMoviesTypePUniversalChildren() *RatingUnitedKingdomMoviesType {
	v := RatingUnitedKingdomMoviesTypeVUniversalChildren
	return &v
}

// RatingUnitedKingdomMoviesTypePParentalGuidance returns a pointer to RatingUnitedKingdomMoviesTypeVParentalGuidance
func RatingUnitedKingdomMoviesTypePParentalGuidance() *RatingUnitedKingdomMoviesType {
	v := RatingUnitedKingdomMoviesTypeVParentalGuidance
	return &v
}

// RatingUnitedKingdomMoviesTypePAgesAbove12Video returns a pointer to RatingUnitedKingdomMoviesTypeVAgesAbove12Video
func RatingUnitedKingdomMoviesTypePAgesAbove12Video() *RatingUnitedKingdomMoviesType {
	v := RatingUnitedKingdomMoviesTypeVAgesAbove12Video
	return &v
}

// RatingUnitedKingdomMoviesTypePAgesAbove12Cinema returns a pointer to RatingUnitedKingdomMoviesTypeVAgesAbove12Cinema
func RatingUnitedKingdomMoviesTypePAgesAbove12Cinema() *RatingUnitedKingdomMoviesType {
	v := RatingUnitedKingdomMoviesTypeVAgesAbove12Cinema
	return &v
}

// RatingUnitedKingdomMoviesTypePAgesAbove15 returns a pointer to RatingUnitedKingdomMoviesTypeVAgesAbove15
func RatingUnitedKingdomMoviesTypePAgesAbove15() *RatingUnitedKingdomMoviesType {
	v := RatingUnitedKingdomMoviesTypeVAgesAbove15
	return &v
}

// RatingUnitedKingdomMoviesTypePAdults returns a pointer to RatingUnitedKingdomMoviesTypeVAdults
func RatingUnitedKingdomMoviesTypePAdults() *RatingUnitedKingdomMoviesType {
	v := RatingUnitedKingdomMoviesTypeVAdults
	return &v
}
