// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RatingFranceMoviesType undocumented
type RatingFranceMoviesType string

const (
	// RatingFranceMoviesTypeVAllAllowed undocumented
	RatingFranceMoviesTypeVAllAllowed RatingFranceMoviesType = "AllAllowed"
	// RatingFranceMoviesTypeVAllBlocked undocumented
	RatingFranceMoviesTypeVAllBlocked RatingFranceMoviesType = "AllBlocked"
	// RatingFranceMoviesTypeVAgesAbove10 undocumented
	RatingFranceMoviesTypeVAgesAbove10 RatingFranceMoviesType = "AgesAbove10"
	// RatingFranceMoviesTypeVAgesAbove12 undocumented
	RatingFranceMoviesTypeVAgesAbove12 RatingFranceMoviesType = "AgesAbove12"
	// RatingFranceMoviesTypeVAgesAbove16 undocumented
	RatingFranceMoviesTypeVAgesAbove16 RatingFranceMoviesType = "AgesAbove16"
	// RatingFranceMoviesTypeVAgesAbove18 undocumented
	RatingFranceMoviesTypeVAgesAbove18 RatingFranceMoviesType = "AgesAbove18"
)

// RatingFranceMoviesTypePAllAllowed returns a pointer to RatingFranceMoviesTypeVAllAllowed
func RatingFranceMoviesTypePAllAllowed() *RatingFranceMoviesType {
	v := RatingFranceMoviesTypeVAllAllowed
	return &v
}

// RatingFranceMoviesTypePAllBlocked returns a pointer to RatingFranceMoviesTypeVAllBlocked
func RatingFranceMoviesTypePAllBlocked() *RatingFranceMoviesType {
	v := RatingFranceMoviesTypeVAllBlocked
	return &v
}

// RatingFranceMoviesTypePAgesAbove10 returns a pointer to RatingFranceMoviesTypeVAgesAbove10
func RatingFranceMoviesTypePAgesAbove10() *RatingFranceMoviesType {
	v := RatingFranceMoviesTypeVAgesAbove10
	return &v
}

// RatingFranceMoviesTypePAgesAbove12 returns a pointer to RatingFranceMoviesTypeVAgesAbove12
func RatingFranceMoviesTypePAgesAbove12() *RatingFranceMoviesType {
	v := RatingFranceMoviesTypeVAgesAbove12
	return &v
}

// RatingFranceMoviesTypePAgesAbove16 returns a pointer to RatingFranceMoviesTypeVAgesAbove16
func RatingFranceMoviesTypePAgesAbove16() *RatingFranceMoviesType {
	v := RatingFranceMoviesTypeVAgesAbove16
	return &v
}

// RatingFranceMoviesTypePAgesAbove18 returns a pointer to RatingFranceMoviesTypeVAgesAbove18
func RatingFranceMoviesTypePAgesAbove18() *RatingFranceMoviesType {
	v := RatingFranceMoviesTypeVAgesAbove18
	return &v
}
