// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RatingUnitedStatesTelevisionType undocumented
type RatingUnitedStatesTelevisionType string

const (
	// RatingUnitedStatesTelevisionTypeVAllAllowed undocumented
	RatingUnitedStatesTelevisionTypeVAllAllowed RatingUnitedStatesTelevisionType = "AllAllowed"
	// RatingUnitedStatesTelevisionTypeVAllBlocked undocumented
	RatingUnitedStatesTelevisionTypeVAllBlocked RatingUnitedStatesTelevisionType = "AllBlocked"
	// RatingUnitedStatesTelevisionTypeVChildrenAll undocumented
	RatingUnitedStatesTelevisionTypeVChildrenAll RatingUnitedStatesTelevisionType = "ChildrenAll"
	// RatingUnitedStatesTelevisionTypeVChildrenAbove7 undocumented
	RatingUnitedStatesTelevisionTypeVChildrenAbove7 RatingUnitedStatesTelevisionType = "ChildrenAbove7"
	// RatingUnitedStatesTelevisionTypeVGeneral undocumented
	RatingUnitedStatesTelevisionTypeVGeneral RatingUnitedStatesTelevisionType = "General"
	// RatingUnitedStatesTelevisionTypeVParentalGuidance undocumented
	RatingUnitedStatesTelevisionTypeVParentalGuidance RatingUnitedStatesTelevisionType = "ParentalGuidance"
	// RatingUnitedStatesTelevisionTypeVChildrenAbove14 undocumented
	RatingUnitedStatesTelevisionTypeVChildrenAbove14 RatingUnitedStatesTelevisionType = "ChildrenAbove14"
	// RatingUnitedStatesTelevisionTypeVAdults undocumented
	RatingUnitedStatesTelevisionTypeVAdults RatingUnitedStatesTelevisionType = "Adults"
)

// RatingUnitedStatesTelevisionTypePAllAllowed returns a pointer to RatingUnitedStatesTelevisionTypeVAllAllowed
func RatingUnitedStatesTelevisionTypePAllAllowed() *RatingUnitedStatesTelevisionType {
	v := RatingUnitedStatesTelevisionTypeVAllAllowed
	return &v
}

// RatingUnitedStatesTelevisionTypePAllBlocked returns a pointer to RatingUnitedStatesTelevisionTypeVAllBlocked
func RatingUnitedStatesTelevisionTypePAllBlocked() *RatingUnitedStatesTelevisionType {
	v := RatingUnitedStatesTelevisionTypeVAllBlocked
	return &v
}

// RatingUnitedStatesTelevisionTypePChildrenAll returns a pointer to RatingUnitedStatesTelevisionTypeVChildrenAll
func RatingUnitedStatesTelevisionTypePChildrenAll() *RatingUnitedStatesTelevisionType {
	v := RatingUnitedStatesTelevisionTypeVChildrenAll
	return &v
}

// RatingUnitedStatesTelevisionTypePChildrenAbove7 returns a pointer to RatingUnitedStatesTelevisionTypeVChildrenAbove7
func RatingUnitedStatesTelevisionTypePChildrenAbove7() *RatingUnitedStatesTelevisionType {
	v := RatingUnitedStatesTelevisionTypeVChildrenAbove7
	return &v
}

// RatingUnitedStatesTelevisionTypePGeneral returns a pointer to RatingUnitedStatesTelevisionTypeVGeneral
func RatingUnitedStatesTelevisionTypePGeneral() *RatingUnitedStatesTelevisionType {
	v := RatingUnitedStatesTelevisionTypeVGeneral
	return &v
}

// RatingUnitedStatesTelevisionTypePParentalGuidance returns a pointer to RatingUnitedStatesTelevisionTypeVParentalGuidance
func RatingUnitedStatesTelevisionTypePParentalGuidance() *RatingUnitedStatesTelevisionType {
	v := RatingUnitedStatesTelevisionTypeVParentalGuidance
	return &v
}

// RatingUnitedStatesTelevisionTypePChildrenAbove14 returns a pointer to RatingUnitedStatesTelevisionTypeVChildrenAbove14
func RatingUnitedStatesTelevisionTypePChildrenAbove14() *RatingUnitedStatesTelevisionType {
	v := RatingUnitedStatesTelevisionTypeVChildrenAbove14
	return &v
}

// RatingUnitedStatesTelevisionTypePAdults returns a pointer to RatingUnitedStatesTelevisionTypeVAdults
func RatingUnitedStatesTelevisionTypePAdults() *RatingUnitedStatesTelevisionType {
	v := RatingUnitedStatesTelevisionTypeVAdults
	return &v
}
