// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RatingUnitedKingdomTelevisionType undocumented
type RatingUnitedKingdomTelevisionType string

const (
	// RatingUnitedKingdomTelevisionTypeVAllAllowed undocumented
	RatingUnitedKingdomTelevisionTypeVAllAllowed RatingUnitedKingdomTelevisionType = "AllAllowed"
	// RatingUnitedKingdomTelevisionTypeVAllBlocked undocumented
	RatingUnitedKingdomTelevisionTypeVAllBlocked RatingUnitedKingdomTelevisionType = "AllBlocked"
	// RatingUnitedKingdomTelevisionTypeVCaution undocumented
	RatingUnitedKingdomTelevisionTypeVCaution RatingUnitedKingdomTelevisionType = "Caution"
)

// RatingUnitedKingdomTelevisionTypePAllAllowed returns a pointer to RatingUnitedKingdomTelevisionTypeVAllAllowed
func RatingUnitedKingdomTelevisionTypePAllAllowed() *RatingUnitedKingdomTelevisionType {
	v := RatingUnitedKingdomTelevisionTypeVAllAllowed
	return &v
}

// RatingUnitedKingdomTelevisionTypePAllBlocked returns a pointer to RatingUnitedKingdomTelevisionTypeVAllBlocked
func RatingUnitedKingdomTelevisionTypePAllBlocked() *RatingUnitedKingdomTelevisionType {
	v := RatingUnitedKingdomTelevisionTypeVAllBlocked
	return &v
}

// RatingUnitedKingdomTelevisionTypePCaution returns a pointer to RatingUnitedKingdomTelevisionTypeVCaution
func RatingUnitedKingdomTelevisionTypePCaution() *RatingUnitedKingdomTelevisionType {
	v := RatingUnitedKingdomTelevisionTypeVCaution
	return &v
}
