// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RatingGermanyTelevisionType undocumented
type RatingGermanyTelevisionType string

const (
	// RatingGermanyTelevisionTypeVAllAllowed undocumented
	RatingGermanyTelevisionTypeVAllAllowed RatingGermanyTelevisionType = "AllAllowed"
	// RatingGermanyTelevisionTypeVAllBlocked undocumented
	RatingGermanyTelevisionTypeVAllBlocked RatingGermanyTelevisionType = "AllBlocked"
	// RatingGermanyTelevisionTypeVGeneral undocumented
	RatingGermanyTelevisionTypeVGeneral RatingGermanyTelevisionType = "General"
	// RatingGermanyTelevisionTypeVAgesAbove6 undocumented
	RatingGermanyTelevisionTypeVAgesAbove6 RatingGermanyTelevisionType = "AgesAbove6"
	// RatingGermanyTelevisionTypeVAgesAbove12 undocumented
	RatingGermanyTelevisionTypeVAgesAbove12 RatingGermanyTelevisionType = "AgesAbove12"
	// RatingGermanyTelevisionTypeVAgesAbove16 undocumented
	RatingGermanyTelevisionTypeVAgesAbove16 RatingGermanyTelevisionType = "AgesAbove16"
	// RatingGermanyTelevisionTypeVAdults undocumented
	RatingGermanyTelevisionTypeVAdults RatingGermanyTelevisionType = "Adults"
)

// RatingGermanyTelevisionTypePAllAllowed returns a pointer to RatingGermanyTelevisionTypeVAllAllowed
func RatingGermanyTelevisionTypePAllAllowed() *RatingGermanyTelevisionType {
	v := RatingGermanyTelevisionTypeVAllAllowed
	return &v
}

// RatingGermanyTelevisionTypePAllBlocked returns a pointer to RatingGermanyTelevisionTypeVAllBlocked
func RatingGermanyTelevisionTypePAllBlocked() *RatingGermanyTelevisionType {
	v := RatingGermanyTelevisionTypeVAllBlocked
	return &v
}

// RatingGermanyTelevisionTypePGeneral returns a pointer to RatingGermanyTelevisionTypeVGeneral
func RatingGermanyTelevisionTypePGeneral() *RatingGermanyTelevisionType {
	v := RatingGermanyTelevisionTypeVGeneral
	return &v
}

// RatingGermanyTelevisionTypePAgesAbove6 returns a pointer to RatingGermanyTelevisionTypeVAgesAbove6
func RatingGermanyTelevisionTypePAgesAbove6() *RatingGermanyTelevisionType {
	v := RatingGermanyTelevisionTypeVAgesAbove6
	return &v
}

// RatingGermanyTelevisionTypePAgesAbove12 returns a pointer to RatingGermanyTelevisionTypeVAgesAbove12
func RatingGermanyTelevisionTypePAgesAbove12() *RatingGermanyTelevisionType {
	v := RatingGermanyTelevisionTypeVAgesAbove12
	return &v
}

// RatingGermanyTelevisionTypePAgesAbove16 returns a pointer to RatingGermanyTelevisionTypeVAgesAbove16
func RatingGermanyTelevisionTypePAgesAbove16() *RatingGermanyTelevisionType {
	v := RatingGermanyTelevisionTypeVAgesAbove16
	return &v
}

// RatingGermanyTelevisionTypePAdults returns a pointer to RatingGermanyTelevisionTypeVAdults
func RatingGermanyTelevisionTypePAdults() *RatingGermanyTelevisionType {
	v := RatingGermanyTelevisionTypeVAdults
	return &v
}
