// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RecurrencePatternType undocumented
type RecurrencePatternType string

const (
	// RecurrencePatternTypeVDaily undocumented
	RecurrencePatternTypeVDaily RecurrencePatternType = "Daily"
	// RecurrencePatternTypeVWeekly undocumented
	RecurrencePatternTypeVWeekly RecurrencePatternType = "Weekly"
	// RecurrencePatternTypeVAbsoluteMonthly undocumented
	RecurrencePatternTypeVAbsoluteMonthly RecurrencePatternType = "AbsoluteMonthly"
	// RecurrencePatternTypeVRelativeMonthly undocumented
	RecurrencePatternTypeVRelativeMonthly RecurrencePatternType = "RelativeMonthly"
	// RecurrencePatternTypeVAbsoluteYearly undocumented
	RecurrencePatternTypeVAbsoluteYearly RecurrencePatternType = "AbsoluteYearly"
	// RecurrencePatternTypeVRelativeYearly undocumented
	RecurrencePatternTypeVRelativeYearly RecurrencePatternType = "RelativeYearly"
)

// RecurrencePatternTypePDaily returns a pointer to RecurrencePatternTypeVDaily
func RecurrencePatternTypePDaily() *RecurrencePatternType {
	v := RecurrencePatternTypeVDaily
	return &v
}

// RecurrencePatternTypePWeekly returns a pointer to RecurrencePatternTypeVWeekly
func RecurrencePatternTypePWeekly() *RecurrencePatternType {
	v := RecurrencePatternTypeVWeekly
	return &v
}

// RecurrencePatternTypePAbsoluteMonthly returns a pointer to RecurrencePatternTypeVAbsoluteMonthly
func RecurrencePatternTypePAbsoluteMonthly() *RecurrencePatternType {
	v := RecurrencePatternTypeVAbsoluteMonthly
	return &v
}

// RecurrencePatternTypePRelativeMonthly returns a pointer to RecurrencePatternTypeVRelativeMonthly
func RecurrencePatternTypePRelativeMonthly() *RecurrencePatternType {
	v := RecurrencePatternTypeVRelativeMonthly
	return &v
}

// RecurrencePatternTypePAbsoluteYearly returns a pointer to RecurrencePatternTypeVAbsoluteYearly
func RecurrencePatternTypePAbsoluteYearly() *RecurrencePatternType {
	v := RecurrencePatternTypeVAbsoluteYearly
	return &v
}

// RecurrencePatternTypePRelativeYearly returns a pointer to RecurrencePatternTypeVRelativeYearly
func RecurrencePatternTypePRelativeYearly() *RecurrencePatternType {
	v := RecurrencePatternTypeVRelativeYearly
	return &v
}
