// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// SafeSearchFilterType undocumented
type SafeSearchFilterType string

const (
	// SafeSearchFilterTypeVUserDefined undocumented
	SafeSearchFilterTypeVUserDefined SafeSearchFilterType = "UserDefined"
	// SafeSearchFilterTypeVStrict undocumented
	SafeSearchFilterTypeVStrict SafeSearchFilterType = "Strict"
	// SafeSearchFilterTypeVModerate undocumented
	SafeSearchFilterTypeVModerate SafeSearchFilterType = "Moderate"
)

// SafeSearchFilterTypePUserDefined returns a pointer to SafeSearchFilterTypeVUserDefined
func SafeSearchFilterTypePUserDefined() *SafeSearchFilterType {
	v := SafeSearchFilterTypeVUserDefined
	return &v
}

// SafeSearchFilterTypePStrict returns a pointer to SafeSearchFilterTypeVStrict
func SafeSearchFilterTypePStrict() *SafeSearchFilterType {
	v := SafeSearchFilterTypeVStrict
	return &v
}

// SafeSearchFilterTypePModerate returns a pointer to SafeSearchFilterTypeVModerate
func SafeSearchFilterTypePModerate() *SafeSearchFilterType {
	v := SafeSearchFilterTypeVModerate
	return &v
}
