// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ScreenSharingRole undocumented
type ScreenSharingRole string

const (
	// ScreenSharingRoleVViewer undocumented
	ScreenSharingRoleVViewer ScreenSharingRole = "Viewer"
	// ScreenSharingRoleVSharer undocumented
	ScreenSharingRoleVSharer ScreenSharingRole = "Sharer"
)

// ScreenSharingRolePViewer returns a pointer to ScreenSharingRoleVViewer
func ScreenSharingRolePViewer() *ScreenSharingRole {
	v := ScreenSharingRoleVViewer
	return &v
}

// ScreenSharingRolePSharer returns a pointer to ScreenSharingRoleVSharer
func ScreenSharingRolePSharer() *ScreenSharingRole {
	v := ScreenSharingRoleVSharer
	return &v
}
