// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// SharedPCAllowedAccountType undocumented
type SharedPCAllowedAccountType string

const (
	// SharedPCAllowedAccountTypeVGuest undocumented
	SharedPCAllowedAccountTypeVGuest SharedPCAllowedAccountType = "Guest"
	// SharedPCAllowedAccountTypeVDomain undocumented
	SharedPCAllowedAccountTypeVDomain SharedPCAllowedAccountType = "Domain"
)

// SharedPCAllowedAccountTypePGuest returns a pointer to SharedPCAllowedAccountTypeVGuest
func SharedPCAllowedAccountTypePGuest() *SharedPCAllowedAccountType {
	v := SharedPCAllowedAccountTypeVGuest
	return &v
}

// SharedPCAllowedAccountTypePDomain returns a pointer to SharedPCAllowedAccountTypeVDomain
func SharedPCAllowedAccountTypePDomain() *SharedPCAllowedAccountType {
	v := SharedPCAllowedAccountTypeVDomain
	return &v
}
