// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// UserAccountSecurityType undocumented
type UserAccountSecurityType string

const (
	// UserAccountSecurityTypeVUnknown undocumented
	UserAccountSecurityTypeVUnknown UserAccountSecurityType = "Unknown"
	// UserAccountSecurityTypeVStandard undocumented
	UserAccountSecurityTypeVStandard UserAccountSecurityType = "Standard"
	// UserAccountSecurityTypeVPower undocumented
	UserAccountSecurityTypeVPower UserAccountSecurityType = "Power"
	// UserAccountSecurityTypeVAdministrator undocumented
	UserAccountSecurityTypeVAdministrator UserAccountSecurityType = "Administrator"
	// UserAccountSecurityTypeVUnknownFutureValue undocumented
	UserAccountSecurityTypeVUnknownFutureValue UserAccountSecurityType = "UnknownFutureValue"
)

// UserAccountSecurityTypePUnknown returns a pointer to UserAccountSecurityTypeVUnknown
func UserAccountSecurityTypePUnknown() *UserAccountSecurityType {
	v := UserAccountSecurityTypeVUnknown
	return &v
}

// UserAccountSecurityTypePStandard returns a pointer to UserAccountSecurityTypeVStandard
func UserAccountSecurityTypePStandard() *UserAccountSecurityType {
	v := UserAccountSecurityTypeVStandard
	return &v
}

// UserAccountSecurityTypePPower returns a pointer to UserAccountSecurityTypeVPower
func UserAccountSecurityTypePPower() *UserAccountSecurityType {
	v := UserAccountSecurityTypeVPower
	return &v
}

// UserAccountSecurityTypePAdministrator returns a pointer to UserAccountSecurityTypeVAdministrator
func UserAccountSecurityTypePAdministrator() *UserAccountSecurityType {
	v := UserAccountSecurityTypeVAdministrator
	return &v
}

// UserAccountSecurityTypePUnknownFutureValue returns a pointer to UserAccountSecurityTypeVUnknownFutureValue
func UserAccountSecurityTypePUnknownFutureValue() *UserAccountSecurityType {
	v := UserAccountSecurityTypeVUnknownFutureValue
	return &v
}
