// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// VppTokenAccountType undocumented
type VppTokenAccountType string

const (
	// VppTokenAccountTypeVBusiness undocumented
	VppTokenAccountTypeVBusiness VppTokenAccountType = "Business"
	// VppTokenAccountTypeVEducation undocumented
	VppTokenAccountTypeVEducation VppTokenAccountType = "Education"
)

// VppTokenAccountTypePBusiness returns a pointer to VppTokenAccountTypeVBusiness
func VppTokenAccountTypePBusiness() *VppTokenAccountType {
	v := VppTokenAccountTypeVBusiness
	return &v
}

// VppTokenAccountTypePEducation returns a pointer to VppTokenAccountTypeVEducation
func VppTokenAccountTypePEducation() *VppTokenAccountType {
	v := VppTokenAccountTypeVEducation
	return &v
}
