// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WebBrowserCookieSettings undocumented
type WebBrowserCookieSettings string

const (
	// WebBrowserCookieSettingsVBrowserDefault undocumented
	WebBrowserCookieSettingsVBrowserDefault WebBrowserCookieSettings = "BrowserDefault"
	// WebBrowserCookieSettingsVBlockAlways undocumented
	WebBrowserCookieSettingsVBlockAlways WebBrowserCookieSettings = "BlockAlways"
	// WebBrowserCookieSettingsVAllowCurrentWebSite undocumented
	WebBrowserCookieSettingsVAllowCurrentWebSite WebBrowserCookieSettings = "AllowCurrentWebSite"
	// WebBrowserCookieSettingsVAllowFromWebsitesVisited undocumented
	WebBrowserCookieSettingsVAllowFromWebsitesVisited WebBrowserCookieSettings = "AllowFromWebsitesVisited"
	// WebBrowserCookieSettingsVAllowAlways undocumented
	WebBrowserCookieSettingsVAllowAlways WebBrowserCookieSettings = "AllowAlways"
)

// WebBrowserCookieSettingsPBrowserDefault returns a pointer to WebBrowserCookieSettingsVBrowserDefault
func WebBrowserCookieSettingsPBrowserDefault() *WebBrowserCookieSettings {
	v := WebBrowserCookieSettingsVBrowserDefault
	return &v
}

// WebBrowserCookieSettingsPBlockAlways returns a pointer to WebBrowserCookieSettingsVBlockAlways
func WebBrowserCookieSettingsPBlockAlways() *WebBrowserCookieSettings {
	v := WebBrowserCookieSettingsVBlockAlways
	return &v
}

// WebBrowserCookieSettingsPAllowCurrentWebSite returns a pointer to WebBrowserCookieSettingsVAllowCurrentWebSite
func WebBrowserCookieSettingsPAllowCurrentWebSite() *WebBrowserCookieSettings {
	v := WebBrowserCookieSettingsVAllowCurrentWebSite
	return &v
}

// WebBrowserCookieSettingsPAllowFromWebsitesVisited returns a pointer to WebBrowserCookieSettingsVAllowFromWebsitesVisited
func WebBrowserCookieSettingsPAllowFromWebsitesVisited() *WebBrowserCookieSettings {
	v := WebBrowserCookieSettingsVAllowFromWebsitesVisited
	return &v
}

// WebBrowserCookieSettingsPAllowAlways returns a pointer to WebBrowserCookieSettingsVAllowAlways
func WebBrowserCookieSettingsPAllowAlways() *WebBrowserCookieSettings {
	v := WebBrowserCookieSettingsVAllowAlways
	return &v
}
