// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WindowsStartMenuModeType undocumented
type WindowsStartMenuModeType string

const (
	// WindowsStartMenuModeTypeVUserDefined undocumented
	WindowsStartMenuModeTypeVUserDefined WindowsStartMenuModeType = "UserDefined"
	// WindowsStartMenuModeTypeVFullScreen undocumented
	WindowsStartMenuModeTypeVFullScreen WindowsStartMenuModeType = "FullScreen"
	// WindowsStartMenuModeTypeVNonFullScreen undocumented
	WindowsStartMenuModeTypeVNonFullScreen WindowsStartMenuModeType = "NonFullScreen"
)

// WindowsStartMenuModeTypePUserDefined returns a pointer to WindowsStartMenuModeTypeVUserDefined
func WindowsStartMenuModeTypePUserDefined() *WindowsStartMenuModeType {
	v := WindowsStartMenuModeTypeVUserDefined
	return &v
}

// WindowsStartMenuModeTypePFullScreen returns a pointer to WindowsStartMenuModeTypeVFullScreen
func WindowsStartMenuModeTypePFullScreen() *WindowsStartMenuModeType {
	v := WindowsStartMenuModeTypeVFullScreen
	return &v
}

// WindowsStartMenuModeTypePNonFullScreen returns a pointer to WindowsStartMenuModeTypeVNonFullScreen
func WindowsStartMenuModeTypePNonFullScreen() *WindowsStartMenuModeType {
	v := WindowsStartMenuModeTypeVNonFullScreen
	return &v
}
