// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WindowsDeviceType undocumented
type WindowsDeviceType string

const (
	// WindowsDeviceTypeVNone undocumented
	WindowsDeviceTypeVNone WindowsDeviceType = "None"
	// WindowsDeviceTypeVDesktop undocumented
	WindowsDeviceTypeVDesktop WindowsDeviceType = "Desktop"
	// WindowsDeviceTypeVMobile undocumented
	WindowsDeviceTypeVMobile WindowsDeviceType = "Mobile"
	// WindowsDeviceTypeVHolographic undocumented
	WindowsDeviceTypeVHolographic WindowsDeviceType = "Holographic"
	// WindowsDeviceTypeVTeam undocumented
	WindowsDeviceTypeVTeam WindowsDeviceType = "Team"
)

// WindowsDeviceTypePNone returns a pointer to WindowsDeviceTypeVNone
func WindowsDeviceTypePNone() *WindowsDeviceType {
	v := WindowsDeviceTypeVNone
	return &v
}

// WindowsDeviceTypePDesktop returns a pointer to WindowsDeviceTypeVDesktop
func WindowsDeviceTypePDesktop() *WindowsDeviceType {
	v := WindowsDeviceTypeVDesktop
	return &v
}

// WindowsDeviceTypePMobile returns a pointer to WindowsDeviceTypeVMobile
func WindowsDeviceTypePMobile() *WindowsDeviceType {
	v := WindowsDeviceTypeVMobile
	return &v
}

// WindowsDeviceTypePHolographic returns a pointer to WindowsDeviceTypeVHolographic
func WindowsDeviceTypePHolographic() *WindowsDeviceType {
	v := WindowsDeviceTypeVHolographic
	return &v
}

// WindowsDeviceTypePTeam returns a pointer to WindowsDeviceTypeVTeam
func WindowsDeviceTypePTeam() *WindowsDeviceType {
	v := WindowsDeviceTypeVTeam
	return &v
}
