// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WindowsSpotlightEnablementSettings undocumented
type WindowsSpotlightEnablementSettings string

const (
	// WindowsSpotlightEnablementSettingsVNotConfigured undocumented
	WindowsSpotlightEnablementSettingsVNotConfigured WindowsSpotlightEnablementSettings = "NotConfigured"
	// WindowsSpotlightEnablementSettingsVDisabled undocumented
	WindowsSpotlightEnablementSettingsVDisabled WindowsSpotlightEnablementSettings = "Disabled"
	// WindowsSpotlightEnablementSettingsVEnabled undocumented
	WindowsSpotlightEnablementSettingsVEnabled WindowsSpotlightEnablementSettings = "Enabled"
)

// WindowsSpotlightEnablementSettingsPNotConfigured returns a pointer to WindowsSpotlightEnablementSettingsVNotConfigured
func WindowsSpotlightEnablementSettingsPNotConfigured() *WindowsSpotlightEnablementSettings {
	v := WindowsSpotlightEnablementSettingsVNotConfigured
	return &v
}

// WindowsSpotlightEnablementSettingsPDisabled returns a pointer to WindowsSpotlightEnablementSettingsVDisabled
func WindowsSpotlightEnablementSettingsPDisabled() *WindowsSpotlightEnablementSettings {
	v := WindowsSpotlightEnablementSettingsVDisabled
	return &v
}

// WindowsSpotlightEnablementSettingsPEnabled returns a pointer to WindowsSpotlightEnablementSettingsVEnabled
func WindowsSpotlightEnablementSettingsPEnabled() *WindowsSpotlightEnablementSettings {
	v := WindowsSpotlightEnablementSettingsVEnabled
	return &v
}
