// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WindowsStartMenuAppListVisibilityType undocumented
type WindowsStartMenuAppListVisibilityType string

const (
	// WindowsStartMenuAppListVisibilityTypeVUserDefined undocumented
	WindowsStartMenuAppListVisibilityTypeVUserDefined WindowsStartMenuAppListVisibilityType = "UserDefined"
	// WindowsStartMenuAppListVisibilityTypeVCollapse undocumented
	WindowsStartMenuAppListVisibilityTypeVCollapse WindowsStartMenuAppListVisibilityType = "Collapse"
	// WindowsStartMenuAppListVisibilityTypeVRemove undocumented
	WindowsStartMenuAppListVisibilityTypeVRemove WindowsStartMenuAppListVisibilityType = "Remove"
	// WindowsStartMenuAppListVisibilityTypeVDisableSettingsApp undocumented
	WindowsStartMenuAppListVisibilityTypeVDisableSettingsApp WindowsStartMenuAppListVisibilityType = "DisableSettingsApp"
)

// WindowsStartMenuAppListVisibilityTypePUserDefined returns a pointer to WindowsStartMenuAppListVisibilityTypeVUserDefined
func WindowsStartMenuAppListVisibilityTypePUserDefined() *WindowsStartMenuAppListVisibilityType {
	v := WindowsStartMenuAppListVisibilityTypeVUserDefined
	return &v
}

// WindowsStartMenuAppListVisibilityTypePCollapse returns a pointer to WindowsStartMenuAppListVisibilityTypeVCollapse
func WindowsStartMenuAppListVisibilityTypePCollapse() *WindowsStartMenuAppListVisibilityType {
	v := WindowsStartMenuAppListVisibilityTypeVCollapse
	return &v
}

// WindowsStartMenuAppListVisibilityTypePRemove returns a pointer to WindowsStartMenuAppListVisibilityTypeVRemove
func WindowsStartMenuAppListVisibilityTypePRemove() *WindowsStartMenuAppListVisibilityType {
	v := WindowsStartMenuAppListVisibilityTypeVRemove
	return &v
}

// WindowsStartMenuAppListVisibilityTypePDisableSettingsApp returns a pointer to WindowsStartMenuAppListVisibilityTypeVDisableSettingsApp
func WindowsStartMenuAppListVisibilityTypePDisableSettingsApp() *WindowsStartMenuAppListVisibilityType {
	v := WindowsStartMenuAppListVisibilityTypeVDisableSettingsApp
	return &v
}
