// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AccessType undocumented
type AccessType string

const (
	// AccessTypeVGrant undocumented
	AccessTypeVGrant AccessType = "Grant"
	// AccessTypeVDeny undocumented
	AccessTypeVDeny AccessType = "Deny"
)

// AccessTypePGrant returns a pointer to AccessTypeVGrant
func AccessTypePGrant() *AccessType {
	v := AccessTypeVGrant
	return &v
}

// AccessTypePDeny returns a pointer to AccessTypeVDeny
func AccessTypePDeny() *AccessType {
	v := AccessTypeVDeny
	return &v
}
