// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ActivityType undocumented
type ActivityType string

const (
	// ActivityTypeVSignin undocumented
	ActivityTypeVSignin ActivityType = "Signin"
	// ActivityTypeVUser undocumented
	ActivityTypeVUser ActivityType = "User"
	// ActivityTypeVUnknownFutureValue undocumented
	ActivityTypeVUnknownFutureValue ActivityType = "UnknownFutureValue"
)

// ActivityTypePSignin returns a pointer to ActivityTypeVSignin
func ActivityTypePSignin() *ActivityType {
	v := ActivityTypeVSignin
	return &v
}

// ActivityTypePUser returns a pointer to ActivityTypeVUser
func ActivityTypePUser() *ActivityType {
	v := ActivityTypeVUser
	return &v
}

// ActivityTypePUnknownFutureValue returns a pointer to ActivityTypeVUnknownFutureValue
func ActivityTypePUnknownFutureValue() *ActivityType {
	v := ActivityTypeVUnknownFutureValue
	return &v
}
