// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ActionState undocumented
type ActionState string

const (
	// ActionStateVNone undocumented
	ActionStateVNone ActionState = "None"
	// ActionStateVPending undocumented
	ActionStateVPending ActionState = "Pending"
	// ActionStateVCanceled undocumented
	ActionStateVCanceled ActionState = "Canceled"
	// ActionStateVActive undocumented
	ActionStateVActive ActionState = "Active"
	// ActionStateVDone undocumented
	ActionStateVDone ActionState = "Done"
	// ActionStateVFailed undocumented
	ActionStateVFailed ActionState = "Failed"
	// ActionStateVNotSupported undocumented
	ActionStateVNotSupported ActionState = "NotSupported"
)

// ActionStatePNone returns a pointer to ActionStateVNone
func ActionStatePNone() *ActionState {
	v := ActionStateVNone
	return &v
}

// ActionStatePPending returns a pointer to ActionStateVPending
func ActionStatePPending() *ActionState {
	v := ActionStateVPending
	return &v
}

// ActionStatePCanceled returns a pointer to ActionStateVCanceled
func ActionStatePCanceled() *ActionState {
	v := ActionStateVCanceled
	return &v
}

// ActionStatePActive returns a pointer to ActionStateVActive
func ActionStatePActive() *ActionState {
	v := ActionStateVActive
	return &v
}

// ActionStatePDone returns a pointer to ActionStateVDone
func ActionStatePDone() *ActionState {
	v := ActionStateVDone
	return &v
}

// ActionStatePFailed returns a pointer to ActionStateVFailed
func ActionStatePFailed() *ActionState {
	v := ActionStateVFailed
	return &v
}

// ActionStatePNotSupported returns a pointer to ActionStateVNotSupported
func ActionStatePNotSupported() *ActionState {
	v := ActionStateVNotSupported
	return &v
}
