// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ActionSource undocumented
type ActionSource string

const (
	// ActionSourceVManual undocumented
	ActionSourceVManual ActionSource = "Manual"
	// ActionSourceVAutomatic undocumented
	ActionSourceVAutomatic ActionSource = "Automatic"
	// ActionSourceVRecommended undocumented
	ActionSourceVRecommended ActionSource = "Recommended"
	// ActionSourceVDefault undocumented
	ActionSourceVDefault ActionSource = "Default"
)

// ActionSourcePManual returns a pointer to ActionSourceVManual
func ActionSourcePManual() *ActionSource {
	v := ActionSourceVManual
	return &v
}

// ActionSourcePAutomatic returns a pointer to ActionSourceVAutomatic
func ActionSourcePAutomatic() *ActionSource {
	v := ActionSourceVAutomatic
	return &v
}

// ActionSourcePRecommended returns a pointer to ActionSourceVRecommended
func ActionSourcePRecommended() *ActionSource {
	v := ActionSourceVRecommended
	return &v
}

// ActionSourcePDefault returns a pointer to ActionSourceVDefault
func ActionSourcePDefault() *ActionSource {
	v := ActionSourceVDefault
	return &v
}
