// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AdvancedBitLockerState undocumented
type AdvancedBitLockerState string

const (
	// AdvancedBitLockerStateVSuccess undocumented
	AdvancedBitLockerStateVSuccess AdvancedBitLockerState = "Success"
	// AdvancedBitLockerStateVNoUserConsent undocumented
	AdvancedBitLockerStateVNoUserConsent AdvancedBitLockerState = "NoUserConsent"
	// AdvancedBitLockerStateVOsVolumeEncryptionMethodMismatch undocumented
	AdvancedBitLockerStateVOsVolumeEncryptionMethodMismatch AdvancedBitLockerState = "OsVolumeEncryptionMethodMismatch"
	// AdvancedBitLockerStateVOsVolumeTpmRequired undocumented
	AdvancedBitLockerStateVOsVolumeTpmRequired AdvancedBitLockerState = "OsVolumeTpmRequired"
	// AdvancedBitLockerStateVOsVolumeTpmOnlyRequired undocumented
	AdvancedBitLockerStateVOsVolumeTpmOnlyRequired AdvancedBitLockerState = "OsVolumeTpmOnlyRequired"
	// AdvancedBitLockerStateVOsVolumeTpmPinRequired undocumented
	AdvancedBitLockerStateVOsVolumeTpmPinRequired AdvancedBitLockerState = "OsVolumeTpmPinRequired"
	// AdvancedBitLockerStateVOsVolumeTpmStartupKeyRequired undocumented
	AdvancedBitLockerStateVOsVolumeTpmStartupKeyRequired AdvancedBitLockerState = "OsVolumeTpmStartupKeyRequired"
	// AdvancedBitLockerStateVOsVolumeTpmPinStartupKeyRequired undocumented
	AdvancedBitLockerStateVOsVolumeTpmPinStartupKeyRequired AdvancedBitLockerState = "OsVolumeTpmPinStartupKeyRequired"
	// AdvancedBitLockerStateVOsVolumeUnprotected undocumented
	AdvancedBitLockerStateVOsVolumeUnprotected AdvancedBitLockerState = "OsVolumeUnprotected"
	// AdvancedBitLockerStateVRecoveryKeyBackupFailed undocumented
	AdvancedBitLockerStateVRecoveryKeyBackupFailed AdvancedBitLockerState = "RecoveryKeyBackupFailed"
	// AdvancedBitLockerStateVFixedDriveNotEncrypted undocumented
	AdvancedBitLockerStateVFixedDriveNotEncrypted AdvancedBitLockerState = "FixedDriveNotEncrypted"
	// AdvancedBitLockerStateVFixedDriveEncryptionMethodMismatch undocumented
	AdvancedBitLockerStateVFixedDriveEncryptionMethodMismatch AdvancedBitLockerState = "FixedDriveEncryptionMethodMismatch"
	// AdvancedBitLockerStateVLoggedOnUserNonAdmin undocumented
	AdvancedBitLockerStateVLoggedOnUserNonAdmin AdvancedBitLockerState = "LoggedOnUserNonAdmin"
	// AdvancedBitLockerStateVWindowsRecoveryEnvironmentNotConfigured undocumented
	AdvancedBitLockerStateVWindowsRecoveryEnvironmentNotConfigured AdvancedBitLockerState = "WindowsRecoveryEnvironmentNotConfigured"
	// AdvancedBitLockerStateVTpmNotAvailable undocumented
	AdvancedBitLockerStateVTpmNotAvailable AdvancedBitLockerState = "TpmNotAvailable"
	// AdvancedBitLockerStateVTpmNotReady undocumented
	AdvancedBitLockerStateVTpmNotReady AdvancedBitLockerState = "TpmNotReady"
	// AdvancedBitLockerStateVNetworkError undocumented
	AdvancedBitLockerStateVNetworkError AdvancedBitLockerState = "NetworkError"
)

// AdvancedBitLockerStatePSuccess returns a pointer to AdvancedBitLockerStateVSuccess
func AdvancedBitLockerStatePSuccess() *AdvancedBitLockerState {
	v := AdvancedBitLockerStateVSuccess
	return &v
}

// AdvancedBitLockerStatePNoUserConsent returns a pointer to AdvancedBitLockerStateVNoUserConsent
func AdvancedBitLockerStatePNoUserConsent() *AdvancedBitLockerState {
	v := AdvancedBitLockerStateVNoUserConsent
	return &v
}

// AdvancedBitLockerStatePOsVolumeEncryptionMethodMismatch returns a pointer to AdvancedBitLockerStateVOsVolumeEncryptionMethodMismatch
func AdvancedBitLockerStatePOsVolumeEncryptionMethodMismatch() *AdvancedBitLockerState {
	v := AdvancedBitLockerStateVOsVolumeEncryptionMethodMismatch
	return &v
}

// AdvancedBitLockerStatePOsVolumeTpmRequired returns a pointer to AdvancedBitLockerStateVOsVolumeTpmRequired
func AdvancedBitLockerStatePOsVolumeTpmRequired() *AdvancedBitLockerState {
	v := AdvancedBitLockerStateVOsVolumeTpmRequired
	return &v
}

// AdvancedBitLockerStatePOsVolumeTpmOnlyRequired returns a pointer to AdvancedBitLockerStateVOsVolumeTpmOnlyRequired
func AdvancedBitLockerStatePOsVolumeTpmOnlyRequired() *AdvancedBitLockerState {
	v := AdvancedBitLockerStateVOsVolumeTpmOnlyRequired
	return &v
}

// AdvancedBitLockerStatePOsVolumeTpmPinRequired returns a pointer to AdvancedBitLockerStateVOsVolumeTpmPinRequired
func AdvancedBitLockerStatePOsVolumeTpmPinRequired() *AdvancedBitLockerState {
	v := AdvancedBitLockerStateVOsVolumeTpmPinRequired
	return &v
}

// AdvancedBitLockerStatePOsVolumeTpmStartupKeyRequired returns a pointer to AdvancedBitLockerStateVOsVolumeTpmStartupKeyRequired
func AdvancedBitLockerStatePOsVolumeTpmStartupKeyRequired() *AdvancedBitLockerState {
	v := AdvancedBitLockerStateVOsVolumeTpmStartupKeyRequired
	return &v
}

// AdvancedBitLockerStatePOsVolumeTpmPinStartupKeyRequired returns a pointer to AdvancedBitLockerStateVOsVolumeTpmPinStartupKeyRequired
func AdvancedBitLockerStatePOsVolumeTpmPinStartupKeyRequired() *AdvancedBitLockerState {
	v := AdvancedBitLockerStateVOsVolumeTpmPinStartupKeyRequired
	return &v
}

// AdvancedBitLockerStatePOsVolumeUnprotected returns a pointer to AdvancedBitLockerStateVOsVolumeUnprotected
func AdvancedBitLockerStatePOsVolumeUnprotected() *AdvancedBitLockerState {
	v := AdvancedBitLockerStateVOsVolumeUnprotected
	return &v
}

// AdvancedBitLockerStatePRecoveryKeyBackupFailed returns a pointer to AdvancedBitLockerStateVRecoveryKeyBackupFailed
func AdvancedBitLockerStatePRecoveryKeyBackupFailed() *AdvancedBitLockerState {
	v := AdvancedBitLockerStateVRecoveryKeyBackupFailed
	return &v
}

// AdvancedBitLockerStatePFixedDriveNotEncrypted returns a pointer to AdvancedBitLockerStateVFixedDriveNotEncrypted
func AdvancedBitLockerStatePFixedDriveNotEncrypted() *AdvancedBitLockerState {
	v := AdvancedBitLockerStateVFixedDriveNotEncrypted
	return &v
}

// AdvancedBitLockerStatePFixedDriveEncryptionMethodMismatch returns a pointer to AdvancedBitLockerStateVFixedDriveEncryptionMethodMismatch
func AdvancedBitLockerStatePFixedDriveEncryptionMethodMismatch() *AdvancedBitLockerState {
	v := AdvancedBitLockerStateVFixedDriveEncryptionMethodMismatch
	return &v
}

// AdvancedBitLockerStatePLoggedOnUserNonAdmin returns a pointer to AdvancedBitLockerStateVLoggedOnUserNonAdmin
func AdvancedBitLockerStatePLoggedOnUserNonAdmin() *AdvancedBitLockerState {
	v := AdvancedBitLockerStateVLoggedOnUserNonAdmin
	return &v
}

// AdvancedBitLockerStatePWindowsRecoveryEnvironmentNotConfigured returns a pointer to AdvancedBitLockerStateVWindowsRecoveryEnvironmentNotConfigured
func AdvancedBitLockerStatePWindowsRecoveryEnvironmentNotConfigured() *AdvancedBitLockerState {
	v := AdvancedBitLockerStateVWindowsRecoveryEnvironmentNotConfigured
	return &v
}

// AdvancedBitLockerStatePTpmNotAvailable returns a pointer to AdvancedBitLockerStateVTpmNotAvailable
func AdvancedBitLockerStatePTpmNotAvailable() *AdvancedBitLockerState {
	v := AdvancedBitLockerStateVTpmNotAvailable
	return &v
}

// AdvancedBitLockerStatePTpmNotReady returns a pointer to AdvancedBitLockerStateVTpmNotReady
func AdvancedBitLockerStatePTpmNotReady() *AdvancedBitLockerState {
	v := AdvancedBitLockerStateVTpmNotReady
	return &v
}

// AdvancedBitLockerStatePNetworkError returns a pointer to AdvancedBitLockerStateVNetworkError
func AdvancedBitLockerStatePNetworkError() *AdvancedBitLockerState {
	v := AdvancedBitLockerStateVNetworkError
	return &v
}
