// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AgreementAcceptanceState undocumented
type AgreementAcceptanceState string

const (
	// AgreementAcceptanceStateVAccepted undocumented
	AgreementAcceptanceStateVAccepted AgreementAcceptanceState = "Accepted"
	// AgreementAcceptanceStateVDeclined undocumented
	AgreementAcceptanceStateVDeclined AgreementAcceptanceState = "Declined"
)

// AgreementAcceptanceStatePAccepted returns a pointer to AgreementAcceptanceStateVAccepted
func AgreementAcceptanceStatePAccepted() *AgreementAcceptanceState {
	v := AgreementAcceptanceStateVAccepted
	return &v
}

// AgreementAcceptanceStatePDeclined returns a pointer to AgreementAcceptanceStateVDeclined
func AgreementAcceptanceStatePDeclined() *AgreementAcceptanceState {
	v := AgreementAcceptanceStateVDeclined
	return &v
}
