// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AlertFeedback undocumented
type AlertFeedback string

const (
	// AlertFeedbackVUnknown undocumented
	AlertFeedbackVUnknown AlertFeedback = "Unknown"
	// AlertFeedbackVTruePositive undocumented
	AlertFeedbackVTruePositive AlertFeedback = "TruePositive"
	// AlertFeedbackVFalsePositive undocumented
	AlertFeedbackVFalsePositive AlertFeedback = "FalsePositive"
	// AlertFeedbackVBenignPositive undocumented
	AlertFeedbackVBenignPositive AlertFeedback = "BenignPositive"
	// AlertFeedbackVUnknownFutureValue undocumented
	AlertFeedbackVUnknownFutureValue AlertFeedback = "UnknownFutureValue"
)

// AlertFeedbackPUnknown returns a pointer to AlertFeedbackVUnknown
func AlertFeedbackPUnknown() *AlertFeedback {
	v := AlertFeedbackVUnknown
	return &v
}

// AlertFeedbackPTruePositive returns a pointer to AlertFeedbackVTruePositive
func AlertFeedbackPTruePositive() *AlertFeedback {
	v := AlertFeedbackVTruePositive
	return &v
}

// AlertFeedbackPFalsePositive returns a pointer to AlertFeedbackVFalsePositive
func AlertFeedbackPFalsePositive() *AlertFeedback {
	v := AlertFeedbackVFalsePositive
	return &v
}

// AlertFeedbackPBenignPositive returns a pointer to AlertFeedbackVBenignPositive
func AlertFeedbackPBenignPositive() *AlertFeedback {
	v := AlertFeedbackVBenignPositive
	return &v
}

// AlertFeedbackPUnknownFutureValue returns a pointer to AlertFeedbackVUnknownFutureValue
func AlertFeedbackPUnknownFutureValue() *AlertFeedback {
	v := AlertFeedbackVUnknownFutureValue
	return &v
}
