// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// Alignment undocumented
type Alignment string

const (
	// AlignmentVLeft undocumented
	AlignmentVLeft Alignment = "Left"
	// AlignmentVRight undocumented
	AlignmentVRight Alignment = "Right"
	// AlignmentVCenter undocumented
	AlignmentVCenter Alignment = "Center"
)

// AlignmentPLeft returns a pointer to AlignmentVLeft
func AlignmentPLeft() *Alignment {
	v := AlignmentVLeft
	return &v
}

// AlignmentPRight returns a pointer to AlignmentVRight
func AlignmentPRight() *Alignment {
	v := AlignmentVRight
	return &v
}

// AlignmentPCenter returns a pointer to AlignmentVCenter
func AlignmentPCenter() *Alignment {
	v := AlignmentVCenter
	return &v
}
