// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AndroidForWorkSyncStatus undocumented
type AndroidForWorkSyncStatus string

const (
	// AndroidForWorkSyncStatusVSuccess undocumented
	AndroidForWorkSyncStatusVSuccess AndroidForWorkSyncStatus = "Success"
	// AndroidForWorkSyncStatusVCredentialsNotValid undocumented
	AndroidForWorkSyncStatusVCredentialsNotValid AndroidForWorkSyncStatus = "CredentialsNotValid"
	// AndroidForWorkSyncStatusVAndroidForWorkAPIError undocumented
	AndroidForWorkSyncStatusVAndroidForWorkAPIError AndroidForWorkSyncStatus = "AndroidForWorkAPIError"
	// AndroidForWorkSyncStatusVManagementServiceError undocumented
	AndroidForWorkSyncStatusVManagementServiceError AndroidForWorkSyncStatus = "ManagementServiceError"
	// AndroidForWorkSyncStatusVUnknownError undocumented
	AndroidForWorkSyncStatusVUnknownError AndroidForWorkSyncStatus = "UnknownError"
	// AndroidForWorkSyncStatusVNone undocumented
	AndroidForWorkSyncStatusVNone AndroidForWorkSyncStatus = "None"
)

// AndroidForWorkSyncStatusPSuccess returns a pointer to AndroidForWorkSyncStatusVSuccess
func AndroidForWorkSyncStatusPSuccess() *AndroidForWorkSyncStatus {
	v := AndroidForWorkSyncStatusVSuccess
	return &v
}

// AndroidForWorkSyncStatusPCredentialsNotValid returns a pointer to AndroidForWorkSyncStatusVCredentialsNotValid
func AndroidForWorkSyncStatusPCredentialsNotValid() *AndroidForWorkSyncStatus {
	v := AndroidForWorkSyncStatusVCredentialsNotValid
	return &v
}

// AndroidForWorkSyncStatusPAndroidForWorkAPIError returns a pointer to AndroidForWorkSyncStatusVAndroidForWorkAPIError
func AndroidForWorkSyncStatusPAndroidForWorkAPIError() *AndroidForWorkSyncStatus {
	v := AndroidForWorkSyncStatusVAndroidForWorkAPIError
	return &v
}

// AndroidForWorkSyncStatusPManagementServiceError returns a pointer to AndroidForWorkSyncStatusVManagementServiceError
func AndroidForWorkSyncStatusPManagementServiceError() *AndroidForWorkSyncStatus {
	v := AndroidForWorkSyncStatusVManagementServiceError
	return &v
}

// AndroidForWorkSyncStatusPUnknownError returns a pointer to AndroidForWorkSyncStatusVUnknownError
func AndroidForWorkSyncStatusPUnknownError() *AndroidForWorkSyncStatus {
	v := AndroidForWorkSyncStatusVUnknownError
	return &v
}

// AndroidForWorkSyncStatusPNone returns a pointer to AndroidForWorkSyncStatusVNone
func AndroidForWorkSyncStatusPNone() *AndroidForWorkSyncStatus {
	v := AndroidForWorkSyncStatusVNone
	return &v
}
