// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AndroidForWorkEnrollmentTarget undocumented
type AndroidForWorkEnrollmentTarget string

const (
	// AndroidForWorkEnrollmentTargetVNone undocumented
	AndroidForWorkEnrollmentTargetVNone AndroidForWorkEnrollmentTarget = "None"
	// AndroidForWorkEnrollmentTargetVAll undocumented
	AndroidForWorkEnrollmentTargetVAll AndroidForWorkEnrollmentTarget = "All"
	// AndroidForWorkEnrollmentTargetVTargeted undocumented
	AndroidForWorkEnrollmentTargetVTargeted AndroidForWorkEnrollmentTarget = "Targeted"
	// AndroidForWorkEnrollmentTargetVTargetedAsEnrollmentRestrictions undocumented
	AndroidForWorkEnrollmentTargetVTargetedAsEnrollmentRestrictions AndroidForWorkEnrollmentTarget = "TargetedAsEnrollmentRestrictions"
)

// AndroidForWorkEnrollmentTargetPNone returns a pointer to AndroidForWorkEnrollmentTargetVNone
func AndroidForWorkEnrollmentTargetPNone() *AndroidForWorkEnrollmentTarget {
	v := AndroidForWorkEnrollmentTargetVNone
	return &v
}

// AndroidForWorkEnrollmentTargetPAll returns a pointer to AndroidForWorkEnrollmentTargetVAll
func AndroidForWorkEnrollmentTargetPAll() *AndroidForWorkEnrollmentTarget {
	v := AndroidForWorkEnrollmentTargetVAll
	return &v
}

// AndroidForWorkEnrollmentTargetPTargeted returns a pointer to AndroidForWorkEnrollmentTargetVTargeted
func AndroidForWorkEnrollmentTargetPTargeted() *AndroidForWorkEnrollmentTarget {
	v := AndroidForWorkEnrollmentTargetVTargeted
	return &v
}

// AndroidForWorkEnrollmentTargetPTargetedAsEnrollmentRestrictions returns a pointer to AndroidForWorkEnrollmentTargetVTargetedAsEnrollmentRestrictions
func AndroidForWorkEnrollmentTargetPTargetedAsEnrollmentRestrictions() *AndroidForWorkEnrollmentTarget {
	v := AndroidForWorkEnrollmentTargetVTargetedAsEnrollmentRestrictions
	return &v
}
