// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

import "context"

// AndroidDeviceOwnerTrustedRootCertificateRequestBuilder is request builder for AndroidDeviceOwnerTrustedRootCertificate
type AndroidDeviceOwnerTrustedRootCertificateRequestBuilder struct{ BaseRequestBuilder }

// Request returns AndroidDeviceOwnerTrustedRootCertificateRequest
func (b *AndroidDeviceOwnerTrustedRootCertificateRequestBuilder) Request() *AndroidDeviceOwnerTrustedRootCertificateRequest {
	return &AndroidDeviceOwnerTrustedRootCertificateRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Delta appends "/delta" onto the builder
func (b *AndroidDeviceOwnerTrustedRootCertificateRequestBuilder) Delta() *AndroidDeviceOwnerTrustedRootCertificateRequestBuilder {
	b.baseUrl = b.baseUrl + "/delta"
	return b
}

// AndroidDeviceOwnerTrustedRootCertificateRequest is request for AndroidDeviceOwnerTrustedRootCertificate
type AndroidDeviceOwnerTrustedRootCertificateRequest struct{ BaseRequest }

// Get performs GET request for AndroidDeviceOwnerTrustedRootCertificate
func (r *AndroidDeviceOwnerTrustedRootCertificateRequest) Get(ctx context.Context) (resObj *AndroidDeviceOwnerTrustedRootCertificate, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for AndroidDeviceOwnerTrustedRootCertificate
func (r *AndroidDeviceOwnerTrustedRootCertificateRequest) Update(ctx context.Context, reqObj *AndroidDeviceOwnerTrustedRootCertificate) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for AndroidDeviceOwnerTrustedRootCertificate
func (r *AndroidDeviceOwnerTrustedRootCertificateRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
