// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AndroidKeyguardFeature undocumented
type AndroidKeyguardFeature string

const (
	// AndroidKeyguardFeatureVNotConfigured undocumented
	AndroidKeyguardFeatureVNotConfigured AndroidKeyguardFeature = "NotConfigured"
	// AndroidKeyguardFeatureVCamera undocumented
	AndroidKeyguardFeatureVCamera AndroidKeyguardFeature = "Camera"
	// AndroidKeyguardFeatureVNotifications undocumented
	AndroidKeyguardFeatureVNotifications AndroidKeyguardFeature = "Notifications"
	// AndroidKeyguardFeatureVUnredactedNotifications undocumented
	AndroidKeyguardFeatureVUnredactedNotifications AndroidKeyguardFeature = "UnredactedNotifications"
	// AndroidKeyguardFeatureVTrustAgents undocumented
	AndroidKeyguardFeatureVTrustAgents AndroidKeyguardFeature = "TrustAgents"
	// AndroidKeyguardFeatureVFingerprint undocumented
	AndroidKeyguardFeatureVFingerprint AndroidKeyguardFeature = "Fingerprint"
	// AndroidKeyguardFeatureVRemoteInput undocumented
	AndroidKeyguardFeatureVRemoteInput AndroidKeyguardFeature = "RemoteInput"
	// AndroidKeyguardFeatureVAllFeatures undocumented
	AndroidKeyguardFeatureVAllFeatures AndroidKeyguardFeature = "AllFeatures"
)

// AndroidKeyguardFeaturePNotConfigured returns a pointer to AndroidKeyguardFeatureVNotConfigured
func AndroidKeyguardFeaturePNotConfigured() *AndroidKeyguardFeature {
	v := AndroidKeyguardFeatureVNotConfigured
	return &v
}

// AndroidKeyguardFeaturePCamera returns a pointer to AndroidKeyguardFeatureVCamera
func AndroidKeyguardFeaturePCamera() *AndroidKeyguardFeature {
	v := AndroidKeyguardFeatureVCamera
	return &v
}

// AndroidKeyguardFeaturePNotifications returns a pointer to AndroidKeyguardFeatureVNotifications
func AndroidKeyguardFeaturePNotifications() *AndroidKeyguardFeature {
	v := AndroidKeyguardFeatureVNotifications
	return &v
}

// AndroidKeyguardFeaturePUnredactedNotifications returns a pointer to AndroidKeyguardFeatureVUnredactedNotifications
func AndroidKeyguardFeaturePUnredactedNotifications() *AndroidKeyguardFeature {
	v := AndroidKeyguardFeatureVUnredactedNotifications
	return &v
}

// AndroidKeyguardFeaturePTrustAgents returns a pointer to AndroidKeyguardFeatureVTrustAgents
func AndroidKeyguardFeaturePTrustAgents() *AndroidKeyguardFeature {
	v := AndroidKeyguardFeatureVTrustAgents
	return &v
}

// AndroidKeyguardFeaturePFingerprint returns a pointer to AndroidKeyguardFeatureVFingerprint
func AndroidKeyguardFeaturePFingerprint() *AndroidKeyguardFeature {
	v := AndroidKeyguardFeatureVFingerprint
	return &v
}

// AndroidKeyguardFeaturePRemoteInput returns a pointer to AndroidKeyguardFeatureVRemoteInput
func AndroidKeyguardFeaturePRemoteInput() *AndroidKeyguardFeature {
	v := AndroidKeyguardFeatureVRemoteInput
	return &v
}

// AndroidKeyguardFeaturePAllFeatures returns a pointer to AndroidKeyguardFeatureVAllFeatures
func AndroidKeyguardFeaturePAllFeatures() *AndroidKeyguardFeature {
	v := AndroidKeyguardFeatureVAllFeatures
	return &v
}
