// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AndroidPermissionActionType undocumented
type AndroidPermissionActionType string

const (
	// AndroidPermissionActionTypeVPrompt undocumented
	AndroidPermissionActionTypeVPrompt AndroidPermissionActionType = "Prompt"
	// AndroidPermissionActionTypeVAutoGrant undocumented
	AndroidPermissionActionTypeVAutoGrant AndroidPermissionActionType = "AutoGrant"
	// AndroidPermissionActionTypeVAutoDeny undocumented
	AndroidPermissionActionTypeVAutoDeny AndroidPermissionActionType = "AutoDeny"
)

// AndroidPermissionActionTypePPrompt returns a pointer to AndroidPermissionActionTypeVPrompt
func AndroidPermissionActionTypePPrompt() *AndroidPermissionActionType {
	v := AndroidPermissionActionTypeVPrompt
	return &v
}

// AndroidPermissionActionTypePAutoGrant returns a pointer to AndroidPermissionActionTypeVAutoGrant
func AndroidPermissionActionTypePAutoGrant() *AndroidPermissionActionType {
	v := AndroidPermissionActionTypeVAutoGrant
	return &v
}

// AndroidPermissionActionTypePAutoDeny returns a pointer to AndroidPermissionActionTypeVAutoDeny
func AndroidPermissionActionTypePAutoDeny() *AndroidPermissionActionType {
	v := AndroidPermissionActionTypeVAutoDeny
	return &v
}
