// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AndroidForWorkBindStatus undocumented
type AndroidForWorkBindStatus string

const (
	// AndroidForWorkBindStatusVNotBound undocumented
	AndroidForWorkBindStatusVNotBound AndroidForWorkBindStatus = "NotBound"
	// AndroidForWorkBindStatusVBound undocumented
	AndroidForWorkBindStatusVBound AndroidForWorkBindStatus = "Bound"
	// AndroidForWorkBindStatusVBoundAndValidated undocumented
	AndroidForWorkBindStatusVBoundAndValidated AndroidForWorkBindStatus = "BoundAndValidated"
	// AndroidForWorkBindStatusVUnbinding undocumented
	AndroidForWorkBindStatusVUnbinding AndroidForWorkBindStatus = "Unbinding"
)

// AndroidForWorkBindStatusPNotBound returns a pointer to AndroidForWorkBindStatusVNotBound
func AndroidForWorkBindStatusPNotBound() *AndroidForWorkBindStatus {
	v := AndroidForWorkBindStatusVNotBound
	return &v
}

// AndroidForWorkBindStatusPBound returns a pointer to AndroidForWorkBindStatusVBound
func AndroidForWorkBindStatusPBound() *AndroidForWorkBindStatus {
	v := AndroidForWorkBindStatusVBound
	return &v
}

// AndroidForWorkBindStatusPBoundAndValidated returns a pointer to AndroidForWorkBindStatusVBoundAndValidated
func AndroidForWorkBindStatusPBoundAndValidated() *AndroidForWorkBindStatus {
	v := AndroidForWorkBindStatusVBoundAndValidated
	return &v
}

// AndroidForWorkBindStatusPUnbinding returns a pointer to AndroidForWorkBindStatusVUnbinding
func AndroidForWorkBindStatusPUnbinding() *AndroidForWorkBindStatus {
	v := AndroidForWorkBindStatusVUnbinding
	return &v
}
