// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AppInstallControlType undocumented
type AppInstallControlType string

const (
	// AppInstallControlTypeVNotConfigured undocumented
	AppInstallControlTypeVNotConfigured AppInstallControlType = "NotConfigured"
	// AppInstallControlTypeVAnywhere undocumented
	AppInstallControlTypeVAnywhere AppInstallControlType = "Anywhere"
	// AppInstallControlTypeVStoreOnly undocumented
	AppInstallControlTypeVStoreOnly AppInstallControlType = "StoreOnly"
	// AppInstallControlTypeVRecommendations undocumented
	AppInstallControlTypeVRecommendations AppInstallControlType = "Recommendations"
	// AppInstallControlTypeVPreferStore undocumented
	AppInstallControlTypeVPreferStore AppInstallControlType = "PreferStore"
)

// AppInstallControlTypePNotConfigured returns a pointer to AppInstallControlTypeVNotConfigured
func AppInstallControlTypePNotConfigured() *AppInstallControlType {
	v := AppInstallControlTypeVNotConfigured
	return &v
}

// AppInstallControlTypePAnywhere returns a pointer to AppInstallControlTypeVAnywhere
func AppInstallControlTypePAnywhere() *AppInstallControlType {
	v := AppInstallControlTypeVAnywhere
	return &v
}

// AppInstallControlTypePStoreOnly returns a pointer to AppInstallControlTypeVStoreOnly
func AppInstallControlTypePStoreOnly() *AppInstallControlType {
	v := AppInstallControlTypeVStoreOnly
	return &v
}

// AppInstallControlTypePRecommendations returns a pointer to AppInstallControlTypeVRecommendations
func AppInstallControlTypePRecommendations() *AppInstallControlType {
	v := AppInstallControlTypeVRecommendations
	return &v
}

// AppInstallControlTypePPreferStore returns a pointer to AppInstallControlTypeVPreferStore
func AppInstallControlTypePPreferStore() *AppInstallControlType {
	v := AppInstallControlTypeVPreferStore
	return &v
}
