// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AppleVpnConnectionType undocumented
type AppleVpnConnectionType string

const (
	// AppleVpnConnectionTypeVCiscoAnyConnect undocumented
	AppleVpnConnectionTypeVCiscoAnyConnect AppleVpnConnectionType = "CiscoAnyConnect"
	// AppleVpnConnectionTypeVPulseSecure undocumented
	AppleVpnConnectionTypeVPulseSecure AppleVpnConnectionType = "PulseSecure"
	// AppleVpnConnectionTypeVF5EdgeClient undocumented
	AppleVpnConnectionTypeVF5EdgeClient AppleVpnConnectionType = "F5EdgeClient"
	// AppleVpnConnectionTypeVDellSonicWallMobileConnect undocumented
	AppleVpnConnectionTypeVDellSonicWallMobileConnect AppleVpnConnectionType = "DellSonicWallMobileConnect"
	// AppleVpnConnectionTypeVCheckPointCapsuleVpn undocumented
	AppleVpnConnectionTypeVCheckPointCapsuleVpn AppleVpnConnectionType = "CheckPointCapsuleVpn"
	// AppleVpnConnectionTypeVCustomVpn undocumented
	AppleVpnConnectionTypeVCustomVpn AppleVpnConnectionType = "CustomVpn"
	// AppleVpnConnectionTypeVCiscoIPSec undocumented
	AppleVpnConnectionTypeVCiscoIPSec AppleVpnConnectionType = "CiscoIPSec"
	// AppleVpnConnectionTypeVCitrix undocumented
	AppleVpnConnectionTypeVCitrix AppleVpnConnectionType = "Citrix"
	// AppleVpnConnectionTypeVCiscoAnyConnectV2 undocumented
	AppleVpnConnectionTypeVCiscoAnyConnectV2 AppleVpnConnectionType = "CiscoAnyConnectV2"
	// AppleVpnConnectionTypeVPaloAltoGlobalProtect undocumented
	AppleVpnConnectionTypeVPaloAltoGlobalProtect AppleVpnConnectionType = "PaloAltoGlobalProtect"
	// AppleVpnConnectionTypeVZscalerPrivateAccess undocumented
	AppleVpnConnectionTypeVZscalerPrivateAccess AppleVpnConnectionType = "ZscalerPrivateAccess"
	// AppleVpnConnectionTypeVF5Access2018 undocumented
	AppleVpnConnectionTypeVF5Access2018 AppleVpnConnectionType = "F5Access2018"
	// AppleVpnConnectionTypeVCitrixSso undocumented
	AppleVpnConnectionTypeVCitrixSso AppleVpnConnectionType = "CitrixSso"
	// AppleVpnConnectionTypeVPaloAltoGlobalProtectV2 undocumented
	AppleVpnConnectionTypeVPaloAltoGlobalProtectV2 AppleVpnConnectionType = "PaloAltoGlobalProtectV2"
	// AppleVpnConnectionTypeVIkEv2 undocumented
	AppleVpnConnectionTypeVIkEv2 AppleVpnConnectionType = "IkEv2"
)

// AppleVpnConnectionTypePCiscoAnyConnect returns a pointer to AppleVpnConnectionTypeVCiscoAnyConnect
func AppleVpnConnectionTypePCiscoAnyConnect() *AppleVpnConnectionType {
	v := AppleVpnConnectionTypeVCiscoAnyConnect
	return &v
}

// AppleVpnConnectionTypePPulseSecure returns a pointer to AppleVpnConnectionTypeVPulseSecure
func AppleVpnConnectionTypePPulseSecure() *AppleVpnConnectionType {
	v := AppleVpnConnectionTypeVPulseSecure
	return &v
}

// AppleVpnConnectionTypePF5EdgeClient returns a pointer to AppleVpnConnectionTypeVF5EdgeClient
func AppleVpnConnectionTypePF5EdgeClient() *AppleVpnConnectionType {
	v := AppleVpnConnectionTypeVF5EdgeClient
	return &v
}

// AppleVpnConnectionTypePDellSonicWallMobileConnect returns a pointer to AppleVpnConnectionTypeVDellSonicWallMobileConnect
func AppleVpnConnectionTypePDellSonicWallMobileConnect() *AppleVpnConnectionType {
	v := AppleVpnConnectionTypeVDellSonicWallMobileConnect
	return &v
}

// AppleVpnConnectionTypePCheckPointCapsuleVpn returns a pointer to AppleVpnConnectionTypeVCheckPointCapsuleVpn
func AppleVpnConnectionTypePCheckPointCapsuleVpn() *AppleVpnConnectionType {
	v := AppleVpnConnectionTypeVCheckPointCapsuleVpn
	return &v
}

// AppleVpnConnectionTypePCustomVpn returns a pointer to AppleVpnConnectionTypeVCustomVpn
func AppleVpnConnectionTypePCustomVpn() *AppleVpnConnectionType {
	v := AppleVpnConnectionTypeVCustomVpn
	return &v
}

// AppleVpnConnectionTypePCiscoIPSec returns a pointer to AppleVpnConnectionTypeVCiscoIPSec
func AppleVpnConnectionTypePCiscoIPSec() *AppleVpnConnectionType {
	v := AppleVpnConnectionTypeVCiscoIPSec
	return &v
}

// AppleVpnConnectionTypePCitrix returns a pointer to AppleVpnConnectionTypeVCitrix
func AppleVpnConnectionTypePCitrix() *AppleVpnConnectionType {
	v := AppleVpnConnectionTypeVCitrix
	return &v
}

// AppleVpnConnectionTypePCiscoAnyConnectV2 returns a pointer to AppleVpnConnectionTypeVCiscoAnyConnectV2
func AppleVpnConnectionTypePCiscoAnyConnectV2() *AppleVpnConnectionType {
	v := AppleVpnConnectionTypeVCiscoAnyConnectV2
	return &v
}

// AppleVpnConnectionTypePPaloAltoGlobalProtect returns a pointer to AppleVpnConnectionTypeVPaloAltoGlobalProtect
func AppleVpnConnectionTypePPaloAltoGlobalProtect() *AppleVpnConnectionType {
	v := AppleVpnConnectionTypeVPaloAltoGlobalProtect
	return &v
}

// AppleVpnConnectionTypePZscalerPrivateAccess returns a pointer to AppleVpnConnectionTypeVZscalerPrivateAccess
func AppleVpnConnectionTypePZscalerPrivateAccess() *AppleVpnConnectionType {
	v := AppleVpnConnectionTypeVZscalerPrivateAccess
	return &v
}

// AppleVpnConnectionTypePF5Access2018 returns a pointer to AppleVpnConnectionTypeVF5Access2018
func AppleVpnConnectionTypePF5Access2018() *AppleVpnConnectionType {
	v := AppleVpnConnectionTypeVF5Access2018
	return &v
}

// AppleVpnConnectionTypePCitrixSso returns a pointer to AppleVpnConnectionTypeVCitrixSso
func AppleVpnConnectionTypePCitrixSso() *AppleVpnConnectionType {
	v := AppleVpnConnectionTypeVCitrixSso
	return &v
}

// AppleVpnConnectionTypePPaloAltoGlobalProtectV2 returns a pointer to AppleVpnConnectionTypeVPaloAltoGlobalProtectV2
func AppleVpnConnectionTypePPaloAltoGlobalProtectV2() *AppleVpnConnectionType {
	v := AppleVpnConnectionTypeVPaloAltoGlobalProtectV2
	return &v
}

// AppleVpnConnectionTypePIkEv2 returns a pointer to AppleVpnConnectionTypeVIkEv2
func AppleVpnConnectionTypePIkEv2() *AppleVpnConnectionType {
	v := AppleVpnConnectionTypeVIkEv2
	return &v
}
