// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AppListType undocumented
type AppListType string

const (
	// AppListTypeVNone undocumented
	AppListTypeVNone AppListType = "None"
	// AppListTypeVAppsInListCompliant undocumented
	AppListTypeVAppsInListCompliant AppListType = "AppsInListCompliant"
	// AppListTypeVAppsNotInListCompliant undocumented
	AppListTypeVAppsNotInListCompliant AppListType = "AppsNotInListCompliant"
)

// AppListTypePNone returns a pointer to AppListTypeVNone
func AppListTypePNone() *AppListType {
	v := AppListTypeVNone
	return &v
}

// AppListTypePAppsInListCompliant returns a pointer to AppListTypeVAppsInListCompliant
func AppListTypePAppsInListCompliant() *AppListType {
	v := AppListTypeVAppsInListCompliant
	return &v
}

// AppListTypePAppsNotInListCompliant returns a pointer to AppListTypeVAppsNotInListCompliant
func AppListTypePAppsNotInListCompliant() *AppListType {
	v := AppListTypeVAppsNotInListCompliant
	return &v
}
