// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ApplicationMode undocumented
type ApplicationMode string

const (
	// ApplicationModeVManual undocumented
	ApplicationModeVManual ApplicationMode = "Manual"
	// ApplicationModeVAutomatic undocumented
	ApplicationModeVAutomatic ApplicationMode = "Automatic"
	// ApplicationModeVRecommended undocumented
	ApplicationModeVRecommended ApplicationMode = "Recommended"
)

// ApplicationModePManual returns a pointer to ApplicationModeVManual
func ApplicationModePManual() *ApplicationMode {
	v := ApplicationModeVManual
	return &v
}

// ApplicationModePAutomatic returns a pointer to ApplicationModeVAutomatic
func ApplicationModePAutomatic() *ApplicationMode {
	v := ApplicationModeVAutomatic
	return &v
}

// ApplicationModePRecommended returns a pointer to ApplicationModeVRecommended
func ApplicationModePRecommended() *ApplicationMode {
	v := ApplicationModeVRecommended
	return &v
}
