// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AppleUserInitiatedEnrollmentType undocumented
type AppleUserInitiatedEnrollmentType string

const (
	// AppleUserInitiatedEnrollmentTypeVUnknown undocumented
	AppleUserInitiatedEnrollmentTypeVUnknown AppleUserInitiatedEnrollmentType = "Unknown"
	// AppleUserInitiatedEnrollmentTypeVDevice undocumented
	AppleUserInitiatedEnrollmentTypeVDevice AppleUserInitiatedEnrollmentType = "Device"
	// AppleUserInitiatedEnrollmentTypeVUser undocumented
	AppleUserInitiatedEnrollmentTypeVUser AppleUserInitiatedEnrollmentType = "User"
)

// AppleUserInitiatedEnrollmentTypePUnknown returns a pointer to AppleUserInitiatedEnrollmentTypeVUnknown
func AppleUserInitiatedEnrollmentTypePUnknown() *AppleUserInitiatedEnrollmentType {
	v := AppleUserInitiatedEnrollmentTypeVUnknown
	return &v
}

// AppleUserInitiatedEnrollmentTypePDevice returns a pointer to AppleUserInitiatedEnrollmentTypeVDevice
func AppleUserInitiatedEnrollmentTypePDevice() *AppleUserInitiatedEnrollmentType {
	v := AppleUserInitiatedEnrollmentTypeVDevice
	return &v
}

// AppleUserInitiatedEnrollmentTypePUser returns a pointer to AppleUserInitiatedEnrollmentTypeVUser
func AppleUserInitiatedEnrollmentTypePUser() *AppleUserInitiatedEnrollmentType {
	v := AppleUserInitiatedEnrollmentTypeVUser
	return &v
}
