// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AssignmentMethod undocumented
type AssignmentMethod string

const (
	// AssignmentMethodVStandard undocumented
	AssignmentMethodVStandard AssignmentMethod = "Standard"
	// AssignmentMethodVPrivileged undocumented
	AssignmentMethodVPrivileged AssignmentMethod = "Privileged"
	// AssignmentMethodVAuto undocumented
	AssignmentMethodVAuto AssignmentMethod = "Auto"
)

// AssignmentMethodPStandard returns a pointer to AssignmentMethodVStandard
func AssignmentMethodPStandard() *AssignmentMethod {
	v := AssignmentMethodVStandard
	return &v
}

// AssignmentMethodPPrivileged returns a pointer to AssignmentMethodVPrivileged
func AssignmentMethodPPrivileged() *AssignmentMethod {
	v := AssignmentMethodVPrivileged
	return &v
}

// AssignmentMethodPAuto returns a pointer to AssignmentMethodVAuto
func AssignmentMethodPAuto() *AssignmentMethod {
	v := AssignmentMethodVAuto
	return &v
}
