// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AuthMethodsType undocumented
type AuthMethodsType string

const (
	// AuthMethodsTypeVEmail undocumented
	AuthMethodsTypeVEmail AuthMethodsType = "Email"
	// AuthMethodsTypeVMobileSMS undocumented
	AuthMethodsTypeVMobileSMS AuthMethodsType = "MobileSMS"
	// AuthMethodsTypeVMobilePhone undocumented
	AuthMethodsTypeVMobilePhone AuthMethodsType = "MobilePhone"
	// AuthMethodsTypeVOfficePhone undocumented
	AuthMethodsTypeVOfficePhone AuthMethodsType = "OfficePhone"
	// AuthMethodsTypeVSecurityQuestion undocumented
	AuthMethodsTypeVSecurityQuestion AuthMethodsType = "SecurityQuestion"
	// AuthMethodsTypeVAppNotification undocumented
	AuthMethodsTypeVAppNotification AuthMethodsType = "AppNotification"
	// AuthMethodsTypeVAppNotificationCode undocumented
	AuthMethodsTypeVAppNotificationCode AuthMethodsType = "AppNotificationCode"
	// AuthMethodsTypeVAppNotificationAndCode undocumented
	AuthMethodsTypeVAppNotificationAndCode AuthMethodsType = "AppNotificationAndCode"
	// AuthMethodsTypeVAppPassword undocumented
	AuthMethodsTypeVAppPassword AuthMethodsType = "AppPassword"
	// AuthMethodsTypeVFido undocumented
	AuthMethodsTypeVFido AuthMethodsType = "Fido"
	// AuthMethodsTypeVAlternateMobilePhone undocumented
	AuthMethodsTypeVAlternateMobilePhone AuthMethodsType = "AlternateMobilePhone"
	// AuthMethodsTypeVMobilePhoneAndSMS undocumented
	AuthMethodsTypeVMobilePhoneAndSMS AuthMethodsType = "MobilePhoneAndSMS"
	// AuthMethodsTypeVUnknownFutureValue undocumented
	AuthMethodsTypeVUnknownFutureValue AuthMethodsType = "UnknownFutureValue"
)

// AuthMethodsTypePEmail returns a pointer to AuthMethodsTypeVEmail
func AuthMethodsTypePEmail() *AuthMethodsType {
	v := AuthMethodsTypeVEmail
	return &v
}

// AuthMethodsTypePMobileSMS returns a pointer to AuthMethodsTypeVMobileSMS
func AuthMethodsTypePMobileSMS() *AuthMethodsType {
	v := AuthMethodsTypeVMobileSMS
	return &v
}

// AuthMethodsTypePMobilePhone returns a pointer to AuthMethodsTypeVMobilePhone
func AuthMethodsTypePMobilePhone() *AuthMethodsType {
	v := AuthMethodsTypeVMobilePhone
	return &v
}

// AuthMethodsTypePOfficePhone returns a pointer to AuthMethodsTypeVOfficePhone
func AuthMethodsTypePOfficePhone() *AuthMethodsType {
	v := AuthMethodsTypeVOfficePhone
	return &v
}

// AuthMethodsTypePSecurityQuestion returns a pointer to AuthMethodsTypeVSecurityQuestion
func AuthMethodsTypePSecurityQuestion() *AuthMethodsType {
	v := AuthMethodsTypeVSecurityQuestion
	return &v
}

// AuthMethodsTypePAppNotification returns a pointer to AuthMethodsTypeVAppNotification
func AuthMethodsTypePAppNotification() *AuthMethodsType {
	v := AuthMethodsTypeVAppNotification
	return &v
}

// AuthMethodsTypePAppNotificationCode returns a pointer to AuthMethodsTypeVAppNotificationCode
func AuthMethodsTypePAppNotificationCode() *AuthMethodsType {
	v := AuthMethodsTypeVAppNotificationCode
	return &v
}

// AuthMethodsTypePAppNotificationAndCode returns a pointer to AuthMethodsTypeVAppNotificationAndCode
func AuthMethodsTypePAppNotificationAndCode() *AuthMethodsType {
	v := AuthMethodsTypeVAppNotificationAndCode
	return &v
}

// AuthMethodsTypePAppPassword returns a pointer to AuthMethodsTypeVAppPassword
func AuthMethodsTypePAppPassword() *AuthMethodsType {
	v := AuthMethodsTypeVAppPassword
	return &v
}

// AuthMethodsTypePFido returns a pointer to AuthMethodsTypeVFido
func AuthMethodsTypePFido() *AuthMethodsType {
	v := AuthMethodsTypeVFido
	return &v
}

// AuthMethodsTypePAlternateMobilePhone returns a pointer to AuthMethodsTypeVAlternateMobilePhone
func AuthMethodsTypePAlternateMobilePhone() *AuthMethodsType {
	v := AuthMethodsTypeVAlternateMobilePhone
	return &v
}

// AuthMethodsTypePMobilePhoneAndSMS returns a pointer to AuthMethodsTypeVMobilePhoneAndSMS
func AuthMethodsTypePMobilePhoneAndSMS() *AuthMethodsType {
	v := AuthMethodsTypeVMobilePhoneAndSMS
	return &v
}

// AuthMethodsTypePUnknownFutureValue returns a pointer to AuthMethodsTypeVUnknownFutureValue
func AuthMethodsTypePUnknownFutureValue() *AuthMethodsType {
	v := AuthMethodsTypeVUnknownFutureValue
	return &v
}
