// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AutoAdmittedUsersType undocumented
type AutoAdmittedUsersType string

const (
	// AutoAdmittedUsersTypeVEveryoneInCompany undocumented
	AutoAdmittedUsersTypeVEveryoneInCompany AutoAdmittedUsersType = "EveryoneInCompany"
	// AutoAdmittedUsersTypeVEveryone undocumented
	AutoAdmittedUsersTypeVEveryone AutoAdmittedUsersType = "Everyone"
)

// AutoAdmittedUsersTypePEveryoneInCompany returns a pointer to AutoAdmittedUsersTypeVEveryoneInCompany
func AutoAdmittedUsersTypePEveryoneInCompany() *AutoAdmittedUsersType {
	v := AutoAdmittedUsersTypeVEveryoneInCompany
	return &v
}

// AutoAdmittedUsersTypePEveryone returns a pointer to AutoAdmittedUsersTypeVEveryone
func AutoAdmittedUsersTypePEveryone() *AutoAdmittedUsersType {
	v := AutoAdmittedUsersTypeVEveryone
	return &v
}
