// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// BookingPriceType undocumented
type BookingPriceType string

const (
	// BookingPriceTypeVUndefined undocumented
	BookingPriceTypeVUndefined BookingPriceType = "Undefined"
	// BookingPriceTypeVFixedPrice undocumented
	BookingPriceTypeVFixedPrice BookingPriceType = "FixedPrice"
	// BookingPriceTypeVStartingAt undocumented
	BookingPriceTypeVStartingAt BookingPriceType = "StartingAt"
	// BookingPriceTypeVHourly undocumented
	BookingPriceTypeVHourly BookingPriceType = "Hourly"
	// BookingPriceTypeVFree undocumented
	BookingPriceTypeVFree BookingPriceType = "Free"
	// BookingPriceTypeVPriceVaries undocumented
	BookingPriceTypeVPriceVaries BookingPriceType = "PriceVaries"
	// BookingPriceTypeVCallUs undocumented
	BookingPriceTypeVCallUs BookingPriceType = "CallUs"
	// BookingPriceTypeVNotSet undocumented
	BookingPriceTypeVNotSet BookingPriceType = "NotSet"
)

// BookingPriceTypePUndefined returns a pointer to BookingPriceTypeVUndefined
func BookingPriceTypePUndefined() *BookingPriceType {
	v := BookingPriceTypeVUndefined
	return &v
}

// BookingPriceTypePFixedPrice returns a pointer to BookingPriceTypeVFixedPrice
func BookingPriceTypePFixedPrice() *BookingPriceType {
	v := BookingPriceTypeVFixedPrice
	return &v
}

// BookingPriceTypePStartingAt returns a pointer to BookingPriceTypeVStartingAt
func BookingPriceTypePStartingAt() *BookingPriceType {
	v := BookingPriceTypeVStartingAt
	return &v
}

// BookingPriceTypePHourly returns a pointer to BookingPriceTypeVHourly
func BookingPriceTypePHourly() *BookingPriceType {
	v := BookingPriceTypeVHourly
	return &v
}

// BookingPriceTypePFree returns a pointer to BookingPriceTypeVFree
func BookingPriceTypePFree() *BookingPriceType {
	v := BookingPriceTypeVFree
	return &v
}

// BookingPriceTypePPriceVaries returns a pointer to BookingPriceTypeVPriceVaries
func BookingPriceTypePPriceVaries() *BookingPriceType {
	v := BookingPriceTypeVPriceVaries
	return &v
}

// BookingPriceTypePCallUs returns a pointer to BookingPriceTypeVCallUs
func BookingPriceTypePCallUs() *BookingPriceType {
	v := BookingPriceTypeVCallUs
	return &v
}

// BookingPriceTypePNotSet returns a pointer to BookingPriceTypeVNotSet
func BookingPriceTypePNotSet() *BookingPriceType {
	v := BookingPriceTypeVNotSet
	return &v
}
