// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// CalendarSharingActionType undocumented
type CalendarSharingActionType string

const (
	// CalendarSharingActionTypeVAccept undocumented
	CalendarSharingActionTypeVAccept CalendarSharingActionType = "Accept"
)

// CalendarSharingActionTypePAccept returns a pointer to CalendarSharingActionTypeVAccept
func CalendarSharingActionTypePAccept() *CalendarSharingActionType {
	v := CalendarSharingActionTypeVAccept
	return &v
}
