// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// CalendarSharingActionImportance undocumented
type CalendarSharingActionImportance string

const (
	// CalendarSharingActionImportanceVPrimary undocumented
	CalendarSharingActionImportanceVPrimary CalendarSharingActionImportance = "Primary"
	// CalendarSharingActionImportanceVSecondary undocumented
	CalendarSharingActionImportanceVSecondary CalendarSharingActionImportance = "Secondary"
)

// CalendarSharingActionImportancePPrimary returns a pointer to CalendarSharingActionImportanceVPrimary
func CalendarSharingActionImportancePPrimary() *CalendarSharingActionImportance {
	v := CalendarSharingActionImportanceVPrimary
	return &v
}

// CalendarSharingActionImportancePSecondary returns a pointer to CalendarSharingActionImportanceVSecondary
func CalendarSharingActionImportancePSecondary() *CalendarSharingActionImportance {
	v := CalendarSharingActionImportanceVSecondary
	return &v
}
