// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// CalendarColor undocumented
type CalendarColor string

const (
	// CalendarColorVLightBlue undocumented
	CalendarColorVLightBlue CalendarColor = "LightBlue"
	// CalendarColorVLightGreen undocumented
	CalendarColorVLightGreen CalendarColor = "LightGreen"
	// CalendarColorVLightOrange undocumented
	CalendarColorVLightOrange CalendarColor = "LightOrange"
	// CalendarColorVLightGray undocumented
	CalendarColorVLightGray CalendarColor = "LightGray"
	// CalendarColorVLightYellow undocumented
	CalendarColorVLightYellow CalendarColor = "LightYellow"
	// CalendarColorVLightTeal undocumented
	CalendarColorVLightTeal CalendarColor = "LightTeal"
	// CalendarColorVLightPink undocumented
	CalendarColorVLightPink CalendarColor = "LightPink"
	// CalendarColorVLightBrown undocumented
	CalendarColorVLightBrown CalendarColor = "LightBrown"
	// CalendarColorVLightRed undocumented
	CalendarColorVLightRed CalendarColor = "LightRed"
	// CalendarColorVMaxColor undocumented
	CalendarColorVMaxColor CalendarColor = "MaxColor"
	// CalendarColorVAuto undocumented
	CalendarColorVAuto CalendarColor = "Auto"
)

// CalendarColorPLightBlue returns a pointer to CalendarColorVLightBlue
func CalendarColorPLightBlue() *CalendarColor {
	v := CalendarColorVLightBlue
	return &v
}

// CalendarColorPLightGreen returns a pointer to CalendarColorVLightGreen
func CalendarColorPLightGreen() *CalendarColor {
	v := CalendarColorVLightGreen
	return &v
}

// CalendarColorPLightOrange returns a pointer to CalendarColorVLightOrange
func CalendarColorPLightOrange() *CalendarColor {
	v := CalendarColorVLightOrange
	return &v
}

// CalendarColorPLightGray returns a pointer to CalendarColorVLightGray
func CalendarColorPLightGray() *CalendarColor {
	v := CalendarColorVLightGray
	return &v
}

// CalendarColorPLightYellow returns a pointer to CalendarColorVLightYellow
func CalendarColorPLightYellow() *CalendarColor {
	v := CalendarColorVLightYellow
	return &v
}

// CalendarColorPLightTeal returns a pointer to CalendarColorVLightTeal
func CalendarColorPLightTeal() *CalendarColor {
	v := CalendarColorVLightTeal
	return &v
}

// CalendarColorPLightPink returns a pointer to CalendarColorVLightPink
func CalendarColorPLightPink() *CalendarColor {
	v := CalendarColorVLightPink
	return &v
}

// CalendarColorPLightBrown returns a pointer to CalendarColorVLightBrown
func CalendarColorPLightBrown() *CalendarColor {
	v := CalendarColorVLightBrown
	return &v
}

// CalendarColorPLightRed returns a pointer to CalendarColorVLightRed
func CalendarColorPLightRed() *CalendarColor {
	v := CalendarColorVLightRed
	return &v
}

// CalendarColorPMaxColor returns a pointer to CalendarColorVMaxColor
func CalendarColorPMaxColor() *CalendarColor {
	v := CalendarColorVMaxColor
	return &v
}

// CalendarColorPAuto returns a pointer to CalendarColorVAuto
func CalendarColorPAuto() *CalendarColor {
	v := CalendarColorVAuto
	return &v
}
