// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// CallDisposition undocumented
type CallDisposition string

const (
	// CallDispositionVDefault undocumented
	CallDispositionVDefault CallDisposition = "Default"
	// CallDispositionVSimultaneousRing undocumented
	CallDispositionVSimultaneousRing CallDisposition = "SimultaneousRing"
	// CallDispositionVForward undocumented
	CallDispositionVForward CallDisposition = "Forward"
)

// CallDispositionPDefault returns a pointer to CallDispositionVDefault
func CallDispositionPDefault() *CallDisposition {
	v := CallDispositionVDefault
	return &v
}

// CallDispositionPSimultaneousRing returns a pointer to CallDispositionVSimultaneousRing
func CallDispositionPSimultaneousRing() *CallDisposition {
	v := CallDispositionVSimultaneousRing
	return &v
}

// CallDispositionPForward returns a pointer to CallDispositionVForward
func CallDispositionPForward() *CallDisposition {
	v := CallDispositionVForward
	return &v
}
