// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// CategoryColor undocumented
type CategoryColor string

const (
	// CategoryColorVPreset0 undocumented
	CategoryColorVPreset0 CategoryColor = "Preset0"
	// CategoryColorVPreset1 undocumented
	CategoryColorVPreset1 CategoryColor = "Preset1"
	// CategoryColorVPreset2 undocumented
	CategoryColorVPreset2 CategoryColor = "Preset2"
	// CategoryColorVPreset3 undocumented
	CategoryColorVPreset3 CategoryColor = "Preset3"
	// CategoryColorVPreset4 undocumented
	CategoryColorVPreset4 CategoryColor = "Preset4"
	// CategoryColorVPreset5 undocumented
	CategoryColorVPreset5 CategoryColor = "Preset5"
	// CategoryColorVPreset6 undocumented
	CategoryColorVPreset6 CategoryColor = "Preset6"
	// CategoryColorVPreset7 undocumented
	CategoryColorVPreset7 CategoryColor = "Preset7"
	// CategoryColorVPreset8 undocumented
	CategoryColorVPreset8 CategoryColor = "Preset8"
	// CategoryColorVPreset9 undocumented
	CategoryColorVPreset9 CategoryColor = "Preset9"
	// CategoryColorVPreset10 undocumented
	CategoryColorVPreset10 CategoryColor = "Preset10"
	// CategoryColorVPreset11 undocumented
	CategoryColorVPreset11 CategoryColor = "Preset11"
	// CategoryColorVPreset12 undocumented
	CategoryColorVPreset12 CategoryColor = "Preset12"
	// CategoryColorVPreset13 undocumented
	CategoryColorVPreset13 CategoryColor = "Preset13"
	// CategoryColorVPreset14 undocumented
	CategoryColorVPreset14 CategoryColor = "Preset14"
	// CategoryColorVPreset15 undocumented
	CategoryColorVPreset15 CategoryColor = "Preset15"
	// CategoryColorVPreset16 undocumented
	CategoryColorVPreset16 CategoryColor = "Preset16"
	// CategoryColorVPreset17 undocumented
	CategoryColorVPreset17 CategoryColor = "Preset17"
	// CategoryColorVPreset18 undocumented
	CategoryColorVPreset18 CategoryColor = "Preset18"
	// CategoryColorVPreset19 undocumented
	CategoryColorVPreset19 CategoryColor = "Preset19"
	// CategoryColorVPreset20 undocumented
	CategoryColorVPreset20 CategoryColor = "Preset20"
	// CategoryColorVPreset21 undocumented
	CategoryColorVPreset21 CategoryColor = "Preset21"
	// CategoryColorVPreset22 undocumented
	CategoryColorVPreset22 CategoryColor = "Preset22"
	// CategoryColorVPreset23 undocumented
	CategoryColorVPreset23 CategoryColor = "Preset23"
	// CategoryColorVPreset24 undocumented
	CategoryColorVPreset24 CategoryColor = "Preset24"
	// CategoryColorVNone undocumented
	CategoryColorVNone CategoryColor = "None"
)

// CategoryColorPPreset0 returns a pointer to CategoryColorVPreset0
func CategoryColorPPreset0() *CategoryColor {
	v := CategoryColorVPreset0
	return &v
}

// CategoryColorPPreset1 returns a pointer to CategoryColorVPreset1
func CategoryColorPPreset1() *CategoryColor {
	v := CategoryColorVPreset1
	return &v
}

// CategoryColorPPreset2 returns a pointer to CategoryColorVPreset2
func CategoryColorPPreset2() *CategoryColor {
	v := CategoryColorVPreset2
	return &v
}

// CategoryColorPPreset3 returns a pointer to CategoryColorVPreset3
func CategoryColorPPreset3() *CategoryColor {
	v := CategoryColorVPreset3
	return &v
}

// CategoryColorPPreset4 returns a pointer to CategoryColorVPreset4
func CategoryColorPPreset4() *CategoryColor {
	v := CategoryColorVPreset4
	return &v
}

// CategoryColorPPreset5 returns a pointer to CategoryColorVPreset5
func CategoryColorPPreset5() *CategoryColor {
	v := CategoryColorVPreset5
	return &v
}

// CategoryColorPPreset6 returns a pointer to CategoryColorVPreset6
func CategoryColorPPreset6() *CategoryColor {
	v := CategoryColorVPreset6
	return &v
}

// CategoryColorPPreset7 returns a pointer to CategoryColorVPreset7
func CategoryColorPPreset7() *CategoryColor {
	v := CategoryColorVPreset7
	return &v
}

// CategoryColorPPreset8 returns a pointer to CategoryColorVPreset8
func CategoryColorPPreset8() *CategoryColor {
	v := CategoryColorVPreset8
	return &v
}

// CategoryColorPPreset9 returns a pointer to CategoryColorVPreset9
func CategoryColorPPreset9() *CategoryColor {
	v := CategoryColorVPreset9
	return &v
}

// CategoryColorPPreset10 returns a pointer to CategoryColorVPreset10
func CategoryColorPPreset10() *CategoryColor {
	v := CategoryColorVPreset10
	return &v
}

// CategoryColorPPreset11 returns a pointer to CategoryColorVPreset11
func CategoryColorPPreset11() *CategoryColor {
	v := CategoryColorVPreset11
	return &v
}

// CategoryColorPPreset12 returns a pointer to CategoryColorVPreset12
func CategoryColorPPreset12() *CategoryColor {
	v := CategoryColorVPreset12
	return &v
}

// CategoryColorPPreset13 returns a pointer to CategoryColorVPreset13
func CategoryColorPPreset13() *CategoryColor {
	v := CategoryColorVPreset13
	return &v
}

// CategoryColorPPreset14 returns a pointer to CategoryColorVPreset14
func CategoryColorPPreset14() *CategoryColor {
	v := CategoryColorVPreset14
	return &v
}

// CategoryColorPPreset15 returns a pointer to CategoryColorVPreset15
func CategoryColorPPreset15() *CategoryColor {
	v := CategoryColorVPreset15
	return &v
}

// CategoryColorPPreset16 returns a pointer to CategoryColorVPreset16
func CategoryColorPPreset16() *CategoryColor {
	v := CategoryColorVPreset16
	return &v
}

// CategoryColorPPreset17 returns a pointer to CategoryColorVPreset17
func CategoryColorPPreset17() *CategoryColor {
	v := CategoryColorVPreset17
	return &v
}

// CategoryColorPPreset18 returns a pointer to CategoryColorVPreset18
func CategoryColorPPreset18() *CategoryColor {
	v := CategoryColorVPreset18
	return &v
}

// CategoryColorPPreset19 returns a pointer to CategoryColorVPreset19
func CategoryColorPPreset19() *CategoryColor {
	v := CategoryColorVPreset19
	return &v
}

// CategoryColorPPreset20 returns a pointer to CategoryColorVPreset20
func CategoryColorPPreset20() *CategoryColor {
	v := CategoryColorVPreset20
	return &v
}

// CategoryColorPPreset21 returns a pointer to CategoryColorVPreset21
func CategoryColorPPreset21() *CategoryColor {
	v := CategoryColorVPreset21
	return &v
}

// CategoryColorPPreset22 returns a pointer to CategoryColorVPreset22
func CategoryColorPPreset22() *CategoryColor {
	v := CategoryColorVPreset22
	return &v
}

// CategoryColorPPreset23 returns a pointer to CategoryColorVPreset23
func CategoryColorPPreset23() *CategoryColor {
	v := CategoryColorVPreset23
	return &v
}

// CategoryColorPPreset24 returns a pointer to CategoryColorVPreset24
func CategoryColorPPreset24() *CategoryColor {
	v := CategoryColorVPreset24
	return &v
}

// CategoryColorPNone returns a pointer to CategoryColorVNone
func CategoryColorPNone() *CategoryColor {
	v := CategoryColorVNone
	return &v
}
