// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// CertificateDestinationStore undocumented
type CertificateDestinationStore string

const (
	// CertificateDestinationStoreVComputerCertStoreRoot undocumented
	CertificateDestinationStoreVComputerCertStoreRoot CertificateDestinationStore = "ComputerCertStoreRoot"
	// CertificateDestinationStoreVComputerCertStoreIntermediate undocumented
	CertificateDestinationStoreVComputerCertStoreIntermediate CertificateDestinationStore = "ComputerCertStoreIntermediate"
	// CertificateDestinationStoreVUserCertStoreIntermediate undocumented
	CertificateDestinationStoreVUserCertStoreIntermediate CertificateDestinationStore = "UserCertStoreIntermediate"
)

// CertificateDestinationStorePComputerCertStoreRoot returns a pointer to CertificateDestinationStoreVComputerCertStoreRoot
func CertificateDestinationStorePComputerCertStoreRoot() *CertificateDestinationStore {
	v := CertificateDestinationStoreVComputerCertStoreRoot
	return &v
}

// CertificateDestinationStorePComputerCertStoreIntermediate returns a pointer to CertificateDestinationStoreVComputerCertStoreIntermediate
func CertificateDestinationStorePComputerCertStoreIntermediate() *CertificateDestinationStore {
	v := CertificateDestinationStoreVComputerCertStoreIntermediate
	return &v
}

// CertificateDestinationStorePUserCertStoreIntermediate returns a pointer to CertificateDestinationStoreVUserCertStoreIntermediate
func CertificateDestinationStorePUserCertStoreIntermediate() *CertificateDestinationStore {
	v := CertificateDestinationStoreVUserCertStoreIntermediate
	return &v
}
