// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// CertificateStore undocumented
type CertificateStore string

const (
	// CertificateStoreVUser undocumented
	CertificateStoreVUser CertificateStore = "User"
	// CertificateStoreVMachine undocumented
	CertificateStoreVMachine CertificateStore = "Machine"
)

// CertificateStorePUser returns a pointer to CertificateStoreVUser
func CertificateStorePUser() *CertificateStore {
	v := CertificateStoreVUser
	return &v
}

// CertificateStorePMachine returns a pointer to CertificateStoreVMachine
func CertificateStorePMachine() *CertificateStore {
	v := CertificateStoreVMachine
	return &v
}
