// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// CompanyPortalAction undocumented
type CompanyPortalAction string

const (
	// CompanyPortalActionVUnknown undocumented
	CompanyPortalActionVUnknown CompanyPortalAction = "Unknown"
	// CompanyPortalActionVRemove undocumented
	CompanyPortalActionVRemove CompanyPortalAction = "Remove"
	// CompanyPortalActionVReset undocumented
	CompanyPortalActionVReset CompanyPortalAction = "Reset"
)

// CompanyPortalActionPUnknown returns a pointer to CompanyPortalActionVUnknown
func CompanyPortalActionPUnknown() *CompanyPortalAction {
	v := CompanyPortalActionVUnknown
	return &v
}

// CompanyPortalActionPRemove returns a pointer to CompanyPortalActionVRemove
func CompanyPortalActionPRemove() *CompanyPortalAction {
	v := CompanyPortalActionVRemove
	return &v
}

// CompanyPortalActionPReset returns a pointer to CompanyPortalActionVReset
func CompanyPortalActionPReset() *CompanyPortalAction {
	v := CompanyPortalActionVReset
	return &v
}
