// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ConditionalAccessDevicePlatform undocumented
type ConditionalAccessDevicePlatform string

const (
	// ConditionalAccessDevicePlatformVAndroid undocumented
	ConditionalAccessDevicePlatformVAndroid ConditionalAccessDevicePlatform = "Android"
	// ConditionalAccessDevicePlatformVIOS undocumented
	ConditionalAccessDevicePlatformVIOS ConditionalAccessDevicePlatform = "IOS"
	// ConditionalAccessDevicePlatformVWindows undocumented
	ConditionalAccessDevicePlatformVWindows ConditionalAccessDevicePlatform = "Windows"
	// ConditionalAccessDevicePlatformVWindowsPhone undocumented
	ConditionalAccessDevicePlatformVWindowsPhone ConditionalAccessDevicePlatform = "WindowsPhone"
	// ConditionalAccessDevicePlatformVMacOS undocumented
	ConditionalAccessDevicePlatformVMacOS ConditionalAccessDevicePlatform = "MacOS"
	// ConditionalAccessDevicePlatformVAll undocumented
	ConditionalAccessDevicePlatformVAll ConditionalAccessDevicePlatform = "All"
)

// ConditionalAccessDevicePlatformPAndroid returns a pointer to ConditionalAccessDevicePlatformVAndroid
func ConditionalAccessDevicePlatformPAndroid() *ConditionalAccessDevicePlatform {
	v := ConditionalAccessDevicePlatformVAndroid
	return &v
}

// ConditionalAccessDevicePlatformPIOS returns a pointer to ConditionalAccessDevicePlatformVIOS
func ConditionalAccessDevicePlatformPIOS() *ConditionalAccessDevicePlatform {
	v := ConditionalAccessDevicePlatformVIOS
	return &v
}

// ConditionalAccessDevicePlatformPWindows returns a pointer to ConditionalAccessDevicePlatformVWindows
func ConditionalAccessDevicePlatformPWindows() *ConditionalAccessDevicePlatform {
	v := ConditionalAccessDevicePlatformVWindows
	return &v
}

// ConditionalAccessDevicePlatformPWindowsPhone returns a pointer to ConditionalAccessDevicePlatformVWindowsPhone
func ConditionalAccessDevicePlatformPWindowsPhone() *ConditionalAccessDevicePlatform {
	v := ConditionalAccessDevicePlatformVWindowsPhone
	return &v
}

// ConditionalAccessDevicePlatformPMacOS returns a pointer to ConditionalAccessDevicePlatformVMacOS
func ConditionalAccessDevicePlatformPMacOS() *ConditionalAccessDevicePlatform {
	v := ConditionalAccessDevicePlatformVMacOS
	return &v
}

// ConditionalAccessDevicePlatformPAll returns a pointer to ConditionalAccessDevicePlatformVAll
func ConditionalAccessDevicePlatformPAll() *ConditionalAccessDevicePlatform {
	v := ConditionalAccessDevicePlatformVAll
	return &v
}
