// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ConnectionStatus undocumented
type ConnectionStatus string

const (
	// ConnectionStatusVUnknown undocumented
	ConnectionStatusVUnknown ConnectionStatus = "Unknown"
	// ConnectionStatusVAttempted undocumented
	ConnectionStatusVAttempted ConnectionStatus = "Attempted"
	// ConnectionStatusVSucceeded undocumented
	ConnectionStatusVSucceeded ConnectionStatus = "Succeeded"
	// ConnectionStatusVBlocked undocumented
	ConnectionStatusVBlocked ConnectionStatus = "Blocked"
	// ConnectionStatusVFailed undocumented
	ConnectionStatusVFailed ConnectionStatus = "Failed"
	// ConnectionStatusVUnknownFutureValue undocumented
	ConnectionStatusVUnknownFutureValue ConnectionStatus = "UnknownFutureValue"
)

// ConnectionStatusPUnknown returns a pointer to ConnectionStatusVUnknown
func ConnectionStatusPUnknown() *ConnectionStatus {
	v := ConnectionStatusVUnknown
	return &v
}

// ConnectionStatusPAttempted returns a pointer to ConnectionStatusVAttempted
func ConnectionStatusPAttempted() *ConnectionStatus {
	v := ConnectionStatusVAttempted
	return &v
}

// ConnectionStatusPSucceeded returns a pointer to ConnectionStatusVSucceeded
func ConnectionStatusPSucceeded() *ConnectionStatus {
	v := ConnectionStatusVSucceeded
	return &v
}

// ConnectionStatusPBlocked returns a pointer to ConnectionStatusVBlocked
func ConnectionStatusPBlocked() *ConnectionStatus {
	v := ConnectionStatusVBlocked
	return &v
}

// ConnectionStatusPFailed returns a pointer to ConnectionStatusVFailed
func ConnectionStatusPFailed() *ConnectionStatus {
	v := ConnectionStatusVFailed
	return &v
}

// ConnectionStatusPUnknownFutureValue returns a pointer to ConnectionStatusVUnknownFutureValue
func ConnectionStatusPUnknownFutureValue() *ConnectionStatus {
	v := ConnectionStatusVUnknownFutureValue
	return &v
}
