// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ContentFormat undocumented
type ContentFormat string

const (
	// ContentFormatVDefault undocumented
	ContentFormatVDefault ContentFormat = "Default"
	// ContentFormatVEmail undocumented
	ContentFormatVEmail ContentFormat = "Email"
)

// ContentFormatPDefault returns a pointer to ContentFormatVDefault
func ContentFormatPDefault() *ContentFormat {
	v := ContentFormatVDefault
	return &v
}

// ContentFormatPEmail returns a pointer to ContentFormatVEmail
func ContentFormatPEmail() *ContentFormat {
	v := ContentFormatVEmail
	return &v
}
