// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ContentState undocumented
type ContentState string

const (
	// ContentStateVRest undocumented
	ContentStateVRest ContentState = "Rest"
	// ContentStateVMotion undocumented
	ContentStateVMotion ContentState = "Motion"
	// ContentStateVUse undocumented
	ContentStateVUse ContentState = "Use"
)

// ContentStatePRest returns a pointer to ContentStateVRest
func ContentStatePRest() *ContentState {
	v := ContentStateVRest
	return &v
}

// ContentStatePMotion returns a pointer to ContentStateVMotion
func ContentStatePMotion() *ContentState {
	v := ContentStateVMotion
	return &v
}

// ContentStatePUse returns a pointer to ContentStateVUse
func ContentStatePUse() *ContentState {
	v := ContentStateVUse
	return &v
}
