// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ContentAlignment undocumented
type ContentAlignment string

const (
	// ContentAlignmentVLeft undocumented
	ContentAlignmentVLeft ContentAlignment = "Left"
	// ContentAlignmentVRight undocumented
	ContentAlignmentVRight ContentAlignment = "Right"
	// ContentAlignmentVCenter undocumented
	ContentAlignmentVCenter ContentAlignment = "Center"
)

// ContentAlignmentPLeft returns a pointer to ContentAlignmentVLeft
func ContentAlignmentPLeft() *ContentAlignment {
	v := ContentAlignmentVLeft
	return &v
}

// ContentAlignmentPRight returns a pointer to ContentAlignmentVRight
func ContentAlignmentPRight() *ContentAlignment {
	v := ContentAlignmentVRight
	return &v
}

// ContentAlignmentPCenter returns a pointer to ContentAlignmentVCenter
func ContentAlignmentPCenter() *ContentAlignment {
	v := ContentAlignmentVCenter
	return &v
}
