// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

import "context"

// CurrencyRequestBuilder is request builder for Currency
type CurrencyRequestBuilder struct{ BaseRequestBuilder }

// Request returns CurrencyRequest
func (b *CurrencyRequestBuilder) Request() *CurrencyRequest {
	return &CurrencyRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Delta appends "/delta" onto the builder
func (b *CurrencyRequestBuilder) Delta() *CurrencyRequestBuilder {
	b.baseUrl = b.baseUrl + "/delta"
	return b
}

// CurrencyRequest is request for Currency
type CurrencyRequest struct{ BaseRequest }

// Get performs GET request for Currency
func (r *CurrencyRequest) Get(ctx context.Context) (resObj *Currency, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Currency
func (r *CurrencyRequest) Update(ctx context.Context, reqObj *Currency) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Currency
func (r *CurrencyRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
