// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DefenderScanType undocumented
type DefenderScanType string

const (
	// DefenderScanTypeVUserDefined undocumented
	DefenderScanTypeVUserDefined DefenderScanType = "UserDefined"
	// DefenderScanTypeVDisabled undocumented
	DefenderScanTypeVDisabled DefenderScanType = "Disabled"
	// DefenderScanTypeVQuick undocumented
	DefenderScanTypeVQuick DefenderScanType = "Quick"
	// DefenderScanTypeVFull undocumented
	DefenderScanTypeVFull DefenderScanType = "Full"
)

// DefenderScanTypePUserDefined returns a pointer to DefenderScanTypeVUserDefined
func DefenderScanTypePUserDefined() *DefenderScanType {
	v := DefenderScanTypeVUserDefined
	return &v
}

// DefenderScanTypePDisabled returns a pointer to DefenderScanTypeVDisabled
func DefenderScanTypePDisabled() *DefenderScanType {
	v := DefenderScanTypeVDisabled
	return &v
}

// DefenderScanTypePQuick returns a pointer to DefenderScanTypeVQuick
func DefenderScanTypePQuick() *DefenderScanType {
	v := DefenderScanTypeVQuick
	return &v
}

// DefenderScanTypePFull returns a pointer to DefenderScanTypeVFull
func DefenderScanTypePFull() *DefenderScanType {
	v := DefenderScanTypeVFull
	return &v
}
