// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DeviceComplianceActionType undocumented
type DeviceComplianceActionType string

const (
	// DeviceComplianceActionTypeVNoAction undocumented
	DeviceComplianceActionTypeVNoAction DeviceComplianceActionType = "NoAction"
	// DeviceComplianceActionTypeVNotification undocumented
	DeviceComplianceActionTypeVNotification DeviceComplianceActionType = "Notification"
	// DeviceComplianceActionTypeVBlock undocumented
	DeviceComplianceActionTypeVBlock DeviceComplianceActionType = "Block"
	// DeviceComplianceActionTypeVRetire undocumented
	DeviceComplianceActionTypeVRetire DeviceComplianceActionType = "Retire"
	// DeviceComplianceActionTypeVWipe undocumented
	DeviceComplianceActionTypeVWipe DeviceComplianceActionType = "Wipe"
	// DeviceComplianceActionTypeVRemoveResourceAccessProfiles undocumented
	DeviceComplianceActionTypeVRemoveResourceAccessProfiles DeviceComplianceActionType = "RemoveResourceAccessProfiles"
	// DeviceComplianceActionTypeVPushNotification undocumented
	DeviceComplianceActionTypeVPushNotification DeviceComplianceActionType = "PushNotification"
	// DeviceComplianceActionTypeVRemoteLock undocumented
	DeviceComplianceActionTypeVRemoteLock DeviceComplianceActionType = "RemoteLock"
)

// DeviceComplianceActionTypePNoAction returns a pointer to DeviceComplianceActionTypeVNoAction
func DeviceComplianceActionTypePNoAction() *DeviceComplianceActionType {
	v := DeviceComplianceActionTypeVNoAction
	return &v
}

// DeviceComplianceActionTypePNotification returns a pointer to DeviceComplianceActionTypeVNotification
func DeviceComplianceActionTypePNotification() *DeviceComplianceActionType {
	v := DeviceComplianceActionTypeVNotification
	return &v
}

// DeviceComplianceActionTypePBlock returns a pointer to DeviceComplianceActionTypeVBlock
func DeviceComplianceActionTypePBlock() *DeviceComplianceActionType {
	v := DeviceComplianceActionTypeVBlock
	return &v
}

// DeviceComplianceActionTypePRetire returns a pointer to DeviceComplianceActionTypeVRetire
func DeviceComplianceActionTypePRetire() *DeviceComplianceActionType {
	v := DeviceComplianceActionTypeVRetire
	return &v
}

// DeviceComplianceActionTypePWipe returns a pointer to DeviceComplianceActionTypeVWipe
func DeviceComplianceActionTypePWipe() *DeviceComplianceActionType {
	v := DeviceComplianceActionTypeVWipe
	return &v
}

// DeviceComplianceActionTypePRemoveResourceAccessProfiles returns a pointer to DeviceComplianceActionTypeVRemoveResourceAccessProfiles
func DeviceComplianceActionTypePRemoveResourceAccessProfiles() *DeviceComplianceActionType {
	v := DeviceComplianceActionTypeVRemoveResourceAccessProfiles
	return &v
}

// DeviceComplianceActionTypePPushNotification returns a pointer to DeviceComplianceActionTypeVPushNotification
func DeviceComplianceActionTypePPushNotification() *DeviceComplianceActionType {
	v := DeviceComplianceActionTypeVPushNotification
	return &v
}

// DeviceComplianceActionTypePRemoteLock returns a pointer to DeviceComplianceActionTypeVRemoteLock
func DeviceComplianceActionTypePRemoteLock() *DeviceComplianceActionType {
	v := DeviceComplianceActionTypeVRemoteLock
	return &v
}
