// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DeviceRegistrationState undocumented
type DeviceRegistrationState string

const (
	// DeviceRegistrationStateVNotRegistered undocumented
	DeviceRegistrationStateVNotRegistered DeviceRegistrationState = "NotRegistered"
	// DeviceRegistrationStateVRegistered undocumented
	DeviceRegistrationStateVRegistered DeviceRegistrationState = "Registered"
	// DeviceRegistrationStateVRevoked undocumented
	DeviceRegistrationStateVRevoked DeviceRegistrationState = "Revoked"
	// DeviceRegistrationStateVKeyConflict undocumented
	DeviceRegistrationStateVKeyConflict DeviceRegistrationState = "KeyConflict"
	// DeviceRegistrationStateVApprovalPending undocumented
	DeviceRegistrationStateVApprovalPending DeviceRegistrationState = "ApprovalPending"
	// DeviceRegistrationStateVCertificateReset undocumented
	DeviceRegistrationStateVCertificateReset DeviceRegistrationState = "CertificateReset"
	// DeviceRegistrationStateVNotRegisteredPendingEnrollment undocumented
	DeviceRegistrationStateVNotRegisteredPendingEnrollment DeviceRegistrationState = "NotRegisteredPendingEnrollment"
	// DeviceRegistrationStateVUnknown undocumented
	DeviceRegistrationStateVUnknown DeviceRegistrationState = "Unknown"
)

// DeviceRegistrationStatePNotRegistered returns a pointer to DeviceRegistrationStateVNotRegistered
func DeviceRegistrationStatePNotRegistered() *DeviceRegistrationState {
	v := DeviceRegistrationStateVNotRegistered
	return &v
}

// DeviceRegistrationStatePRegistered returns a pointer to DeviceRegistrationStateVRegistered
func DeviceRegistrationStatePRegistered() *DeviceRegistrationState {
	v := DeviceRegistrationStateVRegistered
	return &v
}

// DeviceRegistrationStatePRevoked returns a pointer to DeviceRegistrationStateVRevoked
func DeviceRegistrationStatePRevoked() *DeviceRegistrationState {
	v := DeviceRegistrationStateVRevoked
	return &v
}

// DeviceRegistrationStatePKeyConflict returns a pointer to DeviceRegistrationStateVKeyConflict
func DeviceRegistrationStatePKeyConflict() *DeviceRegistrationState {
	v := DeviceRegistrationStateVKeyConflict
	return &v
}

// DeviceRegistrationStatePApprovalPending returns a pointer to DeviceRegistrationStateVApprovalPending
func DeviceRegistrationStatePApprovalPending() *DeviceRegistrationState {
	v := DeviceRegistrationStateVApprovalPending
	return &v
}

// DeviceRegistrationStatePCertificateReset returns a pointer to DeviceRegistrationStateVCertificateReset
func DeviceRegistrationStatePCertificateReset() *DeviceRegistrationState {
	v := DeviceRegistrationStateVCertificateReset
	return &v
}

// DeviceRegistrationStatePNotRegisteredPendingEnrollment returns a pointer to DeviceRegistrationStateVNotRegisteredPendingEnrollment
func DeviceRegistrationStatePNotRegisteredPendingEnrollment() *DeviceRegistrationState {
	v := DeviceRegistrationStateVNotRegisteredPendingEnrollment
	return &v
}

// DeviceRegistrationStatePUnknown returns a pointer to DeviceRegistrationStateVUnknown
func DeviceRegistrationStatePUnknown() *DeviceRegistrationState {
	v := DeviceRegistrationStateVUnknown
	return &v
}
