// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DeviceThreatProtectionLevel undocumented
type DeviceThreatProtectionLevel string

const (
	// DeviceThreatProtectionLevelVUnavailable undocumented
	DeviceThreatProtectionLevelVUnavailable DeviceThreatProtectionLevel = "Unavailable"
	// DeviceThreatProtectionLevelVSecured undocumented
	DeviceThreatProtectionLevelVSecured DeviceThreatProtectionLevel = "Secured"
	// DeviceThreatProtectionLevelVLow undocumented
	DeviceThreatProtectionLevelVLow DeviceThreatProtectionLevel = "Low"
	// DeviceThreatProtectionLevelVMedium undocumented
	DeviceThreatProtectionLevelVMedium DeviceThreatProtectionLevel = "Medium"
	// DeviceThreatProtectionLevelVHigh undocumented
	DeviceThreatProtectionLevelVHigh DeviceThreatProtectionLevel = "High"
	// DeviceThreatProtectionLevelVNotSet undocumented
	DeviceThreatProtectionLevelVNotSet DeviceThreatProtectionLevel = "NotSet"
)

// DeviceThreatProtectionLevelPUnavailable returns a pointer to DeviceThreatProtectionLevelVUnavailable
func DeviceThreatProtectionLevelPUnavailable() *DeviceThreatProtectionLevel {
	v := DeviceThreatProtectionLevelVUnavailable
	return &v
}

// DeviceThreatProtectionLevelPSecured returns a pointer to DeviceThreatProtectionLevelVSecured
func DeviceThreatProtectionLevelPSecured() *DeviceThreatProtectionLevel {
	v := DeviceThreatProtectionLevelVSecured
	return &v
}

// DeviceThreatProtectionLevelPLow returns a pointer to DeviceThreatProtectionLevelVLow
func DeviceThreatProtectionLevelPLow() *DeviceThreatProtectionLevel {
	v := DeviceThreatProtectionLevelVLow
	return &v
}

// DeviceThreatProtectionLevelPMedium returns a pointer to DeviceThreatProtectionLevelVMedium
func DeviceThreatProtectionLevelPMedium() *DeviceThreatProtectionLevel {
	v := DeviceThreatProtectionLevelVMedium
	return &v
}

// DeviceThreatProtectionLevelPHigh returns a pointer to DeviceThreatProtectionLevelVHigh
func DeviceThreatProtectionLevelPHigh() *DeviceThreatProtectionLevel {
	v := DeviceThreatProtectionLevelVHigh
	return &v
}

// DeviceThreatProtectionLevelPNotSet returns a pointer to DeviceThreatProtectionLevelVNotSet
func DeviceThreatProtectionLevelPNotSet() *DeviceThreatProtectionLevel {
	v := DeviceThreatProtectionLevelVNotSet
	return &v
}
