// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DeviceManagementScheduledReportRecurrence undocumented
type DeviceManagementScheduledReportRecurrence string

const (
	// DeviceManagementScheduledReportRecurrenceVNone undocumented
	DeviceManagementScheduledReportRecurrenceVNone DeviceManagementScheduledReportRecurrence = "None"
	// DeviceManagementScheduledReportRecurrenceVDaily undocumented
	DeviceManagementScheduledReportRecurrenceVDaily DeviceManagementScheduledReportRecurrence = "Daily"
	// DeviceManagementScheduledReportRecurrenceVWeekly undocumented
	DeviceManagementScheduledReportRecurrenceVWeekly DeviceManagementScheduledReportRecurrence = "Weekly"
	// DeviceManagementScheduledReportRecurrenceVMonthly undocumented
	DeviceManagementScheduledReportRecurrenceVMonthly DeviceManagementScheduledReportRecurrence = "Monthly"
)

// DeviceManagementScheduledReportRecurrencePNone returns a pointer to DeviceManagementScheduledReportRecurrenceVNone
func DeviceManagementScheduledReportRecurrencePNone() *DeviceManagementScheduledReportRecurrence {
	v := DeviceManagementScheduledReportRecurrenceVNone
	return &v
}

// DeviceManagementScheduledReportRecurrencePDaily returns a pointer to DeviceManagementScheduledReportRecurrenceVDaily
func DeviceManagementScheduledReportRecurrencePDaily() *DeviceManagementScheduledReportRecurrence {
	v := DeviceManagementScheduledReportRecurrenceVDaily
	return &v
}

// DeviceManagementScheduledReportRecurrencePWeekly returns a pointer to DeviceManagementScheduledReportRecurrenceVWeekly
func DeviceManagementScheduledReportRecurrencePWeekly() *DeviceManagementScheduledReportRecurrence {
	v := DeviceManagementScheduledReportRecurrenceVWeekly
	return &v
}

// DeviceManagementScheduledReportRecurrencePMonthly returns a pointer to DeviceManagementScheduledReportRecurrenceVMonthly
func DeviceManagementScheduledReportRecurrencePMonthly() *DeviceManagementScheduledReportRecurrence {
	v := DeviceManagementScheduledReportRecurrenceVMonthly
	return &v
}
