// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DeviceManagementReportFileFormat undocumented
type DeviceManagementReportFileFormat string

const (
	// DeviceManagementReportFileFormatVCsv undocumented
	DeviceManagementReportFileFormatVCsv DeviceManagementReportFileFormat = "Csv"
	// DeviceManagementReportFileFormatVPdf undocumented
	DeviceManagementReportFileFormatVPdf DeviceManagementReportFileFormat = "Pdf"
)

// DeviceManagementReportFileFormatPCsv returns a pointer to DeviceManagementReportFileFormatVCsv
func DeviceManagementReportFileFormatPCsv() *DeviceManagementReportFileFormat {
	v := DeviceManagementReportFileFormatVCsv
	return &v
}

// DeviceManagementReportFileFormatPPdf returns a pointer to DeviceManagementReportFileFormatVPdf
func DeviceManagementReportFileFormatPPdf() *DeviceManagementReportFileFormat {
	v := DeviceManagementReportFileFormatVPdf
	return &v
}
