// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DeviceAppManagementTaskStatus undocumented
type DeviceAppManagementTaskStatus string

const (
	// DeviceAppManagementTaskStatusVUnknown undocumented
	DeviceAppManagementTaskStatusVUnknown DeviceAppManagementTaskStatus = "Unknown"
	// DeviceAppManagementTaskStatusVPending undocumented
	DeviceAppManagementTaskStatusVPending DeviceAppManagementTaskStatus = "Pending"
	// DeviceAppManagementTaskStatusVActive undocumented
	DeviceAppManagementTaskStatusVActive DeviceAppManagementTaskStatus = "Active"
	// DeviceAppManagementTaskStatusVCompleted undocumented
	DeviceAppManagementTaskStatusVCompleted DeviceAppManagementTaskStatus = "Completed"
	// DeviceAppManagementTaskStatusVRejected undocumented
	DeviceAppManagementTaskStatusVRejected DeviceAppManagementTaskStatus = "Rejected"
)

// DeviceAppManagementTaskStatusPUnknown returns a pointer to DeviceAppManagementTaskStatusVUnknown
func DeviceAppManagementTaskStatusPUnknown() *DeviceAppManagementTaskStatus {
	v := DeviceAppManagementTaskStatusVUnknown
	return &v
}

// DeviceAppManagementTaskStatusPPending returns a pointer to DeviceAppManagementTaskStatusVPending
func DeviceAppManagementTaskStatusPPending() *DeviceAppManagementTaskStatus {
	v := DeviceAppManagementTaskStatusVPending
	return &v
}

// DeviceAppManagementTaskStatusPActive returns a pointer to DeviceAppManagementTaskStatusVActive
func DeviceAppManagementTaskStatusPActive() *DeviceAppManagementTaskStatus {
	v := DeviceAppManagementTaskStatusVActive
	return &v
}

// DeviceAppManagementTaskStatusPCompleted returns a pointer to DeviceAppManagementTaskStatusVCompleted
func DeviceAppManagementTaskStatusPCompleted() *DeviceAppManagementTaskStatus {
	v := DeviceAppManagementTaskStatusVCompleted
	return &v
}

// DeviceAppManagementTaskStatusPRejected returns a pointer to DeviceAppManagementTaskStatusVRejected
func DeviceAppManagementTaskStatusPRejected() *DeviceAppManagementTaskStatus {
	v := DeviceAppManagementTaskStatusVRejected
	return &v
}
