// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DeviceManagementSubscriptions undocumented
type DeviceManagementSubscriptions string

const (
	// DeviceManagementSubscriptionsVNone undocumented
	DeviceManagementSubscriptionsVNone DeviceManagementSubscriptions = "None"
	// DeviceManagementSubscriptionsVIntune undocumented
	DeviceManagementSubscriptionsVIntune DeviceManagementSubscriptions = "Intune"
	// DeviceManagementSubscriptionsVOffice365 undocumented
	DeviceManagementSubscriptionsVOffice365 DeviceManagementSubscriptions = "Office365"
	// DeviceManagementSubscriptionsVIntunePremium undocumented
	DeviceManagementSubscriptionsVIntunePremium DeviceManagementSubscriptions = "IntunePremium"
	// DeviceManagementSubscriptionsVIntune_EDU undocumented
	DeviceManagementSubscriptionsVIntune_EDU DeviceManagementSubscriptions = "Intune_EDU"
	// DeviceManagementSubscriptionsVIntune_SMB undocumented
	DeviceManagementSubscriptionsVIntune_SMB DeviceManagementSubscriptions = "Intune_SMB"
)

// DeviceManagementSubscriptionsPNone returns a pointer to DeviceManagementSubscriptionsVNone
func DeviceManagementSubscriptionsPNone() *DeviceManagementSubscriptions {
	v := DeviceManagementSubscriptionsVNone
	return &v
}

// DeviceManagementSubscriptionsPIntune returns a pointer to DeviceManagementSubscriptionsVIntune
func DeviceManagementSubscriptionsPIntune() *DeviceManagementSubscriptions {
	v := DeviceManagementSubscriptionsVIntune
	return &v
}

// DeviceManagementSubscriptionsPOffice365 returns a pointer to DeviceManagementSubscriptionsVOffice365
func DeviceManagementSubscriptionsPOffice365() *DeviceManagementSubscriptions {
	v := DeviceManagementSubscriptionsVOffice365
	return &v
}

// DeviceManagementSubscriptionsPIntunePremium returns a pointer to DeviceManagementSubscriptionsVIntunePremium
func DeviceManagementSubscriptionsPIntunePremium() *DeviceManagementSubscriptions {
	v := DeviceManagementSubscriptionsVIntunePremium
	return &v
}

// DeviceManagementSubscriptionsPIntune_EDU returns a pointer to DeviceManagementSubscriptionsVIntune_EDU
func DeviceManagementSubscriptionsPIntune_EDU() *DeviceManagementSubscriptions {
	v := DeviceManagementSubscriptionsVIntune_EDU
	return &v
}

// DeviceManagementSubscriptionsPIntune_SMB returns a pointer to DeviceManagementSubscriptionsVIntune_SMB
func DeviceManagementSubscriptionsPIntune_SMB() *DeviceManagementSubscriptions {
	v := DeviceManagementSubscriptionsVIntune_SMB
	return &v
}
