// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DeviceManagementComparisonResult undocumented
type DeviceManagementComparisonResult string

const (
	// DeviceManagementComparisonResultVUnknown undocumented
	DeviceManagementComparisonResultVUnknown DeviceManagementComparisonResult = "Unknown"
	// DeviceManagementComparisonResultVEqual undocumented
	DeviceManagementComparisonResultVEqual DeviceManagementComparisonResult = "Equal"
	// DeviceManagementComparisonResultVNotEqual undocumented
	DeviceManagementComparisonResultVNotEqual DeviceManagementComparisonResult = "NotEqual"
	// DeviceManagementComparisonResultVAdded undocumented
	DeviceManagementComparisonResultVAdded DeviceManagementComparisonResult = "Added"
	// DeviceManagementComparisonResultVRemoved undocumented
	DeviceManagementComparisonResultVRemoved DeviceManagementComparisonResult = "Removed"
)

// DeviceManagementComparisonResultPUnknown returns a pointer to DeviceManagementComparisonResultVUnknown
func DeviceManagementComparisonResultPUnknown() *DeviceManagementComparisonResult {
	v := DeviceManagementComparisonResultVUnknown
	return &v
}

// DeviceManagementComparisonResultPEqual returns a pointer to DeviceManagementComparisonResultVEqual
func DeviceManagementComparisonResultPEqual() *DeviceManagementComparisonResult {
	v := DeviceManagementComparisonResultVEqual
	return &v
}

// DeviceManagementComparisonResultPNotEqual returns a pointer to DeviceManagementComparisonResultVNotEqual
func DeviceManagementComparisonResultPNotEqual() *DeviceManagementComparisonResult {
	v := DeviceManagementComparisonResultVNotEqual
	return &v
}

// DeviceManagementComparisonResultPAdded returns a pointer to DeviceManagementComparisonResultVAdded
func DeviceManagementComparisonResultPAdded() *DeviceManagementComparisonResult {
	v := DeviceManagementComparisonResultVAdded
	return &v
}

// DeviceManagementComparisonResultPRemoved returns a pointer to DeviceManagementComparisonResultVRemoved
func DeviceManagementComparisonResultPRemoved() *DeviceManagementComparisonResult {
	v := DeviceManagementComparisonResultVRemoved
	return &v
}
