// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DeviceManangementIntentValueType undocumented
type DeviceManangementIntentValueType string

const (
	// DeviceManangementIntentValueTypeVInteger undocumented
	DeviceManangementIntentValueTypeVInteger DeviceManangementIntentValueType = "Integer"
	// DeviceManangementIntentValueTypeVBoolean undocumented
	DeviceManangementIntentValueTypeVBoolean DeviceManangementIntentValueType = "Boolean"
	// DeviceManangementIntentValueTypeVString undocumented
	DeviceManangementIntentValueTypeVString DeviceManangementIntentValueType = "String"
	// DeviceManangementIntentValueTypeVComplex undocumented
	DeviceManangementIntentValueTypeVComplex DeviceManangementIntentValueType = "Complex"
	// DeviceManangementIntentValueTypeVCollection undocumented
	DeviceManangementIntentValueTypeVCollection DeviceManangementIntentValueType = "Collection"
	// DeviceManangementIntentValueTypeVAbstractComplex undocumented
	DeviceManangementIntentValueTypeVAbstractComplex DeviceManangementIntentValueType = "AbstractComplex"
)

// DeviceManangementIntentValueTypePInteger returns a pointer to DeviceManangementIntentValueTypeVInteger
func DeviceManangementIntentValueTypePInteger() *DeviceManangementIntentValueType {
	v := DeviceManangementIntentValueTypeVInteger
	return &v
}

// DeviceManangementIntentValueTypePBoolean returns a pointer to DeviceManangementIntentValueTypeVBoolean
func DeviceManangementIntentValueTypePBoolean() *DeviceManangementIntentValueType {
	v := DeviceManangementIntentValueTypeVBoolean
	return &v
}

// DeviceManangementIntentValueTypePString returns a pointer to DeviceManangementIntentValueTypeVString
func DeviceManangementIntentValueTypePString() *DeviceManangementIntentValueType {
	v := DeviceManangementIntentValueTypeVString
	return &v
}

// DeviceManangementIntentValueTypePComplex returns a pointer to DeviceManangementIntentValueTypeVComplex
func DeviceManangementIntentValueTypePComplex() *DeviceManangementIntentValueType {
	v := DeviceManangementIntentValueTypeVComplex
	return &v
}

// DeviceManangementIntentValueTypePCollection returns a pointer to DeviceManangementIntentValueTypeVCollection
func DeviceManangementIntentValueTypePCollection() *DeviceManangementIntentValueType {
	v := DeviceManangementIntentValueTypeVCollection
	return &v
}

// DeviceManangementIntentValueTypePAbstractComplex returns a pointer to DeviceManangementIntentValueTypeVAbstractComplex
func DeviceManangementIntentValueTypePAbstractComplex() *DeviceManangementIntentValueType {
	v := DeviceManangementIntentValueTypeVAbstractComplex
	return &v
}
