// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DeviceManagementExchangeAccessRuleType undocumented
type DeviceManagementExchangeAccessRuleType string

const (
	// DeviceManagementExchangeAccessRuleTypeVFamily undocumented
	DeviceManagementExchangeAccessRuleTypeVFamily DeviceManagementExchangeAccessRuleType = "Family"
	// DeviceManagementExchangeAccessRuleTypeVModel undocumented
	DeviceManagementExchangeAccessRuleTypeVModel DeviceManagementExchangeAccessRuleType = "Model"
)

// DeviceManagementExchangeAccessRuleTypePFamily returns a pointer to DeviceManagementExchangeAccessRuleTypeVFamily
func DeviceManagementExchangeAccessRuleTypePFamily() *DeviceManagementExchangeAccessRuleType {
	v := DeviceManagementExchangeAccessRuleTypeVFamily
	return &v
}

// DeviceManagementExchangeAccessRuleTypePModel returns a pointer to DeviceManagementExchangeAccessRuleTypeVModel
func DeviceManagementExchangeAccessRuleTypePModel() *DeviceManagementExchangeAccessRuleType {
	v := DeviceManagementExchangeAccessRuleTypeVModel
	return &v
}
