// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DeviceType undocumented
type DeviceType string

const (
	// DeviceTypeVDesktop undocumented
	DeviceTypeVDesktop DeviceType = "Desktop"
	// DeviceTypeVWindowsRT undocumented
	DeviceTypeVWindowsRT DeviceType = "WindowsRT"
	// DeviceTypeVWinMO6 undocumented
	DeviceTypeVWinMO6 DeviceType = "WinMO6"
	// DeviceTypeVNokia undocumented
	DeviceTypeVNokia DeviceType = "Nokia"
	// DeviceTypeVWindowsPhone undocumented
	DeviceTypeVWindowsPhone DeviceType = "WindowsPhone"
	// DeviceTypeVMac undocumented
	DeviceTypeVMac DeviceType = "Mac"
	// DeviceTypeVWinCE undocumented
	DeviceTypeVWinCE DeviceType = "WinCE"
	// DeviceTypeVWinEmbedded undocumented
	DeviceTypeVWinEmbedded DeviceType = "WinEmbedded"
	// DeviceTypeVIPhone undocumented
	DeviceTypeVIPhone DeviceType = "IPhone"
	// DeviceTypeVIPad undocumented
	DeviceTypeVIPad DeviceType = "IPad"
	// DeviceTypeVIPod undocumented
	DeviceTypeVIPod DeviceType = "IPod"
	// DeviceTypeVAndroid undocumented
	DeviceTypeVAndroid DeviceType = "Android"
	// DeviceTypeVISocConsumer undocumented
	DeviceTypeVISocConsumer DeviceType = "ISocConsumer"
	// DeviceTypeVUnix undocumented
	DeviceTypeVUnix DeviceType = "Unix"
	// DeviceTypeVMacMDM undocumented
	DeviceTypeVMacMDM DeviceType = "MacMDM"
	// DeviceTypeVHoloLens undocumented
	DeviceTypeVHoloLens DeviceType = "HoloLens"
	// DeviceTypeVSurfaceHub undocumented
	DeviceTypeVSurfaceHub DeviceType = "SurfaceHub"
	// DeviceTypeVAndroidForWork undocumented
	DeviceTypeVAndroidForWork DeviceType = "AndroidForWork"
	// DeviceTypeVAndroidEnterprise undocumented
	DeviceTypeVAndroidEnterprise DeviceType = "AndroidEnterprise"
	// DeviceTypeVBlackberry undocumented
	DeviceTypeVBlackberry DeviceType = "Blackberry"
	// DeviceTypeVPalm undocumented
	DeviceTypeVPalm DeviceType = "Palm"
	// DeviceTypeVUnknown undocumented
	DeviceTypeVUnknown DeviceType = "Unknown"
)

// DeviceTypePDesktop returns a pointer to DeviceTypeVDesktop
func DeviceTypePDesktop() *DeviceType {
	v := DeviceTypeVDesktop
	return &v
}

// DeviceTypePWindowsRT returns a pointer to DeviceTypeVWindowsRT
func DeviceTypePWindowsRT() *DeviceType {
	v := DeviceTypeVWindowsRT
	return &v
}

// DeviceTypePWinMO6 returns a pointer to DeviceTypeVWinMO6
func DeviceTypePWinMO6() *DeviceType {
	v := DeviceTypeVWinMO6
	return &v
}

// DeviceTypePNokia returns a pointer to DeviceTypeVNokia
func DeviceTypePNokia() *DeviceType {
	v := DeviceTypeVNokia
	return &v
}

// DeviceTypePWindowsPhone returns a pointer to DeviceTypeVWindowsPhone
func DeviceTypePWindowsPhone() *DeviceType {
	v := DeviceTypeVWindowsPhone
	return &v
}

// DeviceTypePMac returns a pointer to DeviceTypeVMac
func DeviceTypePMac() *DeviceType {
	v := DeviceTypeVMac
	return &v
}

// DeviceTypePWinCE returns a pointer to DeviceTypeVWinCE
func DeviceTypePWinCE() *DeviceType {
	v := DeviceTypeVWinCE
	return &v
}

// DeviceTypePWinEmbedded returns a pointer to DeviceTypeVWinEmbedded
func DeviceTypePWinEmbedded() *DeviceType {
	v := DeviceTypeVWinEmbedded
	return &v
}

// DeviceTypePIPhone returns a pointer to DeviceTypeVIPhone
func DeviceTypePIPhone() *DeviceType {
	v := DeviceTypeVIPhone
	return &v
}

// DeviceTypePIPad returns a pointer to DeviceTypeVIPad
func DeviceTypePIPad() *DeviceType {
	v := DeviceTypeVIPad
	return &v
}

// DeviceTypePIPod returns a pointer to DeviceTypeVIPod
func DeviceTypePIPod() *DeviceType {
	v := DeviceTypeVIPod
	return &v
}

// DeviceTypePAndroid returns a pointer to DeviceTypeVAndroid
func DeviceTypePAndroid() *DeviceType {
	v := DeviceTypeVAndroid
	return &v
}

// DeviceTypePISocConsumer returns a pointer to DeviceTypeVISocConsumer
func DeviceTypePISocConsumer() *DeviceType {
	v := DeviceTypeVISocConsumer
	return &v
}

// DeviceTypePUnix returns a pointer to DeviceTypeVUnix
func DeviceTypePUnix() *DeviceType {
	v := DeviceTypeVUnix
	return &v
}

// DeviceTypePMacMDM returns a pointer to DeviceTypeVMacMDM
func DeviceTypePMacMDM() *DeviceType {
	v := DeviceTypeVMacMDM
	return &v
}

// DeviceTypePHoloLens returns a pointer to DeviceTypeVHoloLens
func DeviceTypePHoloLens() *DeviceType {
	v := DeviceTypeVHoloLens
	return &v
}

// DeviceTypePSurfaceHub returns a pointer to DeviceTypeVSurfaceHub
func DeviceTypePSurfaceHub() *DeviceType {
	v := DeviceTypeVSurfaceHub
	return &v
}

// DeviceTypePAndroidForWork returns a pointer to DeviceTypeVAndroidForWork
func DeviceTypePAndroidForWork() *DeviceType {
	v := DeviceTypeVAndroidForWork
	return &v
}

// DeviceTypePAndroidEnterprise returns a pointer to DeviceTypeVAndroidEnterprise
func DeviceTypePAndroidEnterprise() *DeviceType {
	v := DeviceTypeVAndroidEnterprise
	return &v
}

// DeviceTypePBlackberry returns a pointer to DeviceTypeVBlackberry
func DeviceTypePBlackberry() *DeviceType {
	v := DeviceTypeVBlackberry
	return &v
}

// DeviceTypePPalm returns a pointer to DeviceTypeVPalm
func DeviceTypePPalm() *DeviceType {
	v := DeviceTypeVPalm
	return &v
}

// DeviceTypePUnknown returns a pointer to DeviceTypeVUnknown
func DeviceTypePUnknown() *DeviceType {
	v := DeviceTypeVUnknown
	return &v
}
