// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

import "context"

// DirectoryAuditRequestBuilder is request builder for DirectoryAudit
type DirectoryAuditRequestBuilder struct{ BaseRequestBuilder }

// Request returns DirectoryAuditRequest
func (b *DirectoryAuditRequestBuilder) Request() *DirectoryAuditRequest {
	return &DirectoryAuditRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Delta appends "/delta" onto the builder
func (b *DirectoryAuditRequestBuilder) Delta() *DirectoryAuditRequestBuilder {
	b.baseUrl = b.baseUrl + "/delta"
	return b
}

// DirectoryAuditRequest is request for DirectoryAudit
type DirectoryAuditRequest struct{ BaseRequest }

// Get performs GET request for DirectoryAudit
func (r *DirectoryAuditRequest) Get(ctx context.Context) (resObj *DirectoryAudit, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for DirectoryAudit
func (r *DirectoryAuditRequest) Update(ctx context.Context, reqObj *DirectoryAudit) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for DirectoryAudit
func (r *DirectoryAuditRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
