// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DiscoverySource undocumented
type DiscoverySource string

const (
	// DiscoverySourceVUnknown undocumented
	DiscoverySourceVUnknown DiscoverySource = "Unknown"
	// DiscoverySourceVAdminImport undocumented
	DiscoverySourceVAdminImport DiscoverySource = "AdminImport"
	// DiscoverySourceVDeviceEnrollmentProgram undocumented
	DiscoverySourceVDeviceEnrollmentProgram DiscoverySource = "DeviceEnrollmentProgram"
)

// DiscoverySourcePUnknown returns a pointer to DiscoverySourceVUnknown
func DiscoverySourcePUnknown() *DiscoverySource {
	v := DiscoverySourceVUnknown
	return &v
}

// DiscoverySourcePAdminImport returns a pointer to DiscoverySourceVAdminImport
func DiscoverySourcePAdminImport() *DiscoverySource {
	v := DiscoverySourceVAdminImport
	return &v
}

// DiscoverySourcePDeviceEnrollmentProgram returns a pointer to DiscoverySourceVDeviceEnrollmentProgram
func DiscoverySourcePDeviceEnrollmentProgram() *DiscoverySource {
	v := DiscoverySourceVDeviceEnrollmentProgram
	return &v
}
