// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DiskType undocumented
type DiskType string

const (
	// DiskTypeVUnkown undocumented
	DiskTypeVUnkown DiskType = "Unkown"
	// DiskTypeVHdd undocumented
	DiskTypeVHdd DiskType = "Hdd"
	// DiskTypeVSsd undocumented
	DiskTypeVSsd DiskType = "Ssd"
)

// DiskTypePUnkown returns a pointer to DiskTypeVUnkown
func DiskTypePUnkown() *DiskType {
	v := DiskTypeVUnkown
	return &v
}

// DiskTypePHdd returns a pointer to DiskTypeVHdd
func DiskTypePHdd() *DiskType {
	v := DiskTypeVHdd
	return &v
}

// DiskTypePSsd returns a pointer to DiskTypeVSsd
func DiskTypePSsd() *DiskType {
	v := DiskTypeVSsd
	return &v
}
