// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// EasAuthenticationMethod undocumented
type EasAuthenticationMethod string

const (
	// EasAuthenticationMethodVUsernameAndPassword undocumented
	EasAuthenticationMethodVUsernameAndPassword EasAuthenticationMethod = "UsernameAndPassword"
	// EasAuthenticationMethodVCertificate undocumented
	EasAuthenticationMethodVCertificate EasAuthenticationMethod = "Certificate"
	// EasAuthenticationMethodVDerivedCredential undocumented
	EasAuthenticationMethodVDerivedCredential EasAuthenticationMethod = "DerivedCredential"
)

// EasAuthenticationMethodPUsernameAndPassword returns a pointer to EasAuthenticationMethodVUsernameAndPassword
func EasAuthenticationMethodPUsernameAndPassword() *EasAuthenticationMethod {
	v := EasAuthenticationMethodVUsernameAndPassword
	return &v
}

// EasAuthenticationMethodPCertificate returns a pointer to EasAuthenticationMethodVCertificate
func EasAuthenticationMethodPCertificate() *EasAuthenticationMethod {
	v := EasAuthenticationMethodVCertificate
	return &v
}

// EasAuthenticationMethodPDerivedCredential returns a pointer to EasAuthenticationMethodVDerivedCredential
func EasAuthenticationMethodPDerivedCredential() *EasAuthenticationMethod {
	v := EasAuthenticationMethodVDerivedCredential
	return &v
}
