// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// EdgeOpenOptions undocumented
type EdgeOpenOptions string

const (
	// EdgeOpenOptionsVNotConfigured undocumented
	EdgeOpenOptionsVNotConfigured EdgeOpenOptions = "NotConfigured"
	// EdgeOpenOptionsVStartPage undocumented
	EdgeOpenOptionsVStartPage EdgeOpenOptions = "StartPage"
	// EdgeOpenOptionsVNewTabPage undocumented
	EdgeOpenOptionsVNewTabPage EdgeOpenOptions = "NewTabPage"
	// EdgeOpenOptionsVPreviousPages undocumented
	EdgeOpenOptionsVPreviousPages EdgeOpenOptions = "PreviousPages"
	// EdgeOpenOptionsVSpecificPages undocumented
	EdgeOpenOptionsVSpecificPages EdgeOpenOptions = "SpecificPages"
)

// EdgeOpenOptionsPNotConfigured returns a pointer to EdgeOpenOptionsVNotConfigured
func EdgeOpenOptionsPNotConfigured() *EdgeOpenOptions {
	v := EdgeOpenOptionsVNotConfigured
	return &v
}

// EdgeOpenOptionsPStartPage returns a pointer to EdgeOpenOptionsVStartPage
func EdgeOpenOptionsPStartPage() *EdgeOpenOptions {
	v := EdgeOpenOptionsVStartPage
	return &v
}

// EdgeOpenOptionsPNewTabPage returns a pointer to EdgeOpenOptionsVNewTabPage
func EdgeOpenOptionsPNewTabPage() *EdgeOpenOptions {
	v := EdgeOpenOptionsVNewTabPage
	return &v
}

// EdgeOpenOptionsPPreviousPages returns a pointer to EdgeOpenOptionsVPreviousPages
func EdgeOpenOptionsPPreviousPages() *EdgeOpenOptions {
	v := EdgeOpenOptionsVPreviousPages
	return &v
}

// EdgeOpenOptionsPSpecificPages returns a pointer to EdgeOpenOptionsVSpecificPages
func EdgeOpenOptionsPSpecificPages() *EdgeOpenOptions {
	v := EdgeOpenOptionsVSpecificPages
	return &v
}
