// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// EdgeTelemetryMode undocumented
type EdgeTelemetryMode string

const (
	// EdgeTelemetryModeVNotConfigured undocumented
	EdgeTelemetryModeVNotConfigured EdgeTelemetryMode = "NotConfigured"
	// EdgeTelemetryModeVIntranet undocumented
	EdgeTelemetryModeVIntranet EdgeTelemetryMode = "Intranet"
	// EdgeTelemetryModeVInternet undocumented
	EdgeTelemetryModeVInternet EdgeTelemetryMode = "Internet"
	// EdgeTelemetryModeVIntranetAndInternet undocumented
	EdgeTelemetryModeVIntranetAndInternet EdgeTelemetryMode = "IntranetAndInternet"
)

// EdgeTelemetryModePNotConfigured returns a pointer to EdgeTelemetryModeVNotConfigured
func EdgeTelemetryModePNotConfigured() *EdgeTelemetryMode {
	v := EdgeTelemetryModeVNotConfigured
	return &v
}

// EdgeTelemetryModePIntranet returns a pointer to EdgeTelemetryModeVIntranet
func EdgeTelemetryModePIntranet() *EdgeTelemetryMode {
	v := EdgeTelemetryModeVIntranet
	return &v
}

// EdgeTelemetryModePInternet returns a pointer to EdgeTelemetryModeVInternet
func EdgeTelemetryModePInternet() *EdgeTelemetryMode {
	v := EdgeTelemetryModeVInternet
	return &v
}

// EdgeTelemetryModePIntranetAndInternet returns a pointer to EdgeTelemetryModeVIntranetAndInternet
func EdgeTelemetryModePIntranetAndInternet() *EdgeTelemetryMode {
	v := EdgeTelemetryModeVIntranetAndInternet
	return &v
}
