// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// EditionUpgradeLicenseType undocumented
type EditionUpgradeLicenseType string

const (
	// EditionUpgradeLicenseTypeVProductKey undocumented
	EditionUpgradeLicenseTypeVProductKey EditionUpgradeLicenseType = "ProductKey"
	// EditionUpgradeLicenseTypeVLicenseFile undocumented
	EditionUpgradeLicenseTypeVLicenseFile EditionUpgradeLicenseType = "LicenseFile"
	// EditionUpgradeLicenseTypeVNotConfigured undocumented
	EditionUpgradeLicenseTypeVNotConfigured EditionUpgradeLicenseType = "NotConfigured"
)

// EditionUpgradeLicenseTypePProductKey returns a pointer to EditionUpgradeLicenseTypeVProductKey
func EditionUpgradeLicenseTypePProductKey() *EditionUpgradeLicenseType {
	v := EditionUpgradeLicenseTypeVProductKey
	return &v
}

// EditionUpgradeLicenseTypePLicenseFile returns a pointer to EditionUpgradeLicenseTypeVLicenseFile
func EditionUpgradeLicenseTypePLicenseFile() *EditionUpgradeLicenseType {
	v := EditionUpgradeLicenseTypeVLicenseFile
	return &v
}

// EditionUpgradeLicenseTypePNotConfigured returns a pointer to EditionUpgradeLicenseTypeVNotConfigured
func EditionUpgradeLicenseTypePNotConfigured() *EditionUpgradeLicenseType {
	v := EditionUpgradeLicenseTypeVNotConfigured
	return &v
}
