// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// EducationSynchronizationStatus undocumented
type EducationSynchronizationStatus string

const (
	// EducationSynchronizationStatusVPaused undocumented
	EducationSynchronizationStatusVPaused EducationSynchronizationStatus = "Paused"
	// EducationSynchronizationStatusVInProgress undocumented
	EducationSynchronizationStatusVInProgress EducationSynchronizationStatus = "InProgress"
	// EducationSynchronizationStatusVSuccess undocumented
	EducationSynchronizationStatusVSuccess EducationSynchronizationStatus = "Success"
	// EducationSynchronizationStatusVError undocumented
	EducationSynchronizationStatusVError EducationSynchronizationStatus = "Error"
	// EducationSynchronizationStatusVValidationError undocumented
	EducationSynchronizationStatusVValidationError EducationSynchronizationStatus = "ValidationError"
	// EducationSynchronizationStatusVQuarantined undocumented
	EducationSynchronizationStatusVQuarantined EducationSynchronizationStatus = "Quarantined"
	// EducationSynchronizationStatusVUnknownFutureValue undocumented
	EducationSynchronizationStatusVUnknownFutureValue EducationSynchronizationStatus = "UnknownFutureValue"
)

// EducationSynchronizationStatusPPaused returns a pointer to EducationSynchronizationStatusVPaused
func EducationSynchronizationStatusPPaused() *EducationSynchronizationStatus {
	v := EducationSynchronizationStatusVPaused
	return &v
}

// EducationSynchronizationStatusPInProgress returns a pointer to EducationSynchronizationStatusVInProgress
func EducationSynchronizationStatusPInProgress() *EducationSynchronizationStatus {
	v := EducationSynchronizationStatusVInProgress
	return &v
}

// EducationSynchronizationStatusPSuccess returns a pointer to EducationSynchronizationStatusVSuccess
func EducationSynchronizationStatusPSuccess() *EducationSynchronizationStatus {
	v := EducationSynchronizationStatusVSuccess
	return &v
}

// EducationSynchronizationStatusPError returns a pointer to EducationSynchronizationStatusVError
func EducationSynchronizationStatusPError() *EducationSynchronizationStatus {
	v := EducationSynchronizationStatusVError
	return &v
}

// EducationSynchronizationStatusPValidationError returns a pointer to EducationSynchronizationStatusVValidationError
func EducationSynchronizationStatusPValidationError() *EducationSynchronizationStatus {
	v := EducationSynchronizationStatusVValidationError
	return &v
}

// EducationSynchronizationStatusPQuarantined returns a pointer to EducationSynchronizationStatusVQuarantined
func EducationSynchronizationStatusPQuarantined() *EducationSynchronizationStatus {
	v := EducationSynchronizationStatusVQuarantined
	return &v
}

// EducationSynchronizationStatusPUnknownFutureValue returns a pointer to EducationSynchronizationStatusVUnknownFutureValue
func EducationSynchronizationStatusPUnknownFutureValue() *EducationSynchronizationStatus {
	v := EducationSynchronizationStatusVUnknownFutureValue
	return &v
}
