// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// EducationSubmissionStatus undocumented
type EducationSubmissionStatus string

const (
	// EducationSubmissionStatusVWorking undocumented
	EducationSubmissionStatusVWorking EducationSubmissionStatus = "Working"
	// EducationSubmissionStatusVSubmitted undocumented
	EducationSubmissionStatusVSubmitted EducationSubmissionStatus = "Submitted"
	// EducationSubmissionStatusVReleased undocumented
	EducationSubmissionStatusVReleased EducationSubmissionStatus = "Released"
	// EducationSubmissionStatusVReturned undocumented
	EducationSubmissionStatusVReturned EducationSubmissionStatus = "Returned"
	// EducationSubmissionStatusVUnknownFutureValue undocumented
	EducationSubmissionStatusVUnknownFutureValue EducationSubmissionStatus = "UnknownFutureValue"
)

// EducationSubmissionStatusPWorking returns a pointer to EducationSubmissionStatusVWorking
func EducationSubmissionStatusPWorking() *EducationSubmissionStatus {
	v := EducationSubmissionStatusVWorking
	return &v
}

// EducationSubmissionStatusPSubmitted returns a pointer to EducationSubmissionStatusVSubmitted
func EducationSubmissionStatusPSubmitted() *EducationSubmissionStatus {
	v := EducationSubmissionStatusVSubmitted
	return &v
}

// EducationSubmissionStatusPReleased returns a pointer to EducationSubmissionStatusVReleased
func EducationSubmissionStatusPReleased() *EducationSubmissionStatus {
	v := EducationSubmissionStatusVReleased
	return &v
}

// EducationSubmissionStatusPReturned returns a pointer to EducationSubmissionStatusVReturned
func EducationSubmissionStatusPReturned() *EducationSubmissionStatus {
	v := EducationSubmissionStatusVReturned
	return &v
}

// EducationSubmissionStatusPUnknownFutureValue returns a pointer to EducationSubmissionStatusVUnknownFutureValue
func EducationSubmissionStatusPUnknownFutureValue() *EducationSubmissionStatus {
	v := EducationSubmissionStatusVUnknownFutureValue
	return &v
}
