// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// EmailSyncDuration undocumented
type EmailSyncDuration string

const (
	// EmailSyncDurationVUserDefined undocumented
	EmailSyncDurationVUserDefined EmailSyncDuration = "UserDefined"
	// EmailSyncDurationVOneDay undocumented
	EmailSyncDurationVOneDay EmailSyncDuration = "OneDay"
	// EmailSyncDurationVThreeDays undocumented
	EmailSyncDurationVThreeDays EmailSyncDuration = "ThreeDays"
	// EmailSyncDurationVOneWeek undocumented
	EmailSyncDurationVOneWeek EmailSyncDuration = "OneWeek"
	// EmailSyncDurationVTwoWeeks undocumented
	EmailSyncDurationVTwoWeeks EmailSyncDuration = "TwoWeeks"
	// EmailSyncDurationVOneMonth undocumented
	EmailSyncDurationVOneMonth EmailSyncDuration = "OneMonth"
	// EmailSyncDurationVUnlimited undocumented
	EmailSyncDurationVUnlimited EmailSyncDuration = "Unlimited"
)

// EmailSyncDurationPUserDefined returns a pointer to EmailSyncDurationVUserDefined
func EmailSyncDurationPUserDefined() *EmailSyncDuration {
	v := EmailSyncDurationVUserDefined
	return &v
}

// EmailSyncDurationPOneDay returns a pointer to EmailSyncDurationVOneDay
func EmailSyncDurationPOneDay() *EmailSyncDuration {
	v := EmailSyncDurationVOneDay
	return &v
}

// EmailSyncDurationPThreeDays returns a pointer to EmailSyncDurationVThreeDays
func EmailSyncDurationPThreeDays() *EmailSyncDuration {
	v := EmailSyncDurationVThreeDays
	return &v
}

// EmailSyncDurationPOneWeek returns a pointer to EmailSyncDurationVOneWeek
func EmailSyncDurationPOneWeek() *EmailSyncDuration {
	v := EmailSyncDurationVOneWeek
	return &v
}

// EmailSyncDurationPTwoWeeks returns a pointer to EmailSyncDurationVTwoWeeks
func EmailSyncDurationPTwoWeeks() *EmailSyncDuration {
	v := EmailSyncDurationVTwoWeeks
	return &v
}

// EmailSyncDurationPOneMonth returns a pointer to EmailSyncDurationVOneMonth
func EmailSyncDurationPOneMonth() *EmailSyncDuration {
	v := EmailSyncDurationVOneMonth
	return &v
}

// EmailSyncDurationPUnlimited returns a pointer to EmailSyncDurationVUnlimited
func EmailSyncDurationPUnlimited() *EmailSyncDuration {
	v := EmailSyncDurationVUnlimited
	return &v
}
