// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// EncryptionReadinessState undocumented
type EncryptionReadinessState string

const (
	// EncryptionReadinessStateVNotReady undocumented
	EncryptionReadinessStateVNotReady EncryptionReadinessState = "NotReady"
	// EncryptionReadinessStateVReady undocumented
	EncryptionReadinessStateVReady EncryptionReadinessState = "Ready"
)

// EncryptionReadinessStatePNotReady returns a pointer to EncryptionReadinessStateVNotReady
func EncryptionReadinessStatePNotReady() *EncryptionReadinessState {
	v := EncryptionReadinessStateVNotReady
	return &v
}

// EncryptionReadinessStatePReady returns a pointer to EncryptionReadinessStateVReady
func EncryptionReadinessStatePReady() *EncryptionReadinessState {
	v := EncryptionReadinessStateVReady
	return &v
}
