// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// EncryptWith undocumented
type EncryptWith string

const (
	// EncryptWithVTemplate undocumented
	EncryptWithVTemplate EncryptWith = "Template"
	// EncryptWithVUserDefinedRights undocumented
	EncryptWithVUserDefinedRights EncryptWith = "UserDefinedRights"
)

// EncryptWithPTemplate returns a pointer to EncryptWithVTemplate
func EncryptWithPTemplate() *EncryptWith {
	v := EncryptWithVTemplate
	return &v
}

// EncryptWithPUserDefinedRights returns a pointer to EncryptWithVUserDefinedRights
func EncryptWithPUserDefinedRights() *EncryptWith {
	v := EncryptWithVUserDefinedRights
	return &v
}
