// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// EntityType undocumented
type EntityType string

const (
	// EntityTypeVEvent undocumented
	EntityTypeVEvent EntityType = "Event"
	// EntityTypeVMessage undocumented
	EntityTypeVMessage EntityType = "Message"
	// EntityTypeVDriveItem undocumented
	EntityTypeVDriveItem EntityType = "DriveItem"
	// EntityTypeVExternalFile undocumented
	EntityTypeVExternalFile EntityType = "ExternalFile"
	// EntityTypeVExternalItem undocumented
	EntityTypeVExternalItem EntityType = "ExternalItem"
)

// EntityTypePEvent returns a pointer to EntityTypeVEvent
func EntityTypePEvent() *EntityType {
	v := EntityTypeVEvent
	return &v
}

// EntityTypePMessage returns a pointer to EntityTypeVMessage
func EntityTypePMessage() *EntityType {
	v := EntityTypeVMessage
	return &v
}

// EntityTypePDriveItem returns a pointer to EntityTypeVDriveItem
func EntityTypePDriveItem() *EntityType {
	v := EntityTypeVDriveItem
	return &v
}

// EntityTypePExternalFile returns a pointer to EntityTypeVExternalFile
func EntityTypePExternalFile() *EntityType {
	v := EntityTypeVExternalFile
	return &v
}

// EntityTypePExternalItem returns a pointer to EntityTypeVExternalItem
func EntityTypePExternalItem() *EntityType {
	v := EntityTypeVExternalItem
	return &v
}
