// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// EntryExportStatus undocumented
type EntryExportStatus string

const (
	// EntryExportStatusVNoop undocumented
	EntryExportStatusVNoop EntryExportStatus = "Noop"
	// EntryExportStatusVSuccess undocumented
	EntryExportStatusVSuccess EntryExportStatus = "Success"
	// EntryExportStatusVRetryableError undocumented
	EntryExportStatusVRetryableError EntryExportStatus = "RetryableError"
	// EntryExportStatusVPermanentError undocumented
	EntryExportStatusVPermanentError EntryExportStatus = "PermanentError"
	// EntryExportStatusVError undocumented
	EntryExportStatusVError EntryExportStatus = "Error"
)

// EntryExportStatusPNoop returns a pointer to EntryExportStatusVNoop
func EntryExportStatusPNoop() *EntryExportStatus {
	v := EntryExportStatusVNoop
	return &v
}

// EntryExportStatusPSuccess returns a pointer to EntryExportStatusVSuccess
func EntryExportStatusPSuccess() *EntryExportStatus {
	v := EntryExportStatusVSuccess
	return &v
}

// EntryExportStatusPRetryableError returns a pointer to EntryExportStatusVRetryableError
func EntryExportStatusPRetryableError() *EntryExportStatus {
	v := EntryExportStatusVRetryableError
	return &v
}

// EntryExportStatusPPermanentError returns a pointer to EntryExportStatusVPermanentError
func EntryExportStatusPPermanentError() *EntryExportStatus {
	v := EntryExportStatusVPermanentError
	return &v
}

// EntryExportStatusPError returns a pointer to EntryExportStatusVError
func EntryExportStatusPError() *EntryExportStatus {
	v := EntryExportStatusVError
	return &v
}
