// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ErrorCode undocumented
type ErrorCode string

const (
	// ErrorCodeVNoError undocumented
	ErrorCodeVNoError ErrorCode = "NoError"
	// ErrorCodeVUnauthorized undocumented
	ErrorCodeVUnauthorized ErrorCode = "Unauthorized"
	// ErrorCodeVNotFound undocumented
	ErrorCodeVNotFound ErrorCode = "NotFound"
	// ErrorCodeVDeleted undocumented
	ErrorCodeVDeleted ErrorCode = "Deleted"
)

// ErrorCodePNoError returns a pointer to ErrorCodeVNoError
func ErrorCodePNoError() *ErrorCode {
	v := ErrorCodeVNoError
	return &v
}

// ErrorCodePUnauthorized returns a pointer to ErrorCodeVUnauthorized
func ErrorCodePUnauthorized() *ErrorCode {
	v := ErrorCodeVUnauthorized
	return &v
}

// ErrorCodePNotFound returns a pointer to ErrorCodeVNotFound
func ErrorCodePNotFound() *ErrorCode {
	v := ErrorCodeVNotFound
	return &v
}

// ErrorCodePDeleted returns a pointer to ErrorCodeVDeleted
func ErrorCodePDeleted() *ErrorCode {
	v := ErrorCodeVDeleted
	return &v
}
