// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// FeatureType undocumented
type FeatureType string

const (
	// FeatureTypeVRegistration undocumented
	FeatureTypeVRegistration FeatureType = "Registration"
	// FeatureTypeVReset undocumented
	FeatureTypeVReset FeatureType = "Reset"
	// FeatureTypeVUnknownFutureValue undocumented
	FeatureTypeVUnknownFutureValue FeatureType = "UnknownFutureValue"
)

// FeatureTypePRegistration returns a pointer to FeatureTypeVRegistration
func FeatureTypePRegistration() *FeatureType {
	v := FeatureTypeVRegistration
	return &v
}

// FeatureTypePReset returns a pointer to FeatureTypeVReset
func FeatureTypePReset() *FeatureType {
	v := FeatureTypeVReset
	return &v
}

// FeatureTypePUnknownFutureValue returns a pointer to FeatureTypeVUnknownFutureValue
func FeatureTypePUnknownFutureValue() *FeatureType {
	v := FeatureTypeVUnknownFutureValue
	return &v
}
