// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// FreeBusyStatus undocumented
type FreeBusyStatus string

const (
	// FreeBusyStatusVFree undocumented
	FreeBusyStatusVFree FreeBusyStatus = "Free"
	// FreeBusyStatusVTentative undocumented
	FreeBusyStatusVTentative FreeBusyStatus = "Tentative"
	// FreeBusyStatusVBusy undocumented
	FreeBusyStatusVBusy FreeBusyStatus = "Busy"
	// FreeBusyStatusVOof undocumented
	FreeBusyStatusVOof FreeBusyStatus = "Oof"
	// FreeBusyStatusVWorkingElsewhere undocumented
	FreeBusyStatusVWorkingElsewhere FreeBusyStatus = "WorkingElsewhere"
	// FreeBusyStatusVUnknown undocumented
	FreeBusyStatusVUnknown FreeBusyStatus = "Unknown"
)

// FreeBusyStatusPFree returns a pointer to FreeBusyStatusVFree
func FreeBusyStatusPFree() *FreeBusyStatus {
	v := FreeBusyStatusVFree
	return &v
}

// FreeBusyStatusPTentative returns a pointer to FreeBusyStatusVTentative
func FreeBusyStatusPTentative() *FreeBusyStatus {
	v := FreeBusyStatusVTentative
	return &v
}

// FreeBusyStatusPBusy returns a pointer to FreeBusyStatusVBusy
func FreeBusyStatusPBusy() *FreeBusyStatus {
	v := FreeBusyStatusVBusy
	return &v
}

// FreeBusyStatusPOof returns a pointer to FreeBusyStatusVOof
func FreeBusyStatusPOof() *FreeBusyStatus {
	v := FreeBusyStatusVOof
	return &v
}

// FreeBusyStatusPWorkingElsewhere returns a pointer to FreeBusyStatusVWorkingElsewhere
func FreeBusyStatusPWorkingElsewhere() *FreeBusyStatus {
	v := FreeBusyStatusVWorkingElsewhere
	return &v
}

// FreeBusyStatusPUnknown returns a pointer to FreeBusyStatusVUnknown
func FreeBusyStatusPUnknown() *FreeBusyStatus {
	v := FreeBusyStatusVUnknown
	return &v
}
