// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// GroupPolicySettingScope undocumented
type GroupPolicySettingScope string

const (
	// GroupPolicySettingScopeVUnknown undocumented
	GroupPolicySettingScopeVUnknown GroupPolicySettingScope = "Unknown"
	// GroupPolicySettingScopeVDevice undocumented
	GroupPolicySettingScopeVDevice GroupPolicySettingScope = "Device"
	// GroupPolicySettingScopeVUser undocumented
	GroupPolicySettingScopeVUser GroupPolicySettingScope = "User"
)

// GroupPolicySettingScopePUnknown returns a pointer to GroupPolicySettingScopeVUnknown
func GroupPolicySettingScopePUnknown() *GroupPolicySettingScope {
	v := GroupPolicySettingScopeVUnknown
	return &v
}

// GroupPolicySettingScopePDevice returns a pointer to GroupPolicySettingScopeVDevice
func GroupPolicySettingScopePDevice() *GroupPolicySettingScope {
	v := GroupPolicySettingScopeVDevice
	return &v
}

// GroupPolicySettingScopePUser returns a pointer to GroupPolicySettingScopeVUser
func GroupPolicySettingScopePUser() *GroupPolicySettingScope {
	v := GroupPolicySettingScopeVUser
	return &v
}
