// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// GroupPolicyConfigurationType undocumented
type GroupPolicyConfigurationType string

const (
	// GroupPolicyConfigurationTypeVPolicy undocumented
	GroupPolicyConfigurationTypeVPolicy GroupPolicyConfigurationType = "Policy"
	// GroupPolicyConfigurationTypeVPreference undocumented
	GroupPolicyConfigurationTypeVPreference GroupPolicyConfigurationType = "Preference"
)

// GroupPolicyConfigurationTypePPolicy returns a pointer to GroupPolicyConfigurationTypeVPolicy
func GroupPolicyConfigurationTypePPolicy() *GroupPolicyConfigurationType {
	v := GroupPolicyConfigurationTypeVPolicy
	return &v
}

// GroupPolicyConfigurationTypePPreference returns a pointer to GroupPolicyConfigurationTypeVPreference
func GroupPolicyConfigurationTypePPreference() *GroupPolicyConfigurationType {
	v := GroupPolicyConfigurationTypeVPreference
	return &v
}
