// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// GroupAccessType undocumented
type GroupAccessType string

const (
	// GroupAccessTypeVNone undocumented
	GroupAccessTypeVNone GroupAccessType = "None"
	// GroupAccessTypeVPrivate undocumented
	GroupAccessTypeVPrivate GroupAccessType = "Private"
	// GroupAccessTypeVSecret undocumented
	GroupAccessTypeVSecret GroupAccessType = "Secret"
	// GroupAccessTypeVPublic undocumented
	GroupAccessTypeVPublic GroupAccessType = "Public"
)

// GroupAccessTypePNone returns a pointer to GroupAccessTypeVNone
func GroupAccessTypePNone() *GroupAccessType {
	v := GroupAccessTypeVNone
	return &v
}

// GroupAccessTypePPrivate returns a pointer to GroupAccessTypeVPrivate
func GroupAccessTypePPrivate() *GroupAccessType {
	v := GroupAccessTypeVPrivate
	return &v
}

// GroupAccessTypePSecret returns a pointer to GroupAccessTypeVSecret
func GroupAccessTypePSecret() *GroupAccessType {
	v := GroupAccessTypeVSecret
	return &v
}

// GroupAccessTypePPublic returns a pointer to GroupAccessTypeVPublic
func GroupAccessTypePPublic() *GroupAccessType {
	v := GroupAccessTypeVPublic
	return &v
}
