// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// InitiatorType undocumented
type InitiatorType string

const (
	// InitiatorTypeVUser undocumented
	InitiatorTypeVUser InitiatorType = "User"
	// InitiatorTypeVApp undocumented
	InitiatorTypeVApp InitiatorType = "App"
	// InitiatorTypeVSystem undocumented
	InitiatorTypeVSystem InitiatorType = "System"
	// InitiatorTypeVUnknownFutureValue undocumented
	InitiatorTypeVUnknownFutureValue InitiatorType = "UnknownFutureValue"
)

// InitiatorTypePUser returns a pointer to InitiatorTypeVUser
func InitiatorTypePUser() *InitiatorType {
	v := InitiatorTypeVUser
	return &v
}

// InitiatorTypePApp returns a pointer to InitiatorTypeVApp
func InitiatorTypePApp() *InitiatorType {
	v := InitiatorTypeVApp
	return &v
}

// InitiatorTypePSystem returns a pointer to InitiatorTypeVSystem
func InitiatorTypePSystem() *InitiatorType {
	v := InitiatorTypeVSystem
	return &v
}

// InitiatorTypePUnknownFutureValue returns a pointer to InitiatorTypeVUnknownFutureValue
func InitiatorTypePUnknownFutureValue() *InitiatorType {
	v := InitiatorTypeVUnknownFutureValue
	return &v
}
