// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// InstallIntent undocumented
type InstallIntent string

const (
	// InstallIntentVAvailable undocumented
	InstallIntentVAvailable InstallIntent = "Available"
	// InstallIntentVRequired undocumented
	InstallIntentVRequired InstallIntent = "Required"
	// InstallIntentVUninstall undocumented
	InstallIntentVUninstall InstallIntent = "Uninstall"
	// InstallIntentVAvailableWithoutEnrollment undocumented
	InstallIntentVAvailableWithoutEnrollment InstallIntent = "AvailableWithoutEnrollment"
)

// InstallIntentPAvailable returns a pointer to InstallIntentVAvailable
func InstallIntentPAvailable() *InstallIntent {
	v := InstallIntentVAvailable
	return &v
}

// InstallIntentPRequired returns a pointer to InstallIntentVRequired
func InstallIntentPRequired() *InstallIntent {
	v := InstallIntentVRequired
	return &v
}

// InstallIntentPUninstall returns a pointer to InstallIntentVUninstall
func InstallIntentPUninstall() *InstallIntent {
	v := InstallIntentVUninstall
	return &v
}

// InstallIntentPAvailableWithoutEnrollment returns a pointer to InstallIntentVAvailableWithoutEnrollment
func InstallIntentPAvailableWithoutEnrollment() *InstallIntent {
	v := InstallIntentVAvailableWithoutEnrollment
	return &v
}
