// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// IntendedPurpose undocumented
type IntendedPurpose string

const (
	// IntendedPurposeVUnassigned undocumented
	IntendedPurposeVUnassigned IntendedPurpose = "Unassigned"
	// IntendedPurposeVSmimeEncryption undocumented
	IntendedPurposeVSmimeEncryption IntendedPurpose = "SmimeEncryption"
	// IntendedPurposeVSmimeSigning undocumented
	IntendedPurposeVSmimeSigning IntendedPurpose = "SmimeSigning"
	// IntendedPurposeVVpn undocumented
	IntendedPurposeVVpn IntendedPurpose = "Vpn"
	// IntendedPurposeVWifi undocumented
	IntendedPurposeVWifi IntendedPurpose = "Wifi"
)

// IntendedPurposePUnassigned returns a pointer to IntendedPurposeVUnassigned
func IntendedPurposePUnassigned() *IntendedPurpose {
	v := IntendedPurposeVUnassigned
	return &v
}

// IntendedPurposePSmimeEncryption returns a pointer to IntendedPurposeVSmimeEncryption
func IntendedPurposePSmimeEncryption() *IntendedPurpose {
	v := IntendedPurposeVSmimeEncryption
	return &v
}

// IntendedPurposePSmimeSigning returns a pointer to IntendedPurposeVSmimeSigning
func IntendedPurposePSmimeSigning() *IntendedPurpose {
	v := IntendedPurposeVSmimeSigning
	return &v
}

// IntendedPurposePVpn returns a pointer to IntendedPurposeVVpn
func IntendedPurposePVpn() *IntendedPurpose {
	v := IntendedPurposeVVpn
	return &v
}

// IntendedPurposePWifi returns a pointer to IntendedPurposeVWifi
func IntendedPurposePWifi() *IntendedPurpose {
	v := IntendedPurposeVWifi
	return &v
}
