// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// InternetExplorerMessageSetting undocumented
type InternetExplorerMessageSetting string

const (
	// InternetExplorerMessageSettingVNotConfigured undocumented
	InternetExplorerMessageSettingVNotConfigured InternetExplorerMessageSetting = "NotConfigured"
	// InternetExplorerMessageSettingVDisabled undocumented
	InternetExplorerMessageSettingVDisabled InternetExplorerMessageSetting = "Disabled"
	// InternetExplorerMessageSettingVEnabled undocumented
	InternetExplorerMessageSettingVEnabled InternetExplorerMessageSetting = "Enabled"
	// InternetExplorerMessageSettingVKeepGoing undocumented
	InternetExplorerMessageSettingVKeepGoing InternetExplorerMessageSetting = "KeepGoing"
)

// InternetExplorerMessageSettingPNotConfigured returns a pointer to InternetExplorerMessageSettingVNotConfigured
func InternetExplorerMessageSettingPNotConfigured() *InternetExplorerMessageSetting {
	v := InternetExplorerMessageSettingVNotConfigured
	return &v
}

// InternetExplorerMessageSettingPDisabled returns a pointer to InternetExplorerMessageSettingVDisabled
func InternetExplorerMessageSettingPDisabled() *InternetExplorerMessageSetting {
	v := InternetExplorerMessageSettingVDisabled
	return &v
}

// InternetExplorerMessageSettingPEnabled returns a pointer to InternetExplorerMessageSettingVEnabled
func InternetExplorerMessageSettingPEnabled() *InternetExplorerMessageSetting {
	v := InternetExplorerMessageSettingVEnabled
	return &v
}

// InternetExplorerMessageSettingPKeepGoing returns a pointer to InternetExplorerMessageSettingVKeepGoing
func InternetExplorerMessageSettingPKeepGoing() *InternetExplorerMessageSetting {
	v := InternetExplorerMessageSettingVKeepGoing
	return &v
}
