// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// IOSUpdatesInstallStatus undocumented
type IOSUpdatesInstallStatus string

const (
	// IOSUpdatesInstallStatusVSuccess undocumented
	IOSUpdatesInstallStatusVSuccess IOSUpdatesInstallStatus = "Success"
	// IOSUpdatesInstallStatusVAvailable undocumented
	IOSUpdatesInstallStatusVAvailable IOSUpdatesInstallStatus = "Available"
	// IOSUpdatesInstallStatusVIdle undocumented
	IOSUpdatesInstallStatusVIdle IOSUpdatesInstallStatus = "Idle"
	// IOSUpdatesInstallStatusVUnknown undocumented
	IOSUpdatesInstallStatusVUnknown IOSUpdatesInstallStatus = "Unknown"
	// IOSUpdatesInstallStatusVDownloading undocumented
	IOSUpdatesInstallStatusVDownloading IOSUpdatesInstallStatus = "Downloading"
	// IOSUpdatesInstallStatusVDownloadFailed undocumented
	IOSUpdatesInstallStatusVDownloadFailed IOSUpdatesInstallStatus = "DownloadFailed"
	// IOSUpdatesInstallStatusVDownloadRequiresComputer undocumented
	IOSUpdatesInstallStatusVDownloadRequiresComputer IOSUpdatesInstallStatus = "DownloadRequiresComputer"
	// IOSUpdatesInstallStatusVDownloadInsufficientSpace undocumented
	IOSUpdatesInstallStatusVDownloadInsufficientSpace IOSUpdatesInstallStatus = "DownloadInsufficientSpace"
	// IOSUpdatesInstallStatusVDownloadInsufficientPower undocumented
	IOSUpdatesInstallStatusVDownloadInsufficientPower IOSUpdatesInstallStatus = "DownloadInsufficientPower"
	// IOSUpdatesInstallStatusVDownloadInsufficientNetwork undocumented
	IOSUpdatesInstallStatusVDownloadInsufficientNetwork IOSUpdatesInstallStatus = "DownloadInsufficientNetwork"
	// IOSUpdatesInstallStatusVInstalling undocumented
	IOSUpdatesInstallStatusVInstalling IOSUpdatesInstallStatus = "Installing"
	// IOSUpdatesInstallStatusVInstallInsufficientSpace undocumented
	IOSUpdatesInstallStatusVInstallInsufficientSpace IOSUpdatesInstallStatus = "InstallInsufficientSpace"
	// IOSUpdatesInstallStatusVInstallInsufficientPower undocumented
	IOSUpdatesInstallStatusVInstallInsufficientPower IOSUpdatesInstallStatus = "InstallInsufficientPower"
	// IOSUpdatesInstallStatusVInstallPhoneCallInProgress undocumented
	IOSUpdatesInstallStatusVInstallPhoneCallInProgress IOSUpdatesInstallStatus = "InstallPhoneCallInProgress"
	// IOSUpdatesInstallStatusVInstallFailed undocumented
	IOSUpdatesInstallStatusVInstallFailed IOSUpdatesInstallStatus = "InstallFailed"
	// IOSUpdatesInstallStatusVNotSupportedOperation undocumented
	IOSUpdatesInstallStatusVNotSupportedOperation IOSUpdatesInstallStatus = "NotSupportedOperation"
	// IOSUpdatesInstallStatusVSharedDeviceUserLoggedInError undocumented
	IOSUpdatesInstallStatusVSharedDeviceUserLoggedInError IOSUpdatesInstallStatus = "SharedDeviceUserLoggedInError"
)

// IOSUpdatesInstallStatusPSuccess returns a pointer to IOSUpdatesInstallStatusVSuccess
func IOSUpdatesInstallStatusPSuccess() *IOSUpdatesInstallStatus {
	v := IOSUpdatesInstallStatusVSuccess
	return &v
}

// IOSUpdatesInstallStatusPAvailable returns a pointer to IOSUpdatesInstallStatusVAvailable
func IOSUpdatesInstallStatusPAvailable() *IOSUpdatesInstallStatus {
	v := IOSUpdatesInstallStatusVAvailable
	return &v
}

// IOSUpdatesInstallStatusPIdle returns a pointer to IOSUpdatesInstallStatusVIdle
func IOSUpdatesInstallStatusPIdle() *IOSUpdatesInstallStatus {
	v := IOSUpdatesInstallStatusVIdle
	return &v
}

// IOSUpdatesInstallStatusPUnknown returns a pointer to IOSUpdatesInstallStatusVUnknown
func IOSUpdatesInstallStatusPUnknown() *IOSUpdatesInstallStatus {
	v := IOSUpdatesInstallStatusVUnknown
	return &v
}

// IOSUpdatesInstallStatusPDownloading returns a pointer to IOSUpdatesInstallStatusVDownloading
func IOSUpdatesInstallStatusPDownloading() *IOSUpdatesInstallStatus {
	v := IOSUpdatesInstallStatusVDownloading
	return &v
}

// IOSUpdatesInstallStatusPDownloadFailed returns a pointer to IOSUpdatesInstallStatusVDownloadFailed
func IOSUpdatesInstallStatusPDownloadFailed() *IOSUpdatesInstallStatus {
	v := IOSUpdatesInstallStatusVDownloadFailed
	return &v
}

// IOSUpdatesInstallStatusPDownloadRequiresComputer returns a pointer to IOSUpdatesInstallStatusVDownloadRequiresComputer
func IOSUpdatesInstallStatusPDownloadRequiresComputer() *IOSUpdatesInstallStatus {
	v := IOSUpdatesInstallStatusVDownloadRequiresComputer
	return &v
}

// IOSUpdatesInstallStatusPDownloadInsufficientSpace returns a pointer to IOSUpdatesInstallStatusVDownloadInsufficientSpace
func IOSUpdatesInstallStatusPDownloadInsufficientSpace() *IOSUpdatesInstallStatus {
	v := IOSUpdatesInstallStatusVDownloadInsufficientSpace
	return &v
}

// IOSUpdatesInstallStatusPDownloadInsufficientPower returns a pointer to IOSUpdatesInstallStatusVDownloadInsufficientPower
func IOSUpdatesInstallStatusPDownloadInsufficientPower() *IOSUpdatesInstallStatus {
	v := IOSUpdatesInstallStatusVDownloadInsufficientPower
	return &v
}

// IOSUpdatesInstallStatusPDownloadInsufficientNetwork returns a pointer to IOSUpdatesInstallStatusVDownloadInsufficientNetwork
func IOSUpdatesInstallStatusPDownloadInsufficientNetwork() *IOSUpdatesInstallStatus {
	v := IOSUpdatesInstallStatusVDownloadInsufficientNetwork
	return &v
}

// IOSUpdatesInstallStatusPInstalling returns a pointer to IOSUpdatesInstallStatusVInstalling
func IOSUpdatesInstallStatusPInstalling() *IOSUpdatesInstallStatus {
	v := IOSUpdatesInstallStatusVInstalling
	return &v
}

// IOSUpdatesInstallStatusPInstallInsufficientSpace returns a pointer to IOSUpdatesInstallStatusVInstallInsufficientSpace
func IOSUpdatesInstallStatusPInstallInsufficientSpace() *IOSUpdatesInstallStatus {
	v := IOSUpdatesInstallStatusVInstallInsufficientSpace
	return &v
}

// IOSUpdatesInstallStatusPInstallInsufficientPower returns a pointer to IOSUpdatesInstallStatusVInstallInsufficientPower
func IOSUpdatesInstallStatusPInstallInsufficientPower() *IOSUpdatesInstallStatus {
	v := IOSUpdatesInstallStatusVInstallInsufficientPower
	return &v
}

// IOSUpdatesInstallStatusPInstallPhoneCallInProgress returns a pointer to IOSUpdatesInstallStatusVInstallPhoneCallInProgress
func IOSUpdatesInstallStatusPInstallPhoneCallInProgress() *IOSUpdatesInstallStatus {
	v := IOSUpdatesInstallStatusVInstallPhoneCallInProgress
	return &v
}

// IOSUpdatesInstallStatusPInstallFailed returns a pointer to IOSUpdatesInstallStatusVInstallFailed
func IOSUpdatesInstallStatusPInstallFailed() *IOSUpdatesInstallStatus {
	v := IOSUpdatesInstallStatusVInstallFailed
	return &v
}

// IOSUpdatesInstallStatusPNotSupportedOperation returns a pointer to IOSUpdatesInstallStatusVNotSupportedOperation
func IOSUpdatesInstallStatusPNotSupportedOperation() *IOSUpdatesInstallStatus {
	v := IOSUpdatesInstallStatusVNotSupportedOperation
	return &v
}

// IOSUpdatesInstallStatusPSharedDeviceUserLoggedInError returns a pointer to IOSUpdatesInstallStatusVSharedDeviceUserLoggedInError
func IOSUpdatesInstallStatusPSharedDeviceUserLoggedInError() *IOSUpdatesInstallStatus {
	v := IOSUpdatesInstallStatusVSharedDeviceUserLoggedInError
	return &v
}
