// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// IOSWallpaperDisplayLocation undocumented
type IOSWallpaperDisplayLocation string

const (
	// IOSWallpaperDisplayLocationVNotConfigured undocumented
	IOSWallpaperDisplayLocationVNotConfigured IOSWallpaperDisplayLocation = "NotConfigured"
	// IOSWallpaperDisplayLocationVLockScreen undocumented
	IOSWallpaperDisplayLocationVLockScreen IOSWallpaperDisplayLocation = "LockScreen"
	// IOSWallpaperDisplayLocationVHomeScreen undocumented
	IOSWallpaperDisplayLocationVHomeScreen IOSWallpaperDisplayLocation = "HomeScreen"
	// IOSWallpaperDisplayLocationVLockAndHomeScreens undocumented
	IOSWallpaperDisplayLocationVLockAndHomeScreens IOSWallpaperDisplayLocation = "LockAndHomeScreens"
)

// IOSWallpaperDisplayLocationPNotConfigured returns a pointer to IOSWallpaperDisplayLocationVNotConfigured
func IOSWallpaperDisplayLocationPNotConfigured() *IOSWallpaperDisplayLocation {
	v := IOSWallpaperDisplayLocationVNotConfigured
	return &v
}

// IOSWallpaperDisplayLocationPLockScreen returns a pointer to IOSWallpaperDisplayLocationVLockScreen
func IOSWallpaperDisplayLocationPLockScreen() *IOSWallpaperDisplayLocation {
	v := IOSWallpaperDisplayLocationVLockScreen
	return &v
}

// IOSWallpaperDisplayLocationPHomeScreen returns a pointer to IOSWallpaperDisplayLocationVHomeScreen
func IOSWallpaperDisplayLocationPHomeScreen() *IOSWallpaperDisplayLocation {
	v := IOSWallpaperDisplayLocationVHomeScreen
	return &v
}

// IOSWallpaperDisplayLocationPLockAndHomeScreens returns a pointer to IOSWallpaperDisplayLocationVLockAndHomeScreens
func IOSWallpaperDisplayLocationPLockAndHomeScreens() *IOSWallpaperDisplayLocation {
	v := IOSWallpaperDisplayLocationVLockAndHomeScreens
	return &v
}
