// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// KeyUsages undocumented
type KeyUsages string

const (
	// KeyUsagesVKeyEncipherment undocumented
	KeyUsagesVKeyEncipherment KeyUsages = "KeyEncipherment"
	// KeyUsagesVDigitalSignature undocumented
	KeyUsagesVDigitalSignature KeyUsages = "DigitalSignature"
)

// KeyUsagesPKeyEncipherment returns a pointer to KeyUsagesVKeyEncipherment
func KeyUsagesPKeyEncipherment() *KeyUsages {
	v := KeyUsagesVKeyEncipherment
	return &v
}

// KeyUsagesPDigitalSignature returns a pointer to KeyUsagesVDigitalSignature
func KeyUsagesPDigitalSignature() *KeyUsages {
	v := KeyUsagesVDigitalSignature
	return &v
}
