// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// LanManagerAuthenticationLevel undocumented
type LanManagerAuthenticationLevel string

const (
	// LanManagerAuthenticationLevelVLmAndNltm undocumented
	LanManagerAuthenticationLevelVLmAndNltm LanManagerAuthenticationLevel = "LmAndNltm"
	// LanManagerAuthenticationLevelVLmNtlmAndNtlmV2 undocumented
	LanManagerAuthenticationLevelVLmNtlmAndNtlmV2 LanManagerAuthenticationLevel = "LmNtlmAndNtlmV2"
	// LanManagerAuthenticationLevelVLmAndNtlmOnly undocumented
	LanManagerAuthenticationLevelVLmAndNtlmOnly LanManagerAuthenticationLevel = "LmAndNtlmOnly"
	// LanManagerAuthenticationLevelVLmAndNtlmV2 undocumented
	LanManagerAuthenticationLevelVLmAndNtlmV2 LanManagerAuthenticationLevel = "LmAndNtlmV2"
	// LanManagerAuthenticationLevelVLmNtlmV2AndNotLm undocumented
	LanManagerAuthenticationLevelVLmNtlmV2AndNotLm LanManagerAuthenticationLevel = "LmNtlmV2AndNotLm"
	// LanManagerAuthenticationLevelVLmNtlmV2AndNotLmOrNtm undocumented
	LanManagerAuthenticationLevelVLmNtlmV2AndNotLmOrNtm LanManagerAuthenticationLevel = "LmNtlmV2AndNotLmOrNtm"
)

// LanManagerAuthenticationLevelPLmAndNltm returns a pointer to LanManagerAuthenticationLevelVLmAndNltm
func LanManagerAuthenticationLevelPLmAndNltm() *LanManagerAuthenticationLevel {
	v := LanManagerAuthenticationLevelVLmAndNltm
	return &v
}

// LanManagerAuthenticationLevelPLmNtlmAndNtlmV2 returns a pointer to LanManagerAuthenticationLevelVLmNtlmAndNtlmV2
func LanManagerAuthenticationLevelPLmNtlmAndNtlmV2() *LanManagerAuthenticationLevel {
	v := LanManagerAuthenticationLevelVLmNtlmAndNtlmV2
	return &v
}

// LanManagerAuthenticationLevelPLmAndNtlmOnly returns a pointer to LanManagerAuthenticationLevelVLmAndNtlmOnly
func LanManagerAuthenticationLevelPLmAndNtlmOnly() *LanManagerAuthenticationLevel {
	v := LanManagerAuthenticationLevelVLmAndNtlmOnly
	return &v
}

// LanManagerAuthenticationLevelPLmAndNtlmV2 returns a pointer to LanManagerAuthenticationLevelVLmAndNtlmV2
func LanManagerAuthenticationLevelPLmAndNtlmV2() *LanManagerAuthenticationLevel {
	v := LanManagerAuthenticationLevelVLmAndNtlmV2
	return &v
}

// LanManagerAuthenticationLevelPLmNtlmV2AndNotLm returns a pointer to LanManagerAuthenticationLevelVLmNtlmV2AndNotLm
func LanManagerAuthenticationLevelPLmNtlmV2AndNotLm() *LanManagerAuthenticationLevel {
	v := LanManagerAuthenticationLevelVLmNtlmV2AndNotLm
	return &v
}

// LanManagerAuthenticationLevelPLmNtlmV2AndNotLmOrNtm returns a pointer to LanManagerAuthenticationLevelVLmNtlmV2AndNotLmOrNtm
func LanManagerAuthenticationLevelPLmNtlmV2AndNotLmOrNtm() *LanManagerAuthenticationLevel {
	v := LanManagerAuthenticationLevelVLmNtlmV2AndNotLmOrNtm
	return &v
}
