// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// LocationType undocumented
type LocationType string

const (
	// LocationTypeVDefault undocumented
	LocationTypeVDefault LocationType = "Default"
	// LocationTypeVConferenceRoom undocumented
	LocationTypeVConferenceRoom LocationType = "ConferenceRoom"
	// LocationTypeVHomeAddress undocumented
	LocationTypeVHomeAddress LocationType = "HomeAddress"
	// LocationTypeVBusinessAddress undocumented
	LocationTypeVBusinessAddress LocationType = "BusinessAddress"
	// LocationTypeVGeoCoordinates undocumented
	LocationTypeVGeoCoordinates LocationType = "GeoCoordinates"
	// LocationTypeVStreetAddress undocumented
	LocationTypeVStreetAddress LocationType = "StreetAddress"
	// LocationTypeVHotel undocumented
	LocationTypeVHotel LocationType = "Hotel"
	// LocationTypeVRestaurant undocumented
	LocationTypeVRestaurant LocationType = "Restaurant"
	// LocationTypeVLocalBusiness undocumented
	LocationTypeVLocalBusiness LocationType = "LocalBusiness"
	// LocationTypeVPostalAddress undocumented
	LocationTypeVPostalAddress LocationType = "PostalAddress"
)

// LocationTypePDefault returns a pointer to LocationTypeVDefault
func LocationTypePDefault() *LocationType {
	v := LocationTypeVDefault
	return &v
}

// LocationTypePConferenceRoom returns a pointer to LocationTypeVConferenceRoom
func LocationTypePConferenceRoom() *LocationType {
	v := LocationTypeVConferenceRoom
	return &v
}

// LocationTypePHomeAddress returns a pointer to LocationTypeVHomeAddress
func LocationTypePHomeAddress() *LocationType {
	v := LocationTypeVHomeAddress
	return &v
}

// LocationTypePBusinessAddress returns a pointer to LocationTypeVBusinessAddress
func LocationTypePBusinessAddress() *LocationType {
	v := LocationTypeVBusinessAddress
	return &v
}

// LocationTypePGeoCoordinates returns a pointer to LocationTypeVGeoCoordinates
func LocationTypePGeoCoordinates() *LocationType {
	v := LocationTypeVGeoCoordinates
	return &v
}

// LocationTypePStreetAddress returns a pointer to LocationTypeVStreetAddress
func LocationTypePStreetAddress() *LocationType {
	v := LocationTypeVStreetAddress
	return &v
}

// LocationTypePHotel returns a pointer to LocationTypeVHotel
func LocationTypePHotel() *LocationType {
	v := LocationTypeVHotel
	return &v
}

// LocationTypePRestaurant returns a pointer to LocationTypeVRestaurant
func LocationTypePRestaurant() *LocationType {
	v := LocationTypeVRestaurant
	return &v
}

// LocationTypePLocalBusiness returns a pointer to LocationTypeVLocalBusiness
func LocationTypePLocalBusiness() *LocationType {
	v := LocationTypeVLocalBusiness
	return &v
}

// LocationTypePPostalAddress returns a pointer to LocationTypeVPostalAddress
func LocationTypePPostalAddress() *LocationType {
	v := LocationTypeVPostalAddress
	return &v
}
