// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// LocationUniqueIDType undocumented
type LocationUniqueIDType string

const (
	// LocationUniqueIDTypeVUnknown undocumented
	LocationUniqueIDTypeVUnknown LocationUniqueIDType = "Unknown"
	// LocationUniqueIDTypeVLocationStore undocumented
	LocationUniqueIDTypeVLocationStore LocationUniqueIDType = "LocationStore"
	// LocationUniqueIDTypeVDirectory undocumented
	LocationUniqueIDTypeVDirectory LocationUniqueIDType = "Directory"
	// LocationUniqueIDTypeVPrivate undocumented
	LocationUniqueIDTypeVPrivate LocationUniqueIDType = "Private"
	// LocationUniqueIDTypeVBing undocumented
	LocationUniqueIDTypeVBing LocationUniqueIDType = "Bing"
)

// LocationUniqueIDTypePUnknown returns a pointer to LocationUniqueIDTypeVUnknown
func LocationUniqueIDTypePUnknown() *LocationUniqueIDType {
	v := LocationUniqueIDTypeVUnknown
	return &v
}

// LocationUniqueIDTypePLocationStore returns a pointer to LocationUniqueIDTypeVLocationStore
func LocationUniqueIDTypePLocationStore() *LocationUniqueIDType {
	v := LocationUniqueIDTypeVLocationStore
	return &v
}

// LocationUniqueIDTypePDirectory returns a pointer to LocationUniqueIDTypeVDirectory
func LocationUniqueIDTypePDirectory() *LocationUniqueIDType {
	v := LocationUniqueIDTypeVDirectory
	return &v
}

// LocationUniqueIDTypePPrivate returns a pointer to LocationUniqueIDTypeVPrivate
func LocationUniqueIDTypePPrivate() *LocationUniqueIDType {
	v := LocationUniqueIDTypeVPrivate
	return &v
}

// LocationUniqueIDTypePBing returns a pointer to LocationUniqueIDTypeVBing
func LocationUniqueIDTypePBing() *LocationUniqueIDType {
	v := LocationUniqueIDTypeVBing
	return &v
}
