// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// LostModeState undocumented
type LostModeState string

const (
	// LostModeStateVDisabled undocumented
	LostModeStateVDisabled LostModeState = "Disabled"
	// LostModeStateVEnabled undocumented
	LostModeStateVEnabled LostModeState = "Enabled"
)

// LostModeStatePDisabled returns a pointer to LostModeStateVDisabled
func LostModeStatePDisabled() *LostModeState {
	v := LostModeStateVDisabled
	return &v
}

// LostModeStatePEnabled returns a pointer to LostModeStateVEnabled
func LostModeStatePEnabled() *LostModeState {
	v := LostModeStateVEnabled
	return &v
}
