// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ManagedBrowserType undocumented
type ManagedBrowserType string

const (
	// ManagedBrowserTypeVNotConfigured undocumented
	ManagedBrowserTypeVNotConfigured ManagedBrowserType = "NotConfigured"
	// ManagedBrowserTypeVMicrosoftEdge undocumented
	ManagedBrowserTypeVMicrosoftEdge ManagedBrowserType = "MicrosoftEdge"
)

// ManagedBrowserTypePNotConfigured returns a pointer to ManagedBrowserTypeVNotConfigured
func ManagedBrowserTypePNotConfigured() *ManagedBrowserType {
	v := ManagedBrowserTypeVNotConfigured
	return &v
}

// ManagedBrowserTypePMicrosoftEdge returns a pointer to ManagedBrowserTypeVMicrosoftEdge
func ManagedBrowserTypePMicrosoftEdge() *ManagedBrowserType {
	v := ManagedBrowserTypeVMicrosoftEdge
	return &v
}
