// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ManagedAppNotificationRestriction undocumented
type ManagedAppNotificationRestriction string

const (
	// ManagedAppNotificationRestrictionVAllow undocumented
	ManagedAppNotificationRestrictionVAllow ManagedAppNotificationRestriction = "Allow"
	// ManagedAppNotificationRestrictionVBlockOrganizationalData undocumented
	ManagedAppNotificationRestrictionVBlockOrganizationalData ManagedAppNotificationRestriction = "BlockOrganizationalData"
	// ManagedAppNotificationRestrictionVBlock undocumented
	ManagedAppNotificationRestrictionVBlock ManagedAppNotificationRestriction = "Block"
)

// ManagedAppNotificationRestrictionPAllow returns a pointer to ManagedAppNotificationRestrictionVAllow
func ManagedAppNotificationRestrictionPAllow() *ManagedAppNotificationRestriction {
	v := ManagedAppNotificationRestrictionVAllow
	return &v
}

// ManagedAppNotificationRestrictionPBlockOrganizationalData returns a pointer to ManagedAppNotificationRestrictionVBlockOrganizationalData
func ManagedAppNotificationRestrictionPBlockOrganizationalData() *ManagedAppNotificationRestriction {
	v := ManagedAppNotificationRestrictionVBlockOrganizationalData
	return &v
}

// ManagedAppNotificationRestrictionPBlock returns a pointer to ManagedAppNotificationRestrictionVBlock
func ManagedAppNotificationRestrictionPBlock() *ManagedAppNotificationRestriction {
	v := ManagedAppNotificationRestrictionVBlock
	return &v
}
