// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ManagedAppAvailability undocumented
type ManagedAppAvailability string

const (
	// ManagedAppAvailabilityVGlobal undocumented
	ManagedAppAvailabilityVGlobal ManagedAppAvailability = "Global"
	// ManagedAppAvailabilityVLineOfBusiness undocumented
	ManagedAppAvailabilityVLineOfBusiness ManagedAppAvailability = "LineOfBusiness"
)

// ManagedAppAvailabilityPGlobal returns a pointer to ManagedAppAvailabilityVGlobal
func ManagedAppAvailabilityPGlobal() *ManagedAppAvailability {
	v := ManagedAppAvailabilityVGlobal
	return &v
}

// ManagedAppAvailabilityPLineOfBusiness returns a pointer to ManagedAppAvailabilityVLineOfBusiness
func ManagedAppAvailabilityPLineOfBusiness() *ManagedAppAvailability {
	v := ManagedAppAvailabilityVLineOfBusiness
	return &v
}
