// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ManagedDeviceRemoteAction undocumented
type ManagedDeviceRemoteAction string

const (
	// ManagedDeviceRemoteActionVRetire undocumented
	ManagedDeviceRemoteActionVRetire ManagedDeviceRemoteAction = "Retire"
	// ManagedDeviceRemoteActionVDelete undocumented
	ManagedDeviceRemoteActionVDelete ManagedDeviceRemoteAction = "Delete"
	// ManagedDeviceRemoteActionVFullScan undocumented
	ManagedDeviceRemoteActionVFullScan ManagedDeviceRemoteAction = "FullScan"
	// ManagedDeviceRemoteActionVQuickScan undocumented
	ManagedDeviceRemoteActionVQuickScan ManagedDeviceRemoteAction = "QuickScan"
	// ManagedDeviceRemoteActionVSignatureUpdate undocumented
	ManagedDeviceRemoteActionVSignatureUpdate ManagedDeviceRemoteAction = "SignatureUpdate"
	// ManagedDeviceRemoteActionVWipe undocumented
	ManagedDeviceRemoteActionVWipe ManagedDeviceRemoteAction = "Wipe"
	// ManagedDeviceRemoteActionVCustomTextNotification undocumented
	ManagedDeviceRemoteActionVCustomTextNotification ManagedDeviceRemoteAction = "CustomTextNotification"
	// ManagedDeviceRemoteActionVRebootNow undocumented
	ManagedDeviceRemoteActionVRebootNow ManagedDeviceRemoteAction = "RebootNow"
	// ManagedDeviceRemoteActionVSetDeviceName undocumented
	ManagedDeviceRemoteActionVSetDeviceName ManagedDeviceRemoteAction = "SetDeviceName"
)

// ManagedDeviceRemoteActionPRetire returns a pointer to ManagedDeviceRemoteActionVRetire
func ManagedDeviceRemoteActionPRetire() *ManagedDeviceRemoteAction {
	v := ManagedDeviceRemoteActionVRetire
	return &v
}

// ManagedDeviceRemoteActionPDelete returns a pointer to ManagedDeviceRemoteActionVDelete
func ManagedDeviceRemoteActionPDelete() *ManagedDeviceRemoteAction {
	v := ManagedDeviceRemoteActionVDelete
	return &v
}

// ManagedDeviceRemoteActionPFullScan returns a pointer to ManagedDeviceRemoteActionVFullScan
func ManagedDeviceRemoteActionPFullScan() *ManagedDeviceRemoteAction {
	v := ManagedDeviceRemoteActionVFullScan
	return &v
}

// ManagedDeviceRemoteActionPQuickScan returns a pointer to ManagedDeviceRemoteActionVQuickScan
func ManagedDeviceRemoteActionPQuickScan() *ManagedDeviceRemoteAction {
	v := ManagedDeviceRemoteActionVQuickScan
	return &v
}

// ManagedDeviceRemoteActionPSignatureUpdate returns a pointer to ManagedDeviceRemoteActionVSignatureUpdate
func ManagedDeviceRemoteActionPSignatureUpdate() *ManagedDeviceRemoteAction {
	v := ManagedDeviceRemoteActionVSignatureUpdate
	return &v
}

// ManagedDeviceRemoteActionPWipe returns a pointer to ManagedDeviceRemoteActionVWipe
func ManagedDeviceRemoteActionPWipe() *ManagedDeviceRemoteAction {
	v := ManagedDeviceRemoteActionVWipe
	return &v
}

// ManagedDeviceRemoteActionPCustomTextNotification returns a pointer to ManagedDeviceRemoteActionVCustomTextNotification
func ManagedDeviceRemoteActionPCustomTextNotification() *ManagedDeviceRemoteAction {
	v := ManagedDeviceRemoteActionVCustomTextNotification
	return &v
}

// ManagedDeviceRemoteActionPRebootNow returns a pointer to ManagedDeviceRemoteActionVRebootNow
func ManagedDeviceRemoteActionPRebootNow() *ManagedDeviceRemoteAction {
	v := ManagedDeviceRemoteActionVRebootNow
	return &v
}

// ManagedDeviceRemoteActionPSetDeviceName returns a pointer to ManagedDeviceRemoteActionVSetDeviceName
func ManagedDeviceRemoteActionPSetDeviceName() *ManagedDeviceRemoteAction {
	v := ManagedDeviceRemoteActionVSetDeviceName
	return &v
}
