// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// MeteredConnectionLimitType undocumented
type MeteredConnectionLimitType string

const (
	// MeteredConnectionLimitTypeVUnrestricted undocumented
	MeteredConnectionLimitTypeVUnrestricted MeteredConnectionLimitType = "Unrestricted"
	// MeteredConnectionLimitTypeVFixed undocumented
	MeteredConnectionLimitTypeVFixed MeteredConnectionLimitType = "Fixed"
	// MeteredConnectionLimitTypeVVariable undocumented
	MeteredConnectionLimitTypeVVariable MeteredConnectionLimitType = "Variable"
)

// MeteredConnectionLimitTypePUnrestricted returns a pointer to MeteredConnectionLimitTypeVUnrestricted
func MeteredConnectionLimitTypePUnrestricted() *MeteredConnectionLimitType {
	v := MeteredConnectionLimitTypeVUnrestricted
	return &v
}

// MeteredConnectionLimitTypePFixed returns a pointer to MeteredConnectionLimitTypeVFixed
func MeteredConnectionLimitTypePFixed() *MeteredConnectionLimitType {
	v := MeteredConnectionLimitTypeVFixed
	return &v
}

// MeteredConnectionLimitTypePVariable returns a pointer to MeteredConnectionLimitTypeVVariable
func MeteredConnectionLimitTypePVariable() *MeteredConnectionLimitType {
	v := MeteredConnectionLimitTypeVVariable
	return &v
}
