// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// MigrationStatus undocumented
type MigrationStatus string

const (
	// MigrationStatusVReady undocumented
	MigrationStatusVReady MigrationStatus = "Ready"
	// MigrationStatusVNeedsReview undocumented
	MigrationStatusVNeedsReview MigrationStatus = "NeedsReview"
	// MigrationStatusVAdditionalStepsRequired undocumented
	MigrationStatusVAdditionalStepsRequired MigrationStatus = "AdditionalStepsRequired"
	// MigrationStatusVUnknownFutureValue undocumented
	MigrationStatusVUnknownFutureValue MigrationStatus = "UnknownFutureValue"
)

// MigrationStatusPReady returns a pointer to MigrationStatusVReady
func MigrationStatusPReady() *MigrationStatus {
	v := MigrationStatusVReady
	return &v
}

// MigrationStatusPNeedsReview returns a pointer to MigrationStatusVNeedsReview
func MigrationStatusPNeedsReview() *MigrationStatus {
	v := MigrationStatusVNeedsReview
	return &v
}

// MigrationStatusPAdditionalStepsRequired returns a pointer to MigrationStatusVAdditionalStepsRequired
func MigrationStatusPAdditionalStepsRequired() *MigrationStatus {
	v := MigrationStatusVAdditionalStepsRequired
	return &v
}

// MigrationStatusPUnknownFutureValue returns a pointer to MigrationStatusVUnknownFutureValue
func MigrationStatusPUnknownFutureValue() *MigrationStatus {
	v := MigrationStatusVUnknownFutureValue
	return &v
}
