// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// MobileAppDependencyType undocumented
type MobileAppDependencyType string

const (
	// MobileAppDependencyTypeVDetect undocumented
	MobileAppDependencyTypeVDetect MobileAppDependencyType = "Detect"
	// MobileAppDependencyTypeVAutoInstall undocumented
	MobileAppDependencyTypeVAutoInstall MobileAppDependencyType = "AutoInstall"
)

// MobileAppDependencyTypePDetect returns a pointer to MobileAppDependencyTypeVDetect
func MobileAppDependencyTypePDetect() *MobileAppDependencyType {
	v := MobileAppDependencyTypeVDetect
	return &v
}

// MobileAppDependencyTypePAutoInstall returns a pointer to MobileAppDependencyTypeVAutoInstall
func MobileAppDependencyTypePAutoInstall() *MobileAppDependencyType {
	v := MobileAppDependencyTypeVAutoInstall
	return &v
}
