// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// MobileThreatPartnerTenantState undocumented
type MobileThreatPartnerTenantState string

const (
	// MobileThreatPartnerTenantStateVUnavailable undocumented
	MobileThreatPartnerTenantStateVUnavailable MobileThreatPartnerTenantState = "Unavailable"
	// MobileThreatPartnerTenantStateVAvailable undocumented
	MobileThreatPartnerTenantStateVAvailable MobileThreatPartnerTenantState = "Available"
	// MobileThreatPartnerTenantStateVEnabled undocumented
	MobileThreatPartnerTenantStateVEnabled MobileThreatPartnerTenantState = "Enabled"
	// MobileThreatPartnerTenantStateVUnresponsive undocumented
	MobileThreatPartnerTenantStateVUnresponsive MobileThreatPartnerTenantState = "Unresponsive"
)

// MobileThreatPartnerTenantStatePUnavailable returns a pointer to MobileThreatPartnerTenantStateVUnavailable
func MobileThreatPartnerTenantStatePUnavailable() *MobileThreatPartnerTenantState {
	v := MobileThreatPartnerTenantStateVUnavailable
	return &v
}

// MobileThreatPartnerTenantStatePAvailable returns a pointer to MobileThreatPartnerTenantStateVAvailable
func MobileThreatPartnerTenantStatePAvailable() *MobileThreatPartnerTenantState {
	v := MobileThreatPartnerTenantStateVAvailable
	return &v
}

// MobileThreatPartnerTenantStatePEnabled returns a pointer to MobileThreatPartnerTenantStateVEnabled
func MobileThreatPartnerTenantStatePEnabled() *MobileThreatPartnerTenantState {
	v := MobileThreatPartnerTenantStateVEnabled
	return &v
}

// MobileThreatPartnerTenantStatePUnresponsive returns a pointer to MobileThreatPartnerTenantStateVUnresponsive
func MobileThreatPartnerTenantStatePUnresponsive() *MobileThreatPartnerTenantState {
	v := MobileThreatPartnerTenantStateVUnresponsive
	return &v
}
