// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// Mutability undocumented
type Mutability string

const (
	// MutabilityVReadWrite undocumented
	MutabilityVReadWrite Mutability = "ReadWrite"
	// MutabilityVReadOnly undocumented
	MutabilityVReadOnly Mutability = "ReadOnly"
	// MutabilityVImmutable undocumented
	MutabilityVImmutable Mutability = "Immutable"
	// MutabilityVWriteOnly undocumented
	MutabilityVWriteOnly Mutability = "WriteOnly"
)

// MutabilityPReadWrite returns a pointer to MutabilityVReadWrite
func MutabilityPReadWrite() *Mutability {
	v := MutabilityVReadWrite
	return &v
}

// MutabilityPReadOnly returns a pointer to MutabilityVReadOnly
func MutabilityPReadOnly() *Mutability {
	v := MutabilityVReadOnly
	return &v
}

// MutabilityPImmutable returns a pointer to MutabilityVImmutable
func MutabilityPImmutable() *Mutability {
	v := MutabilityVImmutable
	return &v
}

// MutabilityPWriteOnly returns a pointer to MutabilityVWriteOnly
func MutabilityPWriteOnly() *Mutability {
	v := MutabilityVWriteOnly
	return &v
}
