// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// NetworkSingleSignOnType undocumented
type NetworkSingleSignOnType string

const (
	// NetworkSingleSignOnTypeVDisabled undocumented
	NetworkSingleSignOnTypeVDisabled NetworkSingleSignOnType = "Disabled"
	// NetworkSingleSignOnTypeVPrelogon undocumented
	NetworkSingleSignOnTypeVPrelogon NetworkSingleSignOnType = "Prelogon"
	// NetworkSingleSignOnTypeVPostlogon undocumented
	NetworkSingleSignOnTypeVPostlogon NetworkSingleSignOnType = "Postlogon"
)

// NetworkSingleSignOnTypePDisabled returns a pointer to NetworkSingleSignOnTypeVDisabled
func NetworkSingleSignOnTypePDisabled() *NetworkSingleSignOnType {
	v := NetworkSingleSignOnTypeVDisabled
	return &v
}

// NetworkSingleSignOnTypePPrelogon returns a pointer to NetworkSingleSignOnTypeVPrelogon
func NetworkSingleSignOnTypePPrelogon() *NetworkSingleSignOnType {
	v := NetworkSingleSignOnTypeVPrelogon
	return &v
}

// NetworkSingleSignOnTypePPostlogon returns a pointer to NetworkSingleSignOnTypeVPostlogon
func NetworkSingleSignOnTypePPostlogon() *NetworkSingleSignOnType {
	v := NetworkSingleSignOnTypeVPostlogon
	return &v
}
