// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// OnenotePatchActionType undocumented
type OnenotePatchActionType string

const (
	// OnenotePatchActionTypeVReplace undocumented
	OnenotePatchActionTypeVReplace OnenotePatchActionType = "Replace"
	// OnenotePatchActionTypeVAppend undocumented
	OnenotePatchActionTypeVAppend OnenotePatchActionType = "Append"
	// OnenotePatchActionTypeVDelete undocumented
	OnenotePatchActionTypeVDelete OnenotePatchActionType = "Delete"
	// OnenotePatchActionTypeVInsert undocumented
	OnenotePatchActionTypeVInsert OnenotePatchActionType = "Insert"
	// OnenotePatchActionTypeVPrepend undocumented
	OnenotePatchActionTypeVPrepend OnenotePatchActionType = "Prepend"
)

// OnenotePatchActionTypePReplace returns a pointer to OnenotePatchActionTypeVReplace
func OnenotePatchActionTypePReplace() *OnenotePatchActionType {
	v := OnenotePatchActionTypeVReplace
	return &v
}

// OnenotePatchActionTypePAppend returns a pointer to OnenotePatchActionTypeVAppend
func OnenotePatchActionTypePAppend() *OnenotePatchActionType {
	v := OnenotePatchActionTypeVAppend
	return &v
}

// OnenotePatchActionTypePDelete returns a pointer to OnenotePatchActionTypeVDelete
func OnenotePatchActionTypePDelete() *OnenotePatchActionType {
	v := OnenotePatchActionTypeVDelete
	return &v
}

// OnenotePatchActionTypePInsert returns a pointer to OnenotePatchActionTypeVInsert
func OnenotePatchActionTypePInsert() *OnenotePatchActionType {
	v := OnenotePatchActionTypeVInsert
	return &v
}

// OnenotePatchActionTypePPrepend returns a pointer to OnenotePatchActionTypeVPrepend
func OnenotePatchActionTypePPrepend() *OnenotePatchActionType {
	v := OnenotePatchActionTypeVPrepend
	return &v
}
