// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// OverrideOption undocumented
type OverrideOption string

const (
	// OverrideOptionVNotAllowed undocumented
	OverrideOptionVNotAllowed OverrideOption = "NotAllowed"
	// OverrideOptionVAllowFalsePositiveOverride undocumented
	OverrideOptionVAllowFalsePositiveOverride OverrideOption = "AllowFalsePositiveOverride"
	// OverrideOptionVAllowWithJustification undocumented
	OverrideOptionVAllowWithJustification OverrideOption = "AllowWithJustification"
	// OverrideOptionVAllowWithoutJustification undocumented
	OverrideOptionVAllowWithoutJustification OverrideOption = "AllowWithoutJustification"
)

// OverrideOptionPNotAllowed returns a pointer to OverrideOptionVNotAllowed
func OverrideOptionPNotAllowed() *OverrideOption {
	v := OverrideOptionVNotAllowed
	return &v
}

// OverrideOptionPAllowFalsePositiveOverride returns a pointer to OverrideOptionVAllowFalsePositiveOverride
func OverrideOptionPAllowFalsePositiveOverride() *OverrideOption {
	v := OverrideOptionVAllowFalsePositiveOverride
	return &v
}

// OverrideOptionPAllowWithJustification returns a pointer to OverrideOptionVAllowWithJustification
func OverrideOptionPAllowWithJustification() *OverrideOption {
	v := OverrideOptionVAllowWithJustification
	return &v
}

// OverrideOptionPAllowWithoutJustification returns a pointer to OverrideOptionVAllowWithoutJustification
func OverrideOptionPAllowWithoutJustification() *OverrideOption {
	v := OverrideOptionVAllowWithoutJustification
	return &v
}
