// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// Platform undocumented
type Platform string

const (
	// PlatformVUnknown undocumented
	PlatformVUnknown Platform = "Unknown"
	// PlatformVIOS undocumented
	PlatformVIOS Platform = "IOS"
	// PlatformVAndroid undocumented
	PlatformVAndroid Platform = "Android"
	// PlatformVWindows undocumented
	PlatformVWindows Platform = "Windows"
	// PlatformVWindowsMobile undocumented
	PlatformVWindowsMobile Platform = "WindowsMobile"
	// PlatformVMacOS undocumented
	PlatformVMacOS Platform = "MacOS"
)

// PlatformPUnknown returns a pointer to PlatformVUnknown
func PlatformPUnknown() *Platform {
	v := PlatformVUnknown
	return &v
}

// PlatformPIOS returns a pointer to PlatformVIOS
func PlatformPIOS() *Platform {
	v := PlatformVIOS
	return &v
}

// PlatformPAndroid returns a pointer to PlatformVAndroid
func PlatformPAndroid() *Platform {
	v := PlatformVAndroid
	return &v
}

// PlatformPWindows returns a pointer to PlatformVWindows
func PlatformPWindows() *Platform {
	v := PlatformVWindows
	return &v
}

// PlatformPWindowsMobile returns a pointer to PlatformVWindowsMobile
func PlatformPWindowsMobile() *Platform {
	v := PlatformVWindowsMobile
	return &v
}

// PlatformPMacOS returns a pointer to PlatformVMacOS
func PlatformPMacOS() *Platform {
	v := PlatformVMacOS
	return &v
}
