// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// PowerActionType undocumented
type PowerActionType string

const (
	// PowerActionTypeVNotConfigured undocumented
	PowerActionTypeVNotConfigured PowerActionType = "NotConfigured"
	// PowerActionTypeVNoAction undocumented
	PowerActionTypeVNoAction PowerActionType = "NoAction"
	// PowerActionTypeVSleep undocumented
	PowerActionTypeVSleep PowerActionType = "Sleep"
	// PowerActionTypeVHibernate undocumented
	PowerActionTypeVHibernate PowerActionType = "Hibernate"
	// PowerActionTypeVShutdown undocumented
	PowerActionTypeVShutdown PowerActionType = "Shutdown"
)

// PowerActionTypePNotConfigured returns a pointer to PowerActionTypeVNotConfigured
func PowerActionTypePNotConfigured() *PowerActionType {
	v := PowerActionTypeVNotConfigured
	return &v
}

// PowerActionTypePNoAction returns a pointer to PowerActionTypeVNoAction
func PowerActionTypePNoAction() *PowerActionType {
	v := PowerActionTypeVNoAction
	return &v
}

// PowerActionTypePSleep returns a pointer to PowerActionTypeVSleep
func PowerActionTypePSleep() *PowerActionType {
	v := PowerActionTypeVSleep
	return &v
}

// PowerActionTypePHibernate returns a pointer to PowerActionTypeVHibernate
func PowerActionTypePHibernate() *PowerActionType {
	v := PowerActionTypeVHibernate
	return &v
}

// PowerActionTypePShutdown returns a pointer to PowerActionTypeVShutdown
func PowerActionTypePShutdown() *PowerActionType {
	v := PowerActionTypeVShutdown
	return &v
}
