// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// Priority undocumented
type Priority string

const (
	// PriorityVNone undocumented
	PriorityVNone Priority = "None"
	// PriorityVHigh undocumented
	PriorityVHigh Priority = "High"
	// PriorityVLow undocumented
	PriorityVLow Priority = "Low"
)

// PriorityPNone returns a pointer to PriorityVNone
func PriorityPNone() *Priority {
	v := PriorityVNone
	return &v
}

// PriorityPHigh returns a pointer to PriorityVHigh
func PriorityPHigh() *Priority {
	v := PriorityVHigh
	return &v
}

// PriorityPLow returns a pointer to PriorityVLow
func PriorityPLow() *Priority {
	v := PriorityVLow
	return &v
}
