// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// PropertyType undocumented
type PropertyType string

const (
	// PropertyTypeVString undocumented
	PropertyTypeVString PropertyType = "String"
	// PropertyTypeVInt64 undocumented
	PropertyTypeVInt64 PropertyType = "Int64"
	// PropertyTypeVDouble undocumented
	PropertyTypeVDouble PropertyType = "Double"
	// PropertyTypeVDateTime undocumented
	PropertyTypeVDateTime PropertyType = "DateTime"
	// PropertyTypeVBoolean undocumented
	PropertyTypeVBoolean PropertyType = "Boolean"
	// PropertyTypeVStringCollection undocumented
	PropertyTypeVStringCollection PropertyType = "StringCollection"
	// PropertyTypeVInt64Collection undocumented
	PropertyTypeVInt64Collection PropertyType = "Int64Collection"
	// PropertyTypeVDoubleCollection undocumented
	PropertyTypeVDoubleCollection PropertyType = "DoubleCollection"
	// PropertyTypeVDateTimeCollection undocumented
	PropertyTypeVDateTimeCollection PropertyType = "DateTimeCollection"
)

// PropertyTypePString returns a pointer to PropertyTypeVString
func PropertyTypePString() *PropertyType {
	v := PropertyTypeVString
	return &v
}

// PropertyTypePInt64 returns a pointer to PropertyTypeVInt64
func PropertyTypePInt64() *PropertyType {
	v := PropertyTypeVInt64
	return &v
}

// PropertyTypePDouble returns a pointer to PropertyTypeVDouble
func PropertyTypePDouble() *PropertyType {
	v := PropertyTypeVDouble
	return &v
}

// PropertyTypePDateTime returns a pointer to PropertyTypeVDateTime
func PropertyTypePDateTime() *PropertyType {
	v := PropertyTypeVDateTime
	return &v
}

// PropertyTypePBoolean returns a pointer to PropertyTypeVBoolean
func PropertyTypePBoolean() *PropertyType {
	v := PropertyTypeVBoolean
	return &v
}

// PropertyTypePStringCollection returns a pointer to PropertyTypeVStringCollection
func PropertyTypePStringCollection() *PropertyType {
	v := PropertyTypeVStringCollection
	return &v
}

// PropertyTypePInt64Collection returns a pointer to PropertyTypeVInt64Collection
func PropertyTypePInt64Collection() *PropertyType {
	v := PropertyTypeVInt64Collection
	return &v
}

// PropertyTypePDoubleCollection returns a pointer to PropertyTypeVDoubleCollection
func PropertyTypePDoubleCollection() *PropertyType {
	v := PropertyTypeVDoubleCollection
	return &v
}

// PropertyTypePDateTimeCollection returns a pointer to PropertyTypeVDateTimeCollection
func PropertyTypePDateTimeCollection() *PropertyType {
	v := PropertyTypeVDateTimeCollection
	return &v
}
