// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ProvisioningResult undocumented
type ProvisioningResult string

const (
	// ProvisioningResultVSuccess undocumented
	ProvisioningResultVSuccess ProvisioningResult = "Success"
	// ProvisioningResultVFailure undocumented
	ProvisioningResultVFailure ProvisioningResult = "Failure"
	// ProvisioningResultVSkipped undocumented
	ProvisioningResultVSkipped ProvisioningResult = "Skipped"
	// ProvisioningResultVUnknownFutureValue undocumented
	ProvisioningResultVUnknownFutureValue ProvisioningResult = "UnknownFutureValue"
)

// ProvisioningResultPSuccess returns a pointer to ProvisioningResultVSuccess
func ProvisioningResultPSuccess() *ProvisioningResult {
	v := ProvisioningResultVSuccess
	return &v
}

// ProvisioningResultPFailure returns a pointer to ProvisioningResultVFailure
func ProvisioningResultPFailure() *ProvisioningResult {
	v := ProvisioningResultVFailure
	return &v
}

// ProvisioningResultPSkipped returns a pointer to ProvisioningResultVSkipped
func ProvisioningResultPSkipped() *ProvisioningResult {
	v := ProvisioningResultVSkipped
	return &v
}

// ProvisioningResultPUnknownFutureValue returns a pointer to ProvisioningResultVUnknownFutureValue
func ProvisioningResultPUnknownFutureValue() *ProvisioningResult {
	v := ProvisioningResultVUnknownFutureValue
	return &v
}
