// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RatingAustraliaTelevisionType undocumented
type RatingAustraliaTelevisionType string

const (
	// RatingAustraliaTelevisionTypeVAllAllowed undocumented
	RatingAustraliaTelevisionTypeVAllAllowed RatingAustraliaTelevisionType = "AllAllowed"
	// RatingAustraliaTelevisionTypeVAllBlocked undocumented
	RatingAustraliaTelevisionTypeVAllBlocked RatingAustraliaTelevisionType = "AllBlocked"
	// RatingAustraliaTelevisionTypeVPreschoolers undocumented
	RatingAustraliaTelevisionTypeVPreschoolers RatingAustraliaTelevisionType = "Preschoolers"
	// RatingAustraliaTelevisionTypeVChildren undocumented
	RatingAustraliaTelevisionTypeVChildren RatingAustraliaTelevisionType = "Children"
	// RatingAustraliaTelevisionTypeVGeneral undocumented
	RatingAustraliaTelevisionTypeVGeneral RatingAustraliaTelevisionType = "General"
	// RatingAustraliaTelevisionTypeVParentalGuidance undocumented
	RatingAustraliaTelevisionTypeVParentalGuidance RatingAustraliaTelevisionType = "ParentalGuidance"
	// RatingAustraliaTelevisionTypeVMature undocumented
	RatingAustraliaTelevisionTypeVMature RatingAustraliaTelevisionType = "Mature"
	// RatingAustraliaTelevisionTypeVAgesAbove15 undocumented
	RatingAustraliaTelevisionTypeVAgesAbove15 RatingAustraliaTelevisionType = "AgesAbove15"
	// RatingAustraliaTelevisionTypeVAgesAbove15AdultViolence undocumented
	RatingAustraliaTelevisionTypeVAgesAbove15AdultViolence RatingAustraliaTelevisionType = "AgesAbove15AdultViolence"
)

// RatingAustraliaTelevisionTypePAllAllowed returns a pointer to RatingAustraliaTelevisionTypeVAllAllowed
func RatingAustraliaTelevisionTypePAllAllowed() *RatingAustraliaTelevisionType {
	v := RatingAustraliaTelevisionTypeVAllAllowed
	return &v
}

// RatingAustraliaTelevisionTypePAllBlocked returns a pointer to RatingAustraliaTelevisionTypeVAllBlocked
func RatingAustraliaTelevisionTypePAllBlocked() *RatingAustraliaTelevisionType {
	v := RatingAustraliaTelevisionTypeVAllBlocked
	return &v
}

// RatingAustraliaTelevisionTypePPreschoolers returns a pointer to RatingAustraliaTelevisionTypeVPreschoolers
func RatingAustraliaTelevisionTypePPreschoolers() *RatingAustraliaTelevisionType {
	v := RatingAustraliaTelevisionTypeVPreschoolers
	return &v
}

// RatingAustraliaTelevisionTypePChildren returns a pointer to RatingAustraliaTelevisionTypeVChildren
func RatingAustraliaTelevisionTypePChildren() *RatingAustraliaTelevisionType {
	v := RatingAustraliaTelevisionTypeVChildren
	return &v
}

// RatingAustraliaTelevisionTypePGeneral returns a pointer to RatingAustraliaTelevisionTypeVGeneral
func RatingAustraliaTelevisionTypePGeneral() *RatingAustraliaTelevisionType {
	v := RatingAustraliaTelevisionTypeVGeneral
	return &v
}

// RatingAustraliaTelevisionTypePParentalGuidance returns a pointer to RatingAustraliaTelevisionTypeVParentalGuidance
func RatingAustraliaTelevisionTypePParentalGuidance() *RatingAustraliaTelevisionType {
	v := RatingAustraliaTelevisionTypeVParentalGuidance
	return &v
}

// RatingAustraliaTelevisionTypePMature returns a pointer to RatingAustraliaTelevisionTypeVMature
func RatingAustraliaTelevisionTypePMature() *RatingAustraliaTelevisionType {
	v := RatingAustraliaTelevisionTypeVMature
	return &v
}

// RatingAustraliaTelevisionTypePAgesAbove15 returns a pointer to RatingAustraliaTelevisionTypeVAgesAbove15
func RatingAustraliaTelevisionTypePAgesAbove15() *RatingAustraliaTelevisionType {
	v := RatingAustraliaTelevisionTypeVAgesAbove15
	return &v
}

// RatingAustraliaTelevisionTypePAgesAbove15AdultViolence returns a pointer to RatingAustraliaTelevisionTypeVAgesAbove15AdultViolence
func RatingAustraliaTelevisionTypePAgesAbove15AdultViolence() *RatingAustraliaTelevisionType {
	v := RatingAustraliaTelevisionTypeVAgesAbove15AdultViolence
	return &v
}
