// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RatingCanadaTelevisionType undocumented
type RatingCanadaTelevisionType string

const (
	// RatingCanadaTelevisionTypeVAllAllowed undocumented
	RatingCanadaTelevisionTypeVAllAllowed RatingCanadaTelevisionType = "AllAllowed"
	// RatingCanadaTelevisionTypeVAllBlocked undocumented
	RatingCanadaTelevisionTypeVAllBlocked RatingCanadaTelevisionType = "AllBlocked"
	// RatingCanadaTelevisionTypeVChildren undocumented
	RatingCanadaTelevisionTypeVChildren RatingCanadaTelevisionType = "Children"
	// RatingCanadaTelevisionTypeVChildrenAbove8 undocumented
	RatingCanadaTelevisionTypeVChildrenAbove8 RatingCanadaTelevisionType = "ChildrenAbove8"
	// RatingCanadaTelevisionTypeVGeneral undocumented
	RatingCanadaTelevisionTypeVGeneral RatingCanadaTelevisionType = "General"
	// RatingCanadaTelevisionTypeVParentalGuidance undocumented
	RatingCanadaTelevisionTypeVParentalGuidance RatingCanadaTelevisionType = "ParentalGuidance"
	// RatingCanadaTelevisionTypeVAgesAbove14 undocumented
	RatingCanadaTelevisionTypeVAgesAbove14 RatingCanadaTelevisionType = "AgesAbove14"
	// RatingCanadaTelevisionTypeVAgesAbove18 undocumented
	RatingCanadaTelevisionTypeVAgesAbove18 RatingCanadaTelevisionType = "AgesAbove18"
)

// RatingCanadaTelevisionTypePAllAllowed returns a pointer to RatingCanadaTelevisionTypeVAllAllowed
func RatingCanadaTelevisionTypePAllAllowed() *RatingCanadaTelevisionType {
	v := RatingCanadaTelevisionTypeVAllAllowed
	return &v
}

// RatingCanadaTelevisionTypePAllBlocked returns a pointer to RatingCanadaTelevisionTypeVAllBlocked
func RatingCanadaTelevisionTypePAllBlocked() *RatingCanadaTelevisionType {
	v := RatingCanadaTelevisionTypeVAllBlocked
	return &v
}

// RatingCanadaTelevisionTypePChildren returns a pointer to RatingCanadaTelevisionTypeVChildren
func RatingCanadaTelevisionTypePChildren() *RatingCanadaTelevisionType {
	v := RatingCanadaTelevisionTypeVChildren
	return &v
}

// RatingCanadaTelevisionTypePChildrenAbove8 returns a pointer to RatingCanadaTelevisionTypeVChildrenAbove8
func RatingCanadaTelevisionTypePChildrenAbove8() *RatingCanadaTelevisionType {
	v := RatingCanadaTelevisionTypeVChildrenAbove8
	return &v
}

// RatingCanadaTelevisionTypePGeneral returns a pointer to RatingCanadaTelevisionTypeVGeneral
func RatingCanadaTelevisionTypePGeneral() *RatingCanadaTelevisionType {
	v := RatingCanadaTelevisionTypeVGeneral
	return &v
}

// RatingCanadaTelevisionTypePParentalGuidance returns a pointer to RatingCanadaTelevisionTypeVParentalGuidance
func RatingCanadaTelevisionTypePParentalGuidance() *RatingCanadaTelevisionType {
	v := RatingCanadaTelevisionTypeVParentalGuidance
	return &v
}

// RatingCanadaTelevisionTypePAgesAbove14 returns a pointer to RatingCanadaTelevisionTypeVAgesAbove14
func RatingCanadaTelevisionTypePAgesAbove14() *RatingCanadaTelevisionType {
	v := RatingCanadaTelevisionTypeVAgesAbove14
	return &v
}

// RatingCanadaTelevisionTypePAgesAbove18 returns a pointer to RatingCanadaTelevisionTypeVAgesAbove18
func RatingCanadaTelevisionTypePAgesAbove18() *RatingCanadaTelevisionType {
	v := RatingCanadaTelevisionTypeVAgesAbove18
	return &v
}
