// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RecordingStatus undocumented
type RecordingStatus string

const (
	// RecordingStatusVUnknown undocumented
	RecordingStatusVUnknown RecordingStatus = "Unknown"
	// RecordingStatusVNotRecording undocumented
	RecordingStatusVNotRecording RecordingStatus = "NotRecording"
	// RecordingStatusVRecording undocumented
	RecordingStatusVRecording RecordingStatus = "Recording"
	// RecordingStatusVFailed undocumented
	RecordingStatusVFailed RecordingStatus = "Failed"
	// RecordingStatusVUnknownFutureValue undocumented
	RecordingStatusVUnknownFutureValue RecordingStatus = "UnknownFutureValue"
)

// RecordingStatusPUnknown returns a pointer to RecordingStatusVUnknown
func RecordingStatusPUnknown() *RecordingStatus {
	v := RecordingStatusVUnknown
	return &v
}

// RecordingStatusPNotRecording returns a pointer to RecordingStatusVNotRecording
func RecordingStatusPNotRecording() *RecordingStatus {
	v := RecordingStatusVNotRecording
	return &v
}

// RecordingStatusPRecording returns a pointer to RecordingStatusVRecording
func RecordingStatusPRecording() *RecordingStatus {
	v := RecordingStatusVRecording
	return &v
}

// RecordingStatusPFailed returns a pointer to RecordingStatusVFailed
func RecordingStatusPFailed() *RecordingStatus {
	v := RecordingStatusVFailed
	return &v
}

// RecordingStatusPUnknownFutureValue returns a pointer to RecordingStatusVUnknownFutureValue
func RecordingStatusPUnknownFutureValue() *RecordingStatus {
	v := RecordingStatusVUnknownFutureValue
	return &v
}
