// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RecordCompletionReason undocumented
type RecordCompletionReason string

const (
	// RecordCompletionReasonVOperationCanceled undocumented
	RecordCompletionReasonVOperationCanceled RecordCompletionReason = "OperationCanceled"
	// RecordCompletionReasonVStopToneDetected undocumented
	RecordCompletionReasonVStopToneDetected RecordCompletionReason = "StopToneDetected"
	// RecordCompletionReasonVMaxRecordDurationReached undocumented
	RecordCompletionReasonVMaxRecordDurationReached RecordCompletionReason = "MaxRecordDurationReached"
	// RecordCompletionReasonVInitialSilenceTimeout undocumented
	RecordCompletionReasonVInitialSilenceTimeout RecordCompletionReason = "InitialSilenceTimeout"
	// RecordCompletionReasonVMaxSilenceTimeout undocumented
	RecordCompletionReasonVMaxSilenceTimeout RecordCompletionReason = "MaxSilenceTimeout"
	// RecordCompletionReasonVPlayPromptFailed undocumented
	RecordCompletionReasonVPlayPromptFailed RecordCompletionReason = "PlayPromptFailed"
	// RecordCompletionReasonVPlayBeepFailed undocumented
	RecordCompletionReasonVPlayBeepFailed RecordCompletionReason = "PlayBeepFailed"
	// RecordCompletionReasonVMediaReceiveTimeout undocumented
	RecordCompletionReasonVMediaReceiveTimeout RecordCompletionReason = "MediaReceiveTimeout"
	// RecordCompletionReasonVUnspecifiedError undocumented
	RecordCompletionReasonVUnspecifiedError RecordCompletionReason = "UnspecifiedError"
)

// RecordCompletionReasonPOperationCanceled returns a pointer to RecordCompletionReasonVOperationCanceled
func RecordCompletionReasonPOperationCanceled() *RecordCompletionReason {
	v := RecordCompletionReasonVOperationCanceled
	return &v
}

// RecordCompletionReasonPStopToneDetected returns a pointer to RecordCompletionReasonVStopToneDetected
func RecordCompletionReasonPStopToneDetected() *RecordCompletionReason {
	v := RecordCompletionReasonVStopToneDetected
	return &v
}

// RecordCompletionReasonPMaxRecordDurationReached returns a pointer to RecordCompletionReasonVMaxRecordDurationReached
func RecordCompletionReasonPMaxRecordDurationReached() *RecordCompletionReason {
	v := RecordCompletionReasonVMaxRecordDurationReached
	return &v
}

// RecordCompletionReasonPInitialSilenceTimeout returns a pointer to RecordCompletionReasonVInitialSilenceTimeout
func RecordCompletionReasonPInitialSilenceTimeout() *RecordCompletionReason {
	v := RecordCompletionReasonVInitialSilenceTimeout
	return &v
}

// RecordCompletionReasonPMaxSilenceTimeout returns a pointer to RecordCompletionReasonVMaxSilenceTimeout
func RecordCompletionReasonPMaxSilenceTimeout() *RecordCompletionReason {
	v := RecordCompletionReasonVMaxSilenceTimeout
	return &v
}

// RecordCompletionReasonPPlayPromptFailed returns a pointer to RecordCompletionReasonVPlayPromptFailed
func RecordCompletionReasonPPlayPromptFailed() *RecordCompletionReason {
	v := RecordCompletionReasonVPlayPromptFailed
	return &v
}

// RecordCompletionReasonPPlayBeepFailed returns a pointer to RecordCompletionReasonVPlayBeepFailed
func RecordCompletionReasonPPlayBeepFailed() *RecordCompletionReason {
	v := RecordCompletionReasonVPlayBeepFailed
	return &v
}

// RecordCompletionReasonPMediaReceiveTimeout returns a pointer to RecordCompletionReasonVMediaReceiveTimeout
func RecordCompletionReasonPMediaReceiveTimeout() *RecordCompletionReason {
	v := RecordCompletionReasonVMediaReceiveTimeout
	return &v
}

// RecordCompletionReasonPUnspecifiedError returns a pointer to RecordCompletionReasonVUnspecifiedError
func RecordCompletionReasonPUnspecifiedError() *RecordCompletionReason {
	v := RecordCompletionReasonVUnspecifiedError
	return &v
}
