// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ReferenceAttachmentPermission undocumented
type ReferenceAttachmentPermission string

const (
	// ReferenceAttachmentPermissionVOther undocumented
	ReferenceAttachmentPermissionVOther ReferenceAttachmentPermission = "Other"
	// ReferenceAttachmentPermissionVView undocumented
	ReferenceAttachmentPermissionVView ReferenceAttachmentPermission = "View"
	// ReferenceAttachmentPermissionVEdit undocumented
	ReferenceAttachmentPermissionVEdit ReferenceAttachmentPermission = "Edit"
	// ReferenceAttachmentPermissionVAnonymousView undocumented
	ReferenceAttachmentPermissionVAnonymousView ReferenceAttachmentPermission = "AnonymousView"
	// ReferenceAttachmentPermissionVAnonymousEdit undocumented
	ReferenceAttachmentPermissionVAnonymousEdit ReferenceAttachmentPermission = "AnonymousEdit"
	// ReferenceAttachmentPermissionVOrganizationView undocumented
	ReferenceAttachmentPermissionVOrganizationView ReferenceAttachmentPermission = "OrganizationView"
	// ReferenceAttachmentPermissionVOrganizationEdit undocumented
	ReferenceAttachmentPermissionVOrganizationEdit ReferenceAttachmentPermission = "OrganizationEdit"
)

// ReferenceAttachmentPermissionPOther returns a pointer to ReferenceAttachmentPermissionVOther
func ReferenceAttachmentPermissionPOther() *ReferenceAttachmentPermission {
	v := ReferenceAttachmentPermissionVOther
	return &v
}

// ReferenceAttachmentPermissionPView returns a pointer to ReferenceAttachmentPermissionVView
func ReferenceAttachmentPermissionPView() *ReferenceAttachmentPermission {
	v := ReferenceAttachmentPermissionVView
	return &v
}

// ReferenceAttachmentPermissionPEdit returns a pointer to ReferenceAttachmentPermissionVEdit
func ReferenceAttachmentPermissionPEdit() *ReferenceAttachmentPermission {
	v := ReferenceAttachmentPermissionVEdit
	return &v
}

// ReferenceAttachmentPermissionPAnonymousView returns a pointer to ReferenceAttachmentPermissionVAnonymousView
func ReferenceAttachmentPermissionPAnonymousView() *ReferenceAttachmentPermission {
	v := ReferenceAttachmentPermissionVAnonymousView
	return &v
}

// ReferenceAttachmentPermissionPAnonymousEdit returns a pointer to ReferenceAttachmentPermissionVAnonymousEdit
func ReferenceAttachmentPermissionPAnonymousEdit() *ReferenceAttachmentPermission {
	v := ReferenceAttachmentPermissionVAnonymousEdit
	return &v
}

// ReferenceAttachmentPermissionPOrganizationView returns a pointer to ReferenceAttachmentPermissionVOrganizationView
func ReferenceAttachmentPermissionPOrganizationView() *ReferenceAttachmentPermission {
	v := ReferenceAttachmentPermissionVOrganizationView
	return &v
}

// ReferenceAttachmentPermissionPOrganizationEdit returns a pointer to ReferenceAttachmentPermissionVOrganizationEdit
func ReferenceAttachmentPermissionPOrganizationEdit() *ReferenceAttachmentPermission {
	v := ReferenceAttachmentPermissionVOrganizationEdit
	return &v
}
