// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RegistryValueType undocumented
type RegistryValueType string

const (
	// RegistryValueTypeVUnknown undocumented
	RegistryValueTypeVUnknown RegistryValueType = "Unknown"
	// RegistryValueTypeVBinary undocumented
	RegistryValueTypeVBinary RegistryValueType = "Binary"
	// RegistryValueTypeVDword undocumented
	RegistryValueTypeVDword RegistryValueType = "Dword"
	// RegistryValueTypeVDwordLittleEndian undocumented
	RegistryValueTypeVDwordLittleEndian RegistryValueType = "DwordLittleEndian"
	// RegistryValueTypeVDwordBigEndian undocumented
	RegistryValueTypeVDwordBigEndian RegistryValueType = "DwordBigEndian"
	// RegistryValueTypeVExpandSz undocumented
	RegistryValueTypeVExpandSz RegistryValueType = "ExpandSz"
	// RegistryValueTypeVLink undocumented
	RegistryValueTypeVLink RegistryValueType = "Link"
	// RegistryValueTypeVMultiSz undocumented
	RegistryValueTypeVMultiSz RegistryValueType = "MultiSz"
	// RegistryValueTypeVNone undocumented
	RegistryValueTypeVNone RegistryValueType = "None"
	// RegistryValueTypeVQword undocumented
	RegistryValueTypeVQword RegistryValueType = "Qword"
	// RegistryValueTypeVQwordlittleEndian undocumented
	RegistryValueTypeVQwordlittleEndian RegistryValueType = "QwordlittleEndian"
	// RegistryValueTypeVSz undocumented
	RegistryValueTypeVSz RegistryValueType = "Sz"
	// RegistryValueTypeVUnknownFutureValue undocumented
	RegistryValueTypeVUnknownFutureValue RegistryValueType = "UnknownFutureValue"
)

// RegistryValueTypePUnknown returns a pointer to RegistryValueTypeVUnknown
func RegistryValueTypePUnknown() *RegistryValueType {
	v := RegistryValueTypeVUnknown
	return &v
}

// RegistryValueTypePBinary returns a pointer to RegistryValueTypeVBinary
func RegistryValueTypePBinary() *RegistryValueType {
	v := RegistryValueTypeVBinary
	return &v
}

// RegistryValueTypePDword returns a pointer to RegistryValueTypeVDword
func RegistryValueTypePDword() *RegistryValueType {
	v := RegistryValueTypeVDword
	return &v
}

// RegistryValueTypePDwordLittleEndian returns a pointer to RegistryValueTypeVDwordLittleEndian
func RegistryValueTypePDwordLittleEndian() *RegistryValueType {
	v := RegistryValueTypeVDwordLittleEndian
	return &v
}

// RegistryValueTypePDwordBigEndian returns a pointer to RegistryValueTypeVDwordBigEndian
func RegistryValueTypePDwordBigEndian() *RegistryValueType {
	v := RegistryValueTypeVDwordBigEndian
	return &v
}

// RegistryValueTypePExpandSz returns a pointer to RegistryValueTypeVExpandSz
func RegistryValueTypePExpandSz() *RegistryValueType {
	v := RegistryValueTypeVExpandSz
	return &v
}

// RegistryValueTypePLink returns a pointer to RegistryValueTypeVLink
func RegistryValueTypePLink() *RegistryValueType {
	v := RegistryValueTypeVLink
	return &v
}

// RegistryValueTypePMultiSz returns a pointer to RegistryValueTypeVMultiSz
func RegistryValueTypePMultiSz() *RegistryValueType {
	v := RegistryValueTypeVMultiSz
	return &v
}

// RegistryValueTypePNone returns a pointer to RegistryValueTypeVNone
func RegistryValueTypePNone() *RegistryValueType {
	v := RegistryValueTypeVNone
	return &v
}

// RegistryValueTypePQword returns a pointer to RegistryValueTypeVQword
func RegistryValueTypePQword() *RegistryValueType {
	v := RegistryValueTypeVQword
	return &v
}

// RegistryValueTypePQwordlittleEndian returns a pointer to RegistryValueTypeVQwordlittleEndian
func RegistryValueTypePQwordlittleEndian() *RegistryValueType {
	v := RegistryValueTypeVQwordlittleEndian
	return &v
}

// RegistryValueTypePSz returns a pointer to RegistryValueTypeVSz
func RegistryValueTypePSz() *RegistryValueType {
	v := RegistryValueTypeVSz
	return &v
}

// RegistryValueTypePUnknownFutureValue returns a pointer to RegistryValueTypeVUnknownFutureValue
func RegistryValueTypePUnknownFutureValue() *RegistryValueType {
	v := RegistryValueTypeVUnknownFutureValue
	return &v
}
