// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RemoteAssistanceOnboardingStatus undocumented
type RemoteAssistanceOnboardingStatus string

const (
	// RemoteAssistanceOnboardingStatusVNotOnboarded undocumented
	RemoteAssistanceOnboardingStatusVNotOnboarded RemoteAssistanceOnboardingStatus = "NotOnboarded"
	// RemoteAssistanceOnboardingStatusVOnboarding undocumented
	RemoteAssistanceOnboardingStatusVOnboarding RemoteAssistanceOnboardingStatus = "Onboarding"
	// RemoteAssistanceOnboardingStatusVOnboarded undocumented
	RemoteAssistanceOnboardingStatusVOnboarded RemoteAssistanceOnboardingStatus = "Onboarded"
)

// RemoteAssistanceOnboardingStatusPNotOnboarded returns a pointer to RemoteAssistanceOnboardingStatusVNotOnboarded
func RemoteAssistanceOnboardingStatusPNotOnboarded() *RemoteAssistanceOnboardingStatus {
	v := RemoteAssistanceOnboardingStatusVNotOnboarded
	return &v
}

// RemoteAssistanceOnboardingStatusPOnboarding returns a pointer to RemoteAssistanceOnboardingStatusVOnboarding
func RemoteAssistanceOnboardingStatusPOnboarding() *RemoteAssistanceOnboardingStatus {
	v := RemoteAssistanceOnboardingStatusVOnboarding
	return &v
}

// RemoteAssistanceOnboardingStatusPOnboarded returns a pointer to RemoteAssistanceOnboardingStatusVOnboarded
func RemoteAssistanceOnboardingStatusPOnboarded() *RemoteAssistanceOnboardingStatus {
	v := RemoteAssistanceOnboardingStatusVOnboarded
	return &v
}
