// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RemoteAction undocumented
type RemoteAction string

const (
	// RemoteActionVUnknown undocumented
	RemoteActionVUnknown RemoteAction = "Unknown"
	// RemoteActionVFactoryReset undocumented
	RemoteActionVFactoryReset RemoteAction = "FactoryReset"
	// RemoteActionVRemoveCompanyData undocumented
	RemoteActionVRemoveCompanyData RemoteAction = "RemoveCompanyData"
	// RemoteActionVResetPasscode undocumented
	RemoteActionVResetPasscode RemoteAction = "ResetPasscode"
	// RemoteActionVRemoteLock undocumented
	RemoteActionVRemoteLock RemoteAction = "RemoteLock"
	// RemoteActionVEnableLostMode undocumented
	RemoteActionVEnableLostMode RemoteAction = "EnableLostMode"
	// RemoteActionVDisableLostMode undocumented
	RemoteActionVDisableLostMode RemoteAction = "DisableLostMode"
	// RemoteActionVLocateDevice undocumented
	RemoteActionVLocateDevice RemoteAction = "LocateDevice"
	// RemoteActionVRebootNow undocumented
	RemoteActionVRebootNow RemoteAction = "RebootNow"
	// RemoteActionVRecoverPasscode undocumented
	RemoteActionVRecoverPasscode RemoteAction = "RecoverPasscode"
	// RemoteActionVCleanWindowsDevice undocumented
	RemoteActionVCleanWindowsDevice RemoteAction = "CleanWindowsDevice"
	// RemoteActionVLogoutSharedAppleDeviceActiveUser undocumented
	RemoteActionVLogoutSharedAppleDeviceActiveUser RemoteAction = "LogoutSharedAppleDeviceActiveUser"
	// RemoteActionVQuickScan undocumented
	RemoteActionVQuickScan RemoteAction = "QuickScan"
	// RemoteActionVFullScan undocumented
	RemoteActionVFullScan RemoteAction = "FullScan"
	// RemoteActionVWindowsDefenderUpdateSignatures undocumented
	RemoteActionVWindowsDefenderUpdateSignatures RemoteAction = "WindowsDefenderUpdateSignatures"
	// RemoteActionVFactoryResetKeepEnrollmentData undocumented
	RemoteActionVFactoryResetKeepEnrollmentData RemoteAction = "FactoryResetKeepEnrollmentData"
	// RemoteActionVUpdateDeviceAccount undocumented
	RemoteActionVUpdateDeviceAccount RemoteAction = "UpdateDeviceAccount"
	// RemoteActionVAutomaticRedeployment undocumented
	RemoteActionVAutomaticRedeployment RemoteAction = "AutomaticRedeployment"
	// RemoteActionVShutDown undocumented
	RemoteActionVShutDown RemoteAction = "ShutDown"
	// RemoteActionVRotateBitLockerKeys undocumented
	RemoteActionVRotateBitLockerKeys RemoteAction = "RotateBitLockerKeys"
	// RemoteActionVRotateFileVaultKey undocumented
	RemoteActionVRotateFileVaultKey RemoteAction = "RotateFileVaultKey"
	// RemoteActionVGetFileVaultKey undocumented
	RemoteActionVGetFileVaultKey RemoteAction = "GetFileVaultKey"
	// RemoteActionVSetDeviceName undocumented
	RemoteActionVSetDeviceName RemoteAction = "SetDeviceName"
)

// RemoteActionPUnknown returns a pointer to RemoteActionVUnknown
func RemoteActionPUnknown() *RemoteAction {
	v := RemoteActionVUnknown
	return &v
}

// RemoteActionPFactoryReset returns a pointer to RemoteActionVFactoryReset
func RemoteActionPFactoryReset() *RemoteAction {
	v := RemoteActionVFactoryReset
	return &v
}

// RemoteActionPRemoveCompanyData returns a pointer to RemoteActionVRemoveCompanyData
func RemoteActionPRemoveCompanyData() *RemoteAction {
	v := RemoteActionVRemoveCompanyData
	return &v
}

// RemoteActionPResetPasscode returns a pointer to RemoteActionVResetPasscode
func RemoteActionPResetPasscode() *RemoteAction {
	v := RemoteActionVResetPasscode
	return &v
}

// RemoteActionPRemoteLock returns a pointer to RemoteActionVRemoteLock
func RemoteActionPRemoteLock() *RemoteAction {
	v := RemoteActionVRemoteLock
	return &v
}

// RemoteActionPEnableLostMode returns a pointer to RemoteActionVEnableLostMode
func RemoteActionPEnableLostMode() *RemoteAction {
	v := RemoteActionVEnableLostMode
	return &v
}

// RemoteActionPDisableLostMode returns a pointer to RemoteActionVDisableLostMode
func RemoteActionPDisableLostMode() *RemoteAction {
	v := RemoteActionVDisableLostMode
	return &v
}

// RemoteActionPLocateDevice returns a pointer to RemoteActionVLocateDevice
func RemoteActionPLocateDevice() *RemoteAction {
	v := RemoteActionVLocateDevice
	return &v
}

// RemoteActionPRebootNow returns a pointer to RemoteActionVRebootNow
func RemoteActionPRebootNow() *RemoteAction {
	v := RemoteActionVRebootNow
	return &v
}

// RemoteActionPRecoverPasscode returns a pointer to RemoteActionVRecoverPasscode
func RemoteActionPRecoverPasscode() *RemoteAction {
	v := RemoteActionVRecoverPasscode
	return &v
}

// RemoteActionPCleanWindowsDevice returns a pointer to RemoteActionVCleanWindowsDevice
func RemoteActionPCleanWindowsDevice() *RemoteAction {
	v := RemoteActionVCleanWindowsDevice
	return &v
}

// RemoteActionPLogoutSharedAppleDeviceActiveUser returns a pointer to RemoteActionVLogoutSharedAppleDeviceActiveUser
func RemoteActionPLogoutSharedAppleDeviceActiveUser() *RemoteAction {
	v := RemoteActionVLogoutSharedAppleDeviceActiveUser
	return &v
}

// RemoteActionPQuickScan returns a pointer to RemoteActionVQuickScan
func RemoteActionPQuickScan() *RemoteAction {
	v := RemoteActionVQuickScan
	return &v
}

// RemoteActionPFullScan returns a pointer to RemoteActionVFullScan
func RemoteActionPFullScan() *RemoteAction {
	v := RemoteActionVFullScan
	return &v
}

// RemoteActionPWindowsDefenderUpdateSignatures returns a pointer to RemoteActionVWindowsDefenderUpdateSignatures
func RemoteActionPWindowsDefenderUpdateSignatures() *RemoteAction {
	v := RemoteActionVWindowsDefenderUpdateSignatures
	return &v
}

// RemoteActionPFactoryResetKeepEnrollmentData returns a pointer to RemoteActionVFactoryResetKeepEnrollmentData
func RemoteActionPFactoryResetKeepEnrollmentData() *RemoteAction {
	v := RemoteActionVFactoryResetKeepEnrollmentData
	return &v
}

// RemoteActionPUpdateDeviceAccount returns a pointer to RemoteActionVUpdateDeviceAccount
func RemoteActionPUpdateDeviceAccount() *RemoteAction {
	v := RemoteActionVUpdateDeviceAccount
	return &v
}

// RemoteActionPAutomaticRedeployment returns a pointer to RemoteActionVAutomaticRedeployment
func RemoteActionPAutomaticRedeployment() *RemoteAction {
	v := RemoteActionVAutomaticRedeployment
	return &v
}

// RemoteActionPShutDown returns a pointer to RemoteActionVShutDown
func RemoteActionPShutDown() *RemoteAction {
	v := RemoteActionVShutDown
	return &v
}

// RemoteActionPRotateBitLockerKeys returns a pointer to RemoteActionVRotateBitLockerKeys
func RemoteActionPRotateBitLockerKeys() *RemoteAction {
	v := RemoteActionVRotateBitLockerKeys
	return &v
}

// RemoteActionPRotateFileVaultKey returns a pointer to RemoteActionVRotateFileVaultKey
func RemoteActionPRotateFileVaultKey() *RemoteAction {
	v := RemoteActionVRotateFileVaultKey
	return &v
}

// RemoteActionPGetFileVaultKey returns a pointer to RemoteActionVGetFileVaultKey
func RemoteActionPGetFileVaultKey() *RemoteAction {
	v := RemoteActionVGetFileVaultKey
	return &v
}

// RemoteActionPSetDeviceName returns a pointer to RemoteActionVSetDeviceName
func RemoteActionPSetDeviceName() *RemoteAction {
	v := RemoteActionVSetDeviceName
	return &v
}
