// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RequiredPasswordType undocumented
type RequiredPasswordType string

const (
	// RequiredPasswordTypeVDeviceDefault undocumented
	RequiredPasswordTypeVDeviceDefault RequiredPasswordType = "DeviceDefault"
	// RequiredPasswordTypeVAlphanumeric undocumented
	RequiredPasswordTypeVAlphanumeric RequiredPasswordType = "Alphanumeric"
	// RequiredPasswordTypeVNumeric undocumented
	RequiredPasswordTypeVNumeric RequiredPasswordType = "Numeric"
)

// RequiredPasswordTypePDeviceDefault returns a pointer to RequiredPasswordTypeVDeviceDefault
func RequiredPasswordTypePDeviceDefault() *RequiredPasswordType {
	v := RequiredPasswordTypeVDeviceDefault
	return &v
}

// RequiredPasswordTypePAlphanumeric returns a pointer to RequiredPasswordTypeVAlphanumeric
func RequiredPasswordTypePAlphanumeric() *RequiredPasswordType {
	v := RequiredPasswordTypeVAlphanumeric
	return &v
}

// RequiredPasswordTypePNumeric returns a pointer to RequiredPasswordTypeVNumeric
func RequiredPasswordTypePNumeric() *RequiredPasswordType {
	v := RequiredPasswordTypeVNumeric
	return &v
}
