// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RestrictionAction undocumented
type RestrictionAction string

const (
	// RestrictionActionVWarn undocumented
	RestrictionActionVWarn RestrictionAction = "Warn"
	// RestrictionActionVAudit undocumented
	RestrictionActionVAudit RestrictionAction = "Audit"
	// RestrictionActionVBlock undocumented
	RestrictionActionVBlock RestrictionAction = "Block"
)

// RestrictionActionPWarn returns a pointer to RestrictionActionVWarn
func RestrictionActionPWarn() *RestrictionAction {
	v := RestrictionActionVWarn
	return &v
}

// RestrictionActionPAudit returns a pointer to RestrictionActionVAudit
func RestrictionActionPAudit() *RestrictionAction {
	v := RestrictionActionVAudit
	return &v
}

// RestrictionActionPBlock returns a pointer to RestrictionActionVBlock
func RestrictionActionPBlock() *RestrictionAction {
	v := RestrictionActionVBlock
	return &v
}
