// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RestrictionTrigger undocumented
type RestrictionTrigger string

const (
	// RestrictionTriggerVCopyPaste undocumented
	RestrictionTriggerVCopyPaste RestrictionTrigger = "CopyPaste"
	// RestrictionTriggerVCopyToNetworkShare undocumented
	RestrictionTriggerVCopyToNetworkShare RestrictionTrigger = "CopyToNetworkShare"
	// RestrictionTriggerVCopyToRemovableMedia undocumented
	RestrictionTriggerVCopyToRemovableMedia RestrictionTrigger = "CopyToRemovableMedia"
	// RestrictionTriggerVScreenCapture undocumented
	RestrictionTriggerVScreenCapture RestrictionTrigger = "ScreenCapture"
	// RestrictionTriggerVPrint undocumented
	RestrictionTriggerVPrint RestrictionTrigger = "Print"
	// RestrictionTriggerVCloudEgress undocumented
	RestrictionTriggerVCloudEgress RestrictionTrigger = "CloudEgress"
	// RestrictionTriggerVUnallowedApps undocumented
	RestrictionTriggerVUnallowedApps RestrictionTrigger = "UnallowedApps"
)

// RestrictionTriggerPCopyPaste returns a pointer to RestrictionTriggerVCopyPaste
func RestrictionTriggerPCopyPaste() *RestrictionTrigger {
	v := RestrictionTriggerVCopyPaste
	return &v
}

// RestrictionTriggerPCopyToNetworkShare returns a pointer to RestrictionTriggerVCopyToNetworkShare
func RestrictionTriggerPCopyToNetworkShare() *RestrictionTrigger {
	v := RestrictionTriggerVCopyToNetworkShare
	return &v
}

// RestrictionTriggerPCopyToRemovableMedia returns a pointer to RestrictionTriggerVCopyToRemovableMedia
func RestrictionTriggerPCopyToRemovableMedia() *RestrictionTrigger {
	v := RestrictionTriggerVCopyToRemovableMedia
	return &v
}

// RestrictionTriggerPScreenCapture returns a pointer to RestrictionTriggerVScreenCapture
func RestrictionTriggerPScreenCapture() *RestrictionTrigger {
	v := RestrictionTriggerVScreenCapture
	return &v
}

// RestrictionTriggerPPrint returns a pointer to RestrictionTriggerVPrint
func RestrictionTriggerPPrint() *RestrictionTrigger {
	v := RestrictionTriggerVPrint
	return &v
}

// RestrictionTriggerPCloudEgress returns a pointer to RestrictionTriggerVCloudEgress
func RestrictionTriggerPCloudEgress() *RestrictionTrigger {
	v := RestrictionTriggerVCloudEgress
	return &v
}

// RestrictionTriggerPUnallowedApps returns a pointer to RestrictionTriggerVUnallowedApps
func RestrictionTriggerPUnallowedApps() *RestrictionTrigger {
	v := RestrictionTriggerVUnallowedApps
	return &v
}
