// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RiskDetectionTimingType undocumented
type RiskDetectionTimingType string

const (
	// RiskDetectionTimingTypeVNotDefined undocumented
	RiskDetectionTimingTypeVNotDefined RiskDetectionTimingType = "NotDefined"
	// RiskDetectionTimingTypeVRealtime undocumented
	RiskDetectionTimingTypeVRealtime RiskDetectionTimingType = "Realtime"
	// RiskDetectionTimingTypeVNearRealtime undocumented
	RiskDetectionTimingTypeVNearRealtime RiskDetectionTimingType = "NearRealtime"
	// RiskDetectionTimingTypeVOffline undocumented
	RiskDetectionTimingTypeVOffline RiskDetectionTimingType = "Offline"
	// RiskDetectionTimingTypeVUnknownFutureValue undocumented
	RiskDetectionTimingTypeVUnknownFutureValue RiskDetectionTimingType = "UnknownFutureValue"
)

// RiskDetectionTimingTypePNotDefined returns a pointer to RiskDetectionTimingTypeVNotDefined
func RiskDetectionTimingTypePNotDefined() *RiskDetectionTimingType {
	v := RiskDetectionTimingTypeVNotDefined
	return &v
}

// RiskDetectionTimingTypePRealtime returns a pointer to RiskDetectionTimingTypeVRealtime
func RiskDetectionTimingTypePRealtime() *RiskDetectionTimingType {
	v := RiskDetectionTimingTypeVRealtime
	return &v
}

// RiskDetectionTimingTypePNearRealtime returns a pointer to RiskDetectionTimingTypeVNearRealtime
func RiskDetectionTimingTypePNearRealtime() *RiskDetectionTimingType {
	v := RiskDetectionTimingTypeVNearRealtime
	return &v
}

// RiskDetectionTimingTypePOffline returns a pointer to RiskDetectionTimingTypeVOffline
func RiskDetectionTimingTypePOffline() *RiskDetectionTimingType {
	v := RiskDetectionTimingTypeVOffline
	return &v
}

// RiskDetectionTimingTypePUnknownFutureValue returns a pointer to RiskDetectionTimingTypeVUnknownFutureValue
func RiskDetectionTimingTypePUnknownFutureValue() *RiskDetectionTimingType {
	v := RiskDetectionTimingTypeVUnknownFutureValue
	return &v
}
