// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RiskEventStatus undocumented
type RiskEventStatus string

const (
	// RiskEventStatusVActive undocumented
	RiskEventStatusVActive RiskEventStatus = "Active"
	// RiskEventStatusVRemediated undocumented
	RiskEventStatusVRemediated RiskEventStatus = "Remediated"
	// RiskEventStatusVDismissedAsFixed undocumented
	RiskEventStatusVDismissedAsFixed RiskEventStatus = "DismissedAsFixed"
	// RiskEventStatusVDismissedAsFalsePositive undocumented
	RiskEventStatusVDismissedAsFalsePositive RiskEventStatus = "DismissedAsFalsePositive"
	// RiskEventStatusVDismissedAsIgnore undocumented
	RiskEventStatusVDismissedAsIgnore RiskEventStatus = "DismissedAsIgnore"
	// RiskEventStatusVLoginBlocked undocumented
	RiskEventStatusVLoginBlocked RiskEventStatus = "LoginBlocked"
	// RiskEventStatusVClosedMFAAuto undocumented
	RiskEventStatusVClosedMFAAuto RiskEventStatus = "ClosedMFAAuto"
	// RiskEventStatusVClosedMultipleReasons undocumented
	RiskEventStatusVClosedMultipleReasons RiskEventStatus = "ClosedMultipleReasons"
)

// RiskEventStatusPActive returns a pointer to RiskEventStatusVActive
func RiskEventStatusPActive() *RiskEventStatus {
	v := RiskEventStatusVActive
	return &v
}

// RiskEventStatusPRemediated returns a pointer to RiskEventStatusVRemediated
func RiskEventStatusPRemediated() *RiskEventStatus {
	v := RiskEventStatusVRemediated
	return &v
}

// RiskEventStatusPDismissedAsFixed returns a pointer to RiskEventStatusVDismissedAsFixed
func RiskEventStatusPDismissedAsFixed() *RiskEventStatus {
	v := RiskEventStatusVDismissedAsFixed
	return &v
}

// RiskEventStatusPDismissedAsFalsePositive returns a pointer to RiskEventStatusVDismissedAsFalsePositive
func RiskEventStatusPDismissedAsFalsePositive() *RiskEventStatus {
	v := RiskEventStatusVDismissedAsFalsePositive
	return &v
}

// RiskEventStatusPDismissedAsIgnore returns a pointer to RiskEventStatusVDismissedAsIgnore
func RiskEventStatusPDismissedAsIgnore() *RiskEventStatus {
	v := RiskEventStatusVDismissedAsIgnore
	return &v
}

// RiskEventStatusPLoginBlocked returns a pointer to RiskEventStatusVLoginBlocked
func RiskEventStatusPLoginBlocked() *RiskEventStatus {
	v := RiskEventStatusVLoginBlocked
	return &v
}

// RiskEventStatusPClosedMFAAuto returns a pointer to RiskEventStatusVClosedMFAAuto
func RiskEventStatusPClosedMFAAuto() *RiskEventStatus {
	v := RiskEventStatusVClosedMFAAuto
	return &v
}

// RiskEventStatusPClosedMultipleReasons returns a pointer to RiskEventStatusVClosedMultipleReasons
func RiskEventStatusPClosedMultipleReasons() *RiskEventStatus {
	v := RiskEventStatusVClosedMultipleReasons
	return &v
}
