// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RiskEventType undocumented
type RiskEventType string

const (
	// RiskEventTypeVUnlikelyTravel undocumented
	RiskEventTypeVUnlikelyTravel RiskEventType = "UnlikelyTravel"
	// RiskEventTypeVAnonymizedIPAddress undocumented
	RiskEventTypeVAnonymizedIPAddress RiskEventType = "AnonymizedIPAddress"
	// RiskEventTypeVMaliciousIPAddress undocumented
	RiskEventTypeVMaliciousIPAddress RiskEventType = "MaliciousIPAddress"
	// RiskEventTypeVUnfamiliarFeatures undocumented
	RiskEventTypeVUnfamiliarFeatures RiskEventType = "UnfamiliarFeatures"
	// RiskEventTypeVMalwareInfectedIPAddress undocumented
	RiskEventTypeVMalwareInfectedIPAddress RiskEventType = "MalwareInfectedIPAddress"
	// RiskEventTypeVSuspiciousIPAddress undocumented
	RiskEventTypeVSuspiciousIPAddress RiskEventType = "SuspiciousIPAddress"
	// RiskEventTypeVLeakedCredentials undocumented
	RiskEventTypeVLeakedCredentials RiskEventType = "LeakedCredentials"
	// RiskEventTypeVInvestigationsThreatIntelligence undocumented
	RiskEventTypeVInvestigationsThreatIntelligence RiskEventType = "InvestigationsThreatIntelligence"
	// RiskEventTypeVGeneric undocumented
	RiskEventTypeVGeneric RiskEventType = "Generic"
	// RiskEventTypeVAdminConfirmedUserCompromised undocumented
	RiskEventTypeVAdminConfirmedUserCompromised RiskEventType = "AdminConfirmedUserCompromised"
	// RiskEventTypeVMcasImpossibleTravel undocumented
	RiskEventTypeVMcasImpossibleTravel RiskEventType = "McasImpossibleTravel"
	// RiskEventTypeVMcasSuspiciousInboxManipulationRules undocumented
	RiskEventTypeVMcasSuspiciousInboxManipulationRules RiskEventType = "McasSuspiciousInboxManipulationRules"
	// RiskEventTypeVInvestigationsThreatIntelligenceSigninLinked undocumented
	RiskEventTypeVInvestigationsThreatIntelligenceSigninLinked RiskEventType = "InvestigationsThreatIntelligenceSigninLinked"
	// RiskEventTypeVMaliciousIPAddressValidCredentialsBlockedIP undocumented
	RiskEventTypeVMaliciousIPAddressValidCredentialsBlockedIP RiskEventType = "MaliciousIPAddressValidCredentialsBlockedIP"
	// RiskEventTypeVUnknownFutureValue undocumented
	RiskEventTypeVUnknownFutureValue RiskEventType = "UnknownFutureValue"
)

// RiskEventTypePUnlikelyTravel returns a pointer to RiskEventTypeVUnlikelyTravel
func RiskEventTypePUnlikelyTravel() *RiskEventType {
	v := RiskEventTypeVUnlikelyTravel
	return &v
}

// RiskEventTypePAnonymizedIPAddress returns a pointer to RiskEventTypeVAnonymizedIPAddress
func RiskEventTypePAnonymizedIPAddress() *RiskEventType {
	v := RiskEventTypeVAnonymizedIPAddress
	return &v
}

// RiskEventTypePMaliciousIPAddress returns a pointer to RiskEventTypeVMaliciousIPAddress
func RiskEventTypePMaliciousIPAddress() *RiskEventType {
	v := RiskEventTypeVMaliciousIPAddress
	return &v
}

// RiskEventTypePUnfamiliarFeatures returns a pointer to RiskEventTypeVUnfamiliarFeatures
func RiskEventTypePUnfamiliarFeatures() *RiskEventType {
	v := RiskEventTypeVUnfamiliarFeatures
	return &v
}

// RiskEventTypePMalwareInfectedIPAddress returns a pointer to RiskEventTypeVMalwareInfectedIPAddress
func RiskEventTypePMalwareInfectedIPAddress() *RiskEventType {
	v := RiskEventTypeVMalwareInfectedIPAddress
	return &v
}

// RiskEventTypePSuspiciousIPAddress returns a pointer to RiskEventTypeVSuspiciousIPAddress
func RiskEventTypePSuspiciousIPAddress() *RiskEventType {
	v := RiskEventTypeVSuspiciousIPAddress
	return &v
}

// RiskEventTypePLeakedCredentials returns a pointer to RiskEventTypeVLeakedCredentials
func RiskEventTypePLeakedCredentials() *RiskEventType {
	v := RiskEventTypeVLeakedCredentials
	return &v
}

// RiskEventTypePInvestigationsThreatIntelligence returns a pointer to RiskEventTypeVInvestigationsThreatIntelligence
func RiskEventTypePInvestigationsThreatIntelligence() *RiskEventType {
	v := RiskEventTypeVInvestigationsThreatIntelligence
	return &v
}

// RiskEventTypePGeneric returns a pointer to RiskEventTypeVGeneric
func RiskEventTypePGeneric() *RiskEventType {
	v := RiskEventTypeVGeneric
	return &v
}

// RiskEventTypePAdminConfirmedUserCompromised returns a pointer to RiskEventTypeVAdminConfirmedUserCompromised
func RiskEventTypePAdminConfirmedUserCompromised() *RiskEventType {
	v := RiskEventTypeVAdminConfirmedUserCompromised
	return &v
}

// RiskEventTypePMcasImpossibleTravel returns a pointer to RiskEventTypeVMcasImpossibleTravel
func RiskEventTypePMcasImpossibleTravel() *RiskEventType {
	v := RiskEventTypeVMcasImpossibleTravel
	return &v
}

// RiskEventTypePMcasSuspiciousInboxManipulationRules returns a pointer to RiskEventTypeVMcasSuspiciousInboxManipulationRules
func RiskEventTypePMcasSuspiciousInboxManipulationRules() *RiskEventType {
	v := RiskEventTypeVMcasSuspiciousInboxManipulationRules
	return &v
}

// RiskEventTypePInvestigationsThreatIntelligenceSigninLinked returns a pointer to RiskEventTypeVInvestigationsThreatIntelligenceSigninLinked
func RiskEventTypePInvestigationsThreatIntelligenceSigninLinked() *RiskEventType {
	v := RiskEventTypeVInvestigationsThreatIntelligenceSigninLinked
	return &v
}

// RiskEventTypePMaliciousIPAddressValidCredentialsBlockedIP returns a pointer to RiskEventTypeVMaliciousIPAddressValidCredentialsBlockedIP
func RiskEventTypePMaliciousIPAddressValidCredentialsBlockedIP() *RiskEventType {
	v := RiskEventTypeVMaliciousIPAddressValidCredentialsBlockedIP
	return &v
}

// RiskEventTypePUnknownFutureValue returns a pointer to RiskEventTypeVUnknownFutureValue
func RiskEventTypePUnknownFutureValue() *RiskEventType {
	v := RiskEventTypeVUnknownFutureValue
	return &v
}
