// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RoleAssignmentScopeType undocumented
type RoleAssignmentScopeType string

const (
	// RoleAssignmentScopeTypeVResourceScope undocumented
	RoleAssignmentScopeTypeVResourceScope RoleAssignmentScopeType = "ResourceScope"
	// RoleAssignmentScopeTypeVAllDevices undocumented
	RoleAssignmentScopeTypeVAllDevices RoleAssignmentScopeType = "AllDevices"
	// RoleAssignmentScopeTypeVAllLicensedUsers undocumented
	RoleAssignmentScopeTypeVAllLicensedUsers RoleAssignmentScopeType = "AllLicensedUsers"
	// RoleAssignmentScopeTypeVAllDevicesAndLicensedUsers undocumented
	RoleAssignmentScopeTypeVAllDevicesAndLicensedUsers RoleAssignmentScopeType = "AllDevicesAndLicensedUsers"
)

// RoleAssignmentScopeTypePResourceScope returns a pointer to RoleAssignmentScopeTypeVResourceScope
func RoleAssignmentScopeTypePResourceScope() *RoleAssignmentScopeType {
	v := RoleAssignmentScopeTypeVResourceScope
	return &v
}

// RoleAssignmentScopeTypePAllDevices returns a pointer to RoleAssignmentScopeTypeVAllDevices
func RoleAssignmentScopeTypePAllDevices() *RoleAssignmentScopeType {
	v := RoleAssignmentScopeTypeVAllDevices
	return &v
}

// RoleAssignmentScopeTypePAllLicensedUsers returns a pointer to RoleAssignmentScopeTypeVAllLicensedUsers
func RoleAssignmentScopeTypePAllLicensedUsers() *RoleAssignmentScopeType {
	v := RoleAssignmentScopeTypeVAllLicensedUsers
	return &v
}

// RoleAssignmentScopeTypePAllDevicesAndLicensedUsers returns a pointer to RoleAssignmentScopeTypeVAllDevicesAndLicensedUsers
func RoleAssignmentScopeTypePAllDevicesAndLicensedUsers() *RoleAssignmentScopeType {
	v := RoleAssignmentScopeTypeVAllDevicesAndLicensedUsers
	return &v
}
