// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RoutingPolicy undocumented
type RoutingPolicy string

const (
	// RoutingPolicyVNone undocumented
	RoutingPolicyVNone RoutingPolicy = "None"
	// RoutingPolicyVNoMissedCall undocumented
	RoutingPolicyVNoMissedCall RoutingPolicy = "NoMissedCall"
	// RoutingPolicyVDisableForwardingExceptPhone undocumented
	RoutingPolicyVDisableForwardingExceptPhone RoutingPolicy = "DisableForwardingExceptPhone"
	// RoutingPolicyVDisableForwarding undocumented
	RoutingPolicyVDisableForwarding RoutingPolicy = "DisableForwarding"
	// RoutingPolicyVPreferSkypeForBusiness undocumented
	RoutingPolicyVPreferSkypeForBusiness RoutingPolicy = "PreferSkypeForBusiness"
	// RoutingPolicyVUnknownFutureValue undocumented
	RoutingPolicyVUnknownFutureValue RoutingPolicy = "UnknownFutureValue"
)

// RoutingPolicyPNone returns a pointer to RoutingPolicyVNone
func RoutingPolicyPNone() *RoutingPolicy {
	v := RoutingPolicyVNone
	return &v
}

// RoutingPolicyPNoMissedCall returns a pointer to RoutingPolicyVNoMissedCall
func RoutingPolicyPNoMissedCall() *RoutingPolicy {
	v := RoutingPolicyVNoMissedCall
	return &v
}

// RoutingPolicyPDisableForwardingExceptPhone returns a pointer to RoutingPolicyVDisableForwardingExceptPhone
func RoutingPolicyPDisableForwardingExceptPhone() *RoutingPolicy {
	v := RoutingPolicyVDisableForwardingExceptPhone
	return &v
}

// RoutingPolicyPDisableForwarding returns a pointer to RoutingPolicyVDisableForwarding
func RoutingPolicyPDisableForwarding() *RoutingPolicy {
	v := RoutingPolicyVDisableForwarding
	return &v
}

// RoutingPolicyPPreferSkypeForBusiness returns a pointer to RoutingPolicyVPreferSkypeForBusiness
func RoutingPolicyPPreferSkypeForBusiness() *RoutingPolicy {
	v := RoutingPolicyVPreferSkypeForBusiness
	return &v
}

// RoutingPolicyPUnknownFutureValue returns a pointer to RoutingPolicyVUnknownFutureValue
func RoutingPolicyPUnknownFutureValue() *RoutingPolicy {
	v := RoutingPolicyVUnknownFutureValue
	return &v
}
