// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RunAsAccountType undocumented
type RunAsAccountType string

const (
	// RunAsAccountTypeVSystem undocumented
	RunAsAccountTypeVSystem RunAsAccountType = "System"
	// RunAsAccountTypeVUser undocumented
	RunAsAccountTypeVUser RunAsAccountType = "User"
)

// RunAsAccountTypePSystem returns a pointer to RunAsAccountTypeVSystem
func RunAsAccountTypePSystem() *RunAsAccountType {
	v := RunAsAccountTypeVSystem
	return &v
}

// RunAsAccountTypePUser returns a pointer to RunAsAccountTypeVUser
func RunAsAccountTypePUser() *RunAsAccountType {
	v := RunAsAccountTypeVUser
	return &v
}
