// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RunState undocumented
type RunState string

const (
	// RunStateVUnknown undocumented
	RunStateVUnknown RunState = "Unknown"
	// RunStateVSuccess undocumented
	RunStateVSuccess RunState = "Success"
	// RunStateVFail undocumented
	RunStateVFail RunState = "Fail"
	// RunStateVScriptError undocumented
	RunStateVScriptError RunState = "ScriptError"
	// RunStateVPending undocumented
	RunStateVPending RunState = "Pending"
	// RunStateVNotApplicable undocumented
	RunStateVNotApplicable RunState = "NotApplicable"
)

// RunStatePUnknown returns a pointer to RunStateVUnknown
func RunStatePUnknown() *RunState {
	v := RunStateVUnknown
	return &v
}

// RunStatePSuccess returns a pointer to RunStateVSuccess
func RunStatePSuccess() *RunState {
	v := RunStateVSuccess
	return &v
}

// RunStatePFail returns a pointer to RunStateVFail
func RunStatePFail() *RunState {
	v := RunStateVFail
	return &v
}

// RunStatePScriptError returns a pointer to RunStateVScriptError
func RunStatePScriptError() *RunState {
	v := RunStateVScriptError
	return &v
}

// RunStatePPending returns a pointer to RunStateVPending
func RunStatePPending() *RunState {
	v := RunStateVPending
	return &v
}

// RunStatePNotApplicable returns a pointer to RunStateVNotApplicable
func RunStatePNotApplicable() *RunState {
	v := RunStateVNotApplicable
	return &v
}
