// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ScheduleChangeState undocumented
type ScheduleChangeState string

const (
	// ScheduleChangeStateVPending undocumented
	ScheduleChangeStateVPending ScheduleChangeState = "Pending"
	// ScheduleChangeStateVApproved undocumented
	ScheduleChangeStateVApproved ScheduleChangeState = "Approved"
	// ScheduleChangeStateVDeclined undocumented
	ScheduleChangeStateVDeclined ScheduleChangeState = "Declined"
	// ScheduleChangeStateVUnknownFutureValue undocumented
	ScheduleChangeStateVUnknownFutureValue ScheduleChangeState = "UnknownFutureValue"
)

// ScheduleChangeStatePPending returns a pointer to ScheduleChangeStateVPending
func ScheduleChangeStatePPending() *ScheduleChangeState {
	v := ScheduleChangeStateVPending
	return &v
}

// ScheduleChangeStatePApproved returns a pointer to ScheduleChangeStateVApproved
func ScheduleChangeStatePApproved() *ScheduleChangeState {
	v := ScheduleChangeStateVApproved
	return &v
}

// ScheduleChangeStatePDeclined returns a pointer to ScheduleChangeStateVDeclined
func ScheduleChangeStatePDeclined() *ScheduleChangeState {
	v := ScheduleChangeStateVDeclined
	return &v
}

// ScheduleChangeStatePUnknownFutureValue returns a pointer to ScheduleChangeStateVUnknownFutureValue
func ScheduleChangeStatePUnknownFutureValue() *ScheduleChangeState {
	v := ScheduleChangeStateVUnknownFutureValue
	return &v
}
