// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ScheduleEntityTheme undocumented
type ScheduleEntityTheme string

const (
	// ScheduleEntityThemeVWhite undocumented
	ScheduleEntityThemeVWhite ScheduleEntityTheme = "White"
	// ScheduleEntityThemeVBlue undocumented
	ScheduleEntityThemeVBlue ScheduleEntityTheme = "Blue"
	// ScheduleEntityThemeVGreen undocumented
	ScheduleEntityThemeVGreen ScheduleEntityTheme = "Green"
	// ScheduleEntityThemeVPurple undocumented
	ScheduleEntityThemeVPurple ScheduleEntityTheme = "Purple"
	// ScheduleEntityThemeVPink undocumented
	ScheduleEntityThemeVPink ScheduleEntityTheme = "Pink"
	// ScheduleEntityThemeVYellow undocumented
	ScheduleEntityThemeVYellow ScheduleEntityTheme = "Yellow"
	// ScheduleEntityThemeVGray undocumented
	ScheduleEntityThemeVGray ScheduleEntityTheme = "Gray"
	// ScheduleEntityThemeVDarkBlue undocumented
	ScheduleEntityThemeVDarkBlue ScheduleEntityTheme = "DarkBlue"
	// ScheduleEntityThemeVDarkGreen undocumented
	ScheduleEntityThemeVDarkGreen ScheduleEntityTheme = "DarkGreen"
	// ScheduleEntityThemeVDarkPurple undocumented
	ScheduleEntityThemeVDarkPurple ScheduleEntityTheme = "DarkPurple"
	// ScheduleEntityThemeVDarkPink undocumented
	ScheduleEntityThemeVDarkPink ScheduleEntityTheme = "DarkPink"
	// ScheduleEntityThemeVDarkYellow undocumented
	ScheduleEntityThemeVDarkYellow ScheduleEntityTheme = "DarkYellow"
	// ScheduleEntityThemeVUnknownFutureValue undocumented
	ScheduleEntityThemeVUnknownFutureValue ScheduleEntityTheme = "UnknownFutureValue"
)

// ScheduleEntityThemePWhite returns a pointer to ScheduleEntityThemeVWhite
func ScheduleEntityThemePWhite() *ScheduleEntityTheme {
	v := ScheduleEntityThemeVWhite
	return &v
}

// ScheduleEntityThemePBlue returns a pointer to ScheduleEntityThemeVBlue
func ScheduleEntityThemePBlue() *ScheduleEntityTheme {
	v := ScheduleEntityThemeVBlue
	return &v
}

// ScheduleEntityThemePGreen returns a pointer to ScheduleEntityThemeVGreen
func ScheduleEntityThemePGreen() *ScheduleEntityTheme {
	v := ScheduleEntityThemeVGreen
	return &v
}

// ScheduleEntityThemePPurple returns a pointer to ScheduleEntityThemeVPurple
func ScheduleEntityThemePPurple() *ScheduleEntityTheme {
	v := ScheduleEntityThemeVPurple
	return &v
}

// ScheduleEntityThemePPink returns a pointer to ScheduleEntityThemeVPink
func ScheduleEntityThemePPink() *ScheduleEntityTheme {
	v := ScheduleEntityThemeVPink
	return &v
}

// ScheduleEntityThemePYellow returns a pointer to ScheduleEntityThemeVYellow
func ScheduleEntityThemePYellow() *ScheduleEntityTheme {
	v := ScheduleEntityThemeVYellow
	return &v
}

// ScheduleEntityThemePGray returns a pointer to ScheduleEntityThemeVGray
func ScheduleEntityThemePGray() *ScheduleEntityTheme {
	v := ScheduleEntityThemeVGray
	return &v
}

// ScheduleEntityThemePDarkBlue returns a pointer to ScheduleEntityThemeVDarkBlue
func ScheduleEntityThemePDarkBlue() *ScheduleEntityTheme {
	v := ScheduleEntityThemeVDarkBlue
	return &v
}

// ScheduleEntityThemePDarkGreen returns a pointer to ScheduleEntityThemeVDarkGreen
func ScheduleEntityThemePDarkGreen() *ScheduleEntityTheme {
	v := ScheduleEntityThemeVDarkGreen
	return &v
}

// ScheduleEntityThemePDarkPurple returns a pointer to ScheduleEntityThemeVDarkPurple
func ScheduleEntityThemePDarkPurple() *ScheduleEntityTheme {
	v := ScheduleEntityThemeVDarkPurple
	return &v
}

// ScheduleEntityThemePDarkPink returns a pointer to ScheduleEntityThemeVDarkPink
func ScheduleEntityThemePDarkPink() *ScheduleEntityTheme {
	v := ScheduleEntityThemeVDarkPink
	return &v
}

// ScheduleEntityThemePDarkYellow returns a pointer to ScheduleEntityThemeVDarkYellow
func ScheduleEntityThemePDarkYellow() *ScheduleEntityTheme {
	v := ScheduleEntityThemeVDarkYellow
	return &v
}

// ScheduleEntityThemePUnknownFutureValue returns a pointer to ScheduleEntityThemeVUnknownFutureValue
func ScheduleEntityThemePUnknownFutureValue() *ScheduleEntityTheme {
	v := ScheduleEntityThemeVUnknownFutureValue
	return &v
}
