// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ScopeOperatorType undocumented
type ScopeOperatorType string

const (
	// ScopeOperatorTypeVBinary undocumented
	ScopeOperatorTypeVBinary ScopeOperatorType = "Binary"
	// ScopeOperatorTypeVUnary undocumented
	ScopeOperatorTypeVUnary ScopeOperatorType = "Unary"
)

// ScopeOperatorTypePBinary returns a pointer to ScopeOperatorTypeVBinary
func ScopeOperatorTypePBinary() *ScopeOperatorType {
	v := ScopeOperatorTypeVBinary
	return &v
}

// ScopeOperatorTypePUnary returns a pointer to ScopeOperatorTypeVUnary
func ScopeOperatorTypePUnary() *ScopeOperatorType {
	v := ScopeOperatorTypeVUnary
	return &v
}
