// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// SecureBootWithDMAType undocumented
type SecureBootWithDMAType string

const (
	// SecureBootWithDMATypeVNotConfigured undocumented
	SecureBootWithDMATypeVNotConfigured SecureBootWithDMAType = "NotConfigured"
	// SecureBootWithDMATypeVWithoutDMA undocumented
	SecureBootWithDMATypeVWithoutDMA SecureBootWithDMAType = "WithoutDMA"
	// SecureBootWithDMATypeVWithDMA undocumented
	SecureBootWithDMATypeVWithDMA SecureBootWithDMAType = "WithDMA"
)

// SecureBootWithDMATypePNotConfigured returns a pointer to SecureBootWithDMATypeVNotConfigured
func SecureBootWithDMATypePNotConfigured() *SecureBootWithDMAType {
	v := SecureBootWithDMATypeVNotConfigured
	return &v
}

// SecureBootWithDMATypePWithoutDMA returns a pointer to SecureBootWithDMATypeVWithoutDMA
func SecureBootWithDMATypePWithoutDMA() *SecureBootWithDMAType {
	v := SecureBootWithDMATypeVWithoutDMA
	return &v
}

// SecureBootWithDMATypePWithDMA returns a pointer to SecureBootWithDMATypeVWithDMA
func SecureBootWithDMATypePWithDMA() *SecureBootWithDMAType {
	v := SecureBootWithDMATypeVWithDMA
	return &v
}
