// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ServiceStartType undocumented
type ServiceStartType string

const (
	// ServiceStartTypeVManual undocumented
	ServiceStartTypeVManual ServiceStartType = "Manual"
	// ServiceStartTypeVAutomatic undocumented
	ServiceStartTypeVAutomatic ServiceStartType = "Automatic"
	// ServiceStartTypeVDisabled undocumented
	ServiceStartTypeVDisabled ServiceStartType = "Disabled"
)

// ServiceStartTypePManual returns a pointer to ServiceStartTypeVManual
func ServiceStartTypePManual() *ServiceStartType {
	v := ServiceStartTypeVManual
	return &v
}

// ServiceStartTypePAutomatic returns a pointer to ServiceStartTypeVAutomatic
func ServiceStartTypePAutomatic() *ServiceStartType {
	v := ServiceStartTypeVAutomatic
	return &v
}

// ServiceStartTypePDisabled returns a pointer to ServiceStartTypeVDisabled
func ServiceStartTypePDisabled() *ServiceStartType {
	v := ServiceStartTypeVDisabled
	return &v
}
