// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// SharedPCAllowedAccountType undocumented
type SharedPCAllowedAccountType string

const (
	// SharedPCAllowedAccountTypeVNotConfigured undocumented
	SharedPCAllowedAccountTypeVNotConfigured SharedPCAllowedAccountType = "NotConfigured"
	// SharedPCAllowedAccountTypeVGuest undocumented
	SharedPCAllowedAccountTypeVGuest SharedPCAllowedAccountType = "Guest"
	// SharedPCAllowedAccountTypeVDomain undocumented
	SharedPCAllowedAccountTypeVDomain SharedPCAllowedAccountType = "Domain"
)

// SharedPCAllowedAccountTypePNotConfigured returns a pointer to SharedPCAllowedAccountTypeVNotConfigured
func SharedPCAllowedAccountTypePNotConfigured() *SharedPCAllowedAccountType {
	v := SharedPCAllowedAccountTypeVNotConfigured
	return &v
}

// SharedPCAllowedAccountTypePGuest returns a pointer to SharedPCAllowedAccountTypeVGuest
func SharedPCAllowedAccountTypePGuest() *SharedPCAllowedAccountType {
	v := SharedPCAllowedAccountTypeVGuest
	return &v
}

// SharedPCAllowedAccountTypePDomain returns a pointer to SharedPCAllowedAccountTypeVDomain
func SharedPCAllowedAccountTypePDomain() *SharedPCAllowedAccountType {
	v := SharedPCAllowedAccountTypeVDomain
	return &v
}
