// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// SignInAssistantOptions undocumented
type SignInAssistantOptions string

const (
	// SignInAssistantOptionsVNotConfigured undocumented
	SignInAssistantOptionsVNotConfigured SignInAssistantOptions = "NotConfigured"
	// SignInAssistantOptionsVDisabled undocumented
	SignInAssistantOptionsVDisabled SignInAssistantOptions = "Disabled"
)

// SignInAssistantOptionsPNotConfigured returns a pointer to SignInAssistantOptionsVNotConfigured
func SignInAssistantOptionsPNotConfigured() *SignInAssistantOptions {
	v := SignInAssistantOptionsVNotConfigured
	return &v
}

// SignInAssistantOptionsPDisabled returns a pointer to SignInAssistantOptionsVDisabled
func SignInAssistantOptionsPDisabled() *SignInAssistantOptions {
	v := SignInAssistantOptionsVDisabled
	return &v
}
