// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// Status undocumented
type Status string

const (
	// StatusVActive undocumented
	StatusVActive Status = "Active"
	// StatusVUpdated undocumented
	StatusVUpdated Status = "Updated"
	// StatusVDeleted undocumented
	StatusVDeleted Status = "Deleted"
	// StatusVIgnored undocumented
	StatusVIgnored Status = "Ignored"
	// StatusVUnknownFutureValue undocumented
	StatusVUnknownFutureValue Status = "UnknownFutureValue"
)

// StatusPActive returns a pointer to StatusVActive
func StatusPActive() *Status {
	v := StatusVActive
	return &v
}

// StatusPUpdated returns a pointer to StatusVUpdated
func StatusPUpdated() *Status {
	v := StatusVUpdated
	return &v
}

// StatusPDeleted returns a pointer to StatusVDeleted
func StatusPDeleted() *Status {
	v := StatusVDeleted
	return &v
}

// StatusPIgnored returns a pointer to StatusVIgnored
func StatusPIgnored() *Status {
	v := StatusVIgnored
	return &v
}

// StatusPUnknownFutureValue returns a pointer to StatusVUnknownFutureValue
func StatusPUnknownFutureValue() *Status {
	v := StatusVUnknownFutureValue
	return &v
}
