// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// SubjectNameFormat undocumented
type SubjectNameFormat string

const (
	// SubjectNameFormatVCommonName undocumented
	SubjectNameFormatVCommonName SubjectNameFormat = "CommonName"
	// SubjectNameFormatVCommonNameIncludingEmail undocumented
	SubjectNameFormatVCommonNameIncludingEmail SubjectNameFormat = "CommonNameIncludingEmail"
	// SubjectNameFormatVCommonNameAsEmail undocumented
	SubjectNameFormatVCommonNameAsEmail SubjectNameFormat = "CommonNameAsEmail"
	// SubjectNameFormatVCustom undocumented
	SubjectNameFormatVCustom SubjectNameFormat = "Custom"
	// SubjectNameFormatVCommonNameAsIMEI undocumented
	SubjectNameFormatVCommonNameAsIMEI SubjectNameFormat = "CommonNameAsIMEI"
	// SubjectNameFormatVCommonNameAsSerialNumber undocumented
	SubjectNameFormatVCommonNameAsSerialNumber SubjectNameFormat = "CommonNameAsSerialNumber"
	// SubjectNameFormatVCommonNameAsAadDeviceID undocumented
	SubjectNameFormatVCommonNameAsAadDeviceID SubjectNameFormat = "CommonNameAsAadDeviceID"
	// SubjectNameFormatVCommonNameAsIntuneDeviceID undocumented
	SubjectNameFormatVCommonNameAsIntuneDeviceID SubjectNameFormat = "CommonNameAsIntuneDeviceID"
	// SubjectNameFormatVCommonNameAsDurableDeviceID undocumented
	SubjectNameFormatVCommonNameAsDurableDeviceID SubjectNameFormat = "CommonNameAsDurableDeviceID"
)

// SubjectNameFormatPCommonName returns a pointer to SubjectNameFormatVCommonName
func SubjectNameFormatPCommonName() *SubjectNameFormat {
	v := SubjectNameFormatVCommonName
	return &v
}

// SubjectNameFormatPCommonNameIncludingEmail returns a pointer to SubjectNameFormatVCommonNameIncludingEmail
func SubjectNameFormatPCommonNameIncludingEmail() *SubjectNameFormat {
	v := SubjectNameFormatVCommonNameIncludingEmail
	return &v
}

// SubjectNameFormatPCommonNameAsEmail returns a pointer to SubjectNameFormatVCommonNameAsEmail
func SubjectNameFormatPCommonNameAsEmail() *SubjectNameFormat {
	v := SubjectNameFormatVCommonNameAsEmail
	return &v
}

// SubjectNameFormatPCustom returns a pointer to SubjectNameFormatVCustom
func SubjectNameFormatPCustom() *SubjectNameFormat {
	v := SubjectNameFormatVCustom
	return &v
}

// SubjectNameFormatPCommonNameAsIMEI returns a pointer to SubjectNameFormatVCommonNameAsIMEI
func SubjectNameFormatPCommonNameAsIMEI() *SubjectNameFormat {
	v := SubjectNameFormatVCommonNameAsIMEI
	return &v
}

// SubjectNameFormatPCommonNameAsSerialNumber returns a pointer to SubjectNameFormatVCommonNameAsSerialNumber
func SubjectNameFormatPCommonNameAsSerialNumber() *SubjectNameFormat {
	v := SubjectNameFormatVCommonNameAsSerialNumber
	return &v
}

// SubjectNameFormatPCommonNameAsAadDeviceID returns a pointer to SubjectNameFormatVCommonNameAsAadDeviceID
func SubjectNameFormatPCommonNameAsAadDeviceID() *SubjectNameFormat {
	v := SubjectNameFormatVCommonNameAsAadDeviceID
	return &v
}

// SubjectNameFormatPCommonNameAsIntuneDeviceID returns a pointer to SubjectNameFormatVCommonNameAsIntuneDeviceID
func SubjectNameFormatPCommonNameAsIntuneDeviceID() *SubjectNameFormat {
	v := SubjectNameFormatVCommonNameAsIntuneDeviceID
	return &v
}

// SubjectNameFormatPCommonNameAsDurableDeviceID returns a pointer to SubjectNameFormatVCommonNameAsDurableDeviceID
func SubjectNameFormatPCommonNameAsDurableDeviceID() *SubjectNameFormat {
	v := SubjectNameFormatVCommonNameAsDurableDeviceID
	return &v
}
