// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// SubjectAlternativeNameType undocumented
type SubjectAlternativeNameType string

const (
	// SubjectAlternativeNameTypeVNone undocumented
	SubjectAlternativeNameTypeVNone SubjectAlternativeNameType = "None"
	// SubjectAlternativeNameTypeVEmailAddress undocumented
	SubjectAlternativeNameTypeVEmailAddress SubjectAlternativeNameType = "EmailAddress"
	// SubjectAlternativeNameTypeVUserPrincipalName undocumented
	SubjectAlternativeNameTypeVUserPrincipalName SubjectAlternativeNameType = "UserPrincipalName"
	// SubjectAlternativeNameTypeVCustomAzureADAttribute undocumented
	SubjectAlternativeNameTypeVCustomAzureADAttribute SubjectAlternativeNameType = "CustomAzureADAttribute"
	// SubjectAlternativeNameTypeVDomainNameService undocumented
	SubjectAlternativeNameTypeVDomainNameService SubjectAlternativeNameType = "DomainNameService"
)

// SubjectAlternativeNameTypePNone returns a pointer to SubjectAlternativeNameTypeVNone
func SubjectAlternativeNameTypePNone() *SubjectAlternativeNameType {
	v := SubjectAlternativeNameTypeVNone
	return &v
}

// SubjectAlternativeNameTypePEmailAddress returns a pointer to SubjectAlternativeNameTypeVEmailAddress
func SubjectAlternativeNameTypePEmailAddress() *SubjectAlternativeNameType {
	v := SubjectAlternativeNameTypeVEmailAddress
	return &v
}

// SubjectAlternativeNameTypePUserPrincipalName returns a pointer to SubjectAlternativeNameTypeVUserPrincipalName
func SubjectAlternativeNameTypePUserPrincipalName() *SubjectAlternativeNameType {
	v := SubjectAlternativeNameTypeVUserPrincipalName
	return &v
}

// SubjectAlternativeNameTypePCustomAzureADAttribute returns a pointer to SubjectAlternativeNameTypeVCustomAzureADAttribute
func SubjectAlternativeNameTypePCustomAzureADAttribute() *SubjectAlternativeNameType {
	v := SubjectAlternativeNameTypeVCustomAzureADAttribute
	return &v
}

// SubjectAlternativeNameTypePDomainNameService returns a pointer to SubjectAlternativeNameTypeVDomainNameService
func SubjectAlternativeNameTypePDomainNameService() *SubjectAlternativeNameType {
	v := SubjectAlternativeNameTypeVDomainNameService
	return &v
}
