// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// SynchronizationTaskExecutionResult undocumented
type SynchronizationTaskExecutionResult string

const (
	// SynchronizationTaskExecutionResultVSucceeded undocumented
	SynchronizationTaskExecutionResultVSucceeded SynchronizationTaskExecutionResult = "Succeeded"
	// SynchronizationTaskExecutionResultVFailed undocumented
	SynchronizationTaskExecutionResultVFailed SynchronizationTaskExecutionResult = "Failed"
	// SynchronizationTaskExecutionResultVEntryLevelErrors undocumented
	SynchronizationTaskExecutionResultVEntryLevelErrors SynchronizationTaskExecutionResult = "EntryLevelErrors"
)

// SynchronizationTaskExecutionResultPSucceeded returns a pointer to SynchronizationTaskExecutionResultVSucceeded
func SynchronizationTaskExecutionResultPSucceeded() *SynchronizationTaskExecutionResult {
	v := SynchronizationTaskExecutionResultVSucceeded
	return &v
}

// SynchronizationTaskExecutionResultPFailed returns a pointer to SynchronizationTaskExecutionResultVFailed
func SynchronizationTaskExecutionResultPFailed() *SynchronizationTaskExecutionResult {
	v := SynchronizationTaskExecutionResultVFailed
	return &v
}

// SynchronizationTaskExecutionResultPEntryLevelErrors returns a pointer to SynchronizationTaskExecutionResultVEntryLevelErrors
func SynchronizationTaskExecutionResultPEntryLevelErrors() *SynchronizationTaskExecutionResult {
	v := SynchronizationTaskExecutionResultVEntryLevelErrors
	return &v
}
