// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// TaskStatus undocumented
type TaskStatus string

const (
	// TaskStatusVNotStarted undocumented
	TaskStatusVNotStarted TaskStatus = "NotStarted"
	// TaskStatusVInProgress undocumented
	TaskStatusVInProgress TaskStatus = "InProgress"
	// TaskStatusVCompleted undocumented
	TaskStatusVCompleted TaskStatus = "Completed"
	// TaskStatusVWaitingOnOthers undocumented
	TaskStatusVWaitingOnOthers TaskStatus = "WaitingOnOthers"
	// TaskStatusVDeferred undocumented
	TaskStatusVDeferred TaskStatus = "Deferred"
)

// TaskStatusPNotStarted returns a pointer to TaskStatusVNotStarted
func TaskStatusPNotStarted() *TaskStatus {
	v := TaskStatusVNotStarted
	return &v
}

// TaskStatusPInProgress returns a pointer to TaskStatusVInProgress
func TaskStatusPInProgress() *TaskStatus {
	v := TaskStatusVInProgress
	return &v
}

// TaskStatusPCompleted returns a pointer to TaskStatusVCompleted
func TaskStatusPCompleted() *TaskStatus {
	v := TaskStatusVCompleted
	return &v
}

// TaskStatusPWaitingOnOthers returns a pointer to TaskStatusVWaitingOnOthers
func TaskStatusPWaitingOnOthers() *TaskStatus {
	v := TaskStatusVWaitingOnOthers
	return &v
}

// TaskStatusPDeferred returns a pointer to TaskStatusVDeferred
func TaskStatusPDeferred() *TaskStatus {
	v := TaskStatusVDeferred
	return &v
}
