// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// TeamsAsyncOperationType undocumented
type TeamsAsyncOperationType string

const (
	// TeamsAsyncOperationTypeVInvalid undocumented
	TeamsAsyncOperationTypeVInvalid TeamsAsyncOperationType = "Invalid"
	// TeamsAsyncOperationTypeVCloneTeam undocumented
	TeamsAsyncOperationTypeVCloneTeam TeamsAsyncOperationType = "CloneTeam"
	// TeamsAsyncOperationTypeVArchiveTeam undocumented
	TeamsAsyncOperationTypeVArchiveTeam TeamsAsyncOperationType = "ArchiveTeam"
	// TeamsAsyncOperationTypeVUnarchiveTeam undocumented
	TeamsAsyncOperationTypeVUnarchiveTeam TeamsAsyncOperationType = "UnarchiveTeam"
	// TeamsAsyncOperationTypeVCreateTeam undocumented
	TeamsAsyncOperationTypeVCreateTeam TeamsAsyncOperationType = "CreateTeam"
	// TeamsAsyncOperationTypeVUnknownFutureValue undocumented
	TeamsAsyncOperationTypeVUnknownFutureValue TeamsAsyncOperationType = "UnknownFutureValue"
)

// TeamsAsyncOperationTypePInvalid returns a pointer to TeamsAsyncOperationTypeVInvalid
func TeamsAsyncOperationTypePInvalid() *TeamsAsyncOperationType {
	v := TeamsAsyncOperationTypeVInvalid
	return &v
}

// TeamsAsyncOperationTypePCloneTeam returns a pointer to TeamsAsyncOperationTypeVCloneTeam
func TeamsAsyncOperationTypePCloneTeam() *TeamsAsyncOperationType {
	v := TeamsAsyncOperationTypeVCloneTeam
	return &v
}

// TeamsAsyncOperationTypePArchiveTeam returns a pointer to TeamsAsyncOperationTypeVArchiveTeam
func TeamsAsyncOperationTypePArchiveTeam() *TeamsAsyncOperationType {
	v := TeamsAsyncOperationTypeVArchiveTeam
	return &v
}

// TeamsAsyncOperationTypePUnarchiveTeam returns a pointer to TeamsAsyncOperationTypeVUnarchiveTeam
func TeamsAsyncOperationTypePUnarchiveTeam() *TeamsAsyncOperationType {
	v := TeamsAsyncOperationTypeVUnarchiveTeam
	return &v
}

// TeamsAsyncOperationTypePCreateTeam returns a pointer to TeamsAsyncOperationTypeVCreateTeam
func TeamsAsyncOperationTypePCreateTeam() *TeamsAsyncOperationType {
	v := TeamsAsyncOperationTypeVCreateTeam
	return &v
}

// TeamsAsyncOperationTypePUnknownFutureValue returns a pointer to TeamsAsyncOperationTypeVUnknownFutureValue
func TeamsAsyncOperationTypePUnknownFutureValue() *TeamsAsyncOperationType {
	v := TeamsAsyncOperationTypeVUnknownFutureValue
	return &v
}
