// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ThreatCategory undocumented
type ThreatCategory string

const (
	// ThreatCategoryVSpam undocumented
	ThreatCategoryVSpam ThreatCategory = "Spam"
	// ThreatCategoryVPhishing undocumented
	ThreatCategoryVPhishing ThreatCategory = "Phishing"
	// ThreatCategoryVMalware undocumented
	ThreatCategoryVMalware ThreatCategory = "Malware"
	// ThreatCategoryVUnknownFutureValue undocumented
	ThreatCategoryVUnknownFutureValue ThreatCategory = "UnknownFutureValue"
)

// ThreatCategoryPSpam returns a pointer to ThreatCategoryVSpam
func ThreatCategoryPSpam() *ThreatCategory {
	v := ThreatCategoryVSpam
	return &v
}

// ThreatCategoryPPhishing returns a pointer to ThreatCategoryVPhishing
func ThreatCategoryPPhishing() *ThreatCategory {
	v := ThreatCategoryVPhishing
	return &v
}

// ThreatCategoryPMalware returns a pointer to ThreatCategoryVMalware
func ThreatCategoryPMalware() *ThreatCategory {
	v := ThreatCategoryVMalware
	return &v
}

// ThreatCategoryPUnknownFutureValue returns a pointer to ThreatCategoryVUnknownFutureValue
func ThreatCategoryPUnknownFutureValue() *ThreatCategory {
	v := ThreatCategoryVUnknownFutureValue
	return &v
}
