// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ThreatAssessmentResultType undocumented
type ThreatAssessmentResultType string

const (
	// ThreatAssessmentResultTypeVCheckPolicy undocumented
	ThreatAssessmentResultTypeVCheckPolicy ThreatAssessmentResultType = "CheckPolicy"
	// ThreatAssessmentResultTypeVRescan undocumented
	ThreatAssessmentResultTypeVRescan ThreatAssessmentResultType = "Rescan"
	// ThreatAssessmentResultTypeVUnknownFutureValue undocumented
	ThreatAssessmentResultTypeVUnknownFutureValue ThreatAssessmentResultType = "UnknownFutureValue"
)

// ThreatAssessmentResultTypePCheckPolicy returns a pointer to ThreatAssessmentResultTypeVCheckPolicy
func ThreatAssessmentResultTypePCheckPolicy() *ThreatAssessmentResultType {
	v := ThreatAssessmentResultTypeVCheckPolicy
	return &v
}

// ThreatAssessmentResultTypePRescan returns a pointer to ThreatAssessmentResultTypeVRescan
func ThreatAssessmentResultTypePRescan() *ThreatAssessmentResultType {
	v := ThreatAssessmentResultTypeVRescan
	return &v
}

// ThreatAssessmentResultTypePUnknownFutureValue returns a pointer to ThreatAssessmentResultTypeVUnknownFutureValue
func ThreatAssessmentResultTypePUnknownFutureValue() *ThreatAssessmentResultType {
	v := ThreatAssessmentResultTypeVUnknownFutureValue
	return &v
}
