// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// TlpLevel undocumented
type TlpLevel string

const (
	// TlpLevelVUnknown undocumented
	TlpLevelVUnknown TlpLevel = "Unknown"
	// TlpLevelVWhite undocumented
	TlpLevelVWhite TlpLevel = "White"
	// TlpLevelVGreen undocumented
	TlpLevelVGreen TlpLevel = "Green"
	// TlpLevelVAmber undocumented
	TlpLevelVAmber TlpLevel = "Amber"
	// TlpLevelVRed undocumented
	TlpLevelVRed TlpLevel = "Red"
	// TlpLevelVUnknownFutureValue undocumented
	TlpLevelVUnknownFutureValue TlpLevel = "UnknownFutureValue"
)

// TlpLevelPUnknown returns a pointer to TlpLevelVUnknown
func TlpLevelPUnknown() *TlpLevel {
	v := TlpLevelVUnknown
	return &v
}

// TlpLevelPWhite returns a pointer to TlpLevelVWhite
func TlpLevelPWhite() *TlpLevel {
	v := TlpLevelVWhite
	return &v
}

// TlpLevelPGreen returns a pointer to TlpLevelVGreen
func TlpLevelPGreen() *TlpLevel {
	v := TlpLevelVGreen
	return &v
}

// TlpLevelPAmber returns a pointer to TlpLevelVAmber
func TlpLevelPAmber() *TlpLevel {
	v := TlpLevelVAmber
	return &v
}

// TlpLevelPRed returns a pointer to TlpLevelVRed
func TlpLevelPRed() *TlpLevel {
	v := TlpLevelVRed
	return &v
}

// TlpLevelPUnknownFutureValue returns a pointer to TlpLevelVUnknownFutureValue
func TlpLevelPUnknownFutureValue() *TlpLevel {
	v := TlpLevelVUnknownFutureValue
	return &v
}
