// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// TokenIssuerType undocumented
type TokenIssuerType string

const (
	// TokenIssuerTypeVAzureAD undocumented
	TokenIssuerTypeVAzureAD TokenIssuerType = "AzureAD"
	// TokenIssuerTypeVADFederationServices undocumented
	TokenIssuerTypeVADFederationServices TokenIssuerType = "ADFederationServices"
	// TokenIssuerTypeVUnknownFutureValue undocumented
	TokenIssuerTypeVUnknownFutureValue TokenIssuerType = "UnknownFutureValue"
)

// TokenIssuerTypePAzureAD returns a pointer to TokenIssuerTypeVAzureAD
func TokenIssuerTypePAzureAD() *TokenIssuerType {
	v := TokenIssuerTypeVAzureAD
	return &v
}

// TokenIssuerTypePADFederationServices returns a pointer to TokenIssuerTypeVADFederationServices
func TokenIssuerTypePADFederationServices() *TokenIssuerType {
	v := TokenIssuerTypeVADFederationServices
	return &v
}

// TokenIssuerTypePUnknownFutureValue returns a pointer to TokenIssuerTypeVUnknownFutureValue
func TokenIssuerTypePUnknownFutureValue() *TokenIssuerType {
	v := TokenIssuerTypeVUnknownFutureValue
	return &v
}
