// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

import "context"

// TrustFrameworkPolicyRequestBuilder is request builder for TrustFrameworkPolicy
type TrustFrameworkPolicyRequestBuilder struct{ BaseRequestBuilder }

// Request returns TrustFrameworkPolicyRequest
func (b *TrustFrameworkPolicyRequestBuilder) Request() *TrustFrameworkPolicyRequest {
	return &TrustFrameworkPolicyRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Delta appends "/delta" onto the builder
func (b *TrustFrameworkPolicyRequestBuilder) Delta() *TrustFrameworkPolicyRequestBuilder {
	b.baseUrl = b.baseUrl + "/delta"
	return b
}

// TrustFrameworkPolicyRequest is request for TrustFrameworkPolicy
type TrustFrameworkPolicyRequest struct{ BaseRequest }

// Get performs GET request for TrustFrameworkPolicy
func (r *TrustFrameworkPolicyRequest) Get(ctx context.Context) (resObj *TrustFrameworkPolicy, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for TrustFrameworkPolicy
func (r *TrustFrameworkPolicyRequest) Update(ctx context.Context, reqObj *TrustFrameworkPolicy) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for TrustFrameworkPolicy
func (r *TrustFrameworkPolicyRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
