// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// UpdateClassification undocumented
type UpdateClassification string

const (
	// UpdateClassificationVUserDefined undocumented
	UpdateClassificationVUserDefined UpdateClassification = "UserDefined"
	// UpdateClassificationVRecommendedAndImportant undocumented
	UpdateClassificationVRecommendedAndImportant UpdateClassification = "RecommendedAndImportant"
	// UpdateClassificationVImportant undocumented
	UpdateClassificationVImportant UpdateClassification = "Important"
	// UpdateClassificationVNone undocumented
	UpdateClassificationVNone UpdateClassification = "None"
)

// UpdateClassificationPUserDefined returns a pointer to UpdateClassificationVUserDefined
func UpdateClassificationPUserDefined() *UpdateClassification {
	v := UpdateClassificationVUserDefined
	return &v
}

// UpdateClassificationPRecommendedAndImportant returns a pointer to UpdateClassificationVRecommendedAndImportant
func UpdateClassificationPRecommendedAndImportant() *UpdateClassification {
	v := UpdateClassificationVRecommendedAndImportant
	return &v
}

// UpdateClassificationPImportant returns a pointer to UpdateClassificationVImportant
func UpdateClassificationPImportant() *UpdateClassification {
	v := UpdateClassificationVImportant
	return &v
}

// UpdateClassificationPNone returns a pointer to UpdateClassificationVNone
func UpdateClassificationPNone() *UpdateClassification {
	v := UpdateClassificationVNone
	return &v
}
