// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// UserPfxPaddingScheme undocumented
type UserPfxPaddingScheme string

const (
	// UserPfxPaddingSchemeVNone undocumented
	UserPfxPaddingSchemeVNone UserPfxPaddingScheme = "None"
	// UserPfxPaddingSchemeVPkcs1 undocumented
	UserPfxPaddingSchemeVPkcs1 UserPfxPaddingScheme = "Pkcs1"
	// UserPfxPaddingSchemeVOaepSha1 undocumented
	UserPfxPaddingSchemeVOaepSha1 UserPfxPaddingScheme = "OaepSha1"
	// UserPfxPaddingSchemeVOaepSha256 undocumented
	UserPfxPaddingSchemeVOaepSha256 UserPfxPaddingScheme = "OaepSha256"
	// UserPfxPaddingSchemeVOaepSha384 undocumented
	UserPfxPaddingSchemeVOaepSha384 UserPfxPaddingScheme = "OaepSha384"
	// UserPfxPaddingSchemeVOaepSha512 undocumented
	UserPfxPaddingSchemeVOaepSha512 UserPfxPaddingScheme = "OaepSha512"
)

// UserPfxPaddingSchemePNone returns a pointer to UserPfxPaddingSchemeVNone
func UserPfxPaddingSchemePNone() *UserPfxPaddingScheme {
	v := UserPfxPaddingSchemeVNone
	return &v
}

// UserPfxPaddingSchemePPkcs1 returns a pointer to UserPfxPaddingSchemeVPkcs1
func UserPfxPaddingSchemePPkcs1() *UserPfxPaddingScheme {
	v := UserPfxPaddingSchemeVPkcs1
	return &v
}

// UserPfxPaddingSchemePOaepSha1 returns a pointer to UserPfxPaddingSchemeVOaepSha1
func UserPfxPaddingSchemePOaepSha1() *UserPfxPaddingScheme {
	v := UserPfxPaddingSchemeVOaepSha1
	return &v
}

// UserPfxPaddingSchemePOaepSha256 returns a pointer to UserPfxPaddingSchemeVOaepSha256
func UserPfxPaddingSchemePOaepSha256() *UserPfxPaddingScheme {
	v := UserPfxPaddingSchemeVOaepSha256
	return &v
}

// UserPfxPaddingSchemePOaepSha384 returns a pointer to UserPfxPaddingSchemeVOaepSha384
func UserPfxPaddingSchemePOaepSha384() *UserPfxPaddingScheme {
	v := UserPfxPaddingSchemeVOaepSha384
	return &v
}

// UserPfxPaddingSchemePOaepSha512 returns a pointer to UserPfxPaddingSchemeVOaepSha512
func UserPfxPaddingSchemePOaepSha512() *UserPfxPaddingScheme {
	v := UserPfxPaddingSchemeVOaepSha512
	return &v
}
