// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// UsernameSource undocumented
type UsernameSource string

const (
	// UsernameSourceVUserPrincipalName undocumented
	UsernameSourceVUserPrincipalName UsernameSource = "UserPrincipalName"
	// UsernameSourceVPrimarySMTPAddress undocumented
	UsernameSourceVPrimarySMTPAddress UsernameSource = "PrimarySMTPAddress"
	// UsernameSourceVSamAccountName undocumented
	UsernameSourceVSamAccountName UsernameSource = "SamAccountName"
)

// UsernameSourcePUserPrincipalName returns a pointer to UsernameSourceVUserPrincipalName
func UsernameSourcePUserPrincipalName() *UsernameSource {
	v := UsernameSourceVUserPrincipalName
	return &v
}

// UsernameSourcePPrimarySMTPAddress returns a pointer to UsernameSourceVPrimarySMTPAddress
func UsernameSourcePPrimarySMTPAddress() *UsernameSource {
	v := UsernameSourceVPrimarySMTPAddress
	return &v
}

// UsernameSourcePSamAccountName returns a pointer to UsernameSourceVSamAccountName
func UsernameSourcePSamAccountName() *UsernameSource {
	v := UsernameSourceVSamAccountName
	return &v
}
