// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// UserRiskLevel undocumented
type UserRiskLevel string

const (
	// UserRiskLevelVUnknown undocumented
	UserRiskLevelVUnknown UserRiskLevel = "Unknown"
	// UserRiskLevelVNone undocumented
	UserRiskLevelVNone UserRiskLevel = "None"
	// UserRiskLevelVLow undocumented
	UserRiskLevelVLow UserRiskLevel = "Low"
	// UserRiskLevelVMedium undocumented
	UserRiskLevelVMedium UserRiskLevel = "Medium"
	// UserRiskLevelVHigh undocumented
	UserRiskLevelVHigh UserRiskLevel = "High"
)

// UserRiskLevelPUnknown returns a pointer to UserRiskLevelVUnknown
func UserRiskLevelPUnknown() *UserRiskLevel {
	v := UserRiskLevelVUnknown
	return &v
}

// UserRiskLevelPNone returns a pointer to UserRiskLevelVNone
func UserRiskLevelPNone() *UserRiskLevel {
	v := UserRiskLevelVNone
	return &v
}

// UserRiskLevelPLow returns a pointer to UserRiskLevelVLow
func UserRiskLevelPLow() *UserRiskLevel {
	v := UserRiskLevelVLow
	return &v
}

// UserRiskLevelPMedium returns a pointer to UserRiskLevelVMedium
func UserRiskLevelPMedium() *UserRiskLevel {
	v := UserRiskLevelVMedium
	return &v
}

// UserRiskLevelPHigh returns a pointer to UserRiskLevelVHigh
func UserRiskLevelPHigh() *UserRiskLevel {
	v := UserRiskLevelVHigh
	return &v
}
