// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// VpnProviderType undocumented
type VpnProviderType string

const (
	// VpnProviderTypeVNotConfigured undocumented
	VpnProviderTypeVNotConfigured VpnProviderType = "NotConfigured"
	// VpnProviderTypeVAppProxy undocumented
	VpnProviderTypeVAppProxy VpnProviderType = "AppProxy"
	// VpnProviderTypeVPacketTunnel undocumented
	VpnProviderTypeVPacketTunnel VpnProviderType = "PacketTunnel"
)

// VpnProviderTypePNotConfigured returns a pointer to VpnProviderTypeVNotConfigured
func VpnProviderTypePNotConfigured() *VpnProviderType {
	v := VpnProviderTypeVNotConfigured
	return &v
}

// VpnProviderTypePAppProxy returns a pointer to VpnProviderTypeVAppProxy
func VpnProviderTypePAppProxy() *VpnProviderType {
	v := VpnProviderTypeVAppProxy
	return &v
}

// VpnProviderTypePPacketTunnel returns a pointer to VpnProviderTypeVPacketTunnel
func VpnProviderTypePPacketTunnel() *VpnProviderType {
	v := VpnProviderTypeVPacketTunnel
	return &v
}
