// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// VpnServerCertificateType undocumented
type VpnServerCertificateType string

const (
	// VpnServerCertificateTypeVRsa undocumented
	VpnServerCertificateTypeVRsa VpnServerCertificateType = "Rsa"
	// VpnServerCertificateTypeVEcdsa256 undocumented
	VpnServerCertificateTypeVEcdsa256 VpnServerCertificateType = "Ecdsa256"
	// VpnServerCertificateTypeVEcdsa384 undocumented
	VpnServerCertificateTypeVEcdsa384 VpnServerCertificateType = "Ecdsa384"
	// VpnServerCertificateTypeVEcdsa521 undocumented
	VpnServerCertificateTypeVEcdsa521 VpnServerCertificateType = "Ecdsa521"
)

// VpnServerCertificateTypePRsa returns a pointer to VpnServerCertificateTypeVRsa
func VpnServerCertificateTypePRsa() *VpnServerCertificateType {
	v := VpnServerCertificateTypeVRsa
	return &v
}

// VpnServerCertificateTypePEcdsa256 returns a pointer to VpnServerCertificateTypeVEcdsa256
func VpnServerCertificateTypePEcdsa256() *VpnServerCertificateType {
	v := VpnServerCertificateTypeVEcdsa256
	return &v
}

// VpnServerCertificateTypePEcdsa384 returns a pointer to VpnServerCertificateTypeVEcdsa384
func VpnServerCertificateTypePEcdsa384() *VpnServerCertificateType {
	v := VpnServerCertificateTypeVEcdsa384
	return &v
}

// VpnServerCertificateTypePEcdsa521 returns a pointer to VpnServerCertificateTypeVEcdsa521
func VpnServerCertificateTypePEcdsa521() *VpnServerCertificateType {
	v := VpnServerCertificateTypeVEcdsa521
	return &v
}
