// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// VpnTrafficRuleAppType undocumented
type VpnTrafficRuleAppType string

const (
	// VpnTrafficRuleAppTypeVNone undocumented
	VpnTrafficRuleAppTypeVNone VpnTrafficRuleAppType = "None"
	// VpnTrafficRuleAppTypeVDesktop undocumented
	VpnTrafficRuleAppTypeVDesktop VpnTrafficRuleAppType = "Desktop"
	// VpnTrafficRuleAppTypeVUniversal undocumented
	VpnTrafficRuleAppTypeVUniversal VpnTrafficRuleAppType = "Universal"
)

// VpnTrafficRuleAppTypePNone returns a pointer to VpnTrafficRuleAppTypeVNone
func VpnTrafficRuleAppTypePNone() *VpnTrafficRuleAppType {
	v := VpnTrafficRuleAppTypeVNone
	return &v
}

// VpnTrafficRuleAppTypePDesktop returns a pointer to VpnTrafficRuleAppTypeVDesktop
func VpnTrafficRuleAppTypePDesktop() *VpnTrafficRuleAppType {
	v := VpnTrafficRuleAppTypeVDesktop
	return &v
}

// VpnTrafficRuleAppTypePUniversal returns a pointer to VpnTrafficRuleAppTypeVUniversal
func VpnTrafficRuleAppTypePUniversal() *VpnTrafficRuleAppType {
	v := VpnTrafficRuleAppTypeVUniversal
	return &v
}
