// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// VppTokenSyncStatus undocumented
type VppTokenSyncStatus string

const (
	// VppTokenSyncStatusVNone undocumented
	VppTokenSyncStatusVNone VppTokenSyncStatus = "None"
	// VppTokenSyncStatusVInProgress undocumented
	VppTokenSyncStatusVInProgress VppTokenSyncStatus = "InProgress"
	// VppTokenSyncStatusVCompleted undocumented
	VppTokenSyncStatusVCompleted VppTokenSyncStatus = "Completed"
	// VppTokenSyncStatusVFailed undocumented
	VppTokenSyncStatusVFailed VppTokenSyncStatus = "Failed"
)

// VppTokenSyncStatusPNone returns a pointer to VppTokenSyncStatusVNone
func VppTokenSyncStatusPNone() *VppTokenSyncStatus {
	v := VppTokenSyncStatusVNone
	return &v
}

// VppTokenSyncStatusPInProgress returns a pointer to VppTokenSyncStatusVInProgress
func VppTokenSyncStatusPInProgress() *VppTokenSyncStatus {
	v := VppTokenSyncStatusVInProgress
	return &v
}

// VppTokenSyncStatusPCompleted returns a pointer to VppTokenSyncStatusVCompleted
func VppTokenSyncStatusPCompleted() *VppTokenSyncStatus {
	v := VppTokenSyncStatusVCompleted
	return &v
}

// VppTokenSyncStatusPFailed returns a pointer to VppTokenSyncStatusVFailed
func VppTokenSyncStatusPFailed() *VppTokenSyncStatus {
	v := VppTokenSyncStatusVFailed
	return &v
}
