// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WatermarkLayout undocumented
type WatermarkLayout string

const (
	// WatermarkLayoutVHorizontal undocumented
	WatermarkLayoutVHorizontal WatermarkLayout = "Horizontal"
	// WatermarkLayoutVDiagonal undocumented
	WatermarkLayoutVDiagonal WatermarkLayout = "Diagonal"
)

// WatermarkLayoutPHorizontal returns a pointer to WatermarkLayoutVHorizontal
func WatermarkLayoutPHorizontal() *WatermarkLayout {
	v := WatermarkLayoutVHorizontal
	return &v
}

// WatermarkLayoutPDiagonal returns a pointer to WatermarkLayoutVDiagonal
func WatermarkLayoutPDiagonal() *WatermarkLayout {
	v := WatermarkLayoutVDiagonal
	return &v
}
