// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WiFiAuthenticationMethod undocumented
type WiFiAuthenticationMethod string

const (
	// WiFiAuthenticationMethodVCertificate undocumented
	WiFiAuthenticationMethodVCertificate WiFiAuthenticationMethod = "Certificate"
	// WiFiAuthenticationMethodVUsernameAndPassword undocumented
	WiFiAuthenticationMethodVUsernameAndPassword WiFiAuthenticationMethod = "UsernameAndPassword"
	// WiFiAuthenticationMethodVDerivedCredential undocumented
	WiFiAuthenticationMethodVDerivedCredential WiFiAuthenticationMethod = "DerivedCredential"
)

// WiFiAuthenticationMethodPCertificate returns a pointer to WiFiAuthenticationMethodVCertificate
func WiFiAuthenticationMethodPCertificate() *WiFiAuthenticationMethod {
	v := WiFiAuthenticationMethodVCertificate
	return &v
}

// WiFiAuthenticationMethodPUsernameAndPassword returns a pointer to WiFiAuthenticationMethodVUsernameAndPassword
func WiFiAuthenticationMethodPUsernameAndPassword() *WiFiAuthenticationMethod {
	v := WiFiAuthenticationMethodVUsernameAndPassword
	return &v
}

// WiFiAuthenticationMethodPDerivedCredential returns a pointer to WiFiAuthenticationMethodVDerivedCredential
func WiFiAuthenticationMethodPDerivedCredential() *WiFiAuthenticationMethod {
	v := WiFiAuthenticationMethodVDerivedCredential
	return &v
}
