// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// Win32LobAppReturnCodeType undocumented
type Win32LobAppReturnCodeType string

const (
	// Win32LobAppReturnCodeTypeVFailed undocumented
	Win32LobAppReturnCodeTypeVFailed Win32LobAppReturnCodeType = "Failed"
	// Win32LobAppReturnCodeTypeVSuccess undocumented
	Win32LobAppReturnCodeTypeVSuccess Win32LobAppReturnCodeType = "Success"
	// Win32LobAppReturnCodeTypeVSoftReboot undocumented
	Win32LobAppReturnCodeTypeVSoftReboot Win32LobAppReturnCodeType = "SoftReboot"
	// Win32LobAppReturnCodeTypeVHardReboot undocumented
	Win32LobAppReturnCodeTypeVHardReboot Win32LobAppReturnCodeType = "HardReboot"
	// Win32LobAppReturnCodeTypeVRetry undocumented
	Win32LobAppReturnCodeTypeVRetry Win32LobAppReturnCodeType = "Retry"
)

// Win32LobAppReturnCodeTypePFailed returns a pointer to Win32LobAppReturnCodeTypeVFailed
func Win32LobAppReturnCodeTypePFailed() *Win32LobAppReturnCodeType {
	v := Win32LobAppReturnCodeTypeVFailed
	return &v
}

// Win32LobAppReturnCodeTypePSuccess returns a pointer to Win32LobAppReturnCodeTypeVSuccess
func Win32LobAppReturnCodeTypePSuccess() *Win32LobAppReturnCodeType {
	v := Win32LobAppReturnCodeTypeVSuccess
	return &v
}

// Win32LobAppReturnCodeTypePSoftReboot returns a pointer to Win32LobAppReturnCodeTypeVSoftReboot
func Win32LobAppReturnCodeTypePSoftReboot() *Win32LobAppReturnCodeType {
	v := Win32LobAppReturnCodeTypeVSoftReboot
	return &v
}

// Win32LobAppReturnCodeTypePHardReboot returns a pointer to Win32LobAppReturnCodeTypeVHardReboot
func Win32LobAppReturnCodeTypePHardReboot() *Win32LobAppReturnCodeType {
	v := Win32LobAppReturnCodeTypeVHardReboot
	return &v
}

// Win32LobAppReturnCodeTypePRetry returns a pointer to Win32LobAppReturnCodeTypeVRetry
func Win32LobAppReturnCodeTypePRetry() *Win32LobAppReturnCodeType {
	v := Win32LobAppReturnCodeTypeVRetry
	return &v
}
