// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// Win32LobAppMsiPackageType undocumented
type Win32LobAppMsiPackageType string

const (
	// Win32LobAppMsiPackageTypeVPerMachine undocumented
	Win32LobAppMsiPackageTypeVPerMachine Win32LobAppMsiPackageType = "PerMachine"
	// Win32LobAppMsiPackageTypeVPerUser undocumented
	Win32LobAppMsiPackageTypeVPerUser Win32LobAppMsiPackageType = "PerUser"
	// Win32LobAppMsiPackageTypeVDualPurpose undocumented
	Win32LobAppMsiPackageTypeVDualPurpose Win32LobAppMsiPackageType = "DualPurpose"
)

// Win32LobAppMsiPackageTypePPerMachine returns a pointer to Win32LobAppMsiPackageTypeVPerMachine
func Win32LobAppMsiPackageTypePPerMachine() *Win32LobAppMsiPackageType {
	v := Win32LobAppMsiPackageTypeVPerMachine
	return &v
}

// Win32LobAppMsiPackageTypePPerUser returns a pointer to Win32LobAppMsiPackageTypeVPerUser
func Win32LobAppMsiPackageTypePPerUser() *Win32LobAppMsiPackageType {
	v := Win32LobAppMsiPackageTypeVPerUser
	return &v
}

// Win32LobAppMsiPackageTypePDualPurpose returns a pointer to Win32LobAppMsiPackageTypeVDualPurpose
func Win32LobAppMsiPackageTypePDualPurpose() *Win32LobAppMsiPackageType {
	v := Win32LobAppMsiPackageTypeVDualPurpose
	return &v
}
