// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// Win32LobAppNotification undocumented
type Win32LobAppNotification string

const (
	// Win32LobAppNotificationVShowAll undocumented
	Win32LobAppNotificationVShowAll Win32LobAppNotification = "ShowAll"
	// Win32LobAppNotificationVShowReboot undocumented
	Win32LobAppNotificationVShowReboot Win32LobAppNotification = "ShowReboot"
	// Win32LobAppNotificationVHideAll undocumented
	Win32LobAppNotificationVHideAll Win32LobAppNotification = "HideAll"
)

// Win32LobAppNotificationPShowAll returns a pointer to Win32LobAppNotificationVShowAll
func Win32LobAppNotificationPShowAll() *Win32LobAppNotification {
	v := Win32LobAppNotificationVShowAll
	return &v
}

// Win32LobAppNotificationPShowReboot returns a pointer to Win32LobAppNotificationVShowReboot
func Win32LobAppNotificationPShowReboot() *Win32LobAppNotification {
	v := Win32LobAppNotificationVShowReboot
	return &v
}

// Win32LobAppNotificationPHideAll returns a pointer to Win32LobAppNotificationVHideAll
func Win32LobAppNotificationPHideAll() *Win32LobAppNotification {
	v := Win32LobAppNotificationVHideAll
	return &v
}
