// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WindowsAutopilotDeviceType undocumented
type WindowsAutopilotDeviceType string

const (
	// WindowsAutopilotDeviceTypeVWindowsPc undocumented
	WindowsAutopilotDeviceTypeVWindowsPc WindowsAutopilotDeviceType = "WindowsPc"
	// WindowsAutopilotDeviceTypeVSurfaceHub2 undocumented
	WindowsAutopilotDeviceTypeVSurfaceHub2 WindowsAutopilotDeviceType = "SurfaceHub2"
)

// WindowsAutopilotDeviceTypePWindowsPc returns a pointer to WindowsAutopilotDeviceTypeVWindowsPc
func WindowsAutopilotDeviceTypePWindowsPc() *WindowsAutopilotDeviceType {
	v := WindowsAutopilotDeviceTypeVWindowsPc
	return &v
}

// WindowsAutopilotDeviceTypePSurfaceHub2 returns a pointer to WindowsAutopilotDeviceTypeVSurfaceHub2
func WindowsAutopilotDeviceTypePSurfaceHub2() *WindowsAutopilotDeviceType {
	v := WindowsAutopilotDeviceTypeVSurfaceHub2
	return &v
}
