// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// Windows10VpnConnectionType undocumented
type Windows10VpnConnectionType string

const (
	// Windows10VpnConnectionTypeVPulseSecure undocumented
	Windows10VpnConnectionTypeVPulseSecure Windows10VpnConnectionType = "PulseSecure"
	// Windows10VpnConnectionTypeVF5EdgeClient undocumented
	Windows10VpnConnectionTypeVF5EdgeClient Windows10VpnConnectionType = "F5EdgeClient"
	// Windows10VpnConnectionTypeVDellSonicWallMobileConnect undocumented
	Windows10VpnConnectionTypeVDellSonicWallMobileConnect Windows10VpnConnectionType = "DellSonicWallMobileConnect"
	// Windows10VpnConnectionTypeVCheckPointCapsuleVpn undocumented
	Windows10VpnConnectionTypeVCheckPointCapsuleVpn Windows10VpnConnectionType = "CheckPointCapsuleVpn"
	// Windows10VpnConnectionTypeVAutomatic undocumented
	Windows10VpnConnectionTypeVAutomatic Windows10VpnConnectionType = "Automatic"
	// Windows10VpnConnectionTypeVIkEv2 undocumented
	Windows10VpnConnectionTypeVIkEv2 Windows10VpnConnectionType = "IkEv2"
	// Windows10VpnConnectionTypeVL2tp undocumented
	Windows10VpnConnectionTypeVL2tp Windows10VpnConnectionType = "L2tp"
	// Windows10VpnConnectionTypeVPptp undocumented
	Windows10VpnConnectionTypeVPptp Windows10VpnConnectionType = "Pptp"
	// Windows10VpnConnectionTypeVCitrix undocumented
	Windows10VpnConnectionTypeVCitrix Windows10VpnConnectionType = "Citrix"
	// Windows10VpnConnectionTypeVPaloAltoGlobalProtect undocumented
	Windows10VpnConnectionTypeVPaloAltoGlobalProtect Windows10VpnConnectionType = "PaloAltoGlobalProtect"
)

// Windows10VpnConnectionTypePPulseSecure returns a pointer to Windows10VpnConnectionTypeVPulseSecure
func Windows10VpnConnectionTypePPulseSecure() *Windows10VpnConnectionType {
	v := Windows10VpnConnectionTypeVPulseSecure
	return &v
}

// Windows10VpnConnectionTypePF5EdgeClient returns a pointer to Windows10VpnConnectionTypeVF5EdgeClient
func Windows10VpnConnectionTypePF5EdgeClient() *Windows10VpnConnectionType {
	v := Windows10VpnConnectionTypeVF5EdgeClient
	return &v
}

// Windows10VpnConnectionTypePDellSonicWallMobileConnect returns a pointer to Windows10VpnConnectionTypeVDellSonicWallMobileConnect
func Windows10VpnConnectionTypePDellSonicWallMobileConnect() *Windows10VpnConnectionType {
	v := Windows10VpnConnectionTypeVDellSonicWallMobileConnect
	return &v
}

// Windows10VpnConnectionTypePCheckPointCapsuleVpn returns a pointer to Windows10VpnConnectionTypeVCheckPointCapsuleVpn
func Windows10VpnConnectionTypePCheckPointCapsuleVpn() *Windows10VpnConnectionType {
	v := Windows10VpnConnectionTypeVCheckPointCapsuleVpn
	return &v
}

// Windows10VpnConnectionTypePAutomatic returns a pointer to Windows10VpnConnectionTypeVAutomatic
func Windows10VpnConnectionTypePAutomatic() *Windows10VpnConnectionType {
	v := Windows10VpnConnectionTypeVAutomatic
	return &v
}

// Windows10VpnConnectionTypePIkEv2 returns a pointer to Windows10VpnConnectionTypeVIkEv2
func Windows10VpnConnectionTypePIkEv2() *Windows10VpnConnectionType {
	v := Windows10VpnConnectionTypeVIkEv2
	return &v
}

// Windows10VpnConnectionTypePL2tp returns a pointer to Windows10VpnConnectionTypeVL2tp
func Windows10VpnConnectionTypePL2tp() *Windows10VpnConnectionType {
	v := Windows10VpnConnectionTypeVL2tp
	return &v
}

// Windows10VpnConnectionTypePPptp returns a pointer to Windows10VpnConnectionTypeVPptp
func Windows10VpnConnectionTypePPptp() *Windows10VpnConnectionType {
	v := Windows10VpnConnectionTypeVPptp
	return &v
}

// Windows10VpnConnectionTypePCitrix returns a pointer to Windows10VpnConnectionTypeVCitrix
func Windows10VpnConnectionTypePCitrix() *Windows10VpnConnectionType {
	v := Windows10VpnConnectionTypeVCitrix
	return &v
}

// Windows10VpnConnectionTypePPaloAltoGlobalProtect returns a pointer to Windows10VpnConnectionTypeVPaloAltoGlobalProtect
func Windows10VpnConnectionTypePPaloAltoGlobalProtect() *Windows10VpnConnectionType {
	v := Windows10VpnConnectionTypeVPaloAltoGlobalProtect
	return &v
}
