// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// Windows10AppsUpdateRecurrence undocumented
type Windows10AppsUpdateRecurrence string

const (
	// Windows10AppsUpdateRecurrenceVNone undocumented
	Windows10AppsUpdateRecurrenceVNone Windows10AppsUpdateRecurrence = "None"
	// Windows10AppsUpdateRecurrenceVDaily undocumented
	Windows10AppsUpdateRecurrenceVDaily Windows10AppsUpdateRecurrence = "Daily"
	// Windows10AppsUpdateRecurrenceVWeekly undocumented
	Windows10AppsUpdateRecurrenceVWeekly Windows10AppsUpdateRecurrence = "Weekly"
	// Windows10AppsUpdateRecurrenceVMonthly undocumented
	Windows10AppsUpdateRecurrenceVMonthly Windows10AppsUpdateRecurrence = "Monthly"
)

// Windows10AppsUpdateRecurrencePNone returns a pointer to Windows10AppsUpdateRecurrenceVNone
func Windows10AppsUpdateRecurrencePNone() *Windows10AppsUpdateRecurrence {
	v := Windows10AppsUpdateRecurrenceVNone
	return &v
}

// Windows10AppsUpdateRecurrencePDaily returns a pointer to Windows10AppsUpdateRecurrenceVDaily
func Windows10AppsUpdateRecurrencePDaily() *Windows10AppsUpdateRecurrence {
	v := Windows10AppsUpdateRecurrenceVDaily
	return &v
}

// Windows10AppsUpdateRecurrencePWeekly returns a pointer to Windows10AppsUpdateRecurrenceVWeekly
func Windows10AppsUpdateRecurrencePWeekly() *Windows10AppsUpdateRecurrence {
	v := Windows10AppsUpdateRecurrenceVWeekly
	return &v
}

// Windows10AppsUpdateRecurrencePMonthly returns a pointer to Windows10AppsUpdateRecurrenceVMonthly
func Windows10AppsUpdateRecurrencePMonthly() *Windows10AppsUpdateRecurrence {
	v := Windows10AppsUpdateRecurrenceVMonthly
	return &v
}
