// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WindowsKioskAppType undocumented
type WindowsKioskAppType string

const (
	// WindowsKioskAppTypeVUnknown undocumented
	WindowsKioskAppTypeVUnknown WindowsKioskAppType = "Unknown"
	// WindowsKioskAppTypeVStore undocumented
	WindowsKioskAppTypeVStore WindowsKioskAppType = "Store"
	// WindowsKioskAppTypeVDesktop undocumented
	WindowsKioskAppTypeVDesktop WindowsKioskAppType = "Desktop"
	// WindowsKioskAppTypeVAumID undocumented
	WindowsKioskAppTypeVAumID WindowsKioskAppType = "AumID"
)

// WindowsKioskAppTypePUnknown returns a pointer to WindowsKioskAppTypeVUnknown
func WindowsKioskAppTypePUnknown() *WindowsKioskAppType {
	v := WindowsKioskAppTypeVUnknown
	return &v
}

// WindowsKioskAppTypePStore returns a pointer to WindowsKioskAppTypeVStore
func WindowsKioskAppTypePStore() *WindowsKioskAppType {
	v := WindowsKioskAppTypeVStore
	return &v
}

// WindowsKioskAppTypePDesktop returns a pointer to WindowsKioskAppTypeVDesktop
func WindowsKioskAppTypePDesktop() *WindowsKioskAppType {
	v := WindowsKioskAppTypeVDesktop
	return &v
}

// WindowsKioskAppTypePAumID returns a pointer to WindowsKioskAppTypeVAumID
func WindowsKioskAppTypePAumID() *WindowsKioskAppType {
	v := WindowsKioskAppTypeVAumID
	return &v
}
