// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WindowsPrivacyDataAccessLevel undocumented
type WindowsPrivacyDataAccessLevel string

const (
	// WindowsPrivacyDataAccessLevelVNotConfigured undocumented
	WindowsPrivacyDataAccessLevelVNotConfigured WindowsPrivacyDataAccessLevel = "NotConfigured"
	// WindowsPrivacyDataAccessLevelVForceAllow undocumented
	WindowsPrivacyDataAccessLevelVForceAllow WindowsPrivacyDataAccessLevel = "ForceAllow"
	// WindowsPrivacyDataAccessLevelVForceDeny undocumented
	WindowsPrivacyDataAccessLevelVForceDeny WindowsPrivacyDataAccessLevel = "ForceDeny"
	// WindowsPrivacyDataAccessLevelVUserInControl undocumented
	WindowsPrivacyDataAccessLevelVUserInControl WindowsPrivacyDataAccessLevel = "UserInControl"
)

// WindowsPrivacyDataAccessLevelPNotConfigured returns a pointer to WindowsPrivacyDataAccessLevelVNotConfigured
func WindowsPrivacyDataAccessLevelPNotConfigured() *WindowsPrivacyDataAccessLevel {
	v := WindowsPrivacyDataAccessLevelVNotConfigured
	return &v
}

// WindowsPrivacyDataAccessLevelPForceAllow returns a pointer to WindowsPrivacyDataAccessLevelVForceAllow
func WindowsPrivacyDataAccessLevelPForceAllow() *WindowsPrivacyDataAccessLevel {
	v := WindowsPrivacyDataAccessLevelVForceAllow
	return &v
}

// WindowsPrivacyDataAccessLevelPForceDeny returns a pointer to WindowsPrivacyDataAccessLevelVForceDeny
func WindowsPrivacyDataAccessLevelPForceDeny() *WindowsPrivacyDataAccessLevel {
	v := WindowsPrivacyDataAccessLevelVForceDeny
	return &v
}

// WindowsPrivacyDataAccessLevelPUserInControl returns a pointer to WindowsPrivacyDataAccessLevelVUserInControl
func WindowsPrivacyDataAccessLevelPUserInControl() *WindowsPrivacyDataAccessLevel {
	v := WindowsPrivacyDataAccessLevelVUserInControl
	return &v
}
