// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WindowsUserType undocumented
type WindowsUserType string

const (
	// WindowsUserTypeVAdministrator undocumented
	WindowsUserTypeVAdministrator WindowsUserType = "Administrator"
	// WindowsUserTypeVStandard undocumented
	WindowsUserTypeVStandard WindowsUserType = "Standard"
)

// WindowsUserTypePAdministrator returns a pointer to WindowsUserTypeVAdministrator
func WindowsUserTypePAdministrator() *WindowsUserType {
	v := WindowsUserTypeVAdministrator
	return &v
}

// WindowsUserTypePStandard returns a pointer to WindowsUserTypeVStandard
func WindowsUserTypePStandard() *WindowsUserType {
	v := WindowsUserTypeVStandard
	return &v
}
