// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WindowsAutopilotSyncStatus undocumented
type WindowsAutopilotSyncStatus string

const (
	// WindowsAutopilotSyncStatusVUnknown undocumented
	WindowsAutopilotSyncStatusVUnknown WindowsAutopilotSyncStatus = "Unknown"
	// WindowsAutopilotSyncStatusVInProgress undocumented
	WindowsAutopilotSyncStatusVInProgress WindowsAutopilotSyncStatus = "InProgress"
	// WindowsAutopilotSyncStatusVCompleted undocumented
	WindowsAutopilotSyncStatusVCompleted WindowsAutopilotSyncStatus = "Completed"
	// WindowsAutopilotSyncStatusVFailed undocumented
	WindowsAutopilotSyncStatusVFailed WindowsAutopilotSyncStatus = "Failed"
)

// WindowsAutopilotSyncStatusPUnknown returns a pointer to WindowsAutopilotSyncStatusVUnknown
func WindowsAutopilotSyncStatusPUnknown() *WindowsAutopilotSyncStatus {
	v := WindowsAutopilotSyncStatusVUnknown
	return &v
}

// WindowsAutopilotSyncStatusPInProgress returns a pointer to WindowsAutopilotSyncStatusVInProgress
func WindowsAutopilotSyncStatusPInProgress() *WindowsAutopilotSyncStatus {
	v := WindowsAutopilotSyncStatusVInProgress
	return &v
}

// WindowsAutopilotSyncStatusPCompleted returns a pointer to WindowsAutopilotSyncStatusVCompleted
func WindowsAutopilotSyncStatusPCompleted() *WindowsAutopilotSyncStatus {
	v := WindowsAutopilotSyncStatusVCompleted
	return &v
}

// WindowsAutopilotSyncStatusPFailed returns a pointer to WindowsAutopilotSyncStatusVFailed
func WindowsAutopilotSyncStatusPFailed() *WindowsAutopilotSyncStatus {
	v := WindowsAutopilotSyncStatusVFailed
	return &v
}
