// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// Windows10EditionType undocumented
type Windows10EditionType string

const (
	// Windows10EditionTypeVWindows10Enterprise undocumented
	Windows10EditionTypeVWindows10Enterprise Windows10EditionType = "Windows10Enterprise"
	// Windows10EditionTypeVWindows10EnterpriseN undocumented
	Windows10EditionTypeVWindows10EnterpriseN Windows10EditionType = "Windows10EnterpriseN"
	// Windows10EditionTypeVWindows10Education undocumented
	Windows10EditionTypeVWindows10Education Windows10EditionType = "Windows10Education"
	// Windows10EditionTypeVWindows10EducationN undocumented
	Windows10EditionTypeVWindows10EducationN Windows10EditionType = "Windows10EducationN"
	// Windows10EditionTypeVWindows10MobileEnterprise undocumented
	Windows10EditionTypeVWindows10MobileEnterprise Windows10EditionType = "Windows10MobileEnterprise"
	// Windows10EditionTypeVWindows10HolographicEnterprise undocumented
	Windows10EditionTypeVWindows10HolographicEnterprise Windows10EditionType = "Windows10HolographicEnterprise"
	// Windows10EditionTypeVWindows10Professional undocumented
	Windows10EditionTypeVWindows10Professional Windows10EditionType = "Windows10Professional"
	// Windows10EditionTypeVWindows10ProfessionalN undocumented
	Windows10EditionTypeVWindows10ProfessionalN Windows10EditionType = "Windows10ProfessionalN"
	// Windows10EditionTypeVWindows10ProfessionalEducation undocumented
	Windows10EditionTypeVWindows10ProfessionalEducation Windows10EditionType = "Windows10ProfessionalEducation"
	// Windows10EditionTypeVWindows10ProfessionalEducationN undocumented
	Windows10EditionTypeVWindows10ProfessionalEducationN Windows10EditionType = "Windows10ProfessionalEducationN"
	// Windows10EditionTypeVWindows10ProfessionalWorkstation undocumented
	Windows10EditionTypeVWindows10ProfessionalWorkstation Windows10EditionType = "Windows10ProfessionalWorkstation"
	// Windows10EditionTypeVWindows10ProfessionalWorkstationN undocumented
	Windows10EditionTypeVWindows10ProfessionalWorkstationN Windows10EditionType = "Windows10ProfessionalWorkstationN"
	// Windows10EditionTypeVNotConfigured undocumented
	Windows10EditionTypeVNotConfigured Windows10EditionType = "NotConfigured"
	// Windows10EditionTypeVWindows10Home undocumented
	Windows10EditionTypeVWindows10Home Windows10EditionType = "Windows10Home"
	// Windows10EditionTypeVWindows10HomeChina undocumented
	Windows10EditionTypeVWindows10HomeChina Windows10EditionType = "Windows10HomeChina"
	// Windows10EditionTypeVWindows10HomeN undocumented
	Windows10EditionTypeVWindows10HomeN Windows10EditionType = "Windows10HomeN"
	// Windows10EditionTypeVWindows10HomeSingleLanguage undocumented
	Windows10EditionTypeVWindows10HomeSingleLanguage Windows10EditionType = "Windows10HomeSingleLanguage"
	// Windows10EditionTypeVWindows10Mobile undocumented
	Windows10EditionTypeVWindows10Mobile Windows10EditionType = "Windows10Mobile"
	// Windows10EditionTypeVWindows10IoTCore undocumented
	Windows10EditionTypeVWindows10IoTCore Windows10EditionType = "Windows10IoTCore"
	// Windows10EditionTypeVWindows10IoTCoreCommercial undocumented
	Windows10EditionTypeVWindows10IoTCoreCommercial Windows10EditionType = "Windows10IoTCoreCommercial"
)

// Windows10EditionTypePWindows10Enterprise returns a pointer to Windows10EditionTypeVWindows10Enterprise
func Windows10EditionTypePWindows10Enterprise() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10Enterprise
	return &v
}

// Windows10EditionTypePWindows10EnterpriseN returns a pointer to Windows10EditionTypeVWindows10EnterpriseN
func Windows10EditionTypePWindows10EnterpriseN() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10EnterpriseN
	return &v
}

// Windows10EditionTypePWindows10Education returns a pointer to Windows10EditionTypeVWindows10Education
func Windows10EditionTypePWindows10Education() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10Education
	return &v
}

// Windows10EditionTypePWindows10EducationN returns a pointer to Windows10EditionTypeVWindows10EducationN
func Windows10EditionTypePWindows10EducationN() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10EducationN
	return &v
}

// Windows10EditionTypePWindows10MobileEnterprise returns a pointer to Windows10EditionTypeVWindows10MobileEnterprise
func Windows10EditionTypePWindows10MobileEnterprise() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10MobileEnterprise
	return &v
}

// Windows10EditionTypePWindows10HolographicEnterprise returns a pointer to Windows10EditionTypeVWindows10HolographicEnterprise
func Windows10EditionTypePWindows10HolographicEnterprise() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10HolographicEnterprise
	return &v
}

// Windows10EditionTypePWindows10Professional returns a pointer to Windows10EditionTypeVWindows10Professional
func Windows10EditionTypePWindows10Professional() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10Professional
	return &v
}

// Windows10EditionTypePWindows10ProfessionalN returns a pointer to Windows10EditionTypeVWindows10ProfessionalN
func Windows10EditionTypePWindows10ProfessionalN() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10ProfessionalN
	return &v
}

// Windows10EditionTypePWindows10ProfessionalEducation returns a pointer to Windows10EditionTypeVWindows10ProfessionalEducation
func Windows10EditionTypePWindows10ProfessionalEducation() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10ProfessionalEducation
	return &v
}

// Windows10EditionTypePWindows10ProfessionalEducationN returns a pointer to Windows10EditionTypeVWindows10ProfessionalEducationN
func Windows10EditionTypePWindows10ProfessionalEducationN() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10ProfessionalEducationN
	return &v
}

// Windows10EditionTypePWindows10ProfessionalWorkstation returns a pointer to Windows10EditionTypeVWindows10ProfessionalWorkstation
func Windows10EditionTypePWindows10ProfessionalWorkstation() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10ProfessionalWorkstation
	return &v
}

// Windows10EditionTypePWindows10ProfessionalWorkstationN returns a pointer to Windows10EditionTypeVWindows10ProfessionalWorkstationN
func Windows10EditionTypePWindows10ProfessionalWorkstationN() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10ProfessionalWorkstationN
	return &v
}

// Windows10EditionTypePNotConfigured returns a pointer to Windows10EditionTypeVNotConfigured
func Windows10EditionTypePNotConfigured() *Windows10EditionType {
	v := Windows10EditionTypeVNotConfigured
	return &v
}

// Windows10EditionTypePWindows10Home returns a pointer to Windows10EditionTypeVWindows10Home
func Windows10EditionTypePWindows10Home() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10Home
	return &v
}

// Windows10EditionTypePWindows10HomeChina returns a pointer to Windows10EditionTypeVWindows10HomeChina
func Windows10EditionTypePWindows10HomeChina() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10HomeChina
	return &v
}

// Windows10EditionTypePWindows10HomeN returns a pointer to Windows10EditionTypeVWindows10HomeN
func Windows10EditionTypePWindows10HomeN() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10HomeN
	return &v
}

// Windows10EditionTypePWindows10HomeSingleLanguage returns a pointer to Windows10EditionTypeVWindows10HomeSingleLanguage
func Windows10EditionTypePWindows10HomeSingleLanguage() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10HomeSingleLanguage
	return &v
}

// Windows10EditionTypePWindows10Mobile returns a pointer to Windows10EditionTypeVWindows10Mobile
func Windows10EditionTypePWindows10Mobile() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10Mobile
	return &v
}

// Windows10EditionTypePWindows10IoTCore returns a pointer to Windows10EditionTypeVWindows10IoTCore
func Windows10EditionTypePWindows10IoTCore() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10IoTCore
	return &v
}

// Windows10EditionTypePWindows10IoTCoreCommercial returns a pointer to Windows10EditionTypeVWindows10IoTCoreCommercial
func Windows10EditionTypePWindows10IoTCoreCommercial() *Windows10EditionType {
	v := Windows10EditionTypeVWindows10IoTCoreCommercial
	return &v
}
