// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WindowsDefenderTamperProtectionOptions undocumented
type WindowsDefenderTamperProtectionOptions string

const (
	// WindowsDefenderTamperProtectionOptionsVNotConfigured undocumented
	WindowsDefenderTamperProtectionOptionsVNotConfigured WindowsDefenderTamperProtectionOptions = "NotConfigured"
	// WindowsDefenderTamperProtectionOptionsVEnable undocumented
	WindowsDefenderTamperProtectionOptionsVEnable WindowsDefenderTamperProtectionOptions = "Enable"
	// WindowsDefenderTamperProtectionOptionsVDisable undocumented
	WindowsDefenderTamperProtectionOptionsVDisable WindowsDefenderTamperProtectionOptions = "Disable"
)

// WindowsDefenderTamperProtectionOptionsPNotConfigured returns a pointer to WindowsDefenderTamperProtectionOptionsVNotConfigured
func WindowsDefenderTamperProtectionOptionsPNotConfigured() *WindowsDefenderTamperProtectionOptions {
	v := WindowsDefenderTamperProtectionOptionsVNotConfigured
	return &v
}

// WindowsDefenderTamperProtectionOptionsPEnable returns a pointer to WindowsDefenderTamperProtectionOptionsVEnable
func WindowsDefenderTamperProtectionOptionsPEnable() *WindowsDefenderTamperProtectionOptions {
	v := WindowsDefenderTamperProtectionOptionsVEnable
	return &v
}

// WindowsDefenderTamperProtectionOptionsPDisable returns a pointer to WindowsDefenderTamperProtectionOptionsVDisable
func WindowsDefenderTamperProtectionOptionsPDisable() *WindowsDefenderTamperProtectionOptions {
	v := WindowsDefenderTamperProtectionOptionsVDisable
	return &v
}
