// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WindowsFirewallRuleNetworkProfileTypes undocumented
type WindowsFirewallRuleNetworkProfileTypes string

const (
	// WindowsFirewallRuleNetworkProfileTypesVNotConfigured undocumented
	WindowsFirewallRuleNetworkProfileTypesVNotConfigured WindowsFirewallRuleNetworkProfileTypes = "NotConfigured"
	// WindowsFirewallRuleNetworkProfileTypesVDomain undocumented
	WindowsFirewallRuleNetworkProfileTypesVDomain WindowsFirewallRuleNetworkProfileTypes = "Domain"
	// WindowsFirewallRuleNetworkProfileTypesVPrivate undocumented
	WindowsFirewallRuleNetworkProfileTypesVPrivate WindowsFirewallRuleNetworkProfileTypes = "Private"
	// WindowsFirewallRuleNetworkProfileTypesVPublic undocumented
	WindowsFirewallRuleNetworkProfileTypesVPublic WindowsFirewallRuleNetworkProfileTypes = "Public"
)

// WindowsFirewallRuleNetworkProfileTypesPNotConfigured returns a pointer to WindowsFirewallRuleNetworkProfileTypesVNotConfigured
func WindowsFirewallRuleNetworkProfileTypesPNotConfigured() *WindowsFirewallRuleNetworkProfileTypes {
	v := WindowsFirewallRuleNetworkProfileTypesVNotConfigured
	return &v
}

// WindowsFirewallRuleNetworkProfileTypesPDomain returns a pointer to WindowsFirewallRuleNetworkProfileTypesVDomain
func WindowsFirewallRuleNetworkProfileTypesPDomain() *WindowsFirewallRuleNetworkProfileTypes {
	v := WindowsFirewallRuleNetworkProfileTypesVDomain
	return &v
}

// WindowsFirewallRuleNetworkProfileTypesPPrivate returns a pointer to WindowsFirewallRuleNetworkProfileTypesVPrivate
func WindowsFirewallRuleNetworkProfileTypesPPrivate() *WindowsFirewallRuleNetworkProfileTypes {
	v := WindowsFirewallRuleNetworkProfileTypesVPrivate
	return &v
}

// WindowsFirewallRuleNetworkProfileTypesPPublic returns a pointer to WindowsFirewallRuleNetworkProfileTypesVPublic
func WindowsFirewallRuleNetworkProfileTypesPPublic() *WindowsFirewallRuleNetworkProfileTypes {
	v := WindowsFirewallRuleNetworkProfileTypesVPublic
	return &v
}
