// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WindowsAppStartLayoutTileSize undocumented
type WindowsAppStartLayoutTileSize string

const (
	// WindowsAppStartLayoutTileSizeVHidden undocumented
	WindowsAppStartLayoutTileSizeVHidden WindowsAppStartLayoutTileSize = "Hidden"
	// WindowsAppStartLayoutTileSizeVSmall undocumented
	WindowsAppStartLayoutTileSizeVSmall WindowsAppStartLayoutTileSize = "Small"
	// WindowsAppStartLayoutTileSizeVMedium undocumented
	WindowsAppStartLayoutTileSizeVMedium WindowsAppStartLayoutTileSize = "Medium"
	// WindowsAppStartLayoutTileSizeVWide undocumented
	WindowsAppStartLayoutTileSizeVWide WindowsAppStartLayoutTileSize = "Wide"
	// WindowsAppStartLayoutTileSizeVLarge undocumented
	WindowsAppStartLayoutTileSizeVLarge WindowsAppStartLayoutTileSize = "Large"
)

// WindowsAppStartLayoutTileSizePHidden returns a pointer to WindowsAppStartLayoutTileSizeVHidden
func WindowsAppStartLayoutTileSizePHidden() *WindowsAppStartLayoutTileSize {
	v := WindowsAppStartLayoutTileSizeVHidden
	return &v
}

// WindowsAppStartLayoutTileSizePSmall returns a pointer to WindowsAppStartLayoutTileSizeVSmall
func WindowsAppStartLayoutTileSizePSmall() *WindowsAppStartLayoutTileSize {
	v := WindowsAppStartLayoutTileSizeVSmall
	return &v
}

// WindowsAppStartLayoutTileSizePMedium returns a pointer to WindowsAppStartLayoutTileSizeVMedium
func WindowsAppStartLayoutTileSizePMedium() *WindowsAppStartLayoutTileSize {
	v := WindowsAppStartLayoutTileSizeVMedium
	return &v
}

// WindowsAppStartLayoutTileSizePWide returns a pointer to WindowsAppStartLayoutTileSizeVWide
func WindowsAppStartLayoutTileSizePWide() *WindowsAppStartLayoutTileSize {
	v := WindowsAppStartLayoutTileSizeVWide
	return &v
}

// WindowsAppStartLayoutTileSizePLarge returns a pointer to WindowsAppStartLayoutTileSizeVLarge
func WindowsAppStartLayoutTileSizePLarge() *WindowsAppStartLayoutTileSize {
	v := WindowsAppStartLayoutTileSizeVLarge
	return &v
}
